### PR TITLE
docs/nia: fix catalog-services typo

### PR DESCRIPTION
**Pull request by findkim**

### CODE REVIEW

**Review by eikenb — APPROVED** [review]
+s :+1:

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/397029.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 993f4715fd76aa09810da4e01b0866104effbaff onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 993f4715fd76aa09810da4e01b0866104effbaff onto `release/1.10.x` succeeded!

**Pull request merged**
