### PR TITLE
Support HTTP check with body

### PR DESCRIPTION
**Pull request by akshayganeshen**
Supports a new `"body"` field for HTTP checks.

See #4148 for use-case.

### CODE REVIEW

**Comment by pierresouchay** [comment]
@akshayganeshen Can you rebase to allow merging?

**Comment by akshayganeshen** [comment]
@pierresouchay Done!

**Comment by freddygv** [comment]
Hi @akshayganeshen are you interested in completing this PR? if so I can provide a review

**Comment by akshayganeshen** [comment]
Hey @freddygv, yes definitely! Give me a couple days to rebase this and I'll open another PR.

**Comment by akshayganeshen** [comment]
Recreated as #6602.

**Pull request closed without merging**
