### PR TITLE
docs: Remove unnecessary use of CodeBlockConfig

### PR DESCRIPTION
**Pull request by blake**
### Description

Remove empty CodeBlockConfig elements. These elements are not providing any benefit for the enclosed code blocks. Removing so that the source is easier to read.

### PR Checklist

* [ ] updated test coverage
* [X] external facing docs updated
* [X] not a security concern
* [ ] checklist [folder](./../docs/config) consulted

### CODE REVIEW

**Review by david-yu — APPROVED** [review]

**Review by trujillo-adam — APPROVED** [review]
Approving, but my two cents is that it might be better to use the code config features (i.e., providing an example filename) rather than just deleting them.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/674096.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 9378880c421a3238ea8c987e5f292dd9cf44feaf onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 9378880c421a3238ea8c987e5f292dd9cf44feaf onto `release/1.12.x` succeeded!

**Pull request merged**
