### PR TITLE
Bring in consulapi

### PR DESCRIPTION
**Pull request by ryanuber**
Brings the consul-api stuff into consul's root repo. This gets rid of the strange dependency trail we had before and unifies the code.

The tests were the trickiest part of all of this, since they previously required the operator to fire up a consul instance and then run them. This is because there is a really fun import cycle if consulapi tries to import the consul agent and vice versa.  There are a few changes to how this works to allow the normal Consul tests to pass independently, since not all environments will have `consul` preinstalled:

* If a `consul` binary exists on the path, then execute that to start a new server for each test case. If it does not exist, then skip the test.
* The consul instance will be torn down after each test has run to make sure we have a clean slate. This prevents sharing state between different tests, which was previously happening on a few tests. They have since been refactored to work in isolation.

### CODE REVIEW

**Comment by sethvargo** [comment]
I assume this is a straight copy-paste with some gofmt magic?

**Comment by ryanuber** [comment]
All of the client code is straight copy/paste, the tests are the only thing that changed, and those changes are just the extra harnessing for launching consul and a few adjustments since there is no more shared state between tests.

**Comment by armon** [comment]
LGTM! Dope!

**Comment by sethvargo** [comment]
@ryanuber any idea why the tests are failing?

**Comment by ryanuber** [comment]
@sethvargo normally we see failures on Travis due to some timing issues, but these look a little scarier. I'll look back and make sure nothing on our end is causing this.

**Comment by sethvargo** [comment]
@ryanuber okay. I'm just wondering if there's a recursive dep or something weird (like we already had a package named "api" from somewhere else)

**Comment by ryanuber** [comment]
The segfaults were fixed in hashicorp/raft@009485a. Merging!

**Pull request merged**
