### PR TITLE
Add CTS and API Gateway to docs on tools page

### PR DESCRIPTION
**Pull request by hannahhearth**
Screen Shot 2022-01-10 at 12 58 01 PM

### CODE REVIEW

**Review by karl-cardenas-coding — APPROVED** [review]
👍🏼

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/547801.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 9a4763bfbfb858684b4e5b67a69ce6c1fde3e792 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 9a4763bfbfb858684b4e5b67a69ce6c1fde3e792 onto `release/1.11.x` succeeded!

**Pull request merged**
