### PR TITLE
Update website/content/docs/connect/config-entries/mesh.mdx

### PR DESCRIPTION
**Pull request by markan**
### Description
Pull some docs fixes that were applied to 1.12.x into main. (https://github.com/hashicorp/consul/pull/12941/)

Co-authored-by: trujillo-adam <47586768+trujillo-adam@users.noreply.github.com>
Signed-off-by: Mark Anderson <manderson@hashicorp.com>

### CODE REVIEW

**Review by trujillo-adam — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/663257.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 7eda81d00d094e7eb0f5fc401ed100a6ba2c3922 onto `stable-website` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/663257)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 7eda81d00d094e7eb0f5fc401ed100a6ba2c3922 onto `release/1.12.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/663257)

**Pull request merged**
