### PR TITLE
Update "testutil" documentation

### PR DESCRIPTION
**Pull request by dtmcmath**
A contribution under the heading "Improve our guides and documentation"...

Building my first application that depends on Consul, I wanted `testutil` for testing.  I discovered that the documentation in the README has been left behind by a couple of refactors.  To make that harder to happen in the future, it seems reasonable to have an executable version of the README.  There's more than one way to do that, and I'm not familiar enough with the build processes to come up with a more clever one than just to make a copy and leave breadcrumbs.  It would be amusing to make the README and the test pull from the same source.

With these changes, "`make test`" still passes.

### CODE REVIEW

**Comment by dtmcmath** [comment]
My first, naïve attempt at turning the test into an example failed, just because "`Example...`" has the wrong signature; there's no "`t`"!

I get the point, though.  I think there's something in the idea.

**Comment by i0rek** [comment]
Thank you for your work @dtmcmath! Are you still interested in merging this?

**Comment by dtmcmath** [comment]
> Thank you for your work @dtmcmath! Are you still interested in merging this?

Frankly, I completely forgot about this.  I'm definitely interested in improving the documentation (which is all this is about) but I think this isn't a good way to do it after all.  It's not obvious (to me) how to keep the readme in sync, and rewriting as "example" didn't pan out for me.

So the answer to the question is probably "no".

**Comment by i0rek** [comment]
Thank you for your fast reply! I will close this now. But if you find another way, let me know!

**Pull request closed without merging**
