### PR TITLE
minor typo

### PR DESCRIPTION
**Pull request by ramramhariram**
Under 'Task' section from 'the that dynamic service data' to 'that dynamic service data'

### CODE REVIEW

**Review by dnephin — APPROVED** [review]
Thank you!

**Comment by dnephin** [comment]
Oh,it looks like this one has a conflict. If you can resolve the conflict we can merge

**Comment by ramramhariram** [comment]
looks like the conflict is for test-integrations and its this step that failed - "dev-upload-docker - Unauthorized" - I am not sure i can resolve this.

**Comment by dnephin** [comment]
Oh, don't worry about that test failure, it is expected that `dev-upload` won't work.

The conflict I was referring to is this one:

> Conflicting files
> website/content/docs/nia/architecture.mdx

There's a "Resolve conflicts" button, and instructions to do it via the CLI in the box just below this.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/557800.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit b0e3956c578d88a80ecd336f74f1ed2728b703da onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit b0e3956c578d88a80ecd336f74f1ed2728b703da onto `release/1.11.x` succeeded!

**Pull request merged**
