### PR TITLE
Fix typo, Layer 7 is application layer not network

### PR DESCRIPTION
**Pull request by saurabh-sp-tripathi**

### CODE REVIEW

**Review by blake — APPROVED** [review]

**Comment by blake** [comment]
Thanks for fixing this!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/536446.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 69c19ca9fc191af90c8e04316b5c87d3e9baa8cd onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 69c19ca9fc191af90c8e04316b5c87d3e9baa8cd onto `release/1.11.x` succeeded!

**Pull request merged**
