### PR TITLE
Contribution guide

### PR DESCRIPTION
**Pull request by freddygv**
This PR adds a contribution guide, primarily pulling ideas from those of [Vault](https://github.com/hashicorp/vault/blob/master/CONTRIBUTING.md) and [Packer](https://github.com/hashicorp/packer/blob/master/.github/CONTRIBUTING.md). Existing docs about developing Consul were moved from the README. 

-------------

#### Issues around serfHealth
As stated in the contribution guide, creating sessions after a test agent/client leads to flaky tests. This is because [here](https://github.com/hashicorp/consul/blob/master/agent/consul/state/session.go#L192) sessionCreateTxn verifies that expected checks are registered, and occasionally the Serf health check has not been registered yet.

This has typically been addressed a few ways:
1. Waiting for the serf checks to be registered:
    a. [testrpc.WaitForTestAgent](https://github.com/hashicorp/consul/blob/master/testrpc/wait.go#L44) when using `agent.NewTestAgent`.
    b. [testutil.WaitForSerfCheck](https://github.com/hashicorp/consul/blob/master/testutil/server.go#L399) when using `api.makeClient`.

2. Creating sessions without checks with [session.CreateNoChecks](https://github.com/hashicorp/consul/blob/master/api/session.go#L46:19).

#### General guidance 

Direct solutions such as creating sessions without checks is preferable to adding waits whenever possible. The more waits accumulate, the greater the risk of timing out. There has also been some potentially related behavior around tests running for longer than the `go test` timeout and then getting killed by Travis for not showing output. Example [here](https://travis-ci.org/hashicorp/consul/jobs/430942918).

Narrower solutions such as waits for a health check are preferable to wrapping the whole test in a retry function. 

However, if needed, a targeted retry with `testutil`'s default configuration can be used as done [here](https://github.com/hashicorp/consul/blob/master/agent/agent_endpoint_test.go#L555). 

#### Debugging other types of flakyness

For tests that are not failing due to a missing serfHealth check, there are times when `WaitForTestAgent` can still greatly increase their stability. 

Since the `test-flake` goal provides all Consul log output for the failed run, `Printf()` style debugging has been useful in the past. 

#### Verifying test improvements

Stability improvements should be validated with a run through the `test-flake` goal. The default settings for `FLAKE_CPUS` and `FLAKE_N` are typically enough to expose a test as flaky. Though increasing the number of iterations with `FLAKE_N` boosts the confidence that the test will not fail in CI. 

If a test in an incoming PR looks like it might become flaky, it may be appropriate to request that the test be run in this repro environment. 

#### Preventing regressions
If the CI build for a PR fails there are two ways to verify that a regression has not occurred:
* Ensuring that all tests pass locally
* Re-trying the failed CI jobs until the failing jobs/tests pass (requires maintainer permissions)

#### Outstanding concerns

As mentioned in the general guidance, there are cases when adding too many waits can lead to strange behavior. [Here](https://travis-ci.org/hashicorp/consul/jobs/416588976) is one example. In that job we can see that four tests took over 300 seconds each, when normally they do not take more than a couple seconds. (In that PR all API tests that used makeClient had a wait for serfHealth, most of those have since been removed)

Also, when this kind of situation happens, the retry built into the makefile does not kick in. `go test` will time out, then no output is generated, and finally Travis kills the job for the lack of output.

### CODE REVIEW

**Comment by pearkes** [comment]
@freddygv Looks awesome. I know you're still WIP from the looks of the PR description so just ping me and I will take a close look!

**Comment by pierresouchay** [comment]
That's a great addition : I spent so much time fighting with Travis, having clear guidelines for test is really a good idea

**Comment by freddygv** [comment]
@pearkes Thanks! You can start taking a closer look and submitting comments to the guide itself. The WIP tag is more for the info dump I wanted to leave in this PR's context comment above.

**Comment by pearkes** [comment]
@freddygv just wanted to get this merged but please do keep improving it as you see fit!

**Pull request merged**
