### PR TITLE
Check NXDOMAIN after filtering nodes

### PR DESCRIPTION
**Pull request by ryanbreen**
Move the check for NXDOMAIN below the service health filter.

### CODE REVIEW

**Comment by armon** [comment]
@ryanbreen Could you add a test to verify the behavior is as we expect?

**Comment by ryanbreen** [comment]
Sure

**Comment by ryanbreen** [comment]
Test case added.  It works after the fix and fails without the fix, and I think this covers everything we want to cover.

**Comment by armon** [comment]
Thanks!

**Pull request merged**
