### PR TITLE
Fixes #19266 : CLI: consul operator autopilot set-config -disable-upgrade-migration false not working

### LINKED ISSUE #19266: CLI: consul operator autopilot set-config -disable-upgrade-migration false not working
#### Overview of the Issue

After `disable-upgrade-migration ` is set to true, it can't be reset to false using the format of `-disable-upgrade-migration false`. Although `-disable-upgrade-migration=false` works, this inconsistency in the CLI will confuse the users.

Further, there might be more cli sub-command with boolean argument have this issue.

---

#### Reproduction Steps

Steps to reproduce this issue

1) start a single server agent,
2) `consul operator autopilot set-config -disable-upgrade-migration true` ,
3) `consul operator autopilot get-config`  to verify disable-upgrade-migration  is true,
4) `consul operator autopilot set-config -disable-upgrade-migration false`  to set it back to false
5) `consul operator autopilot get-config`  is still true and auto migration won't happen

### Consul info for both Client and Server

- Consul 1.16.2+ent
- Consul 1.17.0-rc1+ent

### PR DESCRIPTION
**Pull request by vijayraghav-io**
### Description

fixes #19266 

### Testing & Reproduction steps

Steps to reproduce this issue

1. start a single server agent,
2. consul operator autopilot set-config -disable-upgrade-migration true ,
3. consul operator autopilot get-config to verify disable-upgrade-migration is true,
4. consul operator autopilot set-config -disable-upgrade-migration false to set it back to false
5. consul operator autopilot get-config is still true and auto migration won't happen

### Links

Root cause : 
The issue is occuring from this loc - https://github.com/hashicorp/consul/blob/6ffcf28df036b65fd377fd4c739402cc55e6c41b/command/operator/autopilot/set/operator_autopilot_set.go#L76C12-L76C31
flag.FlagSet.Parse() method which is inbuilt or standard go package method.

The standard flag package in Go library does not support boolean flags in format : -flag x 
Refer : https://pkg.go.dev/flag#:~:text=The%20following%20forms%20are%20permitted%3A

Proposed Solution : 
Convert -flag x to -flag=x

### PR Checklist

* [x] updated test coverage
* [ ] external facing docs updated
* [ ] appropriate backport labels added
* [x] not a security concern

### CODE REVIEW

**Comment by vijayraghav-io** [comment]
@huikang,
updated to support following scenario as it used to work before:

Example : 
`consul operator autopilot set-config -disable-upgrade-migration -cleanup-dead-servers=false -min-quorum 5`

In the above example the value for boolean flag -disable-upgrade-migration is not provided, so the value will be assumed to be true. This works the same way , while also handling `-disable-upgrade-migration false -cleanup-dead-servers=false -min-quorum 5` scenario.

**Comment by huikang** [comment]
@vijayraghav-io , thanks for the PR. As we are approaching the 1.17 GA, it will be slow to review any new PRs. Will get back to you when the GA work is done.

**Comment by vijayraghav-io** [comment]
Hi @huikang, Kindly consider this as a reminder if PRs can be reviewed. Along with this one, there are few PRs waiting for review:

https://github.com/hashicorp/consul/pull/19427 - Displays Certification expiry in UI as notification.
https://github.com/hashicorp/consul/pull/19609 - Merges arguments from cmd and service definition file.
https://github.com/hashicorp/consul/pull/18473 - Using Weakdecode for parseHttpHandlerConfig.
https://github.com/hashicorp/consul/pull/18326 - KV get incremental update.
https://github.com/hashicorp/consul/pull/18456 - Services Tab - improvement in unhealthy marking.
https://github.com/hashicorp/consul/pull/19291 - CLI: consul operator autopilot set-config -disable-upgrade-migration false not working.

**Comment by vijayraghav-io** [comment]
Hi, @huikang @david-yu @jkirschner-hashicorp ,
Reminding if these PRs (in prev comment) can be reviewed.

**Comment by vijayraghav-io** [comment]
Hi @huikang,
Wish you Happy New Year!
Reminding to review these PRs.

**Comment by huikang** [comment]
@vijayraghav-io , happy new year! We had some internal discussions on how to approach this bug. I will follow-up with you with the details. Thanks.

**Comment by vijayraghav-io** [comment]
Sure @huikang Thankyou! will look forward for your follow-up. 
Can you also please look into other PRs I listed in above comments.

**Comment by vijayraghav-io** [comment]
Reminding to review or take this PR forward.

**Pull request closed without merging**
