### PR TITLE
docs: Add note about configurable KV size in FAQ

### PR DESCRIPTION
**Pull request by blake**

### CODE REVIEW

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/386462.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 26b8e8904b423aa7dafd2a8e926beeec30018026 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 26b8e8904b423aa7dafd2a8e926beeec30018026 onto `release/1.10.x` succeeded!

**Pull request merged**
