### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by thisisnotashwin**

### CODE REVIEW

**Review by david-yu — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/453091.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit fd7f670f1207a6a643d8a17890c68e37ac4163be onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit fd7f670f1207a6a643d8a17890c68e37ac4163be onto `release/1.11.x` succeeded!

**Pull request merged**
