### PR TITLE
Add changelog to backported bug fix for Topology Metrics

### PR DESCRIPTION
**Pull request by kaxcode**

### CODE REVIEW

**Review by mikemorris — APPROVED** [review]

**Comment by mikemorris** [comment]
Heh, I'm a little confused why the changelog CI check is failing for this...

**Comment by kaxcode** [comment]
> Heh, I'm a little confused why the changelog CI check is failing for this...

It just needs a `no-chanelog` label beacause the changelog PR doesn't need a changelog 😂 @mikemorris

**Comment by mikemorris** [comment]
Oooh, yea just read through the logic in the bash script, didn't realize it was specifically checking for a changelog entry for _this_ PR only, LGTM!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/401857.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 2df7d13354bd65c48896a54d76971659b45a68e5 onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 2df7d13354bd65c48896a54d76971659b45a68e5 onto `release/1.9.x` succeeded!

**Pull request merged**
