### PR TITLE
Option to disable hostnames from telemetry

### LINKED ISSUE #1241: Telemetry including host in the metric name
Hi folks,

I noticed that some of the metrics include the consul host:

```
consul.consul-i-8de39448.runtime.total_gc_pause_ns
consul.consul-i-8de39448.runtime.num_goroutines
```

vs

```
consul.consul.catalog.deregister
consul.consul.fsm.kvs.lock
```

Is there a way to not have Consul include the host in the metric (which makes it act as a different metric, later instead of former) ?

This way we dont have to rely on extracting the source host from the metricic using regexes.

### PR DESCRIPTION
**Pull request by nbrownus**
This fixes #1241

### CODE REVIEW

**Comment by scalp42** [comment]
Thanks a lot @nbrownus :+1:

**Comment by scalp42** [comment]
Any chance to look at this @slackpad following @nbrownus PR ? Would be greatly appreciated.

**Comment by slackpad** [comment]
Hi @nbrownus - thanks for this! Once we get 0.6 rolled out I'll work with you to review this so we can get it into the following release.

**Comment by BRMatt** [comment]
@slackpad Aside from the merge conflict, is there anything stopping this PR from being merged? I have some time this week and could having a shot at rebasing it if @nbrownus is busy.

**Comment by nbrownus** [comment]
Rebased, `dogstatsd` config merged in.

**Comment by scalp42** [comment]
thanks a lot again @nbrownus much appreciated

**Comment by BRMatt** [comment]
Thanks @nbrownus! :heart:

**Comment by slackpad** [comment]
Thanks for the PR - looks great!

**Pull request merged**
