### PR TITLE
Create glossary.mdx

### PR DESCRIPTION
**Pull request by tsoysergey**

### CODE REVIEW

**Review by tsoysergey — COMMENTED** [review]
stable-website

**Comment by tsoysergey** [comment]
@dnephin can you please help me out with this merge? I'm new to github and I do not quite understand why I can not pass all the checks.

**Review by blake — CHANGES_REQUESTED** [review]
Hi @tsoysergey, thanks for your contribution.

Would you mind rewording the commit message to state that you're fixing the grammar for a section in the glossary? That would more accurately describe the changes being made to this file.

Thanks.

**Review by blake — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/455382.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 978699943f756335cf34131e057ede1408f0fb0e onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 978699943f756335cf34131e057ede1408f0fb0e onto `release/1.10.x` succeeded!

**Pull request merged**
