### PR TITLE
docs: mention that service defaults upstream config sections should not contain wildcards

### PR DESCRIPTION
**Pull request by rboyer**

### CODE REVIEW

**Review by freddygv — COMMENTED** [review]
I just noticed that the UpstreamConfig.Defaults has Name/Namespace specified in the docs, but validation is going to reject those. Can you remove those as well?

**Comment by rboyer** [comment]
Removed.

**Review by freddygv — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/392878.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 24a94023908fbcdfa8ee6769d6d4f9529ef9f0b2 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 24a94023908fbcdfa8ee6769d6d4f9529ef9f0b2 onto `release/1.10.x` succeeded!

**Pull request merged**
