### PR TITLE
Split HTTP API documentation into a page per section

### PR DESCRIPTION
**Pull request by ryanuber**
The HTTP API documentation page has gotten fairly large over time. This splits the page into one page per "section", meaning K/V is a page, Health Checks are a page, etc., and gives each page a sub-nav link on the left hand nav pane:

httpdocs

/cc @pearkes because I'm rather terrible at SCSS and may have made some mistake(s).
/cc @sethvargo because I'm sure this will affect SEO in some way.

### CODE REVIEW

**Comment by ryanuber** [comment]
@pearkes @sethvargo Feel free to pull/update the branch as well if you need to.

**Comment by blalor** [comment]
Does this mean there's no interest in the api documentation I prototyped?

**Comment by ryanuber** [comment]
@blalor i think we are definitely interested in having auto generated docs. This was just a fairly easy split of the existing docs that makes them much easier to navigate and easily fits into the existing consul website.

**Comment by blalor** [comment]
👍

**Comment by armon** [comment]
LGTM!

**Comment by ryanuber** [comment]
ping @pearkes @sethvargo, any input? just a :+1: if you think its ok as-is would be fine.

**Comment by pearkes** [comment]
LGTM!

**Comment by sethvargo** [comment]
:+1:

**Pull request merged**
