### PR TITLE
Add support for RHEL7/Systemd in Terraform example

### PR DESCRIPTION
**Pull request by moofish32**
This change started out as a quick update to RHEL 7 support (aka systemd), in
the process I realized most of the other platforms could use an update. While
trying to cleanup there I discovered I was repeating of bunch of information
that might be better maintained in one place - as a result:
 * consolidated server.sh and install.sh
 * removed upstart-join.conf in a favor of join flag in the consul start
 * removed platform specific folders and increased complexity of install.sh to
   include handling the differences
 * updated and extracted consul version
 * added a specific condition for centos6 - which is not ideal

### CODE REVIEW

**Comment by slackpad** [comment]
Hi @moofish32 thanks for updating these! If you've gotten to test them then we can merge them in case they are useful to others. Only thing I saw from a quick look is that `GOMAXPROCS` doesn't need to be set any more with Go 1.5+.

**Comment by moofish32** [comment]
@slackpad - I need to go back through and plum the `rhel7` variable and a few others. I will also kill the `GOMAXPROCS`

Thinking about this again though I'll probably call it `centos7`. It will take a couple of days to get the free time, in a bit of the busy season over here (as if there is a non-busy season).

**Comment by moofish32** [comment]
@slackpad - so this change drifted a little. When I started I was going after just one and then I found a few others. In an effort to slim down I consolidated scripts. If you don't like this, let's just roll it back and I'll add only the rhel7/centos7 piece. I was a little annoyed I had to `subscribe` to use the centos AMI.

I'm looking into build issue with sudo. I may need to back track a bit.

**Comment by moofish32** [comment]
rebased test passing

**Comment by slackpad** [comment]
Hi @moofish32 it looks like you need another rebase. If you were able to test the older scripts then we can update them all, but if not I'd prefer if we just updated the version 7 ones.

**Comment by moofish32** [comment]
@slackpad rebased to master. A couple quick items:
* Tested - I ran the terraform script for each distro and verified the cluster was up with the right number of members. If there is a better way to test let me know.
* I updated all the Consul versions to 0.6.3, the PR you merged modified many to 0.5.x, was that intentional?
* The big change here is refactored the bash installers into one script. IMHO I think it's easier to maintain.

**Comment by moofish32** [comment]
@slackpad -- I am getting intermittent builds locally and on Travis. Is that new?

**Comment by slackpad** [comment]
Hi @moofish32 moving up to latest Consul is definitely the right thing - sorry I regressed that with the older PR. We have a few tests that are timing dependent that are a little flaky and we are working on those. Your changes definitely don't interact with the unit tests :-)

I was looking through old issues and found this one that we might want to roll into this PR since you're in here - https://github.com/hashicorp/consul/issues/1304. You definitely want all three (8300 for RPC, 8301 for LAN, 8302 for WAN) to be exposed for servers and (8301 for LAN) for clients, though if things are working perhaps these are getting exposed anyway? The comment about a reboot seems apt, too. Would it be possible for you to take a look at that?

**Comment by moofish32** [comment]
@slackpad  -- I was officially dominated by the linux distros today. I'll have a fix up in the next couple of days for all the issues you mentioned, but there is just enough difference between upstart in Ubuntu, Centos, and RHEL that I may have to move those back to separate files :( 

I thought about rendering a template inside a remote exec to append to file, but need to kick the tires one more time.

**Comment by moofish32** [comment]
@slackpad  -- All four OS variants are now tested and can be restarted. Obviously there is still an anchor dependency on the consul-0 host because that is the default join address. Please review and let me know if you find anything else.

**Comment by moofish32** [comment]
@slackpad  -- rebased to latest master

**Comment by slackpad** [comment]
@moofish32 thanks for all the work on this one! Looks good except we should knock this file out :-)

https://github.com/moofish32/consul/blob/update_terraform_rhel7/terraform/aws/terraform.tfvars

**Comment by moofish32** [comment]
@slackpad  -- great catch, bad miss on my part but it was at least only the names; removed file and rebased.

**Comment by slackpad** [comment]
@moofish32 thanks for all your work on this one!

**Pull request merged**
