### PR TITLE
ci: Fix merge conflicts cleanly

### PR DESCRIPTION
**Pull request by kisunji**
Turns out `stash pop` [attempts a merge](https://app.circleci.com/pipelines/github/hashicorp/consul/26874/workflows/17c33cb9-4e41-43f8-8822-0c590a1c47c9/jobs/573010)!

Instead of:
1. Stash `bindata_assetfs.go`
2. Checkout `ci/main-assetfs-build`
3. Merge `main`
4. Stash pop `bindata_assetfs.go`
5. Conflict!

We instead:
1. Reset `ci/main-assetfs-build` to `main`
2. Commit `bindata_assetfs.go`
3. Force push

### CODE REVIEW

**Comment by kisunji** [comment]
Hm I used rebase instead of merge to prevent merge commits but merges should be fast-forwarded according to my diagram

**Comment by eculver** [comment]
> I'd love for this to be a merge but as soon as something breaks the lockstep sync of main <-> ci/main-assetfs-build, ff is impossible

The `ci/main-assetfs-build` should always be based on latest `main` right? And people shouldn't be pushing directly to `ci/main-assetfs-build` right? So, we could we just force push `main` to  `ci/main-assetfs-build`? 

If it's just this one file, we could also just checkout the one file and create a new commit, but then we'd be losing the commit fidelity on `ci/main-assetfs-build`.

**Review by eculver — APPROVED** [review]
🚀

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/584639.

**Pull request merged**
