### PR TITLE
Fix formatting for webhook-certs Consul tutorial

### PR DESCRIPTION
**Pull request by stevenzamborsky**
### Description

Update formatting for webhook certs tutorial to fix the broken formatting that's currently present on the tutorial site.

### CODE REVIEW

**Review by david-yu — APPROVED** [review]

**Comment by david-yu** [comment]
Thanks for the changes!

**Comment by david-yu** [comment]
Probably worth having other folks on docs also looking at this as well due to capitalization and styling changes.

**Comment by stevenzamborsky** [comment]
No problem @david-yu ! I will also reach out to doc team like you suggested regarding those changes.  Note that I did just submit another commit to attempt to sync my whitespace changes.  Whitespace indentation is what was breaking the styling and it can be difficult to get whitespace changes committed in Git.

**Comment by david-yu** [comment]
This looks good upon re-review, I'll go ahead and merge.

**Review by trujillo-adam — APPROVED** [review]

**Pull request merged**
