### PR TITLE
docs: Remove ACLs section from k8s cluster peering page

### PR DESCRIPTION
**Pull request by boruszak**
### Description

Removes ACL specification section from k8s cluster peering page per [this conversation on Slack](https://hashicorp.slack.com/archives/CBXF3CGAF/p1704841360162039)

### PR Checklist

* [ ] updated test coverage
* [X] external facing docs updated
* [X] appropriate backport labels added
* [X] not a security concern

### CODE REVIEW

**Review by trujillo-adam — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
@boruszak, a backport is missing for this PR [20176] for versions [1.15,1.16,1.17] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@boruszak, a backport is missing for this PR [20176] for versions [1.15,1.16,1.17] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@boruszak, a backport is missing for this PR [20176] for versions [1.15,1.16,1.17] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@boruszak, a backport is missing for this PR [20176] for versions [1.15,1.16,1.17] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@boruszak, a backport is missing for this PR [20176] for versions [1.15] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Pull request merged**
