### PR TITLE
docs: Add namespace parameters to /agent/service* endpoints

### LINKED ISSUE #9710: Document that /agent/services supports ?ns and add to API client
#### Feature Description

1. The `/agent/services` endpoint supports namespaces but it's not documented (https://www.consul.io/api-docs/agent/service#list-services)
2. The API client doesn't support passing in a query object: https://github.com/hashicorp/consul/blob/master/api/agent.go#L525

### PR DESCRIPTION
**Pull request by blake**
Document supported namespace parameters for /agent/service* API endpoints.

Resolves #9710

### CODE REVIEW

**Comment by blake** [comment]
Notably missing in this PR are updates to the `/v1/agent/health/service/[id|name]/` endpoints. In my testing the API output from Consul 1.9.6 wildly differs from the current documented output. For example, the current output is missing the AggregatedStatus field.

When did the response format change for these API calls? Is there a need to document both response formats?

**Comment by dnephin** [comment]
`AggregatedStatus` is being set in the response here: https://github.com/hashicorp/consul/blob/v1.9.6/agent/agent_endpoint.go#L788-L799

I'm not sure how it could be missing from the response

**Comment by blake** [comment]
@dnephin Apologies. I meant to say "…the _current_ documented output is missing the AggregatedStatus field." The actual API response definitely contains that field.

**Comment by dnephin** [comment]
Ah! Seems like the field has always been there, added in 4f62a3b5285cef13f25d162f267b678e3b5c0d8e, but the docs didn't match the API response.

If we had API reference docs generated from the code, this type of error would a lot more rare I think.

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/414004.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit c89287dc77da5fab33c8a99a8c41324bf1800f65 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit c89287dc77da5fab33c8a99a8c41324bf1800f65 onto `release/1.10.x` succeeded!

**Pull request merged**
