### PR TITLE
fix broken test

### PR DESCRIPTION
**Pull request by rboyer**
Missed a test in #12711

### CODE REVIEW

**Review by dhiaayachi — APPROVED** [review]
🚀

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/633051.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 9fb8616bac5c27ef0137ee338c32706afdaf7d04 onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/633051)

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/633574.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 9fb8616bac5c27ef0137ee338c32706afdaf7d04 onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/633574)

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/633591.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 9fb8616bac5c27ef0137ee338c32706afdaf7d04 onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/633591)

**Pull request merged**
