### PR TITLE
Fixes #20064 Incorrect validation of proxy-defaults update

### LINKED ISSUE #20064: Incorrect validation of proxy-defaults update
#### Overview of the Issue

I am seeing an error in recognising the default protocol that is configured, when validating configuration updates through the api.

This is trapping k8s in a loop when it goes to reconcile config entries from CRDs.

However a manual PUT request with the same config gets the same error, so I believe this is a consul issue and independent of k8s.

In our setup, proxy-defaults sets a default protocol of http and we specify tcp explicitly for the (one or two) services that use it in their service-defaults.

#### Reproduction Steps

k8s consul-connect-injector error log:

```
2023-12-27T11:38:16.528Z	INFO	controller.proxydefaults	config entry does not match consul	{"request": "consul/global", "modify-index": 2951827}
2023-12-27T11:38:16.568Z	ERROR	Reconciler error	{"controller": "proxydefaults", "controllerGroup": "consul.hashicorp.com", "controllerKind": "ProxyDefaults", "ProxyDefaults": {"name":"global","namespace":"consul"}, "namespace": "consul", "name": "global", "reconcileID": "4ee1fc9d-abde-4392-b5c9-0594c3d3db90", "error": "updating config entry in consul: Unexpected response code: 500 (rpc error making call: discovery chain \"api-mock\" uses a protocol \"tcp\" that does not permit advanced routing or splitting behavior)"}
```

A manual PUT request with the same config gets the same error, so I believe this is a consul issue and independent of k8s

GET https://consul/v1/config/proxy-defaults/global

```
{
	"Kind": "proxy-defaults",
	"Name": "global",
	"Config": {
		"envoy_extra_static_clusters_json": "xxx",
		"protocol": "http"
	},
	"TransparentProxy": {},
	"MeshGateway": {},
	"Expose": {},
	"AccessLogs": {},
	"Meta": {
		"consul.hashicorp.com/source-datacenter": "xxx",
		"external-source": "kubernetes"
	},
	"Hash": 6318623746536045320,
	"CreateIndex": 336,
	"ModifyIndex": 2951827
}
```

api-mock does not have any specified defaults

GET https://consul/v1/config/service-defaults/api-mock return 404

I expect it to pick up the default protocol specified in proxy-defaults.

### Consul info for both Client and Server

Consul: 1.17.1, 5 server nodes
Env: EKS 1.27

### PR DESCRIPTION
**Pull request by vijayraghav-io**
### Description

Fixes #20064 

### Testing & Reproduction steps

**1. Apply proxy-defaults**
curl --location --request PUT 'http://localhost:8500/v1/config' \
--header 'Content-Type: application/json' \
--data '{
    "Kind": "proxy-defaults",
    "Name": "global",
    "Config": {
        "Protocol":"http"
    }
}
'
**2. Apply service-router**
curl --location --request PUT 'http://localhost:8500/v1/config' \
--header 'Content-Type: application/json' \
--data '{
    "Kind": "service-router",
    "Name": "api",
    "Routes":[{"Match":{"HTTP":{"PathPrefix":"/testservice"}},"Destination":{"Service":"testservice"}}]
}
'
**3. Apply proxy-defaults again, Now there should be no error**
curl --location --request PUT 'http://localhost:8500/v1/config' \
--header 'Content-Type: application/json' \
--data '{
    "Kind": "proxy-defaults",
    "Name": "global",
    "Config": {
        "Protocol":"http"
    }
}
'

### CODE REVIEW

**Comment by vijayraghav-io** [comment]
Hi @jkirschner-hashicorp , kindly take this PR for review.

**Comment by vijayraghav-io** [comment]
Hi @david-yu / @huikang , Kindly take this PR for review.

**Comment by reneeckstein** [comment]
Hi, any update here?

**Comment by vijayraghav-io** [comment]
Hi @reneeckstein ,
Waiting for PR review.

@david-yu , @huikang

**Comment by david-yu** [comment]
https://github.com/hashicorp/consul/pull/20481 supersedes this PR so will go ahead and close. Thank you for the investigation!

**Pull request closed without merging**
