### PR TITLE
ui: UI Release Merge (ui-staging merge)

### PR DESCRIPTION
**Pull request by johncowen**
This PR is a 'ui release' from ui-staging. All commits (apart from the final commit) have corresponding approved PRs and have already been individually squash merged to ui-staging.

This merge itself will not be squash merged in order to maintain PR history.

The final commit has not been approved previously but is a result of running `make ui` to ensure anyone building consul from master gets these UI changes.

### CODE REVIEW

**Comment by alvin-huang** [comment]
Makefile and ember exam changes all LGTM. Just a small nit pick but your commit message has a misspelling, might be easier to grep in the future if you change it to `assetfs` instead of `assetsfs`

**Comment by johncowen** [comment]
😆 whoopsie! Cool thanks Alvin thats that done also.

**Comment by johncowen** [comment]
Actually @alvin-huang , I'm kind of working my way towards a consistent way of doing these, is there anything else I can do with these type of merges that might be handy?

**Comment by alvin-huang** [comment]
@johncowen What is 'these' referring to? UI updates?

**Comment by johncowen** [comment]
Oh sorry yeah, one sec let me back up a bit.

So this PR merge is from my 'staging' branch to master, so a collection of PR's I've been doing over the last few weeks or months.

I realised this time around that it would be a good idea to run a `make ui` and add a commit of the result of that onto the end of the PR that anyone building from master would get the updated UI in their build. The assetfs file is kind of like the artifact produced by a UI 'release'

When you mentioned being able to grep the git log for `assetfs` it got me wondering if there's anything else could do with these types of PRs, for example for any future searching or to provide historical information etc. I always try to add a `ui:` to the front of the commit messages for ui PRs but maybe we could add something different for the build of assetfs, and I could try to make a point of consistently doing that also? I dunno, maybe I'm overthinking things.

**Comment by alvin-huang** [comment]
Ah, adding UI in front would be fine or omitting it would be fine too. In general, no one will be PRing that file nor modifying it manually so we shouldn't have to trace the history of it outside of 'build the current JS files and commit the go file'.

**Pull request merged**
