### PR TITLE
Fix data race

### LINKED ISSUE #4357: Data race in github.com/hashicorp/consul/watch library
#### Overview of the Issue

When using the `github.com/hashicorp/consul/watch` package as a library in client code, there appears to be a data race detected by the race detector. Full race detector output is in this gist: https://gist.github.com/KJTsanaktsidis/acef6be673f311488c4ee06d80d74b81

It appears to be a race between setting `p.cancelFunc` here:

```
  github.com/zendesk/outbound/vendor/github.com/hashicorp/consul/watch.makeQueryOptionsWithContext()
      /go/src/github.com/zendesk/outbound/vendor/github.com/hashicorp/consul/watch/funcs.go:310 +0xd7
```
and reading it here:

```
  github.com/zendesk/outbound/vendor/github.com/hashicorp/consul/watch.(*Plan).Stop()
      /go/src/github.com/zendesk/outbound/vendor/github.com/hashicorp/consul/watch/plan.go:136 +0xd1
```

I guess setting `p.cancelFunc` in `makeQueryOptionsWithContext` should be protected by `p.stopLock`, but it's less obvious to me how to protect the places where `p.cancelFunc` is called. 

One option might be to turn `p.stopLock` into a RWMutex and do this in the places where it is called:
```
defer func(){
    p.stopLock.RLock()
   defer p.stopLock.RUnlock()
   if p.cancelFunc != nil {
       p.cancelFunc()
    }
}()
```

although this is kind of ugly... Another option might be to return a local copy of `cancel` from `makeQueryOptionsWithContext` and call that in the places where `p.cancelFunc` is currently called (except for inside `Stop` of course).

I'm happy to submit a patch for either of these two options (or any other way you can think of to slice this).

#### Reproduction Steps

I had this function to setup a Consul watch, and was running in the race detector. It's not a full program but I think it illustrates the issue - see shardelection.go in the gist: https://gist.github.com/KJTsanaktsidis/acef6be673f311488c4ee06d80d74b81

This was using the `v1.2.0` tag of Consul.

### Consul info for both Client and Server

N/A, it's a client library issue

### Operating system and Environment details

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
$ uname -a
Linux 8ac6a25517ab 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by dawxy**
Fix #4357

### CODE REVIEW

**Comment by banks** [comment]
Thanks @dawxy adding to our milestone to be looked at before next release. A quick glance seems simple but as with all concurrency things will need a bit of careful though to reason about whether it could ever be called in a way that will deadlock etc.

**Comment by dawxy** [comment]
@banks 
I checked it again and found no deadlocks.

**Comment by banks** [comment]
> I see one other problem here which is that we could be setting a cancel function after the watch has already been stopped.

Is that a problem? Calling cancel on an already-cancelled Context is safe.

**Comment by mkeeler** [comment]
@banks Its possible that comment was misleading. The actual problem is that we could have go routines sitting around for a long time after they should be stopped.

If the watch gets stopped before setting the cancel func but after the first stop check here: https://github.com/hashicorp/consul/blob/57b5a1de0c5430ae881e4bd941731ec729f27dc9/watch/plan.go#L63-L71

Then the watch still gets executed but nothing can ever attempt to cancel it. It isn't a huge problem but we could for example detect while holding the lock that the watch is stopped and execute the new cancel func. That would prevent the watch from hanging around too long.

**Comment by banks** [comment]
Gotcha. Agree we should avoid leaking the goroutines here. Great catch @mkeeler - exactly the kind of thing I meant about being careful with concurrency stuff!

@dawxy are you keen to implement that?  It's trivial and we can do it but don't want to hijack your contribution without asking!

**Comment by dawxy** [comment]
@mkeeler 
I think it's still necessary to stop lock protection to read the modified cancelFunc in cancelFunc and makeQueryOptionsWithContext() when calling plan.Stop().

**Comment by dawxy** [comment]
@mkeeler PTAL

**Pull request merged**
