### PR TITLE
Add GRPC to HealthCheckDefinition

### PR DESCRIPTION
**Pull request by VictorBac**
Hi guys,

Add GRPC to HealthCheckDefinition because it missing, and it is required for consul-esm to handle GRPC health-checks.

I have no idea if there is anything else to add to this PR. If there is please tell me.

### CODE REVIEW

**Comment by VictorBac** [comment]
@kisunji I see you've been tagged on other PRs. Can you help me validate this ?

**Comment by VictorBac** [comment]
ok, good to know. Thanks for the info

**Comment by kisunji** [comment]
`api.HealthCheckDefinition` has a corresponding type `structs.HealthCheckDefinition` which gets converted in https://github.com/hashicorp/consul/blob/097e1645e32502e988463b73a4f218b1057ce2d0/agent/txn_endpoint.go#L259-L293

Could you add the field to be updated here as well?

Just a caveat that merging this PR will expose the field but I suspect consul-esm will need to be updated to handle it on their side.

**Comment by VictorBac** [comment]
@kisunji  Thanks for the review !

I think GRPCUseTLS is missing too, so I added it.

**Review by kisunji — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/558672.

**Pull request merged**
