### PR TITLE
acl: remove some of the duplicate resolve token methods

### PR DESCRIPTION
**Pull request by dnephin**
This is the first step in #11690, best viewed by individual commit

* Embed `ACLResolver` in `Client` and `Server`
* remove the methods off of `Client` and `Server`, and move one to `ACLResolver`

### CODE REVIEW

**Review by freddygv — APPROVED** [review]

**Review by markan — APPROVED** [review]

**Comment by dnephin** [comment]
Since this is a low risk refactor, and we may want to backport some changes based on this change, I'm going to attempt to auto-backport this. If it fails we can batch up the manul backports later on when we need them.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/571086.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit b2b84e7fc6b48365e11a54e39ed2d160e73acc05 onto `release/1.11.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit b2b84e7fc6b48365e11a54e39ed2d160e73acc05 onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/571086)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit b2b84e7fc6b48365e11a54e39ed2d160e73acc05 onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/571086)

**Pull request merged**
