### PR TITLE
Consul k8s docs typo

### PR DESCRIPTION
**Pull request by im2nguyen**
@sofixa Added missing "primary cluster" in the multi-cluster k8s install docs.

### CODE REVIEW

**Review by david-yu — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/676210.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/676290.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 02732d8d0f1630a1ffe78c4c7f277f4f88d6a045 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 02732d8d0f1630a1ffe78c4c7f277f4f88d6a045 onto `release/1.12.x` succeeded!

**Pull request merged**
