### PR TITLE
Doc changes

### PR DESCRIPTION
**Pull request by luoxuan00733**
- added an illustration of various gateway types into the gateway overview page

### CODE REVIEW

**Review by karl-cardenas-coding — APPROVED** [review]
Looks awesome 👍🏼

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/546668.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 51a77533e4d4e69c44b470bbf0169f01f683bd70 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 51a77533e4d4e69c44b470bbf0169f01f683bd70 onto `release/1.11.x` succeeded!

**Pull request merged**
