### PR TITLE
Allow to restrict servers that can join a given Serf Consul cluster.

### PR DESCRIPTION
**Pull request by pierresouchay**
Based on work done in https://github.com/hashicorp/memberlist/pull/196
This allows restricting the IP ranges that can join a given Serf cluster and be a member of the cluster.

Restrictions on IPs can be done separately using 2 new differents flags and config options to restrict IPs for both LAN and WAN Serf.

This will allow to secure a bit more clusters as well as protecting non-encrypted clusters from an agent in dev mode to join clusters and thus fixing https://github.com/hashicorp/consul/pull/5916

### CODE REVIEW

**Comment by pierresouchay** [comment]
Hello @mkeeler,

Since you were part of discussions in #5916 and memberlist, do you think it might work?

Have a good day

**Comment by i0rek** [comment]
This PR looks good. Could you rebase so that I can review?

**Comment by pierresouchay** [comment]
@i0rek DONE: had to revamp doc

**Comment by pierresouchay** [comment]
@i0rek Done, added the new Unit test for HCL/JSON serialization

**Comment by pierresouchay** [comment]
@i0rek The test failing is `TestAutopilot_MinQuorum` and has nothing to do with the patch... re-force-pushing

**Pull request merged**
