### PR TITLE
Display nicely Networks (CIDR) in runtime configuration

### PR DESCRIPTION
**Pull request by pierresouchay**
CIDR mask is displayed in binary in configuration.
This add support for nicely displaying CIDR in runtime configuration.

Currently, if a configuration contains the following lines:
```json
  "http_config": {
    "allow_write_http_from": [
      "127.0.0.0/8",
      "::1/128"
    ]
  }
```

A call to `/v1/agent/self?pretty` would display
```json
  "AllowWriteHTTPFrom": [
            {
                "IP": "127.0.0.0",
                "Mask": "/wAAAA=="
            },
            {
                "IP": "::1",
                "Mask": "/////////////////////w=="
            }
  ]
```
This PR fixes it and it will now display:
```json
   "AllowWriteHTTPFrom": [ "127.0.0.0/8", "::1/128" ]
```

### CODE REVIEW

**Comment by pierresouchay** [comment]
Note: it will also benefit to #5916 once https://github.com/hashicorp/memberlist/pull/196 is merged (cc @mkeeler)

**Comment by pierresouchay** [comment]
@mkeeler DONE

**Comment by pierresouchay** [comment]
damned unstable tests

**Comment by pierresouchay** [comment]
Set https://www.consul.io/docs/agent/options.html#telemetry-prometheus_retention_time to a few hours (for instance 72h)

**Comment by mkeeler** [comment]
One day our test suite will run reliably. Its been improving for sure but we aren't quite there yet.

**Pull request merged**
