### PR TITLE
changelog: snapshot-agent acl token fix for CLI and ENV

### PR DESCRIPTION
**Pull request by DanStough**
### Description
Adding a changelog for an enterprise-only snapshot agent fix.

### Testing & Reproduction steps
N/A

### PR Checklist

* [ ] ~updated test coverage~
* [ ] ~external facing docs updated~
* [X] not a security concern
* [ ] ~checklist [folder](./../docs/config) consulted~

### CODE REVIEW

**Review by kisunji — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/651332.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 8cddaef47b8e060a0cf3198a6c8b944441a297c2 onto `release/1.12.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 8cddaef47b8e060a0cf3198a6c8b944441a297c2 onto `release/1.11.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 8cddaef47b8e060a0cf3198a6c8b944441a297c2 onto `release/1.10.x` succeeded!

**Pull request merged**
