### PR TITLE
agent: consolidate handling of 405 Method Not Allowed

### PR DESCRIPTION
**Pull request by magiconair**
This patch consolidates the handling of the 405 Method Not Allowed status code and updates documentation and methods according to both each other and reality.

There is a new test which covers all endpoints and which replaces the spurious other tests for this status code.

I'm open to move the definition of which status codes are allowed somewhere else or to refactor the code to something more readable or better suited.

### CODE REVIEW

**Comment by magiconair** [comment]
Hmm, two tests are still failing which I'll fix but I'd appreciate feedback on the approach nevertheless.

**Comment by slackpad** [comment]
Thought about a helper so we don't have to stutter the methods into the error, but it seemed like overkill for 3 lines of code, so the approach looks good.

**Comment by magiconair** [comment]
OK, then I'll just merge the doc change for now.

**Comment by magiconair** [comment]
Rebased to master

**Comment by kyeett** [comment]
Is there a way to disable this check in >1.0.0, like a flag? We have some legacy system that were run on 0.6.3, but I would like to use the consul docker with is using 1.0.1, thus breaking the legacy system.

Thanks!

**Comment by slackpad** [comment]
Hi @kyeett unfortunately not - we wanted to break these and tighten up the handling as part of 1.0 so we would be in a better position to support Consul's interfaces for the long term.

**Comment by kyeett** [comment]
A colleague helped me find the somewhat hidden consul:0.9.3 docker image :-) We will use that for now!

**Pull request merged**
