### PR TITLE
1.18 UI regen

### PR DESCRIPTION
**Pull request by sarahalsmiller**
### Description

Try setting worktree to dirty 

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [ ] appropriate backport labels added
* [ ] not a security concern

### CODE REVIEW

**Comment by hc-github-team-consul-core** [comment]
This PR has diffs in `agent/uiserver/dist`. If the changes are intentional, add the label `pr/update-ui-assets`. Otherwise, revert changes to `agent/uiserver/dist`.

**Comment by hc-github-team-consul-core** [comment]
This PR has diffs in `agent/uiserver/dist`. If the changes are intentional, add the label `pr/update-ui-assets`. Otherwise, revert changes to `agent/uiserver/dist`.

**Comment by hc-github-team-consul-core** [comment]
This PR has diffs in `agent/uiserver/dist`. If the changes are intentional, add the label `pr/update-ui-assets`. Otherwise, revert changes to `agent/uiserver/dist`.

**Comment by hc-github-team-consul-core** [comment]
This PR has diffs in `agent/uiserver/dist`. If the changes are intentional, add the label `pr/update-ui-assets`. Otherwise, revert changes to `agent/uiserver/dist`.

**Review by wangxinyi7 — APPROVED** [review]

**Pull request merged**
