### PR TITLE
Remove demo directory

### PR DESCRIPTION
**Pull request by dnephin**
Related to #11664

These demo setups are no longer maintained. https://github.com/hashicorp/demo-consul-101 exists for a maintained demo that uses docker-compose.

Since these demos are not maintained, and may no longer work this PR removes them.

### CODE REVIEW

**Review by kisunji — APPROVED** [review]
🎉 Love deleting top-level directories

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/567080.

**Comment by mikeobr** [comment]
This broke a link on the tutorial page: https://learn.hashicorp.com/tutorials/consul/get-started-create-datacenter#set-up-the-environment, the `demo Vagrant file` linked to this deleted directory.

**Comment by dnephin** [comment]
Thanks for calling out this broken link! We've got a PR to fix the learn guide here: https://github.com/hashicorp/learn/pull/4335

**Pull request merged**
