### PR TITLE
docs: added information about a conflict when using auto_config and a…

### PR DESCRIPTION
**Pull request by karl-cardenas-coding**
This PR adds information about a conflict when using `auto_encrypt` with `auto_config`

### CODE REVIEW

**Comment by blake** [comment]
> @blake Is this what you had in mind?

Yes, however would it be possible to indent the callout under the TLS option?

**Comment by karl-cardenas-coding** [comment]
@blake Done 😄 

image

image

**Review by blake — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/437567.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 222ce6b6212da52ef226c2fde2827b9e9d2d6d0e onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 222ce6b6212da52ef226c2fde2827b9e9d2d6d0e onto `release/1.10.x` succeeded!

**Pull request merged**
