### PR TITLE
docs: Add admin partitions to Enterprise Overview page

### PR DESCRIPTION
**Pull request by david-yu**

### CODE REVIEW

**Review by karl-cardenas-coding — APPROVED** [review]
Good call David

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/532231.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit a20a6111b5359a0b02c69a37dc3155128f9023fb onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit a20a6111b5359a0b02c69a37dc3155128f9023fb onto `release/1.11.x` succeeded!

**Pull request merged**
