### PR TITLE
Make RPC, Serf LAN, Serf WAN port configurable from CLI

### PR DESCRIPTION
**Pull request by azam**
Currently RPC, Serf LAN, Serf WAN ports are only configurable through configuration files.
In a deployment environment that chooses command line over configuration files, having to be able to define the ports from the CLI is helpful.

### CODE REVIEW

**Comment by banks** [comment]
Hey @azam, thanks for the PR.

We already allow several differnt options for specifying these things so I'd be reluctant to add yet more unless there is a really compelling reason you can't use an existing one.

Is there a reason you can't just use `consul agent -hcl 'ports { serf_lan = 1234, serf_wan = 2345 }'` etc?

**Comment by azam** [comment]
@banks 
I happen to work on a build and deploy environment where executables' arguments are scanned and audited, so having a 'normal' argument as opposed to an opaque string argument is preferable for tokenizing and increase visibility to what values goes into which arguments.

Having to use hcl means that we have to parse them (and implement a parser for it) first to achieve what the same level of visibility as with normal arguments.

There are other ways getting around that, and one of them is this change PR. It is a matter of convenience and preference. I got your point, but still I thought this was worth trying.

Feel free to merge or close this.

**Comment by banks** [comment]
@azam thanks for the context. You present a more compelling reason than any I could come up with so I'll leave this open for discussion on our weekly team call to review community issues and PRs.

Thanks!

**Comment by pearkes** [comment]
Can you add tests for this (`flags_test.go`)? We agree this is a good addition. See #2263 for some precedent. I don't think dns port is tested from that PR so would be great to add tests for all ports confirmed from the CLI as part of your change.

**Comment by pearkes** [comment]
Also if you rebase the CI (Travis) should be a bit more reliable for tests here.

**Comment by azam** [comment]
@banks @pearkes 
Sorry for the delay. Thank you for the considering this!
Rebased and added tests and doc for the change.

**Pull request merged**
