### PR TITLE
website: Upgrade <HashiStackMenu /> to latest

### PR DESCRIPTION
**Pull request by EnMod**
[:mag: Preview Link](https://consul-git-nqwebupdate-hashistackmenu-hashicorp.vercel.app/)

---

This PR upgrades `<HashiStackMenu />` to the latest version.

### CODE REVIEW

**Review by BRKalow — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/520349.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit b768f9f97cf76e1e3ff3a3498c90bf5865ec9e14 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit b768f9f97cf76e1e3ff3a3498c90bf5865ec9e14 onto `release/1.11.x` succeeded!

**Pull request merged**
