### PR TITLE
website: chore: upgrades react-content

### PR DESCRIPTION
**Pull request by BRKalow**
Upgrades `@hashicorp/react-content`, which removes explicit left alignment on table headings, allowing markdown short-hand for table alignment,

### CODE REVIEW

**Review by jherschman — APPROVED** [review]
Awesome, looking forward to this update!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/558595.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit d7a0392dbce09ca62e2a8992650401237c89a5af onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit d7a0392dbce09ca62e2a8992650401237c89a5af onto `release/1.11.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/558595)

**Pull request merged**
