### PR TITLE
NET-4240 - Snapshots are failing on Windows 

### PR DESCRIPTION
**Pull request by absolutelightning**
### Description

Updates version of https://github.com/rboyer/safeio/pull/3 to github.com/rboyer/safeio v0.2.3. To fix snapshot save in windows. More description here - https://github.com/rboyer/safeio/pull/3

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [ ] appropriate backport labels added
* [ ] not a security concern

### CODE REVIEW

**Comment by absolutelightning** [comment]
@david-yu please let me know what backports needs to be added. Thanks.

**Comment by david-yu** [comment]
Added 1.14.x-1.16.x for backports since the customer is on an older version. @absolutelightning could you also include a changelog?

**Comment by absolutelightning** [comment]
@rboyer https://github.com/hashicorp/consul/actions/runs/5698317283/job/15480946596?pr=18302
Can you help why is this failing? I ran go mod tidy on local but nothing changed.
also I see one more PR - https://github.com/hashicorp/mog/pull/36
Which one we should take forward?

**Comment by rboyer** [comment]
Did you try `make go-mod-tidy` in the root? We have a wrapper that makes sure to update the myriad of `go.mod` files through the repo in the right order.

**Review by rboyer — APPROVED** [review]

**Pull request merged**
