### PR TITLE
Creating a changelog entry for  #12565

### PR DESCRIPTION
**Pull request by mkeeler**
Adding a changelog entry for a community PR I just merged.

### CODE REVIEW

**Review by markan — APPROVED** [review]

**Review by eculver — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/625793.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit e941d50bc83841110e4628e508c14c64705a8240 onto `release/1.12.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit e941d50bc83841110e4628e508c14c64705a8240 onto `release/1.11.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit e941d50bc83841110e4628e508c14c64705a8240 onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit e941d50bc83841110e4628e508c14c64705a8240 onto `release/1.9.x` succeeded!

**Pull request merged**
