### PR TITLE
Avoid panic on concurrent writes to cached service config map

### LINKED ISSUE #10636: panic: fatal error: concurrent map writes
#### Overview of the Issue

We have been observing occasional panics after upgrading to Consul 1.10.0. In particular, it seems to happen only on machines that are also running multiple Envoy docker containers (>30 containers). Machines with few Envoy docker containers (<10) do not seem to crash.

#### Reproduction Steps

Not certain. The crashes have been occurring in a cluster of 40+ agents, 5 servers, all running Consul 1.10.0 and Nomad 1.1.2, Envoy 1.18.3. It does not happen consistently and I cannot pinpoint a single event that triggers it

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 140
	services = 102
build:
	prerelease = 
	revision = 27de64da
	version = 1.10.0
consul:
	acl = enabled
	known_servers = 5
	server = false
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 2505
	max_procs = 8
	os = linux
	version = go1.16.5
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 235
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 10
	member_time = 647589
	members = 58
	query_queue = 0
	query_time = 119
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 4
	services = 2
build:
	prerelease = 
	revision = db839f18
	version = 1.10.1
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 3
	leader = false
	leader_addr = [REDACTED]
	server = true
raft:
	applied_index = 460524857
	commit_index = 460524857
	fsm_pending = 0
	last_contact = 1.937988ms
	last_log_index = 460524857
	last_log_term = 1971
	last_snapshot_index = 460511579
	last_snapshot_term = 1971
	latest_configuration = [REDACTED]
	latest_configuration_index = 0
	num_peers = 4
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 1971
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 1841
	max_procs = 4
	os = linux
	version = go1.16.6
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 235
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 647589
	members = 48
	query_queue = 0
	query_time = 119
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 185419
	members = 11
	query_queue = 0
	query_time = 119
```

</details>

### Operating system and Environment details

`uname -a`
```
Linux [REDACTED] 5.8.0-1038-aws #40~20.04.1-Ubuntu SMP Thu Jun 17 13:25:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Log Fragments

Here is the panic log. Its really long.
[crash.log](https://github.com/hashicorp/consul/files/6835124/crash.log)

### PR DESCRIPTION
**Pull request by freddygv**
If multiple instances of a service are co-located on the same node then
their proxies will all share a cache entry for their resolved service
configuration. This is because the cache key contains the name of the
watched service but does not take into account the ID of the watching
proxies.

This means that there will be multiple agent service manager watches
that can wake up on the same cache update. These watchers then
concurrently modify the value in the cache when merging the resolved
config into the local proxy definitions.

To avoid this concurrent map write we will only delete the key from
opaque config in the local proxy definition after the merge, rather
than from the cached value before the merge.

Fixes #10636

### CODE REVIEW

**Comment by freddygv** [comment]
Alternatively we could use different cache keys for each requesting proxy:
https://github.com/hashicorp/consul/blob/832896ed112b14b19a5abd603e8ebcb8e58773d7/agent/service_manager.go#L205

Rather than relying on the default:
https://github.com/hashicorp/consul/blob/main/agent/structs/config_entry.go#L645

**Review by dnephin — COMMENTED** [review]
Nice! Change LGTM. Thinking about how to test this, I guess trying to reproduce the panic would be difficult. Maybe we could add a check to the two existing tests that call `mergeServiceConfig` to verify that the `defaults` are not modified after `mergeServiceConfig` returns?

**Review by dnephin — APPROVED** [review]
LGTM!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/413107.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit cf4821885d0056545939eeccd30c55c4801d1233 onto `release/1.10.x` succeeded!

**Pull request merged**
