### PR TITLE
Add a helper for generating Consul's user-agent string

### PR DESCRIPTION
**Pull request by sethvargo**
This is not currently used, but it should be. Refs https://github.com/hashicorp/go-discover/pull/33

/cc @pearkes

### CODE REVIEW

**Comment by mkeeler** [comment]
@sethvargo Thanks for the PR. Do you have ideas already for places in the consul code where you think this new function should be used?

**Comment by sethvargo** [comment]
Right now, nowhere 😄 Once https://github.com/hashicorp/go-discover/pull/33 is merged, it'll be when Consul makes external API calls.

I would also like if Consul set its user agent when invoking health checks, but there's already a [hard-coded user-agent string](https://github.com/hashicorp/consul/blob/10bda48a4150eea7ae8c8fa2c7a41c0e403fcd61/agent/checks/check.go#L36-L38), and I don't know the implications of changing that. Ideally (external) services would like to know more about Consul and the chain, but I don't know if we can change that for BC.

**Comment by pearkes** [comment]
Yeah I think we should think separately about the heath check change for the reasons you mention but we should be able to get this in for the release following 1.0.7.

**Comment by sethvargo** [comment]
Hey @pearkes - I updated this PR to pull in the new lib and connect it all at once. I'm not sure why there are so many changes to vendor. I ran `govendor update github.com/hashicorp/go-discover/...` and it seems to have pulled in the world. I'm guessing those are all transitive dependencies.

**Comment by pearkes** [comment]
Thanks @sethvargo -- yeah I _think_ this will also fix #4082, FYI @preetapan.

**Comment by pearkes** [comment]
@sethvargo thanks for your patience on this! We got the vendor changes in a separate change, so do you mind rebasing which should just include the changes required to set the user agents in the go-discover clients?

**Comment by sethvargo** [comment]
Updated @pearkes. I'm not sure why there's still some whitespacing diffs on three of the vendor files, but I also don't know how to fix it. Hopefully that's okay

**Pull request merged**
