### PR TITLE
added screenshot of k8s service

### PR DESCRIPTION
**Pull request by jnwright**
CleanShot 2022-01-10 at 15 58 16@2x

### CODE REVIEW

**Review by karl-cardenas-coding — APPROVED** [review]
👍🏼

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/547966.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit a4af0a6bb034bae80d4031482fd6acbd6a5e743e onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit a4af0a6bb034bae80d4031482fd6acbd6a5e743e onto `release/1.11.x` succeeded!

**Pull request merged**
