### PR TITLE
add batch interface:/v1/health/services/

### PR DESCRIPTION
**Pull request by stevenLX**
add batch interface:/v1/health/services/
usage example:/v1/health/services/redis,consul?passing

### CODE REVIEW

**Comment by slackpad** [comment]
Hi @stevenLX can you describe your use case a little bit here? This seems like a pretty nuanced use case and may not be worth the complexity, but I'd like to understand more what you are trying to do.

**Comment by stevenLX** [comment]
Hi @slackpad  
Beacuse of we need to send a lot of http request for getting  or checking status for a group of service.
This can be a time-consuming operation.
So we need a  batch interface.

**Comment by slackpad** [comment]
Hi @stevenLX is this for like a status dashboard? I'm wondering if more of an event feed would make sense for that kind of use case.

**Comment by stevenLX** [comment]
Hi @slackpad 
Not only for dashboard.For example,I write a application need access muti services,  so I need get the service's info (inculde regist info and health status)from consul.At this moment I should call the same http api muti-times, and wait for all responses back. It is a time-consuming.
So, Could I push the batch interface for this kind of case?

**Comment by slackpad** [comment]
Hello there,

We talked about this internally, and we probably want to add an interface like this via /v1/txn, or some other mechanism that's a little higher-level and can apply to multiple types of operations. This isn't currently on the roadmap right now. Thank you for the PR, and sorry this sat for so long :-(

**Pull request closed without merging**
