### PR TITLE
deps: upgrade gogo-protobuf to v1.3.2

### PR DESCRIPTION
**Pull request by mikemorris**
Bump to the latest release of gogo/protobuf.

Longer term plan is still removing this dep and switching back to mainline google/protobuf as described in https://github.com/hashicorp/consul/issues/10471, but we should at least move to the latest release before doing that.

### CODE REVIEW

**Comment by mikemorris** [comment]
I'm slightly confused as to why `go mod tidy` and `make --always-make proto` and running locally with no changes for me, but both causing a diff in CI, any help would be appreciated...

**Comment by mikemorris** [comment]
Update: `go mod tidy` behavior changed in Go 1.16 and I was using Go 1.15, `make tools` was needed to first install the updated version of gogo/protobuf before running `make proto`

**Review by kisunji — APPROVED** [review]

**Review by dnephin — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/426350.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 3bae53a9899d2c90dbd22bd5cb1dd095607a09b9 onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/426350)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 3bae53a9899d2c90dbd22bd5cb1dd095607a09b9 onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/426350)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 3bae53a9899d2c90dbd22bd5cb1dd095607a09b9 onto `release/1.8.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/426350)

**Pull request merged**
