### PR TITLE
ui: Ensure disconnect error doesn't appear w/auth change on some pages

### PR DESCRIPTION
**Pull request by johncowen**
We recently updated a bug were in certain configurations you could log in but the view of data would not be refreshed/re-requested using the new token that you logged in with. Details in https://github.com/hashicorp/consul/pull/11681.

The approach in the mentioned PR was to use a client generated 401 error to cancel out all running blocking queries and immediately start them up again using the new token.

Unfortunately, on some pages where things can disappear whilst blocking on them (for instance a service might be deregistered whilst viewing the service detail page), we catch any errors and show a message saying the connection was lost for some reason. In some circumstances we get an error that we can safely ignore, and these are usually our client generated errors (such as our 429 errors which are produced when we force cancel a blocking query due to reaching our connection limit).

As we added a new client generated error code in the above PR (401) we should have also made sure to ignore that error code also, which is what this PR adds in a place that is somewhat 'global'.

### CODE REVIEW

**Review by amyrlam — APPROVED** [review]
Used ?w=1 lgtm!

Will get to the longer PR's in the new year

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/538725.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 72e5d7e1d43e52a54d4f5d663410568de82a6fee onto `release/1.11.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 72e5d7e1d43e52a54d4f5d663410568de82a6fee onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/538725)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 72e5d7e1d43e52a54d4f5d663410568de82a6fee onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/538725)

**Pull request merged**
