### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by lkysow**

### CODE REVIEW

**Review by ishustava — APPROVED** [review]

**Review by david-yu — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/459541.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 410d57879c07da9a8a28b19a1ea2398136942ffc onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 410d57879c07da9a8a28b19a1ea2398136942ffc onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/459541)

**Pull request merged**
