### PR TITLE
Updates docs for CRDs

### PR DESCRIPTION
**Pull request by thisisnotashwin**
### Description
Updates docs for Mesh CRD to be up to date with latest spec

### Links
Asana task : https://app.asana.com/0/1159647457614001/1202475485785044

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [ ] not a security concern

### CODE REVIEW

**Review by david-yu — APPROVED** [review]
Thanks it looks like the docs are pretty up to date then if I read this PR correctly?

**Comment by thisisnotashwin** [comment]
> Thanks it looks like the docs are pretty up to date then if I read this PR correctly?

indeed!!

**Review by NicoletaPopoviciu — APPROVED** [review]
@thisisnotashwin thank you for the help, and for showing where to check for docs discrepancies

**Comment by thisisnotashwin** [comment]
> @thisisnotashwin thank you for the help, and for showing where to check for docs discrepancies

more than happy to!! 😄 you crushed it there on out @NicoletaPopoviciu

**Pull request merged**
