### PR TITLE
Intra datacenter estimated latencies in ui

### PR DESCRIPTION
**Pull request by ross**
Adds a visualization of the intra-dc network tomography to the front page when there's more than 1 dc. Includes estimated min, median, and max times between nodes in the source and dest dcs.

Minor stuff:
- No reason to calculate min and max when we have a sorted array, heh.
- Starts to clean up the tomography dom, js. & css a bit, more needed/coming.
### Examples:

2 dcs, real view, fake names

screen shot 2016-05-21 at 8 10 29 am

Same, but included times to self in there just to show what the visualization looks like with more than 2 dcs (my test setup only has 2)

screen shot 2016-05-21 at 8 10 07 am

There are `svg` `title` elements on the markers (essentially tooltips) that show the source and dest nodes and the estimated latency when you hover over them. I wasn't able to get a screenshot of them up.

This is currently showing min, median, and max, but I may play around with showing all pairs and see what that looks like. Thoughts/feedback solicited.

### CODE REVIEW

**Comment by ross** [comment]
All paris variant in case people think it's a better visualization. There's basically N * M marks, one for each pairing of nodes from the 2 dcs. 

screen shot 2016-05-21 at 8 36 45 am

screen shot 2016-05-21 at 8 38 54 am

**Comment by ross** [comment]
Should I look at polishing this up or not of interest? If so averages or all pairs?

**Comment by slackpad** [comment]
@ross sorry for the delay - I'll pull this down locally and take a look soon. Definitely interested in seeing this land!

**Comment by ross** [comment]
> @ross sorry for the delay - I'll pull this down locally and take a look soon. Definitely interested in seeing this land!

No worries. Just wanted to make sure before I put a bit more time in to clean it up, both visually and code-wise. I should get to that in an evening later this week or early this weekend.

**Comment by ross** [comment]
OK. Made a pass at polishing the look & data a bit and made the naming of things more consistent. Decided that the "all pairs" variant was more interesting than the min, median, max. Visually, the result is:

screen shot 2016-06-04 at 9 25 11 am

**Comment by slackpad** [comment]
Hi @ross sorry about the delay on this one. I ended up making a tiny JS change over in https://github.com/hashicorp/consul/pull/2251 that I think we will need to rebase and port over here. There was a JS error if coordinates were not available. I can help you rebase, or if you'd like to we can get this in - please let me know!

**Comment by ross** [comment]
Hi @slackpad. May be best for you to rebase & fix as it'll take me a bit before it'd get back to the top of my todo list.

**Comment by slackpad** [comment]
We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!

**Pull request closed without merging**
