### PR TITLE
docs: Use "error" to use standard log level value

### PR DESCRIPTION
**Pull request by david-yu**
### Description

"err" was used for backwards compatibility, but we should use "error" as the standard for now per [log_levels.go](https://github.com/hashicorp/consul/blob/401221de5852432d742f2bdb1c4f17fb0d0e7362/logging/log_levels.go#L10) 

### Testing & Reproduction steps
* In the case of bugs, describe how to replicate
* If any manual tests were done, document the steps and the conditions to replicate
* Call out any important/ relevant unit tests, e2e tests or integration tests you have added or are adding

### Links
Include any links here that might be helpful for people reviewing your PR (Tickets, GH issues, API docs, external benchmarks, tools docs, etc). If there are none, feel free to delete this section.

Please be mindful not to leak any customer or confidential information. HashiCorp employees may want to use our internal URL shortener to obfuscate links.

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [ ] not a security concern

### CODE REVIEW

**Review by kisunji — APPROVED** [review]

**Comment by david-yu** [comment]
Retrying after CI failures due to Github Actions outage.

**Review by trujillo-adam — APPROVED** [review]
Ideally, these would all be in monospace font.

**Comment by david-yu** [comment]
@trujillo-adam Do you mean like `trace`, `debug`, `warn`, etc?

**Comment by trujillo-adam** [comment]
> @trujillo-adam Do you mean like `trace`, `debug`, `warn`, etc?

Yeah. The rationale is that we should format text written by a user and text printed to an interface (console or GUI) as code font. According to our style guide, we don't use quotation marks for anything other than direct quotes. It's something we are currently debating. The argument could be made that we are quoting the interface, and therefore the printed text should be in quotation marks. FWIW, I probably should have kept that comment to myself since the debate is still unsettled.

**Comment by david-yu** [comment]
@trujillo-adam I see. I believe I would like to as well but on the Consul Core side it looks like config is heavily tied to HCL formatting as you can see here in this example from https://www.consul.io/docs/agent/config/config-files. Without quotes, this would render a broken HCL config file. I'll leave the formatting as is, since I think we may need to revisit holistically. 

```
datacenter = "east-aws"
data_dir = "/opt/consul"
log_level = "INFO"
node_name = "foobar"
server = true
watches = [
  {
    type = "checks"
    handler = "/usr/bin/health-check-handler.sh"
  }
]

telemetry {
  statsite_address = "127.0.0.1:2180"
}
```

**Pull request merged**
