### PR TITLE
Add support for EDNS0 (RFC6891) udp payload size negotiation

### PR DESCRIPTION
**Pull request by jsipprell**
Modern stub resolvers can be configured to always send EDNS(0)/RFC6891 extended requests to resolvers which, among other things, permits relaxation of the traditional 512 byte maximum UDP payload limit by sending a desired maximum size (usually 4k) and allowing the server to reduce as appropriate in the response frame.

Additionally, caching/recursive resolvers such as Unbound and BIND will prefer to use EDNS(0) when prefetching as well as honoring EDNS(0) when forwarding requests or performing recursion on behalf of a stub-resolver or other client.

This PR adds support for EDNS(0), _if and only if set in the request frame_; it relaxes certain Answer section limits and synchronizes Answer UDP trimming to match the requested EDNS(0) UDP maximum size.

### CODE REVIEW

**Comment by ryanuber** [comment]
Hey @jsipprell, sorry for the delay here. I'll review in depth here soon, but at first glance this sounds great!

**Comment by rangan337** [comment]
@jsipprell - Would it be possible to fix the merge conflicts here ?

**Comment by sethvargo** [comment]
Hey there,

This looks like a reasonable chance, but we do not feel confident without some test coverage. Could you please add some tests and rebase? Thanks! 😄

**Comment by slackpad** [comment]
This ended up going in via #3131, closing this one out.

**Pull request closed without merging**
