### PR TITLE
Update self-hosted-kubernetes.mdx

### PR DESCRIPTION
**Pull request by agmt5989**
Corrected typo, from you _mean_ need to you _may_ need.

### CODE REVIEW

**Comment by agmt5989** [comment]
Would be nice to get approval on this.

**Review by david-yu — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/399465.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit d87263b5eb32271f67ca706f28a13f7035ab1d96 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit d87263b5eb32271f67ca706f28a13f7035ab1d96 onto `release/1.10.x` succeeded!

**Pull request merged**
