### PR TITLE
Fix a tiny typo in logging in autopilot.go

### PR DESCRIPTION
**Pull request by krastin**
Fixing a minuscule typo in logging

### CODE REVIEW

**Review by dnephin — APPROVED** [review]
LGTM, thank you!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/459244.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit bf2a3f6e799a56aaa2af4bca9ded6df7178fe425 onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit bf2a3f6e799a56aaa2af4bca9ded6df7178fe425 onto `release/1.9.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit bf2a3f6e799a56aaa2af4bca9ded6df7178fe425 onto `release/1.8.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/459244)

**Pull request merged**
