### PR TITLE
Fix #20594 : Feature - 'consul tls cert renew' command

### LINKED ISSUE #20594: Consul tls command should be able to renew
#### Feature Description

Currently the `consul tls` command only has `create` functionality for a server certificate.  However, to avert having to distribute a new trust chain to all clients, it would be helpful if this also had a `consul tls renew` that took the current certificate and key, and generated a new certificate that its CA chain resolves to, to avoid a service disruption to clients.

#### Use Case(s)

Renewing a Consul TLS Server Certificate with minimal impact to registered nodes.

### PR DESCRIPTION
**Pull request by vijayraghav-io**
### Description

Add new cli cmd to be able to renew existing TLS Server Certificate -
`consul tls cert renew`

fixes #20594 

The approach used to renew existing TLS certificate - 
1. New Public Key (cert file) is created with same  (existing) input private key.
2. The same CA used to generate initial cert is used to sign. CA file path to be  input.

### Testing & Reproduction steps

1. Create CA with cmd `consul tls ca create`
3. Create Cert with cmd `consul tls cert create -server`
4. Renew Certificate created in step 2 with same private key created in step 2 - with new cmd - `consul tls cert renew -server -existingkey=<key file created in step2>`
5. Replace cert file created in step 2 with new (renewed) cert file created in step3. 
6. This will avert having to distribute a new trust chain to all clients and avoid a service disruption to clients. 

### PR Checklist

* [x] updated test coverage
* [ ] external facing docs updated
* [ ] appropriate backport labels added
* [ ] not a security concern

### CODE REVIEW

**Comment by vijayraghav-io** [comment]
Hi @david-yu,
Kindly review this PR.

**Comment by vijayraghav-io** [comment]
Did one more round of self review, thought of adding an improvement -
Ideally for cert renew command the args like domain, dc, server/client/cli,.. should not be required to be input. These should be read from existing certificate. So added arg -existingcert and removed redundant args.
The updated arg list is - 
-existingcert
-existingkey
-ca
-key
-days
-dnsnames
-ipaddresses

-existingcert and -existingkey are mandatory. Paths to existing cert.pem and key.pem files that have to be renewed.
-ca and -key -> Paths to CA cert and key files
-days defaults to 365
-dnsnames and -ipaddresses -> These are also read from existing cert, the additional dnsnames and ipaddresses if any can be added here while renewing.

**Comment by vijayraghav-io** [comment]
Reminding to review this PR

**Comment by reskin89** [comment]
Bump

**Pull request closed without merging**
