### PR TITLE
Fix checks removal when removing service

### PR DESCRIPTION
**Pull request by vfrz**
Fix my recently discovered issue described here: #5456

### CODE REVIEW

**Comment by Aestek** [comment]
Indeed, LGTM

**Comment by Aestek** [comment]
@vfrz I added a test for this at https://github.com/hashicorp/consul/commit/1824a378859a5221fa340a793dc79fa5679ad772 If you'd like to add it to your PR.

**Comment by vfrz** [comment]
Is there a way to add this commit to my PR or should I create it myself?

**Comment by Aestek** [comment]
You can cherry-pick it from my fork, remote is `https://github.com/Aestek/consul.git`.

**Comment by vfrz** [comment]
Thanks, I was lost with the github UI.
I've pushed the commit.

**Comment by rliebz** [comment]
Running into the same issue as described. 

I took a look at the PR that I think introduces this issue (https://github.com/hashicorp/consul/pull/5012), and while from my local testing this PR does fix it, there's actually two places where the health checks are being de-registered.

First, in the spot that this PR is fixing: https://github.com/hashicorp/consul/blob/e293045751ecc2b8979bc7bc06fcad7617f0ee29/agent/agent.go#L2075

Whose implementation includes this: https://github.com/hashicorp/consul/blob/e293045751ecc2b8979bc7bc06fcad7617f0ee29/agent/local/state.go#L325-L329

Then again, in the same function: https://github.com/hashicorp/consul/blob/e293045751ecc2b8979bc7bc06fcad7617f0ee29/agent/agent.go#L2088-L2095

I'm not sure which of those two places is more appropriate, but I don't think both should need to exist.

**Comment by vfrz** [comment]
True, I think we should remove the code from line 2088 to 2095 since the `RemoveServiceWithChecks` method is called before, it shouldn't do anything.

**Comment by Aestek** [comment]
@rliebz @vfrz These are not the same func. 

* `State.removeCheckLocked` removes the check definition from the agent state.
* `Agent.removeCheckLocked` stops the check task from the agent (the actual goroutine that performs the check, an HTTP call for example).

Although their names are misleadingly the same both are needed to properly deregister a check.

**Comment by rliebz** [comment]
It's not the same function, but it looks like `Agent.removeCheckLocked` already calls `State.RemoveCheck` internally:

https://github.com/hashicorp/consul/blob/e293045751ecc2b8979bc7bc06fcad7617f0ee29/agent/agent.go#L2428-L2436

**Comment by leprechau** [comment]
@pierresouchay as this is a breaking change in 1.4.3 and progress here seems to have stalled could you add a note to the readme warning users dependent on health checks for multiple service instances not to update to 1.4.3?

**Comment by mkeeler** [comment]
@rliebz You are correct that we are calling `removeCheckLocked` twice for each removed check. If the order in which it was done was reversed this would cause issues. It is saved by the fact that the call within the `Agent.removeCheckLocked` does not check the error which should be returned because the check no longer exists when called the second time. 

While its probably worthwhile to eventually fix this, I am not sure it should block merging this PR as the extra call is close to being a no-op. I think we would need to dig a little deeper and do a bit larger of a refactoring to ensure that everything is consistent and working. For the time being this PR fixes the bad behavior.

**Pull request merged**
