### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by voelzmo**

### CODE REVIEW

**Comment by voelzmo** [comment]
Do I need a CLA for fixing typos? I'm not sure how easy this will be with our legal department.

**Comment by pearkes** [comment]
@voelzmo We do have a blanket requirement for the CLA across PRs, there's more information in our blog post [here](https://www.hashicorp.com/blog/introducing-a-cla).

**Comment by pearkes** [comment]
Also note CI was temporarily failing as we moved to go modules (#5517).

If you don't wish to sign the CLA, no problem, just feel free to close this PR.

**Comment by kaitlincarter-hc** [comment]
Unfortunately we can’t merge this PR if the CLA isn’t signed, so we will go ahead and close it.

**Pull request closed without merging**
