### PR TITLE
ui: Add an isDestroyed check for the MenuPanel component

### PR DESCRIPTION
**Pull request by johncowen**
This PR solves an occasionally flakey test I see every so often.

### CODE REVIEW

**Review by kaxcode — APPROVED** [review]
👍

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/453728.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit ececa7da4539281cc85e3a6ac3eec496bda69b12 onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit ececa7da4539281cc85e3a6ac3eec496bda69b12 onto `release/1.9.x` succeeded!

**Pull request merged**
