### PR TITLE
allow 'make dev-docker' to cache resolved modules

### PR DESCRIPTION
**Pull request by rboyer**

### CODE REVIEW

**Comment by rboyer** [comment]
The trick is taken from [https://medium.com/@pliutau/docker-and-go-modules-4265894f9fc#6622]

As-is ALL of the source AND the `go.mod/go.sum` files are copied in as a single layer in the dockerfile, meaning there's a single cacheable layer. If you changed anything about any file in the repo it would trigger the ADD to invalidate the cache and all further layers (including the initial population of the go mod cache).

The trick has you do a minimal copy of the module files  first because they are less likely to change frequently and thus steps between the mod file copy and the rest of the source code copying are much more likely to not be invalidated, like the hefty go mod cache population.

**Comment by banks** [comment]
Nice trick @rboyer, worth putting in a comment in the docker file?

**Comment by mkeeler** [comment]
I see, so if the go.sum or go.mod changes then it will have to pull all of it. 

This is probably partially due to us not knowing that we would need to build with `-mod vendor` to have it actually use our vendor directory. In that case this would be unnecessary.

I guess then we need to have the discussion of long-term what are we going to do with the vendor directory and supporting it in our build (right now we don't and it will pull the deps from the network every time).

**Comment by rboyer** [comment]
> worth putting in a comment in the docker file?

Did just that.

**Pull request merged**
