### PR TITLE
ui: Make sure we pass the nspace through to the API for nodes

### PR DESCRIPTION
**Pull request by johncowen**
Manual backport of https://github.com/hashicorp/consul/pull/9410 to 1.8.x

### CODE REVIEW

**Comment by johncowen** [comment]
@mikemorris , just checking in to make sure this is how you'd want to do this? I did this completely manually and copied over the same change log (with this PRs number)

Thinking if I label as backport to 1.7 from here it _should_ go cleanly from 1.8 to 1.7

**Review by kaxcode — APPROVED** [review]
LGTM

**Comment by mikemorris** [comment]
LGTM for backport targeting 1.8.x!

> Thinking if I label as backport to 1.7 from here it should go cleanly from 1.8 to 1.7

I believe the backport label flow only triggers on PRs targeting `master` currently, @alvin-huang may have thoughts on whether we could/should enable auto-backports like 1.8.x->1.7.x in the future, but cherry-picking this onto 1.7.x after merging would be the path for now.

**Review by mikemorris — APPROVED** [review]

**Comment by johncowen** [comment]
Thanks!

> I believe the backport label flow only triggers on PRs targeting master

Ah cool I did wonder, I can just manually cherry pick if not 👍

**Pull request merged**
