### PR TITLE
Configurable CheckHTTP timeout

### PR DESCRIPTION
**Pull request by arnaudbriche**

### CODE REVIEW

**Comment by armon** [comment]
Could you please add tests for this? I believe there are a few places where the time.Duration must be parsed from a string as well.

**Comment by armon** [comment]
@arnaudbriche Thanks! Could you also add the appropriate doc updates? If you don't have time, I'll eventually swing back around to this

**Comment by arnaudbriche** [comment]
Hi Armon,

As a non-native English speaker, I think you'll do a far better job a writing the doc than me.

**Comment by ryanuber** [comment]
@arnaudbriche I'm going to merge this in and make the documentation changes. I'll link you to the commit after. Thanks for taking care of this!

**Comment by ryanuber** [comment]
@arnaudbriche you can find the adjustments I made [here](https://github.com/hashicorp/consul/compare/45097f9f3d...5c2a764cbe). I had to adjust a few of the tests as well, but nothing major. Thanks!

**Comment by arnaudbriche** [comment]
Thx you guys, I'm glad to be able to contribute to this awesome project !

**Pull request merged**
