### PR TITLE
.gitignore entries for IntelliJ IDEA

### PR DESCRIPTION
**Pull request by dweomer**
My preferred IDE, even for Go code, is IntelliJ IDEA. Please accept his minor addition to the .gitignore which helps prevent accidental pollution into commits of project files and other workspace cruft.

### CODE REVIEW

**Comment by dweomer** [comment]
Interesting that the build failed, I only added to the `.gitignore`!

**Comment by mthenw** [comment]
It's better to ignore those files locally for all repos:
> Patterns which a user wants Git to ignore in all situations (e.g., backup or temporary files generated by the user’s editor of choice) generally go into a file specified by core.excludesFile in the user’s ~/.gitconfig. Its default value is $XDG_CONFIG_HOME/git/ignore. If $XDG_CONFIG_HOME is either not set or empty, $HOME/.config/git/ignore is used instead.

http://git-scm.com/docs/gitignore

**Comment by dweomer** [comment]
@mthenw that is fair. I don't do a lot of setup on machines that I work on which means global gitignore entries are typically forgotten.

**Comment by dweomer** [comment]
Could've sore I did a search on this but it looks like this duplicates, at least in spirit, #1371

**Comment by slackpad** [comment]
Hi @dweomer - thanks for the PR. The build fail wasn't you, but I'll close this out in favor of @mthenw's suggestion in https://github.com/hashicorp/consul/pull/1556#issuecomment-167966975 since there's quite a bit here unrelated to Consul.

**Pull request closed without merging**
