### PR TITLE
Adds metrics and hybrid checks that are handled on agent.

### PR DESCRIPTION
**Pull request by fusiondog**
This is a starting point for metrics handling in consul.  This follows the suggestions made by Armon in google groups https://groups.google.com/forum/#!topic/consul-tool/g1OkeBgBMOo and handles the metric processing on the agent.   Here is an example config used in testing:

```
consul-client:~# cat /etc/consul/fake-metrics-check.json 
{
 "check": {
   "metric": "/tmp/metricsonly.sh",
   "metric_handler": "grep -v mutate | /tmp/metrichandler.sh",
   "interval": "10s",
   "name": "fake-metric-check"
 }
}
consul-client:~# cat /etc/consul/hybrid-check.json 
{
 "check": {
   "script": "/usr/lib/nagios/plugins/check_load -w 5,5,5 -c 10,10,10 ",
   "metric_handler": "/tmp/metrichandler.sh",
   "interval": "10s",
   "name": "hybrid-check"
 }
}
consul-client:~# cat /tmp/metricsonly.sh 
echo "some.tree.for.graphite 42 "`date +%s`
echo "mutate.key.for.graphite 13 "`date +%s`
consul-client:~# cat /tmp/metrichandler.sh 
while read line
do
 echo $line >> /tmp/metrics.log
done < /dev/stdin
consul-client:~# tail /tmp/metrics.log 
load1=0.040;5.000;10.000;0; load5=0.110;5.000;10.000;0; load15=0.130;5.000;10.000;0;
some.tree.for.graphite 42 1461088134
load1=0.030;5.000;10.000;0; load5=0.110;5.000;10.000;0; load15=0.130;5.000;10.000;0;
some.tree.for.graphite 42 1461088144
load1=0.030;5.000;10.000;0; load5=0.110;5.000;10.000;0; load15=0.130;5.000;10.000;0;
some.tree.for.graphite 42 1461088154
load1=0.020;5.000;10.000;0; load5=0.100;5.000;10.000;0; load15=0.130;5.000;10.000;0;
some.tree.for.graphite 42 1461088164
load1=0.020;5.000;10.000;0; load5=0.100;5.000;10.000;0; load15=0.120;5.000;10.000;0;
some.tree.for.graphite 42 1461088174
```

While this is functional, future features might include global control and some case could be made for collecting metrics to the consul server and centralizing handler config.  Here are some notes on options for central control:
1) have the check config list a metrics channel instead of a handler.  Then separately configure the consul servers with channel configs that listed handlers. 
Pros : Centralized config and script management 
Cons: centralizes metrics transit which could scale to a bottleneck if metrics data is large
2)  have a channel selector set either as a KV entry or internal consul state and agents use that data to select the correct handler to emit with.  Either as a global for all metrics on the agent or through subscriptions in the check configs.
Pros: decentralized metrics emission should scale with agents, centralizes handler selection
Cons: handler channels and scripts must still be distributed to agents first.
3) using the KV option above the scheme could be achieved in the handler using a master handler that reads the KV from the triggering consul instance and makes backend selections from there.
Pros: Same as 2 plus flexibility to use simpler handler config and simpler consul code.
Cons: Same as 2

I prefer option 3 because some people may be content with letting chef manage changes in the metrics handling without wanting the extra overhead that would be required to centralize control of backends in the tool.  Consul still provides the framework to easily build controls around it but otherwise consul remains just a metrics bus.  

Also metric and handler scripts (other than hybrid check scripts which still report status of monitor script) that return with non zero exit codes are ignored. Not sure what action should be taken other than perhaps logging it.  Sensu docs indicate it is ignored in sensu code.  It is an open question what if anything should be done to represent the metric checks differently in the UI.  Currently the metrics only checks note they are processing metrics in the check output, perhaps that is sufficient for most people.

### CODE REVIEW

**Comment by cdrage** [comment]
Hey @fusiondog 

Stumbled upon your work when I was reading the mailing list and this really fits into what I'm experiencing as well.

I'd love to get Consul to output to graphite and have this kind of handler.

Have you been updating any of this work lately?

Perhaps we can discuss this with @armon as well in regards to getting the ball rolling again here? :)

**Comment by fusiondog** [comment]
Hey @cdrage 
I haven't done anything since this on the subject.  I wanted to get some feedback from people before going too far down a wrong path.  Assuming that option 3 makes sense to most people, then I just need to merge in the latest upstream and then begin consideration on how to source handlers.

**Comment by slackpad** [comment]
@fusiondog thanks for the PR! I'll try to give this some cycles once we ship 0.7.0.

**Comment by slackpad** [comment]
Still not sure if this is the right way to go, but putting on the roadmap to think about.

**Comment by sethvargo** [comment]
Hey there,

We talked about this as a team. We think this is an interesting idea, but it's quite a large feature. We don't see something like this on our roadmap in the near feature and think it might be exceeding Consul's design scope a bit. Sorry this PR sat for so long, and thank you for all your past contributions!

**Pull request closed without merging**
