### PR TITLE
Rename CatalogDestinationsOnly

### PR DESCRIPTION
**Pull request by freddygv**
CatalogDestinationsOnly is a passthrough that would enable dialing
addresses outside of Consul's catalog. However, when this flag is set to
true only _connect_ endpoints for services can be dialed.

This flag is being renamed to signal that non-Connect endpoints can't be
dialed by transparent proxies when the value is set to true.

### CODE REVIEW

**Review by dnephin — APPROVED** [review]
The new field name SGTM

**Review by rboyer — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/386113.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit ffb13f35f1ad6775a7b60504e528caad294916cd onto `release/1.10.x` succeeded!

**Pull request merged**
