### PR TITLE
docs: Admin Partitions image bump to GA

### PR DESCRIPTION
**Pull request by david-yu**
Bump consul-enterprise image to GA.

### CODE REVIEW

**Review by trujillo-adam — COMMENTED** [review]
LGTM

**Review by trujillo-adam — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/531744.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 8504b689ab6b1fe46469524ab168497fd3e61854 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 8504b689ab6b1fe46469524ab168497fd3e61854 onto `release/1.11.x` succeeded!

**Pull request merged**
