### PR TITLE
docs: Vault Secrets Backend K8s, remove code tabs

### PR DESCRIPTION
**Pull request by david-yu**
- Removal of extraneous code tabs
- Indentation of some steps

### CODE REVIEW

**Review by karl-cardenas-coding — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/562434.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit c69b05ca55755afd569871dc353140dc8e896ec4 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit c69b05ca55755afd569871dc353140dc8e896ec4 onto `release/1.11.x` succeeded!

**Pull request merged**
