### PR TITLE
docs: fix typo in security/acl

### PR DESCRIPTION
**Pull request by nicoche**
### Description

Fix a typo in the docs

### Testing & Reproduction steps

N/A

### Links

N/A

### PR Checklist

N/A

* [x] updated test coverage
* [x] external facing docs updated
* [x] appropriate backport labels added
* [x] not a security concern

### CODE REVIEW

**Review by blake — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
@nicoche, a backport is missing for this PR [21003] for versions [1.16,1.17] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@nicoche, a backport is missing for this PR [21003] for versions [1.16,1.17] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@nicoche, a backport is missing for this PR [21003] for versions [1.16,1.17] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@nicoche, a backport is missing for this PR [21003] for versions [1.16,1.17] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Pull request merged**
