### PR TITLE
Bootstrap w/o Glyphicon Halflings (resolves #2485)

### LINKED ISSUE #2485: Consul built-in assets missing font files
If you do a `wget -r` against the internal UI there are some missing assets:

```
--2016-11-08 14:54:37--  http://localhost:8500/ui/fonts/glyphicons-halflings-regular.eot
Reusing existing connection to localhost:8500.
HTTP request sent, awaiting response... 500 Internal Server Error
2016-11-08 14:54:37 ERROR 500: Internal Server Error.

--2016-11-08 14:54:37--  http://localhost:8500/ui/fonts/glyphicons-halflings-regular.eot?
Reusing existing connection to localhost:8500.
HTTP request sent, awaiting response... 500 Internal Server Error
2016-11-08 14:54:37 ERROR 500: Internal Server Error.

--2016-11-08 14:54:37--  http://localhost:8500/ui/fonts/glyphicons-halflings-regular.woff
Reusing existing connection to localhost:8500.
HTTP request sent, awaiting response... 500 Internal Server Error
2016-11-08 14:54:37 ERROR 500: Internal Server Error.

--2016-11-08 14:54:37--  http://localhost:8500/ui/fonts/glyphicons-halflings-regular.ttf
Reusing existing connection to localhost:8500.
HTTP request sent, awaiting response... 500 Internal Server Error
2016-11-08 14:54:37 ERROR 500: Internal Server Error.

--2016-11-08 14:54:37--  http://localhost:8500/ui/fonts/glyphicons-halflings-regular.svg
Reusing existing connection to localhost:8500.
HTTP request sent, awaiting response... 500 Internal Server Error
2016-11-08 14:54:37 ERROR 500: Internal Server Error.
```

We should fix this and add a check to the ui build to catch these.

### PR DESCRIPTION
**Pull request by brianshumate**
- Remove reference to Glyphicon Halflings @fontface
- Remove unused Glphyicon related classes

### CODE REVIEW

**Comment by brianshumate** [comment]
`/static/bootstrap.min.js` appears to be dynamically generated(?)

**Comment by slackpad** [comment]
@pearkes might be able to give a little guidance on how we update this

**Comment by brianshumate** [comment]
Sorry about all the noise — I had intended to drop this PR as I was not sure what else needed to be done after updating the `bootstrap.min.css` to see that no more requests to the fonts were occurring, but I figured out how it works so I'll restore/reopen and perhaps we can proceed.

It looks like doing a `make ui` builds the UI in a Docker container and also prepares an updated `bindata_assetfs.go` for the binary using [go-bindata-assetfs](https://github.com/elazarl/go-bindata-assetfs). Then `make dev` indeed picks up the updated `command/agent/bindata_assetfs.go` and the subsequent running binary has no more 500 ISEs from a `wget -r`. 😸 

It also looks like I should be committing the updated `bindata_assetfs.go` in this PR as well though(?)

**Comment by slackpad** [comment]
Yeah - that'll pick up your changes in the web assets that are built in for `-ui`. We didn't want to put the Ruby stuff in the normal build path so we check in the generated files. The release build makes sure that we have done this before we build a final release.

**Comment by slackpad** [comment]
Thanks! No more 404s.

**Pull request merged**
