### PR TITLE
docs: Agent configuration hierarchy reorganization

### PR DESCRIPTION
**Pull request by blake**
Second attempt at merging agent config documentation changes that were originally included in #12005.

### CODE REVIEW

**Review by trujillo-adam — APPROVED** [review]

**Review by karl-cardenas-coding — APPROVED** [review]
👍🏼

**Comment by david-yu** [comment]
No cherrypick though?

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/635664.

**Comment by blake** [comment]
> No cherrypick though?

This has docs for changes that are only present in 1.12, so it needs to go live when we publish those the 1.12.x versioned docs.

**Comment by karl-cardenas-coding** [comment]
@blake we didn't add the `cherry-pick` label. So I'm not sure why it got applied.

**Pull request merged**
