### PR TITLE
command/agent: SoftLayer host discovery

### PR DESCRIPTION
**Pull request by jvrplmlmn**
This PR adds several command-line and config options that facilitate host discovery through SoftLayer (SL), in a similar fashion to the AWS and GCE auto-discovery.

Documentation is currently missing, but I'll get to that later on. Looking right now for some early feedback 😃

### CODE REVIEW

**Comment by jvrplmlmn** [comment]
Took me a while to get the vendoring right, I was not very familiar with `govendor`. Solved it with:

`$GOPATH/bin/govendor fetch github.com/softlayer/softlayer-go/...`

**Comment by jvrplmlmn** [comment]
Hello @slackpad before I continue working on the documentation, is this something that would be interesting to have in Consul? If not, is there any plugin mechanism in Consul (similar to Terraform) so I can package it as a plugin?

Thanks!

**Comment by slackpad** [comment]
Hi @jvrplmlmn we are thinking about this internally a bit to figure out the best way forward. It's tough to absorb a ton of new deps per provider, especially since we usually only need a subset, and it does increase the config complexity. It's easy to use and deploy if it's built in, though. Plugins are an option, or we could also make a little library that makes it easy to run a joiner process alongside Consul that just uses the Consul API client.

**Comment by jvrplmlmn** [comment]
@slackpad any news on this? I see that the same mechanism was implemented for Azure in #2978

**Comment by slackpad** [comment]
@jvrplmlmn We have decided to take a different approach and move the discovery code into a separate package which we can then pull into consul and nomad for example. You can find the code in #3144 and it would help us a lot if you could provide us with a PR against https://github.com/hashicorp/go-discover, then it should be relatively easy to pull into Consul.

**Comment by jvrplmlmn** [comment]
Thanks @slackpad! I've opened https://github.com/hashicorp/go-discover/pull/2

I see that #3144 (extracting functionality to [github.com/hashicorp/go-discover](https://github.com/hashicorp/go-discover)) has been reverted in #3180.

How should I continue with this?

**Comment by slackpad** [comment]
> I see that #3144 (extracting functionality to github.com/hashicorp/go-discover) has been reverted in #3180.

That was temporary since we didn't want to pull that into 0.8.5, we are going to pull go-discover back into master, hopefully for 0.9.0. Once we merge on the library side we can pull it into Consul. We need to expose the generic config string, and then it will be easier to support new providers.

**Comment by magiconair** [comment]
I'll review this and integrate this into go-discover.

**Comment by jvrplmlmn** [comment]
> I'll review this and integrate this into go-discover.

@magiconair there is already a pull request for `go-discover`, see: https://github.com/hashicorp/go-discover/pull/2

**Comment by magiconair** [comment]
@jvrplmlmn I know. That's the one I meant. Sorry for not being clear :)

**Comment by slackpad** [comment]
Closing this per https://github.com/hashicorp/consul/pull/2879#issuecomment-313485548.

**Pull request closed without merging**
