### PR TITLE
Add a mock Agent delegate to ease/improve some types of testing

### PR DESCRIPTION
**Pull request by mkeeler**
Also adding a changelog entry for the enterprise additions where this mock would be used.

### CODE REVIEW

**Review by rboyer — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/452554.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit c04d5c4238cc6d099a034f05ecf12cc5e12046ed onto `release/1.11.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit c04d5c4238cc6d099a034f05ecf12cc5e12046ed onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit c04d5c4238cc6d099a034f05ecf12cc5e12046ed onto `release/1.9.x` succeeded!

**Comment by mkeeler** [comment]
Apparently those 4 backports only backported the changelog commit. I will be manually cherry-picking the other commit to each branch.

**Pull request merged**
