### PR TITLE
docs: Updating Gossip EncryptionKey Rotation page with Vault use case

### PR DESCRIPTION
**Pull request by jmurret**

### CODE REVIEW

**Review by david-yu — APPROVED** [review]

**Review by karl-cardenas-coding — APPROVED** [review]
@jmurret  Changes look good. John, while you're making changes  in this page. Could you add `$` to the shell-session commands that are missing the `$` prefix please :)

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/630924.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 62476e25fbcdfba032c1b0b6dd996cf29c6bc11a onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 62476e25fbcdfba032c1b0b6dd996cf29c6bc11a onto `release/1.12.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/630924)

**Pull request merged**
