### PR TITLE
docs: fixes broken url in acl overview page

### PR DESCRIPTION
**Pull request by karl-cardenas-coding**
This PR fixes a broken url in the ACL overview page.

### CODE REVIEW

**Review by trujillo-adam — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/623468.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 13fba7567f061f8d5ea09922ce91d61a61ab41d2 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 13fba7567f061f8d5ea09922ce91d61a61ab41d2 onto `release/1.12.x` succeeded!

**Pull request merged**
