### PR TITLE
ui: Add docs for AppView

### PR DESCRIPTION
**Pull request by johncowen**
During https://github.com/hashicorp/consul/pull/10259 we noticed we had an overwrite here that we no longer needed, so we took the opportunity here to remove that and bring AppView into line with a few of our common project patterns and document.

1. ~Colocated~ chocolated the CSS files along with their JS/HBS files in the `app/components` directory.
2. Updated the grays to use CSS properties instead of SASS vars
3. Removed `%app-view-content-empty` which, whilst is removed from the final production build as we don't use it anywhere, was just dead code.

Its getting to the point now where it would be really nice not to have to remember to add CSS `@import` statements for all our individual components 👀

### CODE REVIEW

**Review by kaxcode — APPROVED** [review]
🗑️ ♻️ LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/373110.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 600f85753137640d6107c7b996c659cd325abd3e onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 600f85753137640d6107c7b996c659cd325abd3e onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/373110)

**Comment by johncowen** [comment]
Hmmm of course, this won't backport to 1.9.x easily due to the main nav changes in 1.10 🤔 .

**Comment by johncowen** [comment]
In the end, this wasn't required in 1.9.x so I ignored the auto backport/1.9.x failure, and removed the backport/1.9.x label, also see

https://github.com/hashicorp/consul/pull/10259 (which this PR was ontop of)
https://github.com/hashicorp/consul/pull/10284 (the revert of #10259)

**Pull request merged**
