### PR TITLE
Move to a makefile-based build

### PR DESCRIPTION
**Pull request by sethvargo**
This PR does a few things, here in no particular order:

- Moves back to `Makefile` (from GNUMakefile)
- Removes Windows-specific build scripts in favor of a unified Makefile and Docker build subsystem. Yes, this means you'll need Docker to build locally, but we already use Docker for final builds. You can still develop locally.
- Adds support for overriding things in enterprise builds (just add another file with the `.mk` extension to override anything, including targets)
- Drops gox in favor of straight GOOS and GOARCH
- Builds both tgz and zip files for distribution
- ⚠️ removes a bunch of code from the UI build. From what I could tell, this code was very legacy, because I cannot see how fix_times would make a difference in the vendored data
- ⚠️ removes publishing the UI as a separate package. We've had over 10 releases of Consul with the embedded UI - I don't think we need to distribute it separately anymore.

### CODE REVIEW

**Comment by slackpad** [comment]
A few quick thoughts from a skim, I'll do a more detailed review tomorrow:

1. We should keep the local build using `go install` since we do that all the time and that was a recent change that got the build way under 1s. We are also planning on shuffling things around so `go build` will work and make Consul like a normal Go project. It's fine if that doesn't have Git info injected/etc. but the project should build without a complex Makefile.
2. The fixup_time script was used during the release build to make sure that the checked in web assets in the .go file match the source html/css (we re-ran the build for those, fixed up the time stamps, and then did a diff) - we could make the release build include the web assets and have some kind of stub for dev builds, but it is handy to always have the UI available even for dev builds.
3. I'm all for getting rid of the UI bundle - that'll help people move over to the built-in one.
4. I'm all for cutting out the old Windows build steps - those were for local development and/or for the old CGO days, but those scripts didn't have anything to do with our actual Windows release build so we should gut them.

**Comment by magiconair** [comment]
Maybe I'm missing something here and if so please let me know. My two cents are below.

* Why do we have `GNUMakefile` and will rename to `Makefile` break things?
* Could you please move the changes for renaming `VersionPrerelease -> VersionPre` into a single commit? They are currently split over two (924980a and 040aaaa)
* I don't think`go test -parallel=20` will speed things up. My tests went from `1m34s` to `1m37s` with `-parallel=20` I think running `go test -i ./...` before running the tests has more impact since then test dependencies won't be built for every package. To improve test performance we should not start a consul server for every test as a separate process or lower the time for convergence (which we've done for `-dev` mode I think).
* `gox` builds all platforms in parallel which should be faster than building them sequentially
* I doubt that we need a `compile.sh` script since I've removed the last `build.sh` script two weeks ago. We can just inline the three commands in the `Makefile`. In general, the `Makefile` looks too verbose for my taste since the commands that we need to run aren't complex and I'd prefer to have them in one place, e.g. we don't need a `generate` target. Projects that need it just add a `go generate ./...` into their `build` target.
* `gofmt/goimports` is something that every Go IDE now runs automatically. We could run this before `test` but in general I'd skip it. The next time you save the file it'll be formatted. 

As for the "always build with Docker" approach:

Having one approach for all use-cases means to either have full reproducibility at the expense of higher turn-around times or faster builds at a somewhat higher risk of discrepancies.

Fully reproducible builds using Docker are only useful IMO if we run them every time and not just for some builds. However, the price all developers would pay is having builds go from `600ms` to `26s` (see below). Even if we can drop this to `5s` I'd say that the complexity isn't worth it since it is the wrong approach for building Go programs in the first place IMO.

The Go team has build a toolchain for creating bit-for-bit reproducible cross-platform builds which we should leverage. If you're concerned about the Go binary itself you can checksum it. Adding Docker makes sense for environments where you have a lot of external dependencies (java, ruby, python, ...) which you cannot control but for all Go binaries the answer is "single repo" and `go get github.com/hashicorp/consul` With that in mind Docker is belts-and-suspenders with no added benefit but significant additional complexity and penalty for build times. 

We run `make dev` hundred times a day and build a release once a month. Therefore, we should optimize the build process for the 99% use-case and make sure that those builds are reproducible so that we don't have to use Docker the one time we cut a release.

Again, maybe I'm missing something non-obvious (e.g. security relevant) and if so please let me know. So far I've been trying to get all Go projects I've been working on to this approach and that worked quite well.

For comparison:

```shell
# first build with Docker
$ time make dev
==> Building github.com/hashicorp/consul...
Unable to find image 'golang:1.8.1' locally
1.8.1: Pulling from library/golang
cd0a524342ef: Pull complete
e39c3ffe4133: Pull complete
85334a7c2001: Pull complete
b5844b8ce46a: Pull complete
07530c4e04c3: Pull complete
b0679b0a872e: Pull complete
3b3241e48946: Pull complete
Digest: sha256:509642e9d391b14b859ebcf19a1177717c8e04115706df6b03c61712e0f656ea
Status: Downloaded newer image for golang:1.8.1
-->       darwin/amd64: github.com/hashicorp/consul
--> Moving into bin/
--> Moving into GOPATH/

real	1m40.289s
user	0m0.245s
sys	0m0.231s

# second build with Docker w/o changes
$ time make dev
==> Building github.com/hashicorp/consul...
-->       darwin/amd64: github.com/hashicorp/consul
--> Moving into bin/
--> Moving into GOPATH/

real	0m26.067s
user	0m0.172s
sys	0m0.233s

# first build w/o Docker
$ rm -rf $GOPATH/pkg/* $GOPATH/bin/consul; time make dev
mkdir -p pkg/darwin_amd64/ bin/
go install -ldflags '-X github.com/hashicorp/consul/version.GitCommit=7fa2471b -X github.com/hashicorp/consul/version.GitDescribe=v0.8.2-13-g7fa2471b' -tags 'consul'
cp /Users/frank/go/bin/consul bin/
cp /Users/frank/go/bin/consul pkg/darwin_amd64

real	0m10.613s
user	0m33.271s
sys	0m4.806s

# second build w/o Docker w/o changes
$  time make dev
mkdir -p pkg/darwin_amd64/ bin/
go install -ldflags '-X github.com/hashicorp/consul/version.GitCommit=7fa2471b -X github.com/hashicorp/consul/version.GitDescribe=v0.8.2-13-g7fa2471b' -tags 'consul'
cp /Users/frank/go/bin/consul bin/
cp /Users/frank/go/bin/consul pkg/darwin_amd64

real	0m0.616s
user	0m0.298s
sys	0m0.258s
```

**Comment by slackpad** [comment]
I agree with most of @magiconair's concerns, but I wanted to add my perspective on Docker:

> We run make dev hundred times a day and build a release once a month. Therefore, we should optimize the build process for the 99% use-case and make sure that those builds are reproducible so that we don't have to use Docker the one time we cut a release.

I love our current speedy `go install` behavior for `make dev` and think that anything that a developer runs all the time like dev builds or tests shouldn't hit Docker. The Go tools are simple and fast and that would only add overhead.

We've never strived for reproducibility, but Docker is great for the release build for isolation. We've got a formally checked-in Go version that will get used and we know the build can't pick up stray dependencies in the `GOPATH` and needs to be using `vendor` deps only. I'm ok having release builds take a little longer to make sure the environment is clean.

Similar for the UI build parts which aren't part of the normal developer workflow. Those require Ruby and a bunch of other stuff that's hard to set up so it's great that the Dockerfile captures all that.

**Comment by magiconair** [comment]
Another way to solve the stray dependency problem:

https://github.com/hashicorp/consul/blob/master/command/agent/command.go#L1096-L1098

**Comment by slackpad** [comment]
> Another way to solve the stray dependency problem:

True but I actually like the simplicity of verifying the Docker solution for isolating the release build - it doesn't have access to anything on the host vs. having to make sure you write filters to ensure everything on the host is ok. We'd also need a check for the Go version, for example.

**Comment by slackpad** [comment]
Several of these things have been done, and a lot has changed since, so closing this out for now. We'd probably want to start fresh to have a go at this again.

**Pull request closed without merging**
