### PR TITLE
add IP validation

### PR DESCRIPTION
**Pull request by ltagliamonte-dd**
Validate service IP.
Fixes https://github.com/hashicorp/consul/issues/9929

### CODE REVIEW

**Comment by ltagliamonte-dd** [comment]
I had a look at the failing tests, they are failing because the registration request don't contain the `Address` field.
Do you want me to fix all the tests? Or `Address` is not a required field?

**Comment by dnephin** [comment]
Thank you for contributing this PR!  We discussed this issue a bit internally and it sounds like the reason that this field allows any string is because hostnames can be used instead of IP addresses. I'm not sure how common it is to use hostnames in this field, but changing that would likely break someone.

There may be some way to warn when the address is not in an expected format, but it seems like the changes in this PR can not be merged as-is. Maybe we can discuss the problem and some options for fixing it on the linked github issue?

**Comment by ltagliamonte-dd** [comment]
Thank you for the reply @dnephin, If consumed via the http API makes sense, I don't think that the DNS interface will work i can't find any CNAME support in [here](https://www.consul.io/docs/discovery/dns)

If hostnames can be used i don't know how can we do any sort of validation, at least I think we should call it out in the doc.

Since this field is a free text, do you think would be safer to "escape it" in order to protect from any malicious injection? I'm using sql terminology just for example here.

**Comment by dnephin** [comment]
Documenting that the field can be an IP or a hostname would be good. We might also want some tests with a hostname. From what I've seen, most of the tests use an IP (probably because that is way easier to test).

I'm not sure how we would escape it. Maybe url encoding, but we definitely don't want to encode `.` or `:` as those are necessary in IP addresses. I don't think any injection is possible in Consul, but maybe something consuming the API would need to take care to encode the responses before it reads them?

**Comment by ltagliamonte-dd** [comment]
i don't know who the doc update work if you have some doc i can look into improving the doc.

About the encoding/injection maybe still something to call out in doc... free test fields can always be used as threat vectors

**Comment by jsosulska** [comment]
Thank you for your PR!
Replied in [thread](https://github.com/hashicorp/consul/issues/9929#issuecomment-824426560).
I will be closing this and updating the issue to reflect a docs update.

**Pull request closed without merging**
