### PR TITLE
Update alert banner for HashiConf Global 2021

### PR DESCRIPTION
**Pull request by EnMod**
[:mag: Preview link upcoming](https://consul-git-nqupdate-alert-banner-hcg2021-hashicorp.vercel.app/)

---

This PR updates the alert banner for HashiConf Global 2021.

### CODE REVIEW

**Comment by mwickett** [comment]
@EnMod I put the `type/docs-cherrypick` label on here so that it'll get backported to `stable-website` automatically.

**Review by mwickett — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/457562.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 47cef4ea4df7285f36f8e4f87c1162821f0bd0f0 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 47cef4ea4df7285f36f8e4f87c1162821f0bd0f0 onto `release/1.10.x` succeeded!

**Pull request merged**
