### PR TITLE
Rename internal references for admin partitions to be "partition"

### PR DESCRIPTION
**Pull request by freddygv**
Renamed for consistency with the HTTP API and CLI flags.

### CODE REVIEW

**Review by markan — APPROVED** [review]
Looks good to me

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/517726.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/523640.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit ddb151aa7e5bb0d259d1bb5e03ebf09ae12d2daa onto `release/1.11.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/523640)

**Pull request merged**
