### PR TITLE
Fix dns service SRV lookup when service address is a fqdn

### PR DESCRIPTION
**Pull request by tionebsalocin**
Refactor dns to have same behavior between A and SRV.
Current implementation returns the node name instead of the service
address.
With this fix when querying for SRV record service address is return in
the SRV record.
And when performing a simple dns lookup it returns a CNAME to the
service address.

(For context history: #6252 and #6283)

### CODE REVIEW

**Comment by tionebsalocin** [comment]
Note: Contributor License has already been signed. I don't know why it is not validated here

**Comment by crhino** [comment]
@tionebsalocin Is the email you used to author this commit (`n.benoit@criteo.com`) associated to your Github account? It looks like Github is unable to make that link right now.

**Comment by tionebsalocin** [comment]
> @tionebsalocin Is the email you used to author this commit (`n.benoit@criteo.com`) associated to your Github account? It looks like Github is unable to make that link right now.

Hello @crhino, I've added this email to my account but still enable to submit the form (all field are pre-filled and not editable). Any suggestion on what I should do from here?

**Comment by banks** [comment]
@tionebsalocin I kicked the CAL check again and it's happy with you this time! I think @mkeeler was going to look over this once more, thanks for your effort here!

**Comment by mkeeler** [comment]
Yep, looking now.

**Pull request merged**
