### PR TITLE
docs: add missing verb

### PR DESCRIPTION
**Pull request by giovtorres**
This change adds a missing verb at the end of the sentence.

### CODE REVIEW

**Review by blake — APPROVED** [review]
Thank you!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/520632.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 38c1f3b9ea97ed043f2304c5899a80e551e87140 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 38c1f3b9ea97ed043f2304c5899a80e551e87140 onto `release/1.11.x` succeeded!

**Pull request merged**
