### PR TITLE
[Fix] Add missing quote in service documentation

### PR DESCRIPTION
**Pull request by M0NsTeRRR**

### CODE REVIEW

**Review by jsosulska — APPROVED** [review]
LGTM!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/397428.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit c138c383925991b7f9affbe66ee226f233ebcf4c onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit c138c383925991b7f9affbe66ee226f233ebcf4c onto `release/1.10.x` succeeded!

**Pull request merged**
