### PR TITLE
Enable compilation with Go 1.11 on Travis to avoid unstable tests

### PR DESCRIPTION
**Pull request by pierresouchay**
There a minor compilation differences between Go 1.10 and 1.x
which is currently Go 1.11 beta.x such as new compilation
warnings.

It will show more obviously the errors in Travus when error
is linked for instance to a new compilation warning

### CODE REVIEW

**Comment by pierresouchay** [comment]
@pearkes Go 1.11 provides additional compilation warnings, so it might be a good idea, but personally, I don't care, if you prefer, I'll switch to 1.10 only

**Comment by pierresouchay** [comment]
@pearkes DONE, compile only with Go 1.10 for now (but we loose the new compilation warnings of Go 1.11-betaX)

**Comment by pierresouchay** [comment]
@freddygv @pearkes As seen by @Aestek in https://travis-ci.org/hashicorp/consul/jobs/433508308 -> not specifying precisely the golang version used by compilation might lead to unexpected failures in tests (in that case, compilation did occur with golang 1.7 !

Specifying precisely is a good idea IMHO

**Comment by pearkes** [comment]
@pierresouchay agree -- we're now on 1.11 so perhaps should update this PR to that then we can get this merged?

**Comment by pierresouchay** [comment]
OK, I'll change it tomorrow

**Comment by pierresouchay** [comment]
@pearkes DONE, switched to golang 1.11

**Pull request merged**
