### PR TITLE
Update ENVOY_VERSIONS

### PR DESCRIPTION
**Pull request by nathancoleman**
### Description
No new minor versions, just incrementing the patches for hygiene's sake

### Links
[Envoy Releases](https://github.com/envoyproxy/envoy/releases)

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [x] appropriate backport labels added
* [x] not a security concern

### CODE REVIEW

**Review by sarahalsmiller — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @nathancoleman! a backport is missing for this PR [21820] for versions [1.15,1.17,1.18,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @nathancoleman! a backport is missing for this PR [21820] for versions [1.15,1.17,1.18,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @nathancoleman! a backport is missing for this PR [21820] for versions [1.15,1.17,1.18,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @nathancoleman! a backport is missing for this PR [21820] for versions [1.15,1.17,1.18,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @nathancoleman! a backport is missing for this PR [21820] for versions [1.15,1.17,1.18,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @nathancoleman! a backport is missing for this PR [21820] for versions [1.15,1.17,1.18,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @nathancoleman! a backport is missing for this PR [21820] for versions [1.15,1.17,1.18,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @nathancoleman! a backport is missing for this PR [21820] for versions [1.15,1.17,1.18,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @nathancoleman! a backport is missing for this PR [21820] for versions [1.15,1.17,1.18,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @nathancoleman! a backport is missing for this PR [21820] for versions [1.15,1.17,1.18,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by jmurret** [comment]
Removing the 1.15 backport label since the envoy versions for consul 1.15 are no longer incrementing on the Envoy side.

**Pull request merged**
