### PR TITLE
UI - minor css amends

### PR DESCRIPTION
**Pull request by johncowen**
Startup image would remain shown if you hit a HTTP error on startup only. This PR addresses that.

Additionally text nudge for healthcheck info on the Nodes listing page.

### CODE REVIEW

**Comment by johncowen** [comment]
Figured out a way to test this using ember tooling, almost there. The test passes when run on its own, but not when run with the other tests as using content in test/index.html means the test isn't isolated. Any other ideas appreciated!

**Comment by meirish** [comment]
@johncowen You could move this to an initializer that removes the content of the root element on boot rather than removing a class on the HTML tag. ember-app-shell takes this approach and I think TFE also has an initializer for this (it was used in the old atlas code). If you wanted to still test it acceptance-style, I think that may be tricky with the way the test suite runs.

**Comment by johncowen** [comment]
Hey @meirish , thanks for looking at this for me!

Happy to relook at changing how this works after the next release. At the moment this is purely to fix a bug I noticed where the startup logo would remain if you immediately hit a 404.

I don't want to completely change how this works at this stage, rather just tweak so that it works as required using the same approach.

The test I've added proves that it is now fixed (although the test needs to be manually run so it is properly isolated)

It sounds like a different approach wouldn't help with me being able to test this within ember either?

**Comment by johncowen** [comment]
ping @DingoEatingFuzz 👍

**Comment by DingoEatingFuzz** [comment]
@meirish, if I'm following correctly, this loading indicator goes away after the application model hook finishes, not when the ember app initializes, so moving to an initializer would result in different behavior.

**Comment by johncowen** [comment]
> Is the content-for change to avoid putting ember-loading in both the application and test index.html file?

Yup

It's also given me an idea for my broccoli woes 😄

**Pull request merged**
