### PR TITLE
Verify service name for the successful dns resolution

### PR DESCRIPTION
**Pull request by Matts966**
#6335 

```
{
  "services": [{
    "name": "docker|build"
  }],
  "bind_addr": "{{GetInterfaceIP \"en0\"}}",
  "data_dir": "~/consul-data/"
}
```

The configuration above can cause dns resolution failure for the service name is not valid as hostname. So this PR added a flag `verify-service-name` to check if the service name is valid as hostname.

Sample usage is as follows.

```
$ consul agent -config-dir ~/conf.d -verify-service-name
==> service name docker|build is not valid, use hostname that matches with ^[a-zA-Z0-9\-\.]$ for successful dns resolution
```

```
$ consul validate -verify-service-name ~/conf.d/config.json
Config validation failed: service name docker|build is not valid, use hostname that matches with ^[a-zA-Z0-9\-\.]$ for successful dns resolution
```

If the flag is not specified, the validation will be skipped.

```
$ consul validate ~/conf.d/config.json
Configuration is valid!
```

### CODE REVIEW

**Comment by i0rek** [comment]
@Matts966 thanks for your work! Could you add tests to make sure you are validating the service name correctly?

**Comment by Matts966** [comment]
@pierresouchay 
Maybe, it should also be validated when service is added by `consul services register` as this CL only validates the name of services in config files?

Also I am not sure if . & _ char in service name cause resolution failure  or not. I can figure it out just by trying it but please teach me if anyone knows it. If it causes resolution failure, I will change the regexps and can't re-use that of nodename.

Finally if _ char is allowed, may I make [this function](https://github.com/hashicorp/consul/blob/ed4e64f6b22fa3f52913b07d2150feb8d9e8976d/agent/consul/acl_endpoint.go#L663) exported, and reuse it?

**Comment by pierresouchay** [comment]
@Matts966 According to RFC https://tools.ietf.org/html/rfc1123#page-13

If am a not mistaken, the regex should probably be:

`^[a-zA-Z0-9][a-zA-Z0-9-]{0,62}`

The warning about node_name should be the same since it is triggered for the same need of compatibility with DNS labels, so IMHO, it should bee the same

**Comment by Matts966** [comment]
@pierresouchay 
Thank you for kind advices.
I pushed some changes to this PR.

- Added tests for http api and validate command
- Move a variable and a constant about dns to config package in order not to cause cyclic import error
- Make the functions pass the test

I'm now waiting for CI result. Some test cases about agent (not modified) failed by no leader error.

**Comment by Matts966** [comment]
Test passed, maybe sometimes agents can't connect each other for network related issues or somthing?

**Comment by i0rek** [comment]
@Matts966 thank you for your work! Are you still interested in adding this?

**Comment by i0rek** [comment]
Closing because no reply. I am happy to reopen in case there are updates. Thanks!

**Pull request closed without merging**
