### PR TITLE
Update NIA Security Model for Beta

### PR DESCRIPTION
**Pull request by picatz**
This PR introduces some minor updates to the NIA security model for the beta.

- Change from Tech Preview to Beta in the sidebar
- Update the overview section to better reflect the other NIA docs.
- Changes to the "NIA Daemon" wording to also refer to `consul-terraform-sync`, using them interchangeably where I thought it made sense.

### CODE REVIEW

**Review by eikenb — APPROVED** [review]
Read through everything once and it sounds good. Naming changes looks good.
:+1:

**Comment by findkim** [comment]
@picatz Do you mind changing the destination branch from `master` to the branch for the next release [`nia/docs-0.1.0-beta`](https://github.com/hashicorp/consul/tree/nia/docs-0.1.0-beta)? Once it's merged there we can push these changes together with the other 0.1.0-beta docs.

**Comment by picatz** [comment]
No problem @findkim, will update destination branch now. 😄

**Comment by findkim** [comment]
Thanks! I just rebased the branch so the diffs in this PR aren't huge.

**Review by findkim — APPROVED** [review]

**Comment by picatz** [comment]
Awesome, thank you!

**Pull request merged**
