### PR TITLE
Allow SOA reply customization

### PR DESCRIPTION
**Pull request by Ashald**
This PR adds an option to configure Consul's SOA response via config file. Only `ns` and `mbox` values can be configured as per example below:
```
{
    "dns_config": {
        "soa": {
            "ns": "ns.acme.co.",
            "mbox": "mbox.acme.co."
        }
    }
}
```

This PR includes the feature itself, tests and documentation update.

I ran into a situation where I need such an option while dealing with the infrastructure where I cannot set forwarding in main DNS server but rather have to set-up a delegation to another DNS server that in turn forwards requests to Consul:

```
Bind X [x.acme.co.] --(zone delegation)--> Bind Y [y.acme.co.] --(forward)--> Consul
```

In order to have this chain work properly I needed to make Consul to reply with a SOA record pointing to `y.acme.co.` from the example above.

Although I don't think my situation is very common I think some people might have to deal with similar circumstances. Moreover this change doesn't look like one that introduces any complexity etc but rather a feature that makes Consul more flexible.

P.S.: Unfortunately I have 0 prior experience with go and could have done something not in the best way. I'd be happy to improve the code in my PR if required if you can point me to issues I need to fix.
P.P.S.: This is the 1st of a series of PRs that I intended to make improving Consul's DNS interface and its compatibility with Bind DNS server.

### CODE REVIEW

**Comment by Ashald** [comment]
Built a version of Consul from this brunch and used it for setup described above. Works like a charm.

**Comment by slackpad** [comment]
@Ashald sorry for the delay reviewing this one - I'll try to knock it out this week.

**Comment by slackpad** [comment]
Hey @Ashald sorry I never had a chance to get back to this one. Did you find you didn't need it? I'm getting ready to cut 0.7 tomorrow so am about to make a sweep through all these long standing PRs and issues so feel free to ping me if you'd like to try to get this in.

**Comment by Ashald** [comment]
Yeah, it turned out that we don't need this feature. generally speaking I still think that it might be useful in some cases but not critical in any way so I decided to close the PR but keep the branch just in case.

**Comment by slackpad** [comment]
Sounds good - thanks for the update and sorry again for the long delay!

**Comment by CVTJNII** [comment]
I'm experiencing an issue with BIND delegation I believe this would solve, and I think allowing administrators to set proper SOA records is a benefit.  I'd like to vote for this to be reopened.

**Comment by magiconair** [comment]
I can pick this up when I'm done with the config refactoring.

**Pull request closed without merging**
