### PR TITLE
Fix a few small bugs

### PR DESCRIPTION
**Pull request by dnephin**
Best viewed by individual commit, details in the commit messages.

### CODE REVIEW

**Review by FFMMM — COMMENTED** [review]
These changes make sense to me 💯 !

Feel free to ping once the changelog is added

**Review by FFMMM — APPROVED** [review]
🚀 !

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/541293.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 065f6f89fbe9f44ae4d66d2096d258f99608b03f onto `release/1.11.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 065f6f89fbe9f44ae4d66d2096d258f99608b03f onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/541293)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 065f6f89fbe9f44ae4d66d2096d258f99608b03f onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/541293)

**Pull request merged**
