### PR TITLE
Add Timeout field to CheckMonitor

### PR DESCRIPTION
**Pull request by mshean**
@slackpad This addresses https://github.com/hashicorp/consul/issues/1508

### CODE REVIEW

**Comment by mshean** [comment]
Any hope of this getting merged? We are running a patched version of consul internally with these changes.

**Comment by akmalabbasov** [comment]
+1

**Comment by slackpad** [comment]
This looks good - thanks!

**Comment by imcom** [comment]
hey guys, it is nice to have a timeout configurable, but there is still a tiny problem, that when the check turns to critical, how should I distinguish it is a timeout or some other failure ? if there is no indication / output from a timed out check ...

**Pull request merged**
