### PR TITLE
Use the new Travis Docker infrastructure and stuff

### PR DESCRIPTION
**Pull request by sethvargo**

### CODE REVIEW

**Comment by ryanuber** [comment]
There are some interesting things in here. If we restrict to master does that prevent us from getting results back on PRs? Branches dont really need travis to run but it helps for PRs.

**Comment by sethvargo** [comment]
@ryanuber quite the opposite actually

Right now, if we (someone who has commit to hashicorp/consul) push a branch (like f-new-feature) to hashicorp/consul, a Travis build is triggered. Next, when we open a PR for said branch, **another** build is triggered. As such, for each commit we push beyond the original PR, **two** builds will happen - one because we pushed to a branch that is in the repo and two because we pushed a commit to an open PR.

**Comment by sethvargo** [comment]
That being said, I don't know why the build is failing...

**Comment by ceh** [comment]
@sethvargo OS X is in beta and can be enabled according to http://docs.travis-ci.com/user/multi-os/

Updates #639.

**Comment by sethvargo** [comment]
@ceh ^

**Comment by sethvargo** [comment]
Just gonna close this out. Not worth pursuing right now.

**Pull request closed without merging**
