### PR TITLE
New header/footer design

### PR DESCRIPTION
**Pull request by captainill**
Along with the header/footer design I've also fixed an issue with #cta div messing up the page width on mobile devices.

'edit this page' has also been moved into the page content instead of appearing in the footer with the nav links.

### CODE REVIEW

**Comment by slackpad** [comment]
Hey @captainill this is looking awesome!

Running this locally and clicking around I had a few questions for you.

###### You probably need to rebase. A "Prepared Queries" section will get added to this nav:

image

###### I'm seeing one 403 for a Typekit-related resource:

image

###### What do you think about anchoring the "edit this page" link to the bottom? When I first landed on this page I thought "oops this is a placeholder". It looks fine for long pages but a little funky for short ones:

image

###### Not sure if it is related to the 403 error, but these headings on the main page ended up super light:

image

(same for the Key Value Storage heading that follows this one)

**Comment by captainill** [comment]
@slackpad Thanks for looking over!

-I'll do the rebase
-The failed to loaded resource 403 is on the live site so it'll be good to fix that anyhow. Not sure what the story is there
-Ah! I actually anchored it in the other sites as I was doing this but I missed it here. Good call.
-I think that the header issue (super light font color) is just a selector issue but I'll fix whatever it is

**Comment by slackpad** [comment]
@captainill any chance you can make a pass through here again before we ship 0.6? Thanks!

**Comment by captainill** [comment]
@slackpad Along with 'by HashiCorp' logo in the header being correct now I

-merged maste into my branch
-pinned the EDIT THIS PAGE link to the bottom
-made the H2 headings on the homepage readable

I had to reach out to Typekit about the 403. As far as I can tell typekit is configured correctly (the correct domain is listed for usage and the embed code is right) so I'm not sure what the deal is. I can report back when I get that sorted but if the rest checks out I would merge this and i'll circle back with a 403 fix when I've got it.

**Comment by slackpad** [comment]
Looks awesome!

**Pull request merged**
