### PR TITLE
Add changelog entry for namespace default policy/role fix

### PR DESCRIPTION
**Pull request by dnephin**

### CODE REVIEW

**Review by dhiaayachi — APPROVED** [review]
LGTM!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/501619.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 81759c7a41eba1ff7bc7586d7625c7447bcfc39a onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 81759c7a41eba1ff7bc7586d7625c7447bcfc39a onto `release/1.9.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 81759c7a41eba1ff7bc7586d7625c7447bcfc39a onto `release/1.8.x` succeeded!

**Pull request merged**
