### PR TITLE
docs: Add example of escaping tracing JSON using jq

### PR DESCRIPTION
**Pull request by blake**

### CODE REVIEW

**Review by dnephin — APPROVED** [review]
Nice!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/386522.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 64d122b0a2447a6e0597bdaa3912e83cd15ef3ed onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 64d122b0a2447a6e0597bdaa3912e83cd15ef3ed onto `release/1.10.x` succeeded!

**Pull request merged**
