### PR TITLE
Updated health check docs page with HCL examples

### PR DESCRIPTION
**Pull request by preetapan**
Updated all the examples in [Health Checks Docs](https://www.consul.io/docs/discovery/checks) to have HCL equivalents

### CODE REVIEW

**Review by FFMMM — APPROVED** [review]
🚢 this LGTM!

**Review by karl-cardenas-coding — APPROVED** [review]
👍🏼

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/545897.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 92cc690e0d90fc935540cb962e4e9cdedc02622e onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 92cc690e0d90fc935540cb962e4e9cdedc02622e onto `release/1.11.x` succeeded!

**Pull request merged**
