### PR TITLE
NET-9143 - sameness group queries in DNS do not respect DefaultForFailover setting and always assume failover behavior

### PR DESCRIPTION
**Pull request by jmurret**
### Description
In Enterprise edition, we fixed a bug related to Sameness Groups and these are the docs changes related to it.

`DefaultForFailover` dictates whether failover behavior should occur when requesting a service using a sameness group. Mesh currently respects this, however, DNS does not. This allows a caller to request DNS for a service using a sameness group and get failover behavior when member services are unhealthy, even though the sameness group was configured not to do this.

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [ ] appropriate backport labels added
* [ ] not a security concern

### CODE REVIEW

**Comment by jmurret** [comment]
Thanks @boruszak!

**Review by DanStough — APPROVED** [review]
Just a drive by review while I was looking at the implementation. Looks good!

**Comment by hc-github-team-consul-core** [comment]
@jmurret, a backport is missing for this PR [21029] for versions [1.16,1.17] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@jmurret, a backport is missing for this PR [21029] for versions [1.16,1.17] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@jmurret, a backport is missing for this PR [21029] for versions [1.16,1.17] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Pull request merged**
