### PR TITLE
[Streaming][Bugfix] Fix error(s) on services not being modified before cache TTL

### PR DESCRIPTION
**Pull request by pierresouchay**
On services not changing much, using the streaming would cause some
errors with context.canceled being returned.

This was caused by TTL of cache being lower than entry TTL.
With streaming, there is no garantee that data will be updated before
10 minutes, thus cache was expiring while request was stil on flight.

We thus ensure that at least a NotModified data will be issued before
the cache does expires.

Another problem that was when the data was being updated because
the cache background routine was stopped because entry did expire.

A new error `ErrCacheRefreshRoutineStopped` has been added to ensure
this result cannot pollute the cache with wrong data.

### CODE REVIEW

**Review by dnephin — COMMENTED** [review]
Thank you for working on this fix!

I'm concerned that this fix requires changing the `agent/cache` in a couple places. The agent cache is already quite complex, and I don't think making it more complex (cyclomatic complexity is increased) for a use case (streaming) that doesn't technically require caching is the right trade off.

I'd like to explore removing the agent/cache from streaming, which I think should make it easier to fix this bug.  I've started some really rough work on that approach in https://github.com/hashicorp/consul/compare/dnephin/remove-streaming-from-cache

**Comment by pierresouchay** [comment]
@dnephin the patch can be smaller by removing some of the changes in getEntryLocked() for instance. It is also possible use a hard-coded value for the timput computation (and thus removing the TTL computation). Might fail sometimes, but not much in case of services being watch continuously (while not being modified). 

Minimal working patch was 3 lines (hard coding cache TTL to 10m+10s and hard coding timeout to 10m), if you want I can do a more minimalist patch (however it might fail a 1 request in some conditions IIRC) 

I do agree however that embedding it into the cache complexifies greatly implementation (most notably because the level of goroutines in direction not really needed), so probably way to go.
I was just trying to fix current implementation with fewer lines as possible and adding a reliable unit test (I had issue with race detection in first iterations).

More globally, the code in cache seems fragile when TTL of entry expires while fetching data (but did not find a way to spot/solve it easily, might be linked to #8980 and similar issues), I feel it is linked to the "first" boolean value (but one again, I tried to make the patch minimal)

**Comment by pierresouchay** [comment]
Here is a full explanation of all the changes:
 1. Use Cache TTL bigger than MaxQueryTimeout -> avoid fecthing to be stopped before entry get evicted: https://github.com/hashicorp/consul/pull/9555/files#diff-97d0de9c08776c4ff05f75254d7319f757e5b56f78b428d0b2574ee43b77bb9dR42-R44
 2. If a cache entry exists, but its TTL is very small, ensure that at least a first snapshot will be retrieved even in the case of eviction while running by increasing the TTL of entry: https://github.com/hashicorp/consul/pull/9555/files#diff-2841640c081feffd396b6b574114bfbfc0cc0362784feecf7d1379f6c0f68059R524-R528 
 3. In the event of change timeout being smaller than eviction time (less likely since item 2 has been changed), be sure to return before eviction: https://github.com/hashicorp/consul/pull/9555/files#diff-2841640c081feffd396b6b574114bfbfc0cc0362784feecf7d1379f6c0f68059R604-R619
 4. In the now very unlikely case where eviction still did take place before streaming was able to retrieve the snapshot (thanks to item 2 & 3), return HTTP 500, not wrong data: https://github.com/hashicorp/consul/pull/9555/files#diff-2841640c081feffd396b6b574114bfbfc0cc0362784feecf7d1379f6c0f68059R494-R500 -> this is also a security measure to avoid returning garbage data (nil with Index=0)
 5. Added unit test that test case 3 and 4, that tries to get an update from the cache when the entry is about to expire

This is far from being perfect, most notably, I am not a big fan of https://github.com/hashicorp/consul/pull/9555/files#diff-2841640c081feffd396b6b574114bfbfc0cc0362784feecf7d1379f6c0f68059R525 since we hardcoded the value 1s, aka: if TTL remaining is less than 1s, increase it. I could use either a different value, either bigger, either as a minimum of time and CacheTTL value.

Now, I cannot crash in any way the new unit test:
```
go test -timeout 30s -run ^TestStreamingHealthServices_IntegrationWithCache_Expiry$ github.com/hashicorp/consul/agent/cache-types -race -gcflags=all=-d=checkptr=0
```

=> so I suspect I fixed most race/timing conditions for streaming.

Well, I agree the fix is not the most beautiful fix ever, but it seems to do the job.

**Comment by pierresouchay** [comment]
@dnephin Ok, the PR has now conflicts :(
This one is very important, as otherwise streaming is not working at all.
The modification of `TestStreamingHealthServices_IntegrationWithCache_Expiry()` https://github.com/hashicorp/consul/pull/9555/files#diff-01421f6ef1e75952c2ce30a9796d77615fb5ceb52b4f833e6fe2ce077a6eb4afR573 really highligh the race issues we have currently

**Comment by banks** [comment]
Hey quick update on this.

This was definitely and important issue. We're not going to merge this PR just because we ended refactoring the client code significantly in the process of our own testing to resolve this and a bunch of other issues we found.

That work hasn't been merged yet but will be soon so I'll close this for now. A fix for this issue will be in 1.10 release though!

Thanks again for the contribution Pierre!

**Pull request closed without merging**
