### PR TITLE
Make sure UDP DNS responses aren't larger than allowed

### LINKED ISSUE #854: go 1.4.2 cannot parse some dns responses from consul
This can be reproduced by calling `net.LookupHost("metrics-api.librato.com")` with go 1.4.2 using consul as the dns server.

After some investigation, we believe the problem is that the udp dns response exceeds the 512 byte limit specified in rfc 1035, and does not set the truncate flag.  The go 1.4.2 implementation of the dns client cannot parse such responses.  This can be seen by looking at `readDNSResponse` starting on [line 41 of net/dnsclient_unix.go](https://github.com/golang/go/blob/master/src/net/dnsclient_unix.go#L42).  The function uses a fixed size buffer, and will only pass part of the message to the deserialization function.  Prior versions of go used a 2000 byte buffer as seen [here](https://github.com/golang/go/blob/release-branch.go1.3/src/pkg/net/dnsclient_unix.go#L58).

Setting the `dns_config.enable_truncate` flag in consul configuration did not resolve this problem.  It appears that the flag is only used when sending srv record responses.

The frequency of this problem could be lowered by using dns message compression (described in section 4.1.4 of rfc 1035).  The response from 8.8.8.8 for the lookup is close to 500 bytes smaller than from consul, and well under the 512 byte limit.

### PR DESCRIPTION
**Pull request by idubinskiy**
Reopen of #1733. This should close #854. It's an analogue/alternative to #971.

### CODE REVIEW

**Comment by idubinskiy** [comment]
I have another branch which adds a commit on top of this one removing the 3-record limit and adding compression before attempting to trim records to fit 512 bytes. I know there were some concerns raised in #971 about compression, and I'm not sure whether removing the limit is a backwards-compatible change. But if that's preferable, I can open a PR with that code instead.

https://github.com/idubinskiy/consul/commit/1f199a674c3f3f7d3c26a7bc50057e522aa220cb

**Comment by idubinskiy** [comment]
Per discussion with @slackpad on IRC, added another commit to the compression branch which adds an `enable_compress` config option and only tries compression if that one is set.

https://github.com/idubinskiy/consul/commit/0ac35ba7f2074caf4cf3d4829f28412eb00c2323

**Comment by slackpad** [comment]
Hi @idubinskiy (just saw your IRC note) I didn't forget about this! Hopefully I'll get a little time tomorrow - I  want to look over the RFC and check a couple things before we merge.

**Comment by idubinskiy** [comment]
@slackpad Thanks!

**Comment by slackpad** [comment]
Hi @idubinskiy I took your PR and make a few small tweaks on the one linked above. Once CI passes I'll merge. Sorry for the delay in reviewing this one and thanks for the fix! I'd like to avoid compression as that puts an additional burden on clients to implement that correctly. Your fix should get at the root of the issue (compression was probably just making things work in some cases), and it doesn't seem necessary to compress on top of this change. We randomly shuffle the results, so even if the user is getting even 1 response back, things should work properly in most cases.

**Pull request closed without merging**
