### PR TITLE
Docs: Rename and re-title docs page for installing Consul API Gateway

### PR DESCRIPTION
**Pull request by Jeff-Apple**
Changing the file name, page name and title of the page containing installation instructions for Consul API Gateway. This should make it easier to find the install instructions when navigating the site and when doing web searches.

### CODE REVIEW

**Review by mikemorris — APPROVED** [review]
This may show one backport failure from a duplicate attempt which should be safe to ignore, intent is for this commit to end up on `release/1.11.x`, `release/1.12.x`, `main` and `stable-website` though.

**Review by karl-cardenas-coding — APPROVED** [review]
👍🏼

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/641779.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit c90315a8e123cd6889ae5aebcde233cf508b4292 onto `stable-website` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/641779)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit c90315a8e123cd6889ae5aebcde233cf508b4292 onto `release/1.12.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/641779)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit c90315a8e123cd6889ae5aebcde233cf508b4292 onto `release/1.11.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/641779)

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/646258.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit c90315a8e123cd6889ae5aebcde233cf508b4292 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit c90315a8e123cd6889ae5aebcde233cf508b4292 onto `release/1.12.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/646258)

**Pull request merged**
