### PR TITLE
Add changelog entry for network area timeout updates

### PR DESCRIPTION
**Pull request by freddygv**

### CODE REVIEW

**Review by mkeeler — APPROVED** [review]

**Review by mkeeler — CHANGES_REQUESTED** [review]
You may want to throw in a `**(Consul Enterprise)**` between `areas:` and the actual changelog.

**Review by mkeeler — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/368777.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit f8c40759533fe450b82f65c841009442589b5bd8 onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit f8c40759533fe450b82f65c841009442589b5bd8 onto `release/1.9.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit f8c40759533fe450b82f65c841009442589b5bd8 onto `release/1.8.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit f8c40759533fe450b82f65c841009442589b5bd8 onto `release/1.7.x` succeeded!

**Pull request merged**
