### PR TITLE
Alibaba Aliyun ECS auto discovery

### PR DESCRIPTION
**Pull request by sunadm**
New -retry-join-ecs configuration options. Allow bootstrapping by automatically discovering Aliyun ECS instances with a given tag key/value at startup.

### CODE REVIEW

**Comment by slackpad** [comment]
Hi @sunadm we are thinking about this internally a bit to figure out the best way forward. It's tough to absorb a ton of new deps per provider, especially since we usually only need a subset, and it does increase the config complexity. Plugins are an option, or we could also make a little library that makes it easy to run a joiner process alongside Consul that just uses the Consul API client.

**Comment by sunadm** [comment]
@slackpad , ur thoughts make sense.

**Comment by magiconair** [comment]
@sunadm We have decided to take a different approach and move the discovery code into a separate package which we can then pull into consul and nomad for example. You can find the code in #3144 and it would help us a lot if you could provide us with a PR that merges against that. This will decouple the discovery code from consul and the integration into consul will be through a simple string value. We then need a second PR for the config change in consul or I can pick this up once your change is merged.

**Comment by magiconair** [comment]
@sunadm Could you please open a PR in github.com/hashicorp/go-discover for this? I'll merge the lib back into consul as soon as I have fully tested it.

**Comment by slackpad** [comment]
Closing this per https://github.com/hashicorp/consul/pull/2655#issuecomment-315400734.

**Pull request closed without merging**
