### PR TITLE
ui: Enable centralized queryParams configuration

### PR DESCRIPTION
**Pull request by johncowen**
We've always found it strange that you define your URLs and URL params in the Router and then you have to define your query parameters in both your Route and your Controller. Whenever you change the queryParams in one place you have to remember to change it in another.

This commit adds a `createQueryParams` function, when passed our custom
routing configuration it will return a function that lets you reference
query params configuration by route name. This can then be used in
Routes and Controllers to avoid duplicated query
parameter configuration.

This essentially moves all URL configuration into the same place, the Router.

We don't use this yet, but will be using it in upcoming work

Usage is as follows:

```javascript
import { queryParams } from 'consul-ui/router';
// route
Route.extend({
  queryParams: queryParams('name.of.route')
})

// controller
Controller.extend({
  queryParams: queryParams('name.of.route')
})

```

Potentially we might just reopen `Route` and `Controller` to make this completely 'automatic' across our app.

### CODE REVIEW

**Comment by gregone** [comment]
curious to know if you had looked at https://github.com/NullVoxPopuli/ember-query-params-service or https://github.com/offirgolan/ember-parachute instead ?

**Comment by johncowen** [comment]
I've seen ember-parachute come up a few times, biggest things that turns me away from it is:

> One important point about this addon is that it is opinionated about where the data is fetched. In a traditional query params setup, your route is responsible for fetching data in its model hook. With this addon, the responsibility moves into the controller. 

Which means that the controller takes on much more responsibility - I'm trying to remove as much responsibility as possible from the controller.

Also:

> The benefit of this approach is that data fetching no longer blocks your UI from loading

We currently need our data fetching to block the UI.

--- 

`ember-query-params-service`

I'm not actually sure if I've seen this, it looks fairly new? Although I think this is the basis for an RFC I've seen (mentioned further down here)

Main thing here:

> Ember.js v3.11 or above

We are currently running 2.18, so this is an immediate no-go for us, right now at least.

Overall the approach we use here, is simple and also means less dependencies. I know there is recognition within the ember community that this is a bugbear for folks (having to configure queryParams in various places), so if/when something comes along to prevent us from having to do this, we can remove these lines of code and adopt whatever that new approach is (I'm aware there is already an RFC floating around by the same person who wrote `ember-query-params-service` that recognises the problem and suggests moving queryParam configuration to the router file, which is basically what we do here)

Overall we don't do anything special here, or non-ember or new, we just return the queryParams json object from a function in another file. The router file seemed to make sense to me as thats where you define the rest of the URL, now URL params and query params configuration are all in the same place.

**Comment by johncowen** [comment]
Hey @gregone 

Just checking in with you here to see if you had any more questions around this PR, or whether its something you can approve or reject?

Thanks!

**Comment by johncowen** [comment]
Closing this for staleness reasons, could be cherrypicked later from here https://github.com/hashicorp/consul/pull/6054/commits/9230d523c5eb28f2c853eb9da485eb64c5ad34a2

**Pull request closed without merging**
