### PR TITLE
Adding post-publish events to ci.hcl.

### PR DESCRIPTION
**Pull request by sarahethompson**
https://docs.google.com/document/d/1dUjhfqccvDnfnKkSPxjTu19zn9v4jSMT4_Lfh0mQ1yQ/edit?usp=sharing

### CODE REVIEW

**Review by samsalisbury — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/596880.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 6f1101e667626e67bc52dce85543dbf7bcf90c13 onto `release/1.11.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 6f1101e667626e67bc52dce85543dbf7bcf90c13 onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 6f1101e667626e67bc52dce85543dbf7bcf90c13 onto `release/1.9.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 6f1101e667626e67bc52dce85543dbf7bcf90c13 onto `release/1.8.x` succeeded!

**Pull request merged**
