### PR TITLE
Add command 'consul catalog services -service <my-service>'

### PR DESCRIPTION
**Pull request by jewertow**
## Purpose

Consul CLI should have a command to view service details #6528

## References

See #6528

## Changes

- Add command `consul catalog services -service <my-service>`

### CODE REVIEW

**Comment by jewertow** [comment]
At the moment command `consul catalog services -service <my-service>` ignores other command options like `-node` and `tags`. I think it should work together, for example:
`consul catalog services -node <node> -service <service-name> -tags`
should return
`<service-name>    <service-address>     <service-port>      <tags>`

@ishustava what do you think?

**Comment by i0rek** [comment]
@jewertow thank you for your work! Is this still something you would like to add?

**Comment by jewertow** [comment]
@i0rek yes, I would like to add it.

**Comment by i0rek** [comment]
Closing because no response. Happy to reopen if that changes.

**Pull request closed without merging**
