### PR TITLE
ui: Remove KV pre-flight auth check

### PR DESCRIPTION
**Pull request by johncowen**
Related to https://github.com/hashicorp/consul/issues/11098

This PR removes the KV pre-flight check to the internal authorization endpoint and instead relies on the response from the normal KV endpoint, thin client style.

### CODE REVIEW

**Review by randallmorey — APPROVED** [review]
Not sure if you have a feature flag system in place but could this be a feature flag?  That may make it more visible so it's not forgotten.  Also a small change so might not be worth it.

**Comment by johncowen** [comment]
👍 ty!

Yeah we could have feature flagged this with code I suppose. I _kinda_ have here, I'm planning on just search for the issue number once the backend issue is resolved, which is kind of like a poor mans feature flag, hence the extra comments in the code I've not changed. tbh I'm not even sure when the backend API issue is going to be resolved.

I suppose also code based feature flagging would involve injecting our env service, adding the flags, probably deciding on what to call the flag etc etc, basically a bunch of code that we will just remove once the backend it fixed. I guess I'm thinking code based feature flagging would be more for being able to turn things on and off and on and off etc etc multiple times, or maybe to be able to work on a feature only in certain environments, not just for enabling something once its working and thats the end of it.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/543441.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit d9a315e2a56df27d03a3e8da40a9f53c5baa29bc onto `release/1.11.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit d9a315e2a56df27d03a3e8da40a9f53c5baa29bc onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/543441)

**Pull request merged**
