### PR TITLE
docs: Fix two small typos in "What is Consul?" introduction

### LINKED ISSUE #21109: docs: Two small typos in "What is Consul?" introduction
#### Overview of the Issue

There are two small typos in the introductory [What is Consul?](https://developer.hashicorp.com/consul/docs/intro) documentation:

- **device** should be **devices** in the following sentence: `Consul offers service discovery, service mesh, traffic management, and automated updates to network infrastructure device.` [(What is Consul?)](https://developer.hashicorp.com/consul/docs/intro#what-is-consul)
- **discloser** should be **disclosure** in the following sentence: `Microservice architectures are complex and difficult to secure against accidental discloser to malicious actors.` [(Enable zero-trust security)](https://developer.hashicorp.com/consul/docs/intro#enable-zero-trust-network-security)

Also, hi! 👋 I'm a first-time contributor and I'd love to create a PR to address this issue, if y'all don't mind.

---

#### Reproduction Steps

1. Visit https://developer.hashicorp.com/consul/docs/intro

### Consul info for both Client and Server

Not applicable

### Operating system and Environment details

Not applicable

### Log Fragments

Not applicable

### PR DESCRIPTION
**Pull request by beckilee**
### Description

This PR fixes #21109. It addresses two small typos in the [What is Consul?](https://developer.hashicorp.com/consul/docs/intro) introductory documentation.

This is my first contribution to Consul, so please let me know if there's anything I need to change. Thanks!

### Testing & Reproduction steps

Not applicable

### Links

- [What is Consul?](https://developer.hashicorp.com/consul/docs/intro) documentation

### PR Checklist

* [ ] updated test coverage
* [X] external facing docs updated
* [x] appropriate backport labels added
* [X] not a security concern

### CODE REVIEW

**Review by blake — APPROVED** [review]
Thank you!

**Comment by hc-github-team-consul-core** [comment]
@beckilee, a backport is missing for this PR [21110] for versions [1.18] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@beckilee, a backport is missing for this PR [21110] for versions [1.18] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by beckilee** [comment]
Hi @blake! Sorry to bother you, but the automated comments on this PR say that a backport is missing for version 1.18, even though a backport PR (#21112) was created. Is there something else I need to do on my end? Thanks so much! 🙂

**Comment by blake** [comment]
@beckilee Thanks for flagging this. I just merged #21112. The changes should be visible on the website shortly.

**Pull request merged**
