### PR TITLE
Services Tab "unhealthy" marking

### LINKED ISSUE #16550: Services Tab "unhealthy" marking
As a feature request, it would be nice if a service wasn't marked red if a single node was unhealthy, rather maybe subtext stating X/Y nodes passing.  

When an entire service is marked red, but potentially only 1 out of many nodes are unhealthy, it gives a false sense of a critical problem. 

Potentially a % based configurable to say "if X% of nodes are failing, mark the service as red"

### PR DESCRIPTION
**Pull request by vijayraghav-io**
Closes #16550 

Hi @jkirschner-hashicorp / @huikang 

PFB  proposed design and implementation

1. "MarkServiceStatusThreshold" - New configuration parameter is introduced inside UIConfig { }
- Default value is set as 0.6 (i.e. 60%). The most acceptable default value can be arrived at and we can update.
- Based on this parameter's value the service is marked red (critical) or green(pass) or warning in Services Tab. Consider the scenario - 6 out of 10 instances, (>=  60%) have all checks passing in 6 instances, then service is marked Green rather than red. The other 4 instances may have critical checks or warning checks.
- Need to update this to documentation (To Do).

2. Three new fields are introduced in "ServiceSummary" struct. These are "InstancesPassing", "InstancesWarning", "InstancesCritical". The purposed of these fields and values it holds are explained below:
- If a node instance has all health checks passing, then it adds to "InstancesPassing" count.
- If a node instance has atleast 1 critical health check, then it adds to "InstancesCritical" count.
- If a node instance has 0 critical health check , but atleast 1 warning health check, then it adds to "InstancesWarning" count.

3. Based on the values of these new fields and new config param (“MarkServiceStatusThreshold”)returned in api - "/v1/internal/ui/services" response, decision is made in UI, whether to mark service as green or not.

Complete Tests on UI and most relevant APP(backend) tests are run and verified. PFB snapshots of same.
Issue_16550_ServicesTab_1

FYI @reskin89

### CODE REVIEW

**Comment by david-yu** [comment]
@vijayraghav-io Thanks for the PR. Are there any UI changes if any to the services view? Could you provide perhaps an example of this in action?

**Comment by vijayraghav-io** [comment]
sure @huikang , below are snapshots of services view with changes and for different scenarios.

1. Number of healthy instances > threshold (default 60%) of total instances
Issue_16550_ServicesTab_4



2. Number of healthy instances < threshold (default 60%) of total instances
Issue_16550_ServicesTab_3



3. Zero healthy instances
Issue_16550_ServicesTab_5



4. Warning instances without critical
Issue_16550_ServicesTab_6



5. Tool tips added for new info
Issue_16550_ServicesTab_7

**Comment by vijayraghav-io** [comment]
Leaving a comment to prevent this PR from auto-closing

**Comment by reskin89** [comment]
Bump this please, it's an important QoL

**Comment by vijayraghav-io** [comment]
Hi @david-yu , please help to review.

**Comment by vijayraghav-io** [comment]
Hi @david-yu , @reskin89 ,

Added these videos just for sake of better understanding or to show feature implemented in action.

Consider the scenario - 
Having a service "web" running on 3 instances, the health check on one of the instance is only failing, rest of 2 instances have all heath checks passing.

1. This video is as-is (without new feature implemented)

https://www.loom.com/share/446d5c19e61c4b1a881d7117333e00e6?sid=dd32a8fc-2128-4e72-9173-58b61fd703df

2. This video is with new feature implemented for same scenario

https://www.loom.com/share/c36a8b66b6a0447f8ecee07cc3530a98?sid=26517e61-557e-41fb-8aed-b7d1e62b1308

**Comment by reskin89** [comment]
@jkirschner-hashicorp does this look like something we'd be able to merge soon? This is a really awesome QoL for the UI

**Comment by jkirschner-hashicorp** [comment]
Hi @vijayraghav-io and @reskin89: I'm acknowledging that I saw your messages and the team is internally discussing this (the proposed solution and the underlying problem it intends to address). I'll follow up after that internal discussion settles.

**Comment by vijayraghav-io** [comment]
Hi @jkirschner-hashicorp, Thankyou! for the response and considering.

**Comment by vijayraghav-io** [comment]
Reminding for review

**Comment by reskin89** [comment]
Re-opening

**Pull request closed without merging**
