### PR TITLE
ui: Upgrade dev tooling dependency

### PR DESCRIPTION
**Pull request by johncowen**
See commit message

### CODE REVIEW

**Comment by mikemorris** [comment]
Any idea why the frontend tests are failing? Looks like a yarn/npm issue of some sort...

**Comment by johncowen** [comment]
Sorted @mikemorris 👍

**Review by mikemorris — APPROVED** [review]
Thanks!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/390454.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 5f17062b0a04499c7d89b553591c1245aa522d55 onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 5f17062b0a04499c7d89b553591c1245aa522d55 onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/390454)

**Pull request merged**
