### PR TITLE
ui: Ensure CopyableCode copy icon/button is fully clickable

### PR DESCRIPTION
**Pull request by johncowen**
### Description
Ensure CopyableCode copy icon/button is fully clickable

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [x] not a security concern

### CODE REVIEW

**Comment by LevelbossMike** [comment]
Not sure if I'm doing something wrong but I still can't seem to press the entire (gray) button to copy the token - it looks like only the blue portion of the button is clickable.

Screenshot 2022-08-03 at 14 58 25

**Comment by johncowen** [comment]
We avoid a full 100% height here as the gray area can extend to be really tall and I don't think its is meant to all be clickable. I suppose I can make this square though, 1 tic I can add that

**Comment by johncowen** [comment]
K this now has the same 40px height also

**Review by LevelbossMike — APPROVED** [review]
:clap:

**Pull request merged**
