### PR TITLE
#875 Add support for inplace lock acquisition

### LINKED ISSUE #875: Support in-place lock acquisition
We should support a lock acquisition that does not modify the key value.

See: https://groups.google.com/forum/#!topic/consul-tool/Cuhr_DVXqZE

### PR DESCRIPTION
**Pull request by tshak**
Resolves #875 

This PR adds the ability to acquire a lock on a KV item "in place", meaning that the original contents of the item are left in tact. This is useful for typical pessimistic locking scenarios where the client does not wish to set a value during lock acquisition as it may have been mutated by another client. This is achieved by using the query parameters `acquire-inplace=<sessionId>` and `release-inplace=<sessionId>`. 
## Examples

```
curl -XPUT localhost:8500/v1/kv/test -d "testValue" // base64: dGVzdFZhbHVl
curl -XPUT localhost:8500/v1/kv/test?acquire-inplace=c29f86a7-83d6-6af9-73d0-d2811cc8c67b
curl localhost:8500/v1/kv/test

// response
[{"LockIndex":1,"Key":"test","Flags":0,"Value":"dGVzdFZhbHVl","Session":"c29f86a7-83d6-6af9-73d0-d2811cc8c67b","CreateIndex":21,"ModifyIndex":76}]
```
## TODO

This PR is ready to merge, but this feature still needs the following: 
- Update API (i.e. Golang SDK)
- Update documentation

### CODE REVIEW

**Comment by slackpad** [comment]
Hi @tshak thanks for the PR! I'm working on the 0.7.0 release right now, but I'll try to give this some cycles shortly after that's done so we can get this into the release that follows.

**Comment by slackpad** [comment]
@tshak sorry for the delay on this one - can you please do a rebase and we can work on getting this in?

**Comment by tshak** [comment]
@slackpad Done!

**Comment by dnephin** [comment]
Thank you for the PR! I believe this is still a limitation of the API today, so it is unfortunate that we never got this merged. I suspect some people are working around this limitation by using a separate key for the lock. If the processes can agree on a separate key ahead of time, they can use that key exclusively as a lock and ignore the value. Once the lock is acquired the key with relevant values can be modified and the lock released. I see that in the original mailing list post that wasn't an option for a particular application, but in general I suspect it works quite well.

Due to the age of this PR it would need substantial changes to resolve merge conflicts. Starting from a fresh checkout of master and porting over some of the tests will likely be a faster approach than attempting to rebase this PR, so I am going to close it.

If anyone is still interested in contributing a fix for this issue I think we should look at making it possible to use `cas` and `acquire` together, instead of adding a new query parameter. By using `cas` with `acquire` together I believe we get the behaviour we want, because the operation would fail if some other process had changed the value after the initial read of the value.

**Pull request closed without merging**
