### PR TITLE
bugfix: tags list layout

### PR DESCRIPTION
**Pull request by freedemster**
Hi,

We have services with a huge number of tags in our company and we are faced with the fact that in the current UI they are displayed incorrectly: when a line of tags reaching the edge of the screen, it is not wrapped to the next line.

These changes fix it.

### CODE REVIEW

**Comment by freedemster** [comment]
Hi,

Thanks for replay!

For now, we have about 10-20 services in consul (their number is expected to grow) with small sets of tags for each. But some of them have multiple tags. I attach a screenshot of one of those services. As you can see some of the tags are not displayed and developer console is the only possible solution to see them due to the inaccessibility of scrolling.

Maybe we are doing something wrong? If so, please tell me where in the documentation we can read about it.

Screenshot

**Comment by johncowen** [comment]
Oh! 😅 Thanks for the screenshot, I completely misunderstood! I'd understood you meant the service listing page not the detail page. This looks like a lovely bug! We should be able to merge this afterall! 🎉  Let me check this properly first thing after the weekend.

Thanks!

**Comment by freedemster** [comment]
Thanks! Have a great weekend!

**Comment by johncowen** [comment]
Hey @freedemster 

Hope you had a good weekend! I've had a bit more of a better look at this.

Firstly, thanks so much for spotting this problem and providing the screengrab. It's one of those 'oh no!! We need some CSS regression testing!!' 😄 

So theres a bit of detail here, which I'll go into below in case you're interested, other than that I'm think theres a straightforward change we can make to what you've done here so we can get this merged in.

Detail:

The mocking tool we use to test the Consul UI with only ever showed us 2 tags on this page! You can see this on once of our staging branches here:

https://consul-ui-staging.netlify.com/ui/ar%20west-5/services/service-0

So, firstly I've changed this to show a lot more tags as well as making the number controllable during testing or during development by setting a `CONSUL_TAG_COUNT` cookie:

https://github.com/hashicorp/consul-api-double/commit/b28dface15e2237fc10c9e4eaf9acd43a5e4b575

This way we are more likely to notice any problems/regressions in the future. (We are yet to publish the above change and pull it in to the main repo)

Secondly, the fix here which is great, does unfortunately cause a problem related to what I go into in my first comment above, see this screengrab of the listing page with the amends applied:

Screenshot 2019-09-16 at 09 14 48

The biggest question is, why were we using `inline-flex` here in the first place? I do remember adding a lot of inline-flex's for the table views a few months back for vertical centering purposes within tables rows whilst maintaining 'truncatability' (flex and truncation don't get on well together).

At first I thought I'd added the `inline-flex` here by accident and my first thought was to remove it and let the spans inside wrap naturally (using the default `inline` display). But if you remove that, the margin between the spans is dictated by the whitespace in the HTML. If you keep `inline-flex` you can control the size of the margin between the tags with CSS (the margin 3px rule). So I'm inclined to keep the `inline-flex` here and add the `flex-wrap` as you've done here.

With the wrap fix added we definitely need the bottom margin for when it wraps. I would guess this should be the same as the right margin so we get that 'brick wall'/'masonry' look when the tags wrap and everything looks equal:

Screenshot 2019-09-16 at 10 25 53

The remaining problem is, when the `%tag-list` is used within a `%dom-recycling-table` we don't want it to have the wrapping or the `margin-bottom`

I think the best option here is to overwrite things in the `%dom-recycling-table` component to reset the flex-wrap back to `nowrap` and overwrite the bottom margin back to a zero margin. For me this makes sense as we are basically saying `%tag-list` should wrap and have a margin between 'wraps' _unless_ it's in the `%dom-recycling-table` component (which dictates 'same height rows' and hence should disable wrapping). CSS has no parent selecting yet we have to 'say this' in `%dom-recycling-component`

Thats my thoughts on it though, let me know what you think.

Oh also, I'm wondering that the `dd:after` pseudo content and the `justify-content` rules are for in your changeset incase I missed something I don't follow, do you remember why you added those?

**Comment by freedemster** [comment]
Thanks, 

It’s great that you added the ability to display more tags it really helps to notice similar problems in the future.

Regarding the problem, unfortunately, I did not notice it, thanks for finding it. I think we may add `nowrap` and remove `margin-bottom` where `%tag-list` is inside `%dom-recycling-table`. I will try it today and add new commit so that we can see what happens.

I add `dd:after` pseudo content for fixing the behavior of `justify-content: space-between`. «Space between» distributes the elements evenly across the container and if there are only two elements in the last line, the first one will be moved to the left edge and the second to the right. It’s quite difficult for me to explain this in words, so I took a screenshot:

Screenshot

I think it looks awful so I added this little hack. If you know a better solution, then let's use it. I do not have a very high skills in `CSS`, I'm a backend developer 😅

**Comment by freedemster** [comment]
Yes, you are right. I added these styles:
```css
%dom-recycling-table %tag-list dd {
  flex-wrap: nowrap;
}
%dom-recycling-table %tag-list dd > * {
  margin-bottom: 0;
}
```
Everything looks better:
Services

**Comment by freedemster** [comment]
Hi,

I made a new commit with changes.

**Comment by johncowen** [comment]
Hey @freedemster ,

Awesome, thanks for doing that! I thought it'd be much nicer to have you do the entire PR rather than me do the last nitty bits.

Thanks again for spotting this! Keep us informed if you spot anything else!

**Comment by freedemster** [comment]
Thanks for the code review and help fixing this bug! 🎉

**Pull request merged**
