### PR TITLE
changelog: entry for snapshot agent `license_path` bug

### PR DESCRIPTION
**Pull request by boxofrad**
Changelog for bug fix in Consul Enterprise.

### CODE REVIEW

**Review by rboyer — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/504450.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit b51dc2f758bf99f958ade3e0cacc069a3d5b3cd7 onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit b51dc2f758bf99f958ade3e0cacc069a3d5b3cd7 onto `release/1.9.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit b51dc2f758bf99f958ade3e0cacc069a3d5b3cd7 onto `release/1.8.x` succeeded!

**Pull request merged**
