### PR TITLE
Proposal for #758 - Windows .msi installer

### PR DESCRIPTION
**Pull request by carlpett**
This PR relates to the discussion in #758, and produces a .msi file for Consul. 

Example invokations
- `.\build.ps1 0.6.3`, downloads and compiles version 0.6.3 for 64-bit.
- `.\build.ps1 0.6.0 386`, downloads and compiles version 0.6.0 for 32-bit
- `.\build.ps1 -Version 0.5.2 -Arch amd64 -Verbose`, downloads and compiles 0.5.2 for 64-bit, with verbose logging.

### CODE REVIEW

**Comment by carlpett** [comment]
Just realized I accidentally didn't include the `GOMAXPROCS` setting. Will update as soon as possible.

**Comment by highlyunavailable** [comment]
You shouldn't need `GOMAXPROCS` any more since as of Go 1.5 it now uses `runtime.NumCpu()` as the max procs, and the whole max procs thing was only for the cgo threads to the data store as far as I know.

**Comment by carlpett** [comment]
@highlyunavailable Ah, excellent! We still haven't upgraded to 0.6, so we always got warnings on startup if it wasn't set. But then I won't update the PR :)

**Comment by slackpad** [comment]
Hi @carlpett thanks for the PR (and sorry for the delayed response). Given that we only distribute binaries outside of any packaging, this is probably better done as a separate project. We'd be happy to link to it from the community page.

**Comment by slackpad** [comment]
Actually missed the context from #758 - maybe we can roll this in to some documentation.

**Comment by slackpad** [comment]
Closing this out since #758 captures the docs forward work.

**Pull request closed without merging**
