### PR TITLE
Update Web Components for Architecture pages

### PR DESCRIPTION
**Pull request by tunzor**
This PR is specifically for the [`architecture` pages](https://www.consul.io/docs/architecture) of the docs.
- Added `<CodeBlockConfig>` tags for code snippets with headings where applicable

### CODE REVIEW

**Review by blake — APPROVED** [review]
LGTM. 👍

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/547218.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 1ad3ed3a2bdb777627496b10d9d8430f607df7d5 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 1ad3ed3a2bdb777627496b10d9d8430f607df7d5 onto `release/1.11.x` succeeded!

**Pull request merged**
