### PR TITLE
ci: test against Go1.16.3

### PR DESCRIPTION
**Pull request by dnephin**

### CODE REVIEW

**Review by rboyer — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/361039.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 3f05e3097f27c672b86603f64826db5f5af40c5c onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/361039)

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/361093.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 3f05e3097f27c672b86603f64826db5f5af40c5c onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/361093)

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/361094.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 3f05e3097f27c672b86603f64826db5f5af40c5c onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/361094)

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/361095.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 3f05e3097f27c672b86603f64826db5f5af40c5c onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/361095)

**Pull request merged**
