### PR TITLE
test: Make testserver start timeout configurable.

### PR DESCRIPTION
**Pull request by cyrilgdn**
Currently, the test server is waiting up to 3 seconds to be started before returning a start error.

In our case, it would be great to changer this timeout because when our CI platform (which is not really a supercomputer) is working hard,  the start can be longer than 3 seconds.

### CODE REVIEW

**Comment by cyrilgdn** [comment]
@magiconair It makes sense indeed, I changed it to a duration.

**Comment by magiconair** [comment]
`StartWaitTimeout` seems redundant. Maybe `StartTimeout` is better but I'll have a look at the full code a bit later.

**Comment by magiconair** [comment]
I suggest to call it `ReadyTimeout`

**Comment by cyrilgdn** [comment]
@magiconair Renamed.

**Pull request merged**
