### PR TITLE
docs: Add audit logging examples

### LINKED ISSUE #8375: Improve Audit Logging Docs
#### Feature Description

The docs we have for the enterprise audit logging feature could be improved. Additional details on the behavior, examples of its output, and guidelines for configuration would help people setting the feature up for the first time.

The docs live here https://www.consul.io/docs/enterprise/audit-logging

The namespace docs have a good level of detail in them, and can be used as a reference for this https://www.consul.io/docs/enterprise/namespaces

### LINKED ISSUE #9055: Add explanation for using audit logs with /dev/stdout
#### Feature Description

In order to write audit logs to stdout, one must use the file sink with a path of `/dev/stdout`. Using stdout for the audit logs is not an uncommon use case, so users should not be left to infer this behavior on their own. We should simply tell them in the docs.

While adding additional docs can help, something that aids in throwing users off is that many of the config options for the file sink, such as those regarding rotations times and max sizes, don't make any sense with an append-only buffer. Users might be better off in the longer term with a sink dedicated to stdout and stderr which elides much of the unnecessary config. In some ways, the file sink accepting `/dev/std{out,err,in}` is an implementation detail we're leaking.

### PR DESCRIPTION
**Pull request by blake**
Resolves #8375, resolves #9055

### CODE REVIEW

**Comment by thomashashi** [comment]
Looks good to me.

**Review by dnephin — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/399772.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 8a9dad08b5cfe62aba2fc4c8552d4fe0831f0abd onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 8a9dad08b5cfe62aba2fc4c8552d4fe0831f0abd onto `release/1.10.x` succeeded!

**Pull request merged**
