### PR TITLE
ui: Read-only CRD/Centralized Config Intentions

### PR DESCRIPTION
**Pull request by johncowen**
This PR adds support for reading Custom Resource Definition and or new style centralized config intentions.

[Preview Link](https://deploy-preview-8659--consul-ui-staging.netlify.app/ui/um_east-0/intentions)

Notable additions include:

- New fragment based models for intention related sub properties.
- New `<RadioCard />` component
- We split up `%composite-row` into 3 parts, in order to use these parts in isolation.
- We made our current tests pass here, but not yet added any specific tests for this feature. If we get to adding editable new style intentions, any tests we write here will be obsolete.

Overall there maybe be additional churn here as we add editability - but felt this read-only feature was at a good point to PR.

Screenshot 2020-09-11 at 11 16 40

### CODE REVIEW

**Review by kaxcode — CHANGES_REQUESTED** [review]
QA Notes:

1. Naming changes - View Intentions Frame
Screen Shot 2020-09-16 at 3 01 50 PM

2. Permission question missing
Screen Shot 2020-09-16 at 3 30 46 PM

3. Cancel button missing in Create Intention Page
Screen Shot 2020-09-16 at 3 22 21 PM

4. Set intention to deny and vice versa pop-ups
Screen Shot 2020-09-16 at 3 33 04 PM

5. Learn more about permission link wording change
Screen Shot 2020-09-16 at 3 34 59 PM

**Comment by johncowen** [comment]
Hey, thanks for taking a look at this!

- [x] Naming changes - View Intentions Frame
- [x] Permission question missing
- [x] Cancel button missing in Create Intention Page
- [ ] Set intention to deny and vice versa pop-ups
  - L7 Intentions are not editable in this PR, so you can't change an intention from allow to deny for an L7 intention. You'd never see this popup until the L7 intentions are editable.
- [ ] Learn more about permission link wording change
  - I think I'm missing something here? I just checked the Figma file and it looks like the text is the same, although reading it now the text doesn't make sense at all as it refers to a 'allow/deny actions above', which doesn't exist in this view.
  - We probably need to correct the link here also, maybe thats what you mean here? If so, I'm not sure if a page exists yet for us to link to?

**Comment by kaxcode** [comment]
> Hey, thanks for taking a look at this!
> 
> * [x]  Naming changes - View Intentions Frame
> * [x]  Permission question missing
> * [x]  Cancel button missing in Create Intention Page
> * [ ]  Set intention to deny and vice versa pop-ups
>   
>   * L7 Intentions are not editable in this PR, so you can't change an intention from allow to deny for an L7 intention. You'd never see this popup until the L7 intentions are editable.
> * [ ]  Learn more about permission link wording change
>   
>   * I think I'm missing something here? I just checked the Figma file and it looks like the text is the same, although reading it now the text doesn't make sense at all as it refers to a 'allow/deny actions above', which doesn't exist in this view.
>   * We probably need to correct the link here also, maybe thats what you mean here? If so, I'm not sure if a page exists yet for us to link to?

@johncowen 
- The pop-ups are not about L7 intentions. They are just a confirmation pop-up for switching between deny -> allow and vice versa. 
- I'm talking about the wording of the link.

**Comment by johncowen** [comment]
🤔  can you explain a bit more about the wording? Unless I'm completely missing something the wording is the same in this PR and the Figma file. Both say 'Learn more about permissions' - the href of the link itself is wrong but we don't have a good link as yet.

What wording are you seeing in the PR and the Figma file? I'm good to change if I know what it needs to be.

**Comment by kaxcode** [comment]
> 🤔 can you explain a bit more about the wording? Unless I'm completely missing something the wording is the same in this PR and the Figma file. Both say 'Learn more about permissions' - the href of the link itself is wrong but we don't have a good link as yet.
> 
> What wording are you seeing in the PR and the Figma file? I'm good to change if I know what it needs to be.

That's right. When I was going through I saw `documentation`.

**Review by kaxcode — APPROVED** [review]
LGTM 👍

**Pull request merged**
