### PR TITLE
connect: Upgrade Envoy 1.20 to 1.20.2

### PR DESCRIPTION
**Pull request by eculver**
This follows #12433 and #12434 in a "reverse-backport" move to upgrade our Envoy versioning matrix to include 1.20.2. I had to do the versioning hack here as was done in the previous PRs as well.

### CODE REVIEW

**Comment by rboyer** [comment]
Missing a `website` update.

**Review by rboyer — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/596235.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit b95f010ac047eb99290b3819fcd8f760f436510e onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit b95f010ac047eb99290b3819fcd8f760f436510e onto `release/1.11.x` succeeded!

**Pull request merged**
