### PR TITLE
Fix check registration in 'services register' command

### PR DESCRIPTION
**Pull request by freddygv**
Currently the CLI drops checks from service definitions if they don't have a name.

The name isn't required since we create one downstream if it's missing, so this PR modifies the check to look for an ID.

### CODE REVIEW

**Comment by freddygv** [comment]
@mkeeler right, just fixed that

**Comment by freddygv** [comment]
If we register a counting service with a check that has:
- an ID but no name, then the name `Service 'counting' check` is set downstream
- a name but no id, then the id `service:counting` is set downstream

**Comment by i0rek** [comment]
Is this still relevant?

**Comment by i0rek** [comment]
Fixed by https://github.com/hashicorp/consul/commit/646da639eed1cb20d10d2c399cb13ee155a7f85a.

**Pull request closed without merging**
