### PR TITLE
docs: Fix invalid JSON in code examples

### PR DESCRIPTION
**Pull request by blake**
### Description

This commit fixes invalid JSON in various code examples.

### PR Checklist

* [ ] updated test coverage
* [X] external facing docs updated
* [X] appropriate backport labels added
* [X] not a security concern

### CODE REVIEW

**Review by trujillo-adam — APPROVED** [review]
Thanks for fixing these. We'll pay closer attention to the details moving forward.

**Comment by hc-github-team-consul-core** [comment]
Backport failed @blake. Run: https://github.com/hashicorp/consul/actions/runs/6265728438

**Comment by hc-github-team-consul-core** [comment]
Backport failed @blake. Run: https://github.com/hashicorp/consul/actions/runs/6265728438

**Comment by hc-github-team-consul-core** [comment]
Backport failed @blake. Run: https://github.com/hashicorp/consul/actions/runs/6265728438

**Pull request merged**
