### PR TITLE
Document consul.hashicorp.com/connect-inject-mount-volume

### PR DESCRIPTION
**Pull request by lkysow**
From this PR: https://github.com/hashicorp/consul-k8s/pull/1111 which was a rebase of https://github.com/hashicorp/consul-k8s/pull/763.

**NOTE:** merge after next k8s release

### CODE REVIEW

**Review by david-yu — APPROVED** [review]

**Review by karl-cardenas-coding — APPROVED** [review]

**Review by ishustava — APPROVED** [review]

**Review by curtbushko — APPROVED** [review]

**Comment by lkysow** [comment]
Wow only 4 approvals? 😢

**Review by thisisnotashwin — APPROVED** [review]
> Wow only 4 approvals? 😢

sorry bout that

**Review by jmurret — APPROVED** [review]
:)

**Review by t-eckert — APPROVED** [review]
Looks good to me. We'll see what the team thinks.

**Review by ndhanushkodi — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/651184.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 0ae269637a98da8338ffe57286c9c729f3448924 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 0ae269637a98da8338ffe57286c9c729f3448924 onto `release/1.12.x` succeeded!

**Pull request merged**
