### PR TITLE
coverage: disable comment and project status, set informational mode

### PR DESCRIPTION
**Pull request by mikemorris**
Prior config was not disabling the `project` status even though `no` and `off` both evaluate to `false` when parsing YAML, let's see if the [suggested config](https://docs.codecov.io/docs/commit-status#section-disabling-a-status) works...

[`informational`](https://docs.codecov.io/docs/commit-status#section-informational) mode should display the `patch` status but without setting a specific threshold or failing a check if that threshold is missed.

This also [disables the coverage comment](https://docs.codecov.io/docs/pull-request-comments#section-disable-comment) as it's a bit noisy and unhelpful currently due to flappy coverage.

### CODE REVIEW

**Comment by mikemorris** [comment]
Not sure why the coverage report isn't getting uploaded successfully here (CodeCov [will still `exit 0` by default even if uploading fails](https://docs.codecov.io/docs/about-the-codecov-bash-uploader#section-uploading-process)), setting verbose mode to check if anything is going wrong...

**Comment by mikemorris** [comment]
Okay, just a CI hiccup, coverage is uploading fine now.

Should I set a config to be able to iterate/tweak this faster from a non-master branch until we get it ironed out?
```
codecov:
  branch: stable
```
https://docs.codecov.io/docs/codecov-yaml#section-master-copy

**Comment by alvin-huang** [comment]
`Codecov will always use the current yaml on the branch being tested by default.` from https://docs.codecov.io/docs/codecov-yaml#section-restricting-changes reads like it uses the config from whatever branch is being tested. This is confusing...

**Comment by mikemorris** [comment]
😭 oops.
> Can I name the file .codecov.yml?

> No. Starting the file with a period can cause issues detecting and reading it. The file can be placed anywhere in your repository.

**Pull request merged**
