### PR TITLE
WIP: Add interfaces for the client

### PR DESCRIPTION
**Pull request by tpickett66**
This is far from complete but I wanted to get early feedback on adding these interfaces. 

The motivation here is that building applications that use the client can't be tested without setting up and running a consul server.

### CODE REVIEW

**Comment by magiconair** [comment]
We went through this in a different PR and decided against this approach. Let me find it.

**Comment by magiconair** [comment]
See #2799 

The main argument is that interfaces should sit with the consumer of the code and not the producer but I'm open to arguments.

**Comment by tpickett66** [comment]
Thanks for getting back to me so quickly, this is why I opened a PR early. :-)

I read through the discussion on that PR and agree with your point about not changing the API for the client. I think having the interfaces declared along side the code that implements them will help keep them in sync. Additionally, having them defined in the originating package eliminates the need for every consumer to generate the same interfaces over and over for testing.

**Comment by slackpad** [comment]
Hi @tpickett66 closing this out under the same general rationale as #2799. Sorry for the late reply on this one!

**Pull request closed without merging**
