### PR TITLE
Regen expired test certs

### PR DESCRIPTION
**Pull request by analogue**
### Description

```
=== FAIL: tlsutil TestConfigurator_OutgoingInternalRPCWrapper/VerifyServerHostname_=_false (re-run 3) (0.00s)
    config_test.go:773: 
        	Error Trace:	/home/runner/work/consul/consul/tlsutil/config_test.go:773
        	Error:      	Received unexpected error:
        	            	x509: certificate has expired or is not yet valid: current time 2023-11-02T02:24:15Z is after 2023-11-01T15:17:35Z
        	Test:       	TestConfigurator_OutgoingInternalRPCWrapper/VerifyServerHostname_=_false
```

### Testing & Reproduction steps

Test passes locally.

### PR Checklist

* [x] updated test coverage
* [ ] external facing docs updated
* [x] appropriate backport labels added
* [x] not a security concern

### CODE REVIEW

**Review by DanStough — APPROVED** [review]
Thank you @analogue !

**Comment by DanStough** [comment]
Can we not push back the expiration more than a year?

**Comment by analogue** [comment]
> Can we not push back the expiration more than a year?

I'm not seeing where it is getting set to a year. Is this some kind of default somewhere?  The only relevant config setting I'm seeing is `default_days` in `myca.conf` which is set to way more than a year.

**Comment by analogue** [comment]
Tracking in https://hashicorp.atlassian.net/browse/NET-6450

**Pull request merged**
