### PR TITLE
Adding singleton option to DNS for getaddrinfo bug.

### PR DESCRIPTION
**Pull request by fusiondog**
A simple fix for a problem in some versions of glibc

### CODE REVIEW

**Comment by fusiondog** [comment]
This is a relatively small change.  I think it failed the check because of other issues you were having with Travis timeout recently.

**Comment by slackpad** [comment]
@fusiondog I think so as well. Do you mind adding a note about this to the docs as well? I'm happy to do that, too - just let me know.

**Comment by sean-** [comment]
@fusiondog Thank you for your PR.  I'm going to take PR and update it so that an administrator can specify an `int` instead of a `bool` to limit the number of addresses returned.

**Comment by fusiondog** [comment]
@sean- Would the bool be able to exceed the default 3 results?  The doc update should probably still make a point of the getaddrinfo bug and that using the setting at value 1 is needed to resolve.

**Comment by sean-** [comment]
This has been committed in #1712, thank you for your PR!

**Pull request closed without merging**
