### PR TITLE
ui: Colocate remaining CSS components to the app/components folder

### PR DESCRIPTION
**Pull request by johncowen**
Second part of https://github.com/hashicorp/consul/pull/10275  

> There are still few more 'non-pseudo addon' CSS files in the old styles/components folder, so we aren't quite there yet, but there'll be a follow up PR to move those coming up soon also, as well as some sort of solution for moving our remaining component related files (our translations yaml files for components).

🍫

We still have translation files and this:

> Lastly the remaining thing to do here will be to import the component CSS files along with the javascript/hbs files, so we don't have to keep adding to the growing list of imports in components.scss. 

to do at some point.

There are a few CSS files still left in `styles` but these are pretty much 'tokens' and other global like layout things, open to suggestions about whether these should stay there or move (and if we should move them then where to?) Personally I'm good to leave them where they are for the minute at least.

### CODE REVIEW

**Comment by kaxcode** [comment]
> There are a few CSS files still left in `styles` but these are pretty much 'tokens' and other global like layout things, open to suggestions about whether these should stay there or move (and if we should move them then where to?) Personally I'm good to leave them where they are for the minute at least.

Yea, let's keep global styles/layouts in the styles folder. @johncowen

**Comment by kaxcode** [comment]
@johncowen looks like this PR needs to be rebased.

**Comment by johncowen** [comment]
Thanks! Rebasing was a little weird, but I think this is good to go again 👍

**Review by kaxcode — APPROVED** [review]
"needs-love" 😂 but LGTM

**Comment by johncowen** [comment]
😂 " 🎼 ...love is all you need 🎶 "

More seriously tho, as well as being fun, I figured it would be easy to search for that if/when we need to. It would be nice to be able to call out what things we would appreciate work on/help with from within our docs somehow - just not sure exactly how yet 🤔

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/394987.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/395034.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit c78f7ecb27175f50bc4d04cca261cf7379f4c0a6 onto `release/1.10.x` succeeded!

**Pull request merged**
