### PR TITLE
Fix Session.Renew to care about 404s properly

### PR DESCRIPTION
**Pull request by rboyer**
Fixes part of #1040.  

Needs some sort of handling for how to deal with RenewPeriodic.

### CODE REVIEW

**Comment by naelyn** [comment]
In a test program with a slightly modified `RenewPeriodic()` call, I had it print the `SessionEntry` and `error` return value every time it was called.  I deliberately had the program take a very long sleep in between creating the session and attempting to renew it (it had delete behavior).  This was to showcase what happens when the leader evaporates your session while you were trying to be a good renewing citizen (but something like a long GC pause or similar caused you to miss your renewal window):

    2015/06/17 09:04:11 created session 85bb5662-4705-2e1b-4b7f-7997c5d2cd55 with ttl of 10s
    2015/06/17 09:05:01 renewing session 85bb5662-4705-2e1b-4b7f-7997c5d2cd55
    2015/06/17 09:05:01 got entry=[*api.SessionEntry/<nil>], err=[*errors.errorString/Unexpected response code: 404 (Session id '85bb5662-4705-2e1b-4b7f-7997c5d2cd55' not found)]
    ...this repeats several times...
    2015/06/17 09:05:06 session died: 85bb5662-4705-2e1b-4b7f-7997c5d2cd55

It only dies because the full TTL elapsed.  With the proposed changes on this MR:

    2015/06/17 09:11:17 renewing session d8ecada8-ec39-8336-7eee-847a34d5a2f1
    2015/06/17 09:11:17 got entry=[*api.SessionEntry/<nil>], err=[<nil>/<nil>]
    2015/06/17 09:11:17 session died: d8ecada8-ec39-8336-7eee-847a34d5a2f1

It doesn't try to keep renewing the session that has evaporated (which is the sane thing to do).

**Comment by rboyer** [comment]
Do I have to do anything else to help move this along?

**Comment by armon** [comment]
@rboyer Sorry about the delay. Could you please add a test case?

**Comment by rboyer** [comment]
Rebased and added tests.

**Comment by rboyer** [comment]
Does this look sufficient now?

**Comment by slackpad** [comment]
Sorry been swamped but I'll try to get to this in the next day or so.

**Comment by slackpad** [comment]
LGTM - thanks!

**Pull request merged**
