### PR TITLE
docs: fix typo in KV store API

### PR DESCRIPTION
**Pull request by kevinpollet**
This PR fixes a typo in the Consul KV Store API documentation.

### CODE REVIEW

**Review by blake — APPROVED** [review]
Thanks for fixing this!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/532593.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 33039f2c2b097739a357e5983a8f6a08bf1fa4cd onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 33039f2c2b097739a357e5983a8f6a08bf1fa4cd onto `release/1.11.x` succeeded!

**Pull request merged**
