### PR TITLE
Port to 1.11.x: Add timeout to Client RPC calls (#11500)

### PR DESCRIPTION
**Pull request by dhiaayachi**
### Description
Adds a timeout (deadline) to client RPC calls, so that streams will no longer hang indefinitely in unstable network conditions.

Co-authored-by: kisunji <ckim@hashicorp.com>

### Testing & Reproduction steps
* Tests were introduced in the initial PR

### Links
Port of:
- #11500 
- https://github.com/hashicorp/consul/pull/14233
### PR Checklist

* [x] updated test coverage
* [x] external facing docs updated
* [ ] not a security concern

### CODE REVIEW

**Review by kisunji — APPROVED** [review]

**Review by kyhavlov — APPROVED** [review]

**Comment by jkirschner-hashicorp** [comment]
@dhiaayachi , @kisunji : Should https://github.com/hashicorp/consul/pull/13344 have also been included in this backport to 1.11? I know that's come up in the context of #11500 before.

**Comment by kisunji** [comment]
@jkirschner-hashicorp It has been backported: https://github.com/hashicorp/consul/pull/13348

**Comment by kisunji** [comment]
Oh yes, I think that may have been missed

**Comment by jkirschner-hashicorp** [comment]
#13348 just backported to 1.12 as far as I can tell, not 1.11

**Comment by dhiaayachi** [comment]
@jkirschner-hashicorp @kisunji I'm not sure I understand the link between this (adding RPC timeout) and the fix introduced in #13344

**Comment by kisunji** [comment]
@dhiaayachi There was an existing bug where KV.Get endpoint was being passed `**structs.KeyRequest` instead of `*structs.KeyRequest` but it didn't matter because RPC dereferences it correctly. However, while adding the RPC timeout we added an interface type assertion which `**structs.KeyRequest` did not fulfil, making it default to 7 seconds (making blocking queries fail after 7s).

**Comment by dhiaayachi** [comment]
Thank you @kisunji, I get it now 🙂 
I will try to backport that, it will go in the next patch release.

**Comment by dhiaayachi** [comment]
Done: https://github.com/hashicorp/consul/commit/c42dde90b78af6be7ce147194952c19640320af2

**Pull request merged**
