### PR TITLE
Bump raft-autopilot version to the latest.

### PR DESCRIPTION
**Pull request by mkeeler**
This is a pretty simple dependency bump. Mainly we are wanting to pull in this fix: https://github.com/hashicorp/raft-autopilot/pull/9

### CODE REVIEW

**Review by banks — APPROVED** [review]
LGTM.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/376797.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 3a0007b1585f21a28d73ade97e6a02c5edc92bf8 onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 3a0007b1585f21a28d73ade97e6a02c5edc92bf8 onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/376797)

**Pull request merged**
