### PR TITLE
Configure linter to forbid use of html/template

### PR DESCRIPTION
**Pull request by nathancoleman**
### Description
We should never use html/template due to the performance penalty and the fact that we are highly unlikely to ever be generating HTML templates. This PR enforces a ban using the linter.

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [x] appropriate backport labels added
* [x] not a security concern

### CODE REVIEW

**Review by zalimeni — APPROVED** [review]

**Review by rboyer — APPROVED** [review]

**Review by sarahalsmiller — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
@nathancoleman, a backport is missing for this PR [21307] for versions [1.16] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@nathancoleman, a backport is missing for this PR [21307] for versions [1.16] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@nathancoleman, a backport is missing for this PR [21307] for versions [1.16] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@nathancoleman, a backport is missing for this PR [21307] for versions [1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Pull request merged**
