### PR TITLE
docs: update register check docs (closes #6635)

### LINKED ISSUE #6635: Register check documentation is misleading
Running: Consul v1.6.1

In the documentation for registering a health check https://www.consul.io/api/agent/check.html#register-check

The 'ID' field is documented as follows. Specifies a unique ID for this check on the node. This defaults to the "Name" parameter, but it may be necessary to provide an ID for uniqueness.

However when I register a service using the ID parameter it does not register with that ID. Instead it works if CheckID is used when registering the check. I believe this should just be a small documentation update that might have someone a bit of time troubleshooting the issue.

Thanks for your time on this.

### PR DESCRIPTION
**Pull request by dhiaayachi**
this is to pull the changes from https://github.com/hashicorp/consul/pull/7364

fixes #6635
Update register check documentation clarify that Id returns as CheckId in the response

Co-Authored-By: Shaker Islam <shaqq@users.noreply.github.com>

### CODE REVIEW

**Review by jsosulska — APPROVED** [review]
LGTM!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/371247.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 7dc78b39c9c5f5120619e70ba168a2d5c12081f2 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 7dc78b39c9c5f5120619e70ba168a2d5c12081f2 onto `release/1.10.x` succeeded!

**Pull request merged**
