### PR TITLE
atomic write service state and checks files

### LINKED ISSUE #1221: unexpected end of JSON input after server crash
After rebooting a server running Consul agent (in server mode), attempting to restart Consul's agent with its previously used parameters throws these errors:
==> Starting Consul agent...
==> Error starting agent: unexpected end of JSON input

Looking in the directories: <consul_data_dir>/checks & <consul_data_dir>/services, I see several files with size 0.

The server's reboot occurred at the same time that we registered health checks to Consul, so I believe that the files are corrupt (empty actually) because they are not being written atomically.
1. Can the files written to the directories mentioned be written atomically?
2. As a workaround, is it safe to delete these directories and restart Consul? It seems to work.

Thanks,
Amir

### PR DESCRIPTION
**Pull request by a86c6f7964**
fixes #1221

### CODE REVIEW

**Comment by shoenig** [comment]
I think you will want to also call Sync on the tmpfile and parent directory for this to actually be atomic

**Comment by a86c6f7964** [comment]
doing a sync would help make it durable, should not have anything to do with it being atomic. I would say doing a sync for these files (which are just to help with entropy) is unnecessary, my original intention is just to make it so there never exists a 0 byte file. Without the sync there will either be a full byte file, or no file.

**Comment by rboyer** [comment]
If your goal is to never have a zero-byte file between system crashes, you **must** call sync on the file before the rename.  If you don't care about the crash/reboot scenario then you can omit the Sync call.

**Comment by a86c6f7964** [comment]
okay. then this helps prevent corrupt state for consul restarts, and consul crashes but not for machine level crashes. I'll defer to the consul devs if they would like to add the sync, or just remove corrupt state files on startup.

**Pull request merged**
