### PR TITLE
docs: fix Amazon EKS service name

### PR DESCRIPTION
**Pull request by allisaurus**

### CODE REVIEW

**Review by lkysow — APPROVED** [review]
🦊

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/372698.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit e4aad106c993d394253c50543e35999147bd48f5 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit e4aad106c993d394253c50543e35999147bd48f5 onto `release/1.10.x` succeeded!

**Pull request merged**
