### PR TITLE
docs/nia: fix catalog-services typos pt 2

### PR DESCRIPTION
**Pull request by lornasong**

### CODE REVIEW

**Review by findkim — APPROVED** [review]
thanks for finding more

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/397280.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit d43f3af2c60ead6c3b7f475fb2f1c5209259a69b onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit d43f3af2c60ead6c3b7f475fb2f1c5209259a69b onto `release/1.10.x` succeeded!

**Pull request merged**
