### PR TITLE
docs: ECS 0.3.0 Updates

### PR DESCRIPTION
**Pull request by pglass**
Updates for Consul on ECS 0.3.0 to document new config options and manual configuration without Terraform.

* Includes https://github.com/hashicorp/consul/pull/12188
* Includes https://github.com/hashicorp/consul/pull/12179
* Includes https://github.com/hashicorp/consul/pull/12113

### CODE REVIEW

**Review by lkysow — APPROVED** [review]

**Comment by pglass** [comment]
Yeah, I think the entire architecture page on the overview is a bit much, now that I'm looking at it again. I added a blurb about architecture on the Overview page, and kept the separate Architecture page for now.

**Comment by pglass** [comment]
Note: `go-test-race` failed, but these are doc changes so merging anyway (I need to remember to prefix the branch name with `docs/`)

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit ada84f12725f5881c99d5a01e3ea36b9909957ca onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit ada84f12725f5881c99d5a01e3ea36b9909957ca onto `release/1.11.x` succeeded!

**Pull request merged**
