### PR TITLE
website(consul-api-gateway): fixup stray div tag and step 8 link

### PR DESCRIPTION
**Pull request by mikemorris**
### Description
Fixes the two following minor rendering issues:

Screen Shot 2022-04-27 at 7 29 16 PM
Screen Shot 2022-04-27 at 7 29 31 PM

### Links
https://www.consul.io/docs/api-gateway/upgrade-specific-versions

### PR Checklist

* [ ] ~~updated test coverage~~
* [x] external facing docs updated
* [x] not a security concern
* [x] checklist [folder](./../docs/config) consulted

### CODE REVIEW

**Review by Jeff-Apple — APPROVED** [review]
LGTM

**Comment by mikemorris** [comment]
One other note on this page is that for step 12, it's not quite clear _why_, as an optional step, a user would want to delete and recreate their routes - is this necessary for them to bind to the new gateway?

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/654760.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 80417f02dc0ca1481f04b312358e97cd612d1280 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 80417f02dc0ca1481f04b312358e97cd612d1280 onto `release/1.12.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/654760)

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 80417f02dc0ca1481f04b312358e97cd612d1280 onto `release/1.11.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/654841.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 80417f02dc0ca1481f04b312358e97cd612d1280 onto `stable-website` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/654841)

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 80417f02dc0ca1481f04b312358e97cd612d1280 onto `release/1.12.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 80417f02dc0ca1481f04b312358e97cd612d1280 onto `release/1.11.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/654841)

**Pull request merged**
