### PR TITLE
Update consul-enterprise.mdx

### PR DESCRIPTION
**Pull request by lkysow**
This block moved to global

### CODE REVIEW

**Review by karl-cardenas-coding — APPROVED** [review]
👍🏼

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/614230.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit c8cdebd9cccb3e853b6f91d343c5f9cb02c33295 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit c8cdebd9cccb3e853b6f91d343c5f9cb02c33295 onto `release/1.11.x` succeeded!

**Pull request merged**
