### PR TITLE
ui: [BUGFIX] Re-enable namespace menus whilst editing intentions

### PR DESCRIPTION
**Pull request by johncowen**
This PR supersedes https://github.com/hashicorp/consul/pull/10706 and fixes https://github.com/hashicorp/consul/issues/10686 whilst making sure that saving intentions continues to work.

The original fix in https://github.com/hashicorp/consul/pull/10706 ignored the `change` action configured for the change event on the menus, meaning that the selected source/destination namespace could not be set by the user when editing/creating intentions. This, coupled with the fact that using the later intention `exact` endpoint for API requests endpoint means that you cannot use wildcard namespaces for saving intentions.

All in all this meant that intentions could no longer be saved using the UI (whilst using ENT):

intention-nspace-menus

This PR reverts https://github.com/hashicorp/consul/pull/10706 to fix the intention saving issue, and adds a fix for the original visual issue of nspaces doubling up in the menu once clicked. This meant repeating this functionality:

https://github.com/hashicorp/consul/blob/b2d17ac4487983b49b006928601d296d7466d2a2/ui/packages/consul-ui/app/components/consul/intention/form/index.js#L143

...for `nspaces` aswell as `services`. It did seem strange to me that the original issue was only apparent for the nspace menus and not the service menus which should all function exactly the same way.

There is potentially more to come here partly related to what the exact functionality should be, but I'm working with other folks to figure out what the best way forwards is longer term. In the meantime this brings us back to the original functionality with the visual issue fixed.

### CODE REVIEW

**Review by kaxcode — APPROVED** [review]
👍

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/452102.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit cfbd1bb84e20c80ed5b3df079fb7f159e56ea39d onto `release/1.11.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit cfbd1bb84e20c80ed5b3df079fb7f159e56ea39d onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit cfbd1bb84e20c80ed5b3df079fb7f159e56ea39d onto `release/1.9.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit cfbd1bb84e20c80ed5b3df079fb7f159e56ea39d onto `release/1.8.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/452102)

**Pull request merged**
