### PR TITLE
Add client ip to http access logs

### LINKED ISSUE #1447: Log client IPs in http access logs
Right now, in DEBUG mode, HTTP access are logged like:

    2015/11/24 15:02:50 [DEBUG] http: Request GET /v1/kv/test (121.887µs )

It would be useful to see the remote client's IP address in these logs as well.

### PR DESCRIPTION
**Pull request by gozer**
Fixes #1447

### CODE REVIEW

**Comment by slackpad** [comment]
Hi @gozer - would you mind sticking the address at the end of the log message and using the new log functions from memberlist, so these will all look the same? Here's an example: https://github.com/hashicorp/consul/blob/master/consul/rpc.go#L86. There's a `LogAddr` function that should work for your use case here. Thanks!

**Comment by gozer** [comment]
Absolutely, will do and update my PR

**Comment by gozer** [comment]
memberlist.LogAddress wants a net.Addr, and req.RemoteAddr is already just a string, not an address anymore, so not sure it's worth trying to convert it back to a net.Addr

**Comment by slackpad** [comment]
@gozer sorry I didn't realize that. In that case, it should be good enough to stick it at the end as `... from=%s` to match the memberlist format then. Agree it's not worth converting to an address.

**Comment by gozer** [comment]
@slackpad done as suggested

**Comment by slackpad** [comment]
@gozer thanks for the update! One other thing - I think your `split()` call will mangle IPV6 addresses - since it's just a string I'd probably just print it with the port number.

**Comment by gozer** [comment]
@slackpad, you are absolutely correct, that address splitting had bothered me from the start, to be honest. Removed as suggested.

**Comment by slackpad** [comment]
LGTM - Thanks!

**Pull request merged**
