### PR TITLE
[WIP] Test coverage checks

### PR DESCRIPTION
**Pull request by skpratt**
Coverage investigation

### CODE REVIEW

**Comment by skpratt** [comment]
All unit tests passed! Total test coverage is now at $COV_PERCENT percent. New coverage report available.

**Comment by skpratt** [comment]
$message

**Comment by skpratt** [comment]
$(message)

**Comment by skpratt** [comment]
All unit tests passed! Total test coverage is now at 71.5% percent. New coverage report available:

**Comment by skpratt** [comment]
All unit tests passed! Total test coverage is now at 71.5%. [New coverage report available]()

**Comment by skpratt** [comment]
All unit tests passed! Total test coverage is now at 71.5%. [New coverage report available]()

**Comment by hc-github-team-consul-core** [comment]
All unit tests passed! Total test coverage is now at 63.9%. [New coverage report available](https://output.circle-artifacts.com/output/job/05591b6f-3423-4bb9-a2e9-11d3c2689aa9/artifacts/0/tmp/output/coverage_heatmap.html)

**Comment by hc-github-team-consul-core** [comment]
All unit tests passed! Total test coverage is now at 63.9%. [New coverage report available](https://output.circle-artifacts.com/output/job/c3e20f30-b524-48a8-9f88-6f1ce496f40b/artifacts/0/tmp/output/coverage_heatmap.html)

**Comment by hc-github-team-consul-core** [comment]
All unit tests passed! Your changes bring test coverage to , from 0. [See coverage delta for your changes]()

**Comment by hc-github-team-consul-core** [comment]
All unit tests passed! Your changes bring test coverage over affected code to 62.0%. Total previous coverage was 0. [See coverage delta for your changes]()

**Comment by hc-github-team-consul-core** [comment]
All unit tests passed! Your changes bring test coverage over affected code to 59.8%. Total previous coverage was 0. [See coverage delta for your changes](https://output.circle-artifacts.com/output/job/98db85b5-51d5-48fc-809e-485536e7e2ad/artifacts/0/tmp/output/diff_coverage_heatmap.html)

**Comment by hc-github-team-consul-core** [comment]
All unit tests passed! Your changes bring test coverage over affected code to 61.0%. Total previous coverage was 63.7%. [See coverage delta for your changes](https://output.circle-artifacts.com/output/job/e36883c0-495e-4646-9e6e-a6b6d233bf49/artifacts/0/tmp/output/diff_coverage_heatmap.html)

**Comment by hc-github-team-consul-core** [comment]
All unit tests passed! Your changes bring test coverage over affected code to 59.5%. Total coverage in main is 63.7%. [See coverage delta for your changes](https://output.circle-artifacts.com/output/job/d6f273b4-9298-41cd-baa2-741ba465dbb8/artifacts/0/tmp/output/diff_coverage_heatmap.html)

**Comment by hc-github-team-consul-core** [comment]
All unit tests passed! Your changes bring test coverage over affected code to 60.8%. Total coverage in main is 63.7%. [See coverage delta for your changes](https://output.circle-artifacts.com/output/job/073e2aed-857d-4f59-9481-0dada19e77ee/artifacts/0/tmp/output/diff_coverage_heatmap.html)

**Pull request closed without merging**
