### PR TITLE
connect/ca: Don't discard old roots on primaryInitialize

### PR DESCRIPTION
**Pull request by kyhavlov**
There are a couple cases in `primaryInitialize` in the `CAManager` that can cause the root to need updating when the leader is starting up. Currently when this happens, the old roots are discarded and only the new root is preserved, which could cause problems if the root was just rotated out and we still need to keep the old root around for interoperability during the switch to the new root. 

This PR changes that behavior to keep the old roots around in this case in `primaryInitialize` - they'll still be pruned through the normal leader routine once enough time has passed after they've been rotated out.

### CODE REVIEW

**Review by dhiaayachi — APPROVED** [review]
LGTM!
Is this fix meant to be backported?

**Review by Jason-123-cyber — COMMENTED** [review]
JJ

**Comment by Jason-123-cyber** [comment]
M

**Review by Jason-123-cyber — COMMENTED** [review]
j

**Comment by Jason-123-cyber** [comment]
b

**Comment by Jason-123-cyber** [comment]
jl

**Pull request merged**
