### PR TITLE
Add changelog entry

### PR DESCRIPTION
**Pull request by 99**

### CODE REVIEW

**Review by dhiaayachi — APPROVED** [review]
LGTM!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/499915.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 0c5fdb167deeb3b87b82372812ec6cb26c81e85a onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 0c5fdb167deeb3b87b82372812ec6cb26c81e85a onto `release/1.9.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 0c5fdb167deeb3b87b82372812ec6cb26c81e85a onto `release/1.8.x` succeeded!

**Pull request merged**
