### PR TITLE
Filter service entry to deduplicate and remove bad entries.

### PR DESCRIPTION
**Pull request by valarauca**
This was written to address https://github.com/hashicorp/consul/issues/7505

### CODE REVIEW

**Comment by valarauca** [comment]
```
Removing volume envoy_workdir
⨯ FAIL
```

Appears while I think the test suite was shutting down containers? I'm not 100% sure.

**Comment by mkeeler** [comment]
@valarauca The test suite can be a little flaky at times and isn't related to your changes.

**Comment by mkeeler** [comment]
I am not sure the problem is having entries in the results that don't have a service address. Its fairly common to omit the service address when you have a consul agent running in the same vm as your proxy and in that way you can inherit addressing from the node instead of having to redefine the address everywhere. So from that standpoint I am not sure the changes in this PR wouldn't break other users setups.

My other inclination was to add a command line parameter to the proxy to be able to register a service address with the proxy. However I then realized the problem goes a bit deeper with conceptually an egress only proxy shouldn't be resolved when discovering other upstream endpoints. It has no public listener so the connection can never work.

I think a solution that wont break others but also allow for egress-only proxies could be to:

1. Add the ability to define service meta when running the builtin proxy.
2. Add filtering capabilities to the native connect resolver to be able to filter out nodes by meta.

For defining the service meta we do so in other commands such as the `consul services register command`:

https://github.com/hashicorp/consul/blob/228284758b8d4aa93174a2f6534ac420f42f3e68/command/services/register/register.go#L47-L49

https://github.com/hashicorp/consul/blob/228284758b8d4aa93174a2f6534ac420f42f3e68/command/services/register/register.go#L90

As for filtering capabilities, we would need to add a `Filter: <filter string>` when creating the query options struct here: https://github.com/hashicorp/consul/blob/9f46759ba2873d03a6e6a8857203deb5d1d6177b/connect/resolver.go#L163-L174

Then in your specific case you could set a meta value of `proxy-mode: egress` and then the filter would be `Service.Meta["proxy-mode"] != "egress"`. The proxies specifically marked for egress only would then be filtered out.

Hopefully that makes sense. Let me know what you think.

**Comment by valarauca** [comment]
> So from that standpoint I am not sure the changes in this PR wouldn't break other users setups.

This use case is actually part of the existing project's test suite, and the 2 fallback conditionals:

https://github.com/valarauca/consul/blob/0581af2188423974bc7953835662f03a50f5c6c3/connect/resolver.go#L295-L307

https://github.com/valarauca/consul/blob/0581af2188423974bc7953835662f03a50f5c6c3/connect/resolver.go#L309-L313

Are there to ensure that the legacy behavior is preserved.

I learned this the hard way. I originally the change was a lot simpler. At first I just planned to remove the offending conditional:

https://github.com/valarauca/consul/blob/0581af2188423974bc7953835662f03a50f5c6c3/connect/resolver.go#L137-L140

That saw a lot a staggering number of failing tests. So the conditional remained, and the fall back cases were added.

**Comment by valarauca** [comment]
Following up

**Comment by markan** [comment]
Thank you for your pull request! We're sorry about having this PR sit open for so long. In the time since the initial PR, we have decided to stop active development on the built-in proxy. ***Please see the notice here [https://www.consul.io/docs/connect/built-in]***

We recommend that users use Envoy as it is most feature-rich proxy integrated with Consul.

Sorry about letting this linger so long without feedback. We're working on improving our process going forward.
Thank you for your patience.

**Pull request closed without merging**
