### PR TITLE
docs: Fix JSON formatted example ACL policies

### PR DESCRIPTION
**Pull request by blake**
### Description
Commit 9333fad added JSON formatted examples for all ACL polices. Most of these these examples are not valid JSON, and thus an error is raised when attempting to create the example policies/rules in Consul.

This commit fixes the example JSON formatted ACL rules so that they are valid JSON. This enables readers to use the policies as-is from the documentation to successfully create policies in Consul.

It also removes unnecessary arrays from the example policies so that the policies are easier for practitioners to read and write.

### Testing & Reproduction steps

Take for example the policy for the `web-prod` service listed at <https://github.com/hashicorp/consul/blame/5451863f9fb9e71aeeadc7756dd72209a6c2f83b/website/content/docs/security/acl/acl-policies.mdx#L136-L141>.

```json
"service": [{
  "web-prod" : [{
    "policy" : "deny"
  }]
}]
```

This is not valid JSON and results in the following error when attempting to create the policy in Consul.

```shell-session
$ consul acl policy create -name=web-prod -rules=@web-prod-policy.json
Failed to create new policy: Unexpected response code: 500 (Failed to parse ACL rules: At 1:10: illegal char)
```

Wrapping the policy in `{ }` makes it valid JSON, and allows it to be created in Consul.

```json
{
  "service": [{
    "web-prod" : [{
      "policy" : "deny"
    }]
  }]
}
```

```shell-session
consul acl policy create -name=web-prod -rules=@web-prod-policy.json
ID:           9f21e81d-b598-9885-4a42-0a6109f405ee
Name:         web-prod
Description:  
Datacenters:  
Rules:
{
  "service": [{
    "web-prod" : [{
      "policy" : "deny"
    }]
  }]
}
```

It is also not necessary for the arrays to be present in the payload. The ACL resource labels can be specified as unique keys within the parent JSON object. The value of each key is a nested JSON object containing one or more policies and its associated policy disposition.

```json
{
  "<resource>": {
    "<label>": {
      "policy": "<policy disposition>"
    }
  }
}
```

The following an equivalent, yet simplified, ACL policy.

```json
{
  "service": {
    "web-prod": {
      "policy": "deny"
    }
  }
}
```

### PR Checklist

* [ ] updated test coverage
* [X] external facing docs updated
* [X] not a security concern
* [ ] checklist [folder](./../docs/config) consulted

### CODE REVIEW

**Review by jkirschner-hashicorp — APPROVED** [review]
LGTM - thanks Blake :)

**Comment by blake** [comment]
@jkirschner-hashicorp Thanks for the review.

I realized that there are other issues related to the ACL documentation (e.g., inconsistent or unclear descriptions of policies) that I would like to fix prior to merging this PR. I added the `do-not-merge` label. I'll work on those other changes and then re-request the review of this PR.

**Comment by blake** [comment]
I made a few more adjustments to these docs, and requested a re-review of the PR prior to it being merged.

**Review by mikemorris — APPROVED** [review]
LGTM, only question is why remove the HCL examples for ServiceIdentities and NodeIdentities?

**Review by im2nguyen — APPROVED** [review]

**Pull request merged**
