### PR TITLE
fix: NET-1521 show latest config in /v1/agent/self

### PR DESCRIPTION
**Pull request by nvanthao**
### Description

This PR is to fix issue NET-1521 where `/v1/agent/self` currently not reflecting latest reloadable config

Before the PR, updating reloadable config and run `consul reload`, the API still show old original config

Original config

```
bootstrap   = true
server      = true
data_dir    = "/tmp/server"
log_level   = "WARN"
bind_addr   = "127.0.0.1"
client_addr = "127.0.0.1"
raft_snapshot_threshold = 500
```

Updated config

```
bootstrap   = true
server      = true
data_dir    = "/tmp/server"
log_level   = "DEBUG"
bind_addr   = "127.0.0.1"
client_addr = "127.0.0.1"
raft_snapshot_threshold = 1000

$ consul reload
Configuration reload triggered
```

Before the PR

```
$ curl -s 0:8500/v1/agent/self\?pretty | grep LogLevel
            "LogLevel": "WARN",

$ curl -s 0:8500/v1/agent/self\?pretty | grep RaftSnapshotThreshold
        "RaftSnapshotThreshold": 500,
```

After the PR

```
$ curl -s 0:8500/v1/agent/self\?pretty | grep LogLevel
            "LogLevel": "DEBUG",
$ curl -s 0:8500/v1/agent/self\?pretty | grep RaftSnapshotThreshold
        "RaftSnapshotThreshold": 1000,
```

### Testing & Reproduction steps

I have tested the changes manually with above config. However, my unit test is not passing. It will be great if someone could help me with guidance on improving the unit test.

### PR Checklist

* [X] updated test coverage
* [ ] external facing docs updated
* [ ] appropriate backport labels added
* [ ] not a security concern

### CODE REVIEW

**Comment by dhiaayachi** [comment]
Hey @nvanthao 
One last change, Could you please update the changelog file name to match the PR number in here `18681`?

**Comment by nvanthao** [comment]
Thanks @dhiaayachi ! This has been done. Please let me know how it goes!

**Review by dhiaayachi — APPROVED** [review]
LGTM! Thank you @nvanthao !

**Comment by hc-github-team-consul-core** [comment]
Backport failed @nvanthao. Run: https://github.com/hashicorp/consul/actions/runs/6115882393

**Pull request merged**
