### PR TITLE
Update version.js

### PR DESCRIPTION
**Pull request by kisunji**

### CODE REVIEW

**Review by dhiaayachi — APPROVED** [review]
LGTM!!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/534194.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit f8b1ab4d67cc4cac869f47485ff7328f42fa519f onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit f8b1ab4d67cc4cac869f47485ff7328f42fa519f onto `release/1.11.x` succeeded!

**Pull request merged**
