### PR TITLE
[1.10.x] acl: fix txn_endpoint to properly authorize service registrations

### PR DESCRIPTION
**Pull request by dnephin**
Backport of the bugfix commit from #10793

### CODE REVIEW

**Review by freddygv — APPROVED** [review]
LGTM, I think it would be worth backporting this to 1.9 and 1.8 as well.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/423200.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 77202756796d4386275ecde5e9aff013e36b72f5 onto `release/1.9.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 77202756796d4386275ecde5e9aff013e36b72f5 onto `release/1.8.x` succeeded!

**Pull request merged**
