### PR TITLE
command/agent: Google Compute Engine host discovery

### PR DESCRIPTION
**Pull request by vancluever**
This PR adds several command-line and config options that facilitate host discovery through Google Compute Engine (GCE), much like the recently added EC2 host discovery options. This should assist with bootstrapping and joining servers within GCE when non-static addresses are used, such as when using managed instance groups.

Documentation has also been added. It should be noted that if running from within a GCE instance, the only option that should be necessary is `-retry-join-gce-tag-value`.

### CODE REVIEW

**Comment by vancluever** [comment]
WIPing this as looks like using the command off the command line is not working - will update soon!

**Comment by vancluever** [comment]
WIP removed - fixed the formatting on the help text and ensured that GCE discovery was actually detected in the same way that EC2 is (ie: adding the presence of the tag value to the same `ec2Enabled` clause).

**Comment by kyhavlov** [comment]
Thanks for the PR, @vancluever! This is a nice piece of functionality to have alongside the EC2 join stuff.

**Comment by vancluever** [comment]
No prob and thanks for the merge @kyhavlov!

**Comment by magiconair** [comment]
@vancluever I've got a question regarding your PR since I'm moving your code to https://github.com/hashicorp/go-discover. You name the override parameter for the project `project-name` but during auto-discovery you lookup the `project-id`. Using the project name also fails for me but it works fine when I use the project ID. Am I missing something?

**Pull request merged**
