### PR TITLE
docs: Fix spelling errors

### PR DESCRIPTION
**Pull request by blake**
Fix miscellaneous spelling errors across website.

### CODE REVIEW

**Review by karl-cardenas-coding — APPROVED** [review]
Thanks for catching these @blake

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/548401.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit e3f36ad45c06bd67ae7c32bd69b47827104362e5 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit e3f36ad45c06bd67ae7c32bd69b47827104362e5 onto `release/1.11.x` succeeded!

**Pull request merged**
