### PR TITLE
Add link for new Cisco TF module

### PR DESCRIPTION
**Pull request by BeenzSyed**
Add a link for a new TF module that Cisco created that dynamically creates and updates Endpoint Security Groups.

### CODE REVIEW

**Review by lornasong — APPROVED** [review]
looks good to me!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/371969.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit ce958e72180d80fb8da054a9483a8172f83076ce onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit ce958e72180d80fb8da054a9483a8172f83076ce onto `release/1.10.x` succeeded!

**Pull request merged**
