### PR TITLE
Document integration tests

### PR DESCRIPTION
**Pull request by lkysow**

### CODE REVIEW

**Comment by lkysow** [comment]
@eculver I started to write out some stuff here. Please feel free to push up your own findings to this branch.

**Review by huikang — APPROVED** [review]
Could we add a link somewhere on this [page](https://github.com/hashicorp/consul/tree/main/docs#contents) to this doc.

**Comment by eculver** [comment]
> Could we add a link somewhere on this [page](https://github.com/hashicorp/consul/tree/main/docs#contents) to this doc.

Yep, I can do that in my change that I'm putting together.

**Comment by lkysow** [comment]
I did that actually.

**Pull request merged**
