### PR TITLE
[Old] using WeakDecode for parseHttpHandlerConfig

### LINKED ISSUE #17595: Agent configuration file parsing error
#### Overview of the Issue

As shown, using the array syntax in hcl, a value is configured
image

But when the agent starts, it reports an error that "got string". I have to explicitly configure multiple values in the array to get around this error
image

---

### PR DESCRIPTION
**Pull request by vijayraghav-io**
Fixes #17595 

Using WeakDecode instead of Decode while parsing HttpHandlerConfig alone.
This ensures slice with single element is decoded to slice instead of just string (if it is required to be a slice as per Config).

### CODE REVIEW

**Comment by vijayraghav-io** [comment]
@Maintainers @team @jkirschner-hashicorp @huikang 
Reminding to review this PR

**Comment by huikang** [comment]
@vijayraghav-io , thanks for the PR. It would be nice if you could add a unit test for the change.

**Comment by vijayraghav-io** [comment]
Hi @huikang, 
Sorry, Some how i had missed to track this conversation and PR, hence delayed response.

Refer new PR - https://github.com/hashicorp/consul/pull/18473

Added the test data - "watches.hcl" as new test data with header element as 1 element slice (issue reported usecase).
Added both test cases for same test data -
- using weakdecode 
- using decode (assert error - to show using decode (as before) would create error for above test data.

Also updated the approach a little bit  ( better design :)  )
- By default and first, Decode is used while parsing httpHandlerConfig (as before), Only if error occurs then WeakDecode is used in 2nd attempt. This ensures we are not using WeakDecode blindly in all cases.

**Comment by vijayraghav-io** [comment]
This PR can be discarded and refer to https://github.com/hashicorp/consul/pull/18473 , for review and discussion

**Comment by vijayraghav-io** [comment]
This is a reference for a new PR - https://github.com/hashicorp/consul/pull/18473

**Pull request closed without merging**
