### PR TITLE
docs: add Exported Services to overview

### PR DESCRIPTION
**Pull request by david-yu**
Adds Enterprise tag to Exported Services Config entry and adds to Overview

### CODE REVIEW

**Review by karl-cardenas-coding — APPROVED** [review]
lgtm

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/533125.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit dd1179177fc8303c8ca3ee84c4cd28182803d4ad onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit dd1179177fc8303c8ca3ee84c4cd28182803d4ad onto `release/1.11.x` succeeded!

**Pull request merged**
