### PR TITLE
?pretty, work without value.

### PR DESCRIPTION
**Pull request by thorduri**

### CODE REVIEW

**Comment by ryanuber** [comment]
LGTM. We should have a test for this to ensure that the value-less option works as expected. You can see an example for the `?stale` argument [here](https://github.com/hashicorp/consul/blob/master/command/agent/http_test.go#L189).

**Comment by thorduri** [comment]
@ryanuber That stale example is testing that you can set either ?stale or ?consistent, but not both.

**Comment by ryanuber** [comment]
Right, I was just thinking if you wanted to bang out a test real quick then you could probably just grab a few lines from that test and tweak it to verify the `?pretty` behavior. It looks like we're actually missing a basic test for the pretty-print functionality anyways, so a few tests might be in order. If you'd rather, I'd be happy to do this after a merge as well.

**Comment by ryanuber** [comment]
@thorduri I just pushed a basic test for pretty-printed responses in e9615c5. If you rebase against master and add one more test (or expand the `TestPrettyPrint` test), we can then merge this in. We want to test that both forms (`?pretty=1` and `?pretty`) work as intended so we don't break any clients.

**Comment by thorduri** [comment]
@ryanuber Done. Hopefully the test refactor is OK.

**Comment by sethvargo** [comment]
Thanks!

**Pull request merged**
