### PR TITLE
contrib: add list of check register flows

### PR DESCRIPTION
**Pull request by dnephin**
Add the list of 6 entrypoints for registering a check. The hope is that this list acts as kind of a checklist for reviewing or modifying health checks, to prevent bugs like #7566.

[Preview](https://github.com/hashicorp/consul/blob/dnephin/contrib-check-register-flows/contributing/service-discovery/health-checks.md)

### CODE REVIEW

**Review by freddygv — APPROVED** [review]
Thanks!

**Review by markan — APPROVED** [review]
Thank you for adding this!
Do you think it is worth adding pointers to the code in question?

**Comment by dnephin** [comment]
Updated the docs to include the name of the struct and fields on the struct that register checks, and also links to the code file for the entrypoints.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/426157.

**Pull request merged**
