### PR TITLE
Replace Statsite prefix with Service prefix

### PR DESCRIPTION
**Pull request by VoyTechnology**
Currently the `sitestat_prefix` is used for all metrics. This is very counterintuitive. This change adds a `service_prefix` configuration option instead and deprecates `sitestat_prefix`.

Also included:
* Minor import fix
* Documentation

### CODE REVIEW

**Comment by magiconair** [comment]
This needs to come after #3480 is merged.

**Comment by magiconair** [comment]
@VoyTechnology if you feel comfortable then I'd ask you to rewrite that change on top of the refactor-config branch since we're going to merge that soon. This will change the entire handling of configuration for the agent. Otherwise, I'll pick this up.

**Comment by VoyTechnology** [comment]
Thanks for response :) I forgot about this change. Will look at it soon

**Comment by magiconair** [comment]
Since we're breaking things for 1.0 anyway we might just do this one properly. We will pull all the doc fixes into a separate commit. I'll close this one in favor of #3498 . Thanks for your submission!

**Pull request closed without merging**
