### PR TITLE
put vendored packages into vendor.json

### PR DESCRIPTION
**Pull request by alvin-huang**
These packages were vendored in from #3995 and #4016 but were not all added to the `vendor.json` file.

I backtraced the PRs and pulled all the relevant refs from:

`govendor fetch github.com/prometheus/client_golang/prometheus/promhttp@f504d69affe11ec1ccb2e5948127f86878c9fd57`

and https://github.com/miekg/dns/blob/v1.0.4/Gopkg.lock

### CODE REVIEW

**Comment by alvin-huang** [comment]
@mkeeler thanks for having a look. That sounds right. What I did was compare the external dependencies that were missing but didn't realize some of the same deps were used by consul directly  and now I see that consul had pulled in newer refs of those deps.

**Comment by mkeeler** [comment]
So interestingly:

when I do a `govendor fetch github.com/prometheus/client_golang/prometheus/promhttp@f504d69affe11ec1ccb2e5948127f86878c9fd57` followed by a make vendorfmt there are 0 changes.

Still looking into the DNS thing

**Comment by mkeeler** [comment]
Yeah, the lock file and what we have in the source definitely dont match. Whether thats good or bad I am not sure.

**Comment by banks** [comment]
Superseded by #4110

**Pull request closed without merging**
