### PR TITLE
Update install.mdx

### PR DESCRIPTION
**Pull request by Petenerd**
missing comma

### CODE REVIEW

**Review by karl-cardenas-coding — APPROVED** [review]
Thanks for addressing this @Petenerd

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/601344.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 8fa808acaf6efba22c67e51a98868bf2475e2f9b onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 8fa808acaf6efba22c67e51a98868bf2475e2f9b onto `release/1.11.x` succeeded!

**Pull request merged**
