### PR TITLE
Logging abstraction

### PR DESCRIPTION
**Pull request by mantzas**
After a quick discussion in issue #5788 i created a PR to demonstrate a possible log abstraction that would allow the user to plugin any logger they want. @pearkes whenever you have time i would like your feedback thanks.

Implemented Option: Lowest intrusion. Nothing has to be added as an argument/parameter. Removed logger as arguments.
Option 2: Medium intrusive: Another option could be using the context to propagate the logger which has to implement an interface.
Option 3: Very intrusive: Add logger as an interface to every function/method that wants to log.

### CODE REVIEW

**Comment by pierresouchay** [comment]
yes, being able to replace printf (and optionally structured logs, so, for instance we can store from which agent the requests are coming from on servers), would be very interesting for us as well

**Comment by mantzas** [comment]
@pierresouchay you can actually do a lot by using your another logging package (context, structured, performance, allocations etc.). 
I think the this should be a abstraction which is provided by the go std package. 
I an encountering this problem almost everywhere.

**Comment by i0rek** [comment]
We are currently moving to `hclog` and I think that should solve this issue. @s-christoff @crhino

**Comment by mantzas** [comment]
> We are currently moving to `hclog` and I think that should solve this issue. @s-christoff @crhino

can we provide our own logger so that our final logging output from our  code and consul client code are the same?

**Comment by i0rek** [comment]
@mantzas if you provide a hclogger to `RunWithClientAndLogger`, you should have the same logging output.

**Comment by mantzas** [comment]
@i0rek thanks for the info. closing this.

**Pull request closed without merging**
