### PR TITLE
Update references to the main branch

### PR DESCRIPTION
**Pull request by dnephin**
The main branch is being renamed from master->main. This commit should update all references to the main branch to the new name.

We may need to do the rename before CI accepts these changes.

### CODE REVIEW

**Review by markan — CHANGES_REQUESTED** [review]
The changes look good, however we might want to fix the links in the CHANGELOG and in website/content/docs/upgrading/instructions/upgrade-to-1-10-x.mdx, which still point to master

**Comment by dnephin** [comment]
Good catch! I made those changes in the last commit.

**Review by markan — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/401187.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit fa5d6270142ad761e2f1b88764859b5cb8386dd8 onto `stable-website` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/401187)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit fa5d6270142ad761e2f1b88764859b5cb8386dd8 onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/401187)

**Pull request merged**
