### PR TITLE
Event Streaming

### PR DESCRIPTION
**Pull request by Kr1sso**
Added an endpoint for event streaming. Clients could be interested in receiving events as they happen on a 'per event' basis. The agent had a LastUserEvent function, it was never exposed in Consuls HTTP API though.

EventList returns all recent events including the new events, and querying with an index only blocks until a new event arrives. With EventStream clients that are interested in every new event can stream changes and react accordingly.

### CODE REVIEW

**Comment by sigil66** [comment]
:heart:

**Comment by i0rek** [comment]
We need that as well.

**Comment by Kr1sso** [comment]
:arrow_double_up:

**Comment by slackpad** [comment]
Hi @Kr1sso sorry for the delay in looking at this - once we get 0.6.1 released (hopefully today) we will make a sweep through all the PRs, including this one.

**Comment by Kr1sso** [comment]
@slackpad Awesome, great work by the way!

**Comment by slackpad** [comment]
Hi @Kr1sso sorry I let this go for so long - we didn't get a ton of additional interest in this feature, and it would need some rework to include things like ACLs, so I'm not sure we want to take on the additional complexity of this. I'm going to close this out for now, please let me know if you are still interested in trying to get this in - I'm kind of on the fence with this one.

**Comment by multipathmaster** [comment]
NOOOOOOOOOOOOOOOOO!!!! (Darth Vader).

All humor aside.  We were really hoping that this would be made available.  Currently the listener we wrote that uses consul watch does some streaming, however it has to be timed to run at certain times (sleep/wait 30 or so).  It would have been awesome to have an endpoint that just pushes forward changes, so that we aren't getting NXDOMAIN errors because consul/nomad haven't updated quick enough to resolve the DNS on the backend.  Which again, a sleep/wait is a good bandaid, but it would have really been nice to have this feature so that others can actually build something around it to update loadbalancers that aren't software based (i.e. physical devices built to handle a very heavy and ever changing workload).

**Pull request closed without merging**
