### PR TITLE
Add "jump to section" dropdown

### PR DESCRIPTION
**Pull request by lkysow**
Copied from terraform.io:
image

Clicking results in:
image

### CODE REVIEW

**Comment by lkysow** [comment]
@nfagerlund I'm stealing your code from terraform.io docs to add a "jump to section" dropdown. Any gotchas I might have missed?

**Comment by nfagerlund** [comment]
@lkysow Oh hey, exciting! :D This all looks fine to me. 

One thing that happened to us was, eventually I had all these text controls whose baselines needed to line up in order to not look messy. The current approach to that is fairly hideous, and it wasn't going to survive adding one more lined-up text control; naturally, the registry folks want to add one more text control up there. 😂 So, I've got a draft PR right now that takes a different approach to the line-up: https://github.com/hashicorp/terraform-website/pull/945 

That one's gross in a different way: it uses jquery to move some of those elements into some container divs in order to make the CSS comprehensible. 

I don't think you need to worry about doing that right now, because: 

- You don't need to deal with the filter thing at the moment, because you don't have a Zork-style darkened maze of provider docs. So, alignment doesn't matter as much. 
- The whole problem stems from not having enough of these page elements separated out as metadata. Like, if we were free to insert the page title wherever we wanted, this wouldn't be an issue, but instead it's embedded as part of the main text. Likewise with the sidebar headers. That's something worth fixing on the next version of the web platform.

**Comment by judithpatudith** [comment]
This is very cool, thanks @lkysow and @nfagerlund! A couple of optional notes:

It seems like the jump-to section only appears when there are three or more headers on a page? It kind of weirded me out that it isn't on every page; I expected it to be consistent. Additionally, on long pages with few headings (for example, the [Jepsen testing page](https://deploy-preview-6722--consul-docs-preview.netlify.com/docs/internals/jepsen.html)) it might be nice to have the dropdown, just to reassure readers that there aren't additional sections way at the bottom. 

I also noticed that on a bunch of the pages we manually added bulleted lists to serve the same function as the dropdown. It might make sense to remove those lists, either here or in a separate PR. Examples I noticed:

- [Consul Glossary](https://deploy-preview-6722--consul-docs-preview.netlify.com/docs/glossary.html)
- [Consul Enterprise](https://deploy-preview-6722--consul-docs-preview.netlify.com/docs/enterprise/index.html)

We also might want to audit for header level mistakes. The one I noticed is in the [Environment Variables section of the CLI page](https://deploy-preview-6722--consul-docs-preview.netlify.com/docs/commands/index.html#consul_http_addr) but there may be others.

**Comment by nfagerlund** [comment]
I can't remember the whole conversation that led to the two-or-less exemption, but I'm not super attached to it! It might have even been a premature response to a complaint we wouldn't have received anyway.

**Comment by lkysow** [comment]
@judithpatudith I've made it so the drop down is always included, even if there's only one header.
I started to go through every page to see if there's mis-nested headings or manual bulleted lists however there's hundreds of pages and I don't have time to do them all.

I think since this is a good start we should merge this.

**Pull request merged**
