### PR TITLE
Fixing spelling under Matching and Prefix Values

### PR DESCRIPTION
**Pull request by ultrafear**
Lending a helping hand.

### CODE REVIEW

**Review by blake — APPROVED** [review]
Thanks for correcting this.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/505267.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 854d6e6d5954ec3d0e39215362f90ea9bfcea022 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 854d6e6d5954ec3d0e39215362f90ea9bfcea022 onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/505267)

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/505424.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 854d6e6d5954ec3d0e39215362f90ea9bfcea022 onto `stable-website` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/505424)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 854d6e6d5954ec3d0e39215362f90ea9bfcea022 onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/505424)

**Pull request merged**
