### PR TITLE
agent: Don't leave old errors around in cache

### LINKED ISSUE #4480: agent: Cache can return errors older than the last non-error result
Assume the first call to the Roots endpoint failed. That cache entry looks a little like this (pseudo code)

```go
CacheEntry{
  Value: nil,
  Error: "not bootstrapped yet",
  Index: 0,
  Valid: false,
}
```

The next blocking call comes in with index=1 since we set that in the leaf client: https://github.com/hashicorp/consul/blob/ec755b4ba7cdbee391b51750238250948774e741/agent/cache-types/connect_ca_leaf.go#L171-L175

So the get makes another request to roots. Let's assume this request _succeeds_.

The non-nil value is populated into the new cache entry, and the index updated: https://github.com/hashicorp/consul/blob/ec755b4ba7cdbee391b51750238250948774e741/agent/cache/cache.go#L346-L364

The cache Entry now looks like this:

```go
CacheEntry{
  Value: <response>,
  Error: "not bootstrapped yet", // nothing cleared this
  Index: 123, // actual index of the response
  Valid: true,
}
```

Then we close the `Waiter` chan unblocking any `Get` calls which loop and hit: https://github.com/hashicorp/consul/blob/ec755b4ba7cdbee391b51750238250948774e741/agent/cache/cache.go#L211-L231

But since there is now actually a change in Index we make it through OK and the comment there explains why the Error value was left and gets ignored in this case.

So far so good.

Then the next blocking `cache.Get` comes in with the same index `123`.

Assume it times out (because roots didn't change) which means the roots `Fetch` returns a good response (same as one in cache) and the same Index.
https://github.com/hashicorp/consul/blob/ec755b4ba7cdbee391b51750238250948774e741/agent/cache/cache.go#L346-L364

That is a no-op since it's setting same value, index, and valid values. So the cache entry still looks the same:

```go
CacheEntry{
  Value: <response>,
  Error: "not bootstrapped yet", // nothing cleared this
  Index: 123, // actual index of the response
  Valid: true,
}
```

**BUT** we close the `Waiter` chan which causes our `Get` to unblock again.

This time we have the same index as the cached block so we fail to enter the happy path here: https://github.com/hashicorp/consul/blob/ec755b4ba7cdbee391b51750238250948774e741/agent/cache/cache.go#L211-L212

We _should_ go back to blocking on another query if `timeoutCh` hasn't fired yet but instead we hit:

https://github.com/hashicorp/consul/blob/ec755b4ba7cdbee391b51750238250948774e741/agent/cache/cache.go#L233-L240

And so we return (early) the error from _before_ the current valid cached result!

### PR DESCRIPTION
**Pull request by banks**
Fixes #4480. 

A full description of the specific case can be found in the issue and is described in the code here.

The basic invariant that was not being correctly enforced is:

  - A cache entry _may_ have both be `Valid = true` _and_ have a non-nil `Error`.
    - This can occur when a previous Fetch succeed, but a more recent blocking fetch errored. We store the _later_ error in the entry so that all currently blocked `Get` calls can return it immediately instead of waiting their whole timeout before failing
  - Thus, an entry where both `Valid = true` and `Error != nil` implies the error is newer and gets returned to blocking clients.

Until this PR, we were failing to enforce that because we never reset the `Error` on a successful fetch so the _older_ error value could suddenly resurface after a successful Fetch value was returned but only for clients that had caught up and were blocking!

The subtleties here are staggering - even with the description in the issue, it took several attempts to write a test that triggered this reliably - it haas to be the Fetch that times out and it has to return the same index. If the Get times out instead then correct behaviour was observed.

The fix is trivial but the reasoning behind it is not! This is now correct.

### CODE REVIEW

**Comment by goushicui** [comment]
why not set newEntry.Error = err after result, err := tEntry.Type.Fetch(fOpts, r) ?

**Comment by banks** [comment]
@goushicui that's a good question. I was going to reply and say it doesn't matter and this way was clearer why it's important but actually I think there is another subtle bug here that your suggestion would fix.

Cache types are allowed to return a nil `Value` and a nil error which means "nothing new, just keep the same cache value you already have".

In this specific sequence the PR as it stands would still have the bug:

 1. Fetch returns success Value: 42
 1. Fetch returns error "servers down"
    - cache state is now `{Value: 42, Valid: true, Error: "servers down"}`
 1. Fetch succeeds but decides to use the "empty value means no change" behaviour that we specifically document is allowed
 1. Subsequent blocking calls will get the error

So yes I should change it, great catch!

**Comment by banks** [comment]
@goushicui thanks, that Pull URL is 404 for me did you take it down again?

**Comment by goushicui** [comment]
[#5308](https://github.com/hashicorp/consul/pull/5038)

**Pull request merged**
