### PR TITLE
toil: use pre-commit to maintain properly formatted imports

### PR DESCRIPTION
**Pull request by analogue**
### Description

We currently don't do a good job of formatting go imports consistently across the code base. This can lead to diffs showing up in PRs that needlessly change the import order or ping-pong between different import orders based on a specific developer's dev environment and tool configuration (vs code vs goland vs vim + friends, etc). 

This PR uses a popular (11k+ github stars) opensource tool, [pre-commit](https://pre-commit.com/), to move this responsibility from individuals + bespoke configuration to a deterministic config that is under source control and applied on every `git commit`. 

The tool can be bypassed if needed via `git commit --no-verify`.

Currently, the behavior is opt-in and only activated if the pre-commit tool is installed.

Support has been added to install pre-commit by extending the existing `make tools` target. Installation is supported via Homebrew on Macs, Python + pip3 on all platforms, and via `apt` on debian based linux distros.

The "fixing of imports" is only applied to files in the commit, not all files in the repo. 

I'd like to let this incubate in "opt-in" mode for a while before making it the default.

See https://hashicorp.atlassian.net/browse/NET-3409 for previous work done to compare various go import formatters and examples of the formatting style.

### Testing & Reproduction steps

Works for me.

### PR Checklist

* [ ] updated test coverage
* [x] external facing docs updated
* [ ] appropriate backport labels added
* [x] not a security concern

### CODE REVIEW

**Comment by analogue** [comment]
I did some more testing and excluded all generated `.go` files in the exclusion list.

**Comment by analogue** [comment]
@dhiaayachi @rboyer Let me know if there are any blockers to get this committed. I'd like to start exploring other pre-commit checks once this is in place to reduce additional toil.

**Review by dhiaayachi — APPROVED** [review]
Thank you @analogue!
Great research and problem documentation! 

The only remaining open question IMO is how that would behave with the combination of other tools automatically updating imports (thinking about goland! 😅). But I guess we will try it and see

**Comment by analogue** [comment]
> Thank you @analogue! Great research and problem documentation!
> 
> The only remaining open question IMO is how that would behave with the combination of other tools automatically updating imports (thinking about goland! 😅). But I guess we will try it and see

I'm hoping folks will eventually tire of having their own editor/tools improperly format imports when they're constantly being fixed on `git commit` by the hook and then invest some time in fixing their editor/tools. It will be annoying at first, but it needs to happen to get everyone on the same page.

**Pull request merged**
