### PR TITLE
Update a couple dependencies

### PR DESCRIPTION
**Pull request by dnephin**
To pickup these changes:
* https://github.com/armon/go-metrics/pull/124
* https://github.com/hashicorp/memberlist/pull/236
* https://github.com/hashicorp/raft/pull/465

Also includes:
* https://github.com/armon/go-metrics/pull/123 (does this need a changelog entry?)

### CODE REVIEW

**Review by banks — APPROVED** [review]
LGTM 👍

**Comment by dnephin** [comment]
I added the raft update for https://github.com/hashicorp/raft/pull/465 to this PR as well.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/362433.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 981fb5322a9859e480e7039b69abd88556b84e11 onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 981fb5322a9859e480e7039b69abd88556b84e11 onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/362433)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 981fb5322a9859e480e7039b69abd88556b84e11 onto `release/1.8.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/362433)

**Pull request merged**
