### PR TITLE
Do not surface left servers

### PR DESCRIPTION
**Pull request by i0rek**
Left servers will never come back so there is no reason to surface them in `GetDatacentersByDistance`. One of the results is that dcs with only left servers will no longer show up in `v1/catalog/datacenters`, which is the right thing to do since this dc is not reachable.

### CODE REVIEW

**Comment by freddygv** [comment]
This feels like a small breaking change since the output of an endpoint is changing. Maybe we should get it into 1.7.0 but not 1.6.x?

**Comment by pierresouchay** [comment]
@freddygv Well, this change the output in very rare occasions (when DC is dead for more than 72 hours or operator did force-leave the servers), so it looks to me like a very reasonable choice that would unlikely break workflows (while helping a lot during decommission).
This looks like a great change to me.

**Comment by i0rek** [comment]
I agree with @pierresouchay on this one. I think this a bugfix, what would anyone want to do with decommissioned datacenters... And thus I think it would be fine to include it into 1.6.x series.

**Comment by i0rek** [comment]
I noticed the other functions that are returning datacenters and I want to make sure to make them all behave similarly.

**Pull request merged**
