### PR TITLE
Add Catalog API as an interface

### PR DESCRIPTION
**Pull request by PumpkinSeed**
I just created a small in-memory representation of the Consul's catalog for pipeline tests, and this implements the Catalog struct's all methods. I would like to change the Catalog struct to a Catalog interface, if I want to mock it in the tests I just have a function which returns the the mock or the real Consul's catalog whether it's in the test or not.

### CODE REVIEW

**Comment by tyson925** [comment]
Do it!

**Comment by pearkes** [comment]
We definitely understand the use-case here and are not opposed to this, but we'd want to make this change package-wide for consistency, rather than just for the catalog endpoints. Let us think about this a bit more.

**Comment by PumpkinSeed** [comment]
Also I would like to help you in the implementation, if you had made the decision and necessary a bit of help.

**Comment by banks** [comment]
Hi,

We discussed this a little and have a few reasons we'd be reluctant to make the change as described.

 1. If the only purpose is for testing, it's nicer to put the interface on the _consumer_ side rather than have an "official" one. One of the best parts of Go's interface model is that the actual implementation _doesn't need_ to explicit define and implement an interface for you to be able to user it as one. For example, in your app you can create a `type ConsulAPI interface{}` which includes all, or just the methods you actually need, and then the real Consul API can be used as a value of your type. Yes it's true that the `api.Client` returning multiple different structs from e.g. `client.API()` methods means you have to make at least a couple of different interfaces to do this, but you can. See https://medium.com/@cep21/preemptive-interface-anti-pattern-in-go-54c18ac0668a or search for other folks describing why this is a better pattern in general.

 2. Changing the `api` package to be an interface and not a struct is binary-incompatible. For users who are only ever doing simple things like calling methods on it it might work without changes, but this is still technically a breaking change since the following (useless) code would no longer compile:
```go
var catalogStruct := api.Catalog{}
```
It is indeed a straw-man argument in that that is a useless thing to do and there are no public members on Catalog you might be accessing, but in general that is not a safe/backwards compatible change in Golang.

The big reason is 1. it's kind of an anti-pattern to define interfaces up front rather than at the point of use unless there is a real need for it in the API.

**Pull request closed without merging**
