### PR TITLE
Add path-based routing example to Ingress docs

### LINKED ISSUE #8018: Ingress gateway - path based routing
#### Feature Description

Currently as documented for ingress gateway, we can add multiple listeners. This request is to allow path based routing - for example: 
http://<ip>:<listenport>/api_service1, http://<ip>:<listenport>/api-service2 

instead of
http://<ip>:listenport1 , http://<ip>:listenport2 

Host headers is not an option for existing apps.

#### Use Case(s)

How can we expose multiple ports within a single service in k8s? If there is a good option, can you pls let me know? We're trying to connect to multiple k8s microservices from outside (legacy apps). Not sure if using this is the right approach or if you all suggest something else.

Thank you!

### PR DESCRIPTION
**Pull request by blake**
Add configuration example for path-based HTTP routing with virtual services to Ingress gateway configuration entry documentation.

Resolves #8018

### CODE REVIEW

**Review by freddygv — COMMENTED** [review]
This LGTM.

One suggestion: what if instead of `api_service1` and `api_service2` we used something like `billing` and `payments`?

Making them more distinct might make the example a bit more concrete.

What do you think?

**Comment by jsosulska** [comment]
> This LGTM.
> 
> One suggestion: what if instead of `api_service1` and `api_service2` we used something like `billing` and `payments`?
> 
> Making them more distinct might make the example a bit more concrete.
> 
> What do you think?

I agree with Freddy. Can we instead use `api/v1`,  and `api/v2`, as we use API through the rest of the guide.

Nice use of tabs!

**Comment by blake** [comment]
> One suggestion: what if instead of `api_service1` and `api_service2` we used something like `billing` and `payments`?
> 
> Making them more distinct might make the example a bit more concrete.
> 
> What do you think?

Great suggestion. I updated the examples to use these names, and also modified the backend service name to be DNS friendly.

**Comment by blake** [comment]
> I agree with Freddy. Can we instead use `api/v1`, and `api/v2`, as we use API through the rest of the guide.

I decided to go with the names "billing" and "payments" because I felt it would be more clear that these paths are being proxied to distinct backend services, whereas v1 and v2 seem more appropriate for a traffic splitting example.

**Review by freddygv — APPROVED** [review]
:shipit:

**Pull request merged**
