### PR TITLE
Add Socket check type

### PR DESCRIPTION
**Pull request by pdf**
Adds the ability to simply check whether a socket accepts connections to
determine if it is healthy.  This is a light-weight - though less
comprehensive than scripting - method of checking network service
health.

Two check parameters are used:
- `Socket` should be set to the location of the socket to be tested, for
  example, `example.com:port`, or `/path/to/unix.sock`
- `Network` accepts any network type that the Go net library accepts,
  as documented here: https://golang.org/pkg/net/#Dial

  `Network` defaults to `tcp`

Example check:

```json
{
  "check": {
    "id": "dns-udp",
    "name": "DNS (UDP)",
    "socket": "ns0.example.com:53",
    "network": "udp",
    "interval": "10s"
  }
}
```

No documentation updates yet for this PR, if you're keen to accept this, I'll
take a pass at updating them too.

### CODE REVIEW

**Comment by armon** [comment]
This is interesting. I think it's worth probably just reducing the scope to tcp only. A UDP health check doesn't really make much sense in any case. 

/cc: @ryanuber @slackpad

**Comment by ryanuber** [comment]
Agreed, although we are just passing parameters to `net.Dial`, so not sure if there is any harm. Nonetheless I'd probably accept TCP only as well. We could also then remove the `network` field altogether to make the definition more simple.

Fixes #976.

**Comment by armon** [comment]
I think renaming the check type from "socket" to "tcp" is also more clear (does it support unix domain sockets for example?)

**Comment by pdf** [comment]
I'm particularly not in love with the naming either.  @armon can I ask why a UDP health check doesn't make sense?  It does support UNIX sockets too BTW.

**Comment by pdf** [comment]
Also, I figured that people may wish to check that a service is available explicitly on IPv4 or IPv6 - if we limit it to `tcp`, this can't be done via hostname.

**Comment by ryanuber** [comment]
Hey @pdf,

UDP checks wouldn't entirely make sense because of the connectionless nature of the protocol. You would need to send packets and wait to receive packets in order to determine a successful transmission, which would require specialized logic on the remote end.

We should still be able to check IP4/IP6. Looking at the [`net.Dial`](http://golang.org/pkg/net/#Dial) function, you can see how passing either format of address is accepted.

**Comment by pdf** [comment]
@ryanbreen of course you're correct on UDP, I wasn't thinking.  We could send a packet with no payload though.  WRT IPv6/IPv4, there's no way to check explicitly for one or the other if you also want to check via hostname, without specifying the protocol..

**Comment by pdf** [comment]
Okay, UDP is not going to be possible cross-platform due to lack of datagram ICMP support on Windows, so if we restrict this to TCP, do we care about supporting explicit IPv4 vs IPv6 checks?

If not, I'll change this to use the `tcp` key and probably enable `DualStack` on the `Dial` so that it will try both IPv4 and IPv6 and return success on any result.  If we wanted to support explicit checks by IP proto version, we could add `tcp` (with the aforementioned behaviour), `tcp4` and `tcp6` keys.

The reason I raise the IPv4/IPv6 issue is that it may be important for people to check that a service is available on _both_ IPv6 and IPv4, rather than 'any'.

**Comment by pdf** [comment]
Current version is `tcp` only.

**Comment by armon** [comment]
@pdf This is looking great. Would you mind updating the documentation as well? I think that is all that is missing.

**Comment by pdf** [comment]
Righteo, I think I hit all the documentation points.

**Comment by pdf** [comment]
Eh, don't think my documentation changes broke the tests :wink:

**Comment by Kosta-Github** [comment]
+1

**Comment by armon** [comment]
Looks great, thanks!

**Pull request merged**
