### PR TITLE
Add zsh completion

### PR DESCRIPTION
**Pull request by gkze**

### CODE REVIEW

**Comment by gkze** [comment]
Not sure why the build is failing...

**Comment by ryanuber** [comment]
@gkze the build failing isn't from your changes, so no worries on that front.

This is great! You might want to take a peek at the master branch since there are a number of new commands and arguments going in to the 0.5 release.

**Comment by gkze** [comment]
@ryanuber thanks for the heads up! Added

**Comment by armon** [comment]
Thanks!

**Pull request merged**
