### PR TITLE
docs: Remove Helm 2 mention in Consul K8s install and uninstall

### PR DESCRIPTION
**Pull request by david-yu**
Helm 2 is no longer supported via Consul K8s. Helm 3 is now the supported version for Consul K8s.

### CODE REVIEW

**Review by kschoche — APPROVED** [review]

**Review by thisisnotashwin — APPROVED** [review]
Thank you @david-yu

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/399482.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 0c63a7b4d47399ef54bcf5c567d033ab62d1f94c onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 0c63a7b4d47399ef54bcf5c567d033ab62d1f94c onto `release/1.10.x` succeeded!

**Pull request merged**
