### PR TITLE
docs: Add HCL examples to watch configs

### PR DESCRIPTION
**Pull request by blake**
* Adds HCL configuration examples to Consul watch configs.
* Updates example output for several watch types.

### CODE REVIEW

**Review by karl-cardenas-coding — APPROVED** [review]
👍🏼

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/592651.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit b44fbd3c3ef1585cd1e2b7bdec964207e6f43f87 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit b44fbd3c3ef1585cd1e2b7bdec964207e6f43f87 onto `release/1.11.x` succeeded!

**Pull request merged**
