### PR TITLE
regenerate expired certs

### PR DESCRIPTION
**Pull request by dhiaayachi**
This is to fix CI, by generating a new set of certificates that replace the expired client certificates used for test

### CODE REVIEW

**Review by kisunji — APPROVED** [review]

**Review by rboyer — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/489914.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/490990.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 280178571045c23147ecc2e0834b185b5fd2281b onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 280178571045c23147ecc2e0834b185b5fd2281b onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/490990)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 280178571045c23147ecc2e0834b185b5fd2281b onto `release/1.8.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/490990)

**Pull request merged**
