### PR TITLE
website: fixup incorrect markdown syntax

### PR DESCRIPTION
**Pull request by kylemac**
the bracket/parenthesis link syntax was flipped here

### CODE REVIEW

**Review by karl-cardenas-coding — APPROVED** [review]
Thanks for catching this Kyle

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/443188.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 4b966094ff35f4dc07b5a72f4ff4e84dcc47c779 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 4b966094ff35f4dc07b5a72f4ff4e84dcc47c779 onto `release/1.10.x` succeeded!

**Pull request merged**
