### PR TITLE
Panic for unregistered types

### PR DESCRIPTION
**Pull request by mkeeler**
### Description

If controllers get configured to watch invalid types or otherwise make invalid requests to the resource service, these can go unnoticed (especially for code that is not intended to be finished yet). This PR changes that. Now if a controller would make invalid requests it causes a panic of the whole server. This should cause these issues to surface in other tests which and therefore should block merging of invalid code due to CI failures.

The goal is to catch all of these before code gets merged so that we minimize the impact of any wip code going into main/release branches.

### Testing & Reproduction steps

If you remove the second commit, you can see that the api-gw controller makes invalid requests to the resource service and will cause a server panic.

### CODE REVIEW

**Review by nathancoleman — APPROVED** [review]

**Review by nathancoleman — CHANGES_REQUESTED** [review]
Interestingly, there is a failure in the unit tests brought to light by this change

```log
panic: controller link attempted to initiate an invalid watch: "rpc error: code = InvalidArgument desc = resource type hcp.v2.Link not registered". This is a bug within the controller.
```

**Review by jm96441n — APPROVED** [review]
LGTM, there's a few failing tests but those look more like flakes than actual failures

**Comment by mkeeler** [comment]
The `go-test` failures are legit. Now that I fixed the test server to register all the types, there is a golden file based test which looks at all controller dependencies and emits a mermaid diagram of all the v2 type dependencies.

**Comment by mkeeler** [comment]
I found a couple more places that were inadvertently running controllers without having registered their dependent types.

🤞 that I got all the places and CI will pass

**Review by nathancoleman — APPROVED** [review]
Nice addition! Thanks for working through adding this 🏅

**Pull request merged**
