### PR TITLE
ui: Move action to the correct button for session invalidation

### PR DESCRIPTION
**Pull request by johncowen**

### CODE REVIEW

**Review by kaxcode — APPROVED** [review]
👍

**Comment by johncowen** [comment]
Found out that the `refresh-route` is not needed at all here, so I removed it.

Also checked to make sure this has no real change for users (it worked fine before this change and continues to with this change applied). The change here is just because, as the UI is now more robust these little mistakes that previously didn't manifest themselves in tests now do, which is a win for everybody.

Following that, I decided a changelog wasn't required here.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/456090.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit e59b8ffc172aed3d2fa7028217893432a34210f5 onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit e59b8ffc172aed3d2fa7028217893432a34210f5 onto `release/1.9.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit e59b8ffc172aed3d2fa7028217893432a34210f5 onto `release/1.8.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/456090)

**Pull request merged**
