### PR TITLE
Fix caveat about resolvers operating at L4

### PR DESCRIPTION
**Pull request by freddygv**
Service resolvers can specify L4 rules such as redirects, or L7 rules such as
hash-based load balancing policies.

### CODE REVIEW

**Review by rboyer — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/495919.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 5e7eb85f2ad68545e922e4ac58b9aab72e614196 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 5e7eb85f2ad68545e922e4ac58b9aab72e614196 onto `release/1.10.x` succeeded!

**Pull request merged**
