### PR TITLE
adding metrics to track status of agent side health checks (any, unkn…

### PR DESCRIPTION
**Pull request by ophiradi**
…own, passing, warn critical)

### CODE REVIEW

**Comment by slackpad** [comment]
Hi @ophiradi - thanks for the PR. These metrics will be a little unusual because they have the configuration-dependent name in them, so some people could end up with a ton of new metrics. Right now there's a relatively stable/fixed set of metrics and not much in there that's dependent on user-configured values, so it's a simple interface.

Can you describe how you want to use these in a little more detail? Maybe there's another way to get that data without adding a bunch of new metrics.

**Comment by victortrac** [comment]
Hi @slackpad, Consul is already emitting configuration-specific metrics here:
https://github.com/hashicorp/consul/blob/master/consul/health_endpoint.go#L101

As for the PR from @ophiradi, we are interested in graphing historical health-check passes/failures from consul's perspective on a service-by-service basis. It would be another source to alert from when our failures go above a certain rate or to be able to see another measure of quality over time.

**Comment by slackpad** [comment]
Ok - I see. How about reducing the granularity from check id to service name? This would be more on par the the other use you found.

**Comment by slackpad** [comment]
Hi @ophiradi any thoughts on just using service name?

**Comment by slackpad** [comment]
Going to close this one out - please open another PR if you are interested in pursuing this.

**Pull request closed without merging**
