### PR TITLE
URL-encode/decode resource names for HTTP API part 3

### PR DESCRIPTION
**Pull request by dttung2905**
## Overview
This MR continues to fix the issue in #11258 (part 3)

### CODE REVIEW

**Comment by dttung2905** [comment]
Hi @kisunji ,could you help taking a look at this ?

**Review by kisunji — DISMISSED** [review]
Thank you for another contribution! Could you remove the changelog entry? We'd like to add one closer to next release summarizing all the changes around url-encode/decoding

**Review by kisunji — CHANGES_REQUESTED** [review]
Oops, I missed a step. For each endpoint you update here, could you please look at the corresponding call in the `api` package?

For example, `"/v1/event/fire/"` gets called in `api/event.go` in this line 
```go
r := e.c.newRequest("PUT", "/v1/event/fire/"+params.Name)
```
which should encode the name

**Comment by dttung2905** [comment]
Hi @kisunji, do the two failed tests ; `TestAPI_SemaphoreMonitorRetry` and `TestAPI_SemaphoreMonitorRetry` seem related to this commit to you ? I checked out the latest remote master branch and ran the test locally, but still encounter the same failed tests [link](https://app.circleci.com/pipelines/github/hashicorp/consul/26333/workflows/eec5920a-3e89-4171-906d-c9c35b693b02/jobs/560206/tests#failed-test-1)

**Comment by kisunji** [comment]
> Hi @kisunji, do the two failed tests ; `TestAPI_SemaphoreMonitorRetry` and `TestAPI_SemaphoreMonitorRetry` seem related to this commit to you ? I checked out the latest remote master branch and ran the test locally, but still encounter the same failed tests [link](https://app.circleci.com/pipelines/github/hashicorp/consul/26333/workflows/eec5920a-3e89-4171-906d-c9c35b693b02/jobs/560206/tests#failed-test-1)

Will take a look!

**Comment by kisunji** [comment]
Hmm it looks like one of your changes has affected a test. Will look deeper into this but may not get back to you until next week

**Comment by dttung2905** [comment]
Just a litle update. I was able to trace back to the changes that fails the CI test and reverted it in the latest commit

**Comment by kisunji** [comment]
Hey @dttung2905, thank you for investigating.

I think you may have uncovered a bug (actually my misunderstanding) with our path escaping (cc @jkirschner-hashicorp):
We SHOULD NOT escape arguments in the `api` package.

```
c.doRequest(r)
// calls
req, err := r.toHTTP()
            ^^^
// calls
req, err := http.NewRequest(r.method, r.url.RequestURI(), r.body)
                                            ^^^
```

It turns out that `(*URL).RequestURI` actually [escapes the path](https://cs.opensource.google/go/go/+/refs/tags/go1.17.6:src/net/url/url.go;l=1139) already.

This means that we are double-escaping URLs in the `api` package, but have not caught any errors until now because 1) we never published new versions of `api`; 2) we haven't run tests in module `consul` which depended on our updated `api` until now (the KV get/set is used heavily).

```
# test string "@#(*SADF/%"

# with url.PathEscape
[DEBUG] agent.http: Request finished: method=GET url=/v1/kv/@%2523%2528%252ASADF%252F%2525 from=127.0.0.1:64873 latency=107.959µs

# without url.PathEscape
[DEBUG] agent.http: Request finished: method=GET url=/v1/kv/@%23%28%2ASADF/%25 from=127.0.0.1:65057 latency=94.57µs


```

I will submit a separate PR to remove any previously merged URL escapes; @dttung2905 could you revert the changes to `api` in this PR as well?

Apologies for making you go back and forth; this was a lesson learned on my part and I'm glad you helped us catch it sooner than later 😱

**Comment by dttung2905** [comment]
Thanks for the detailed explanation. I think I get it now :100: Let me revert the changes and update you later tomorrow. Its midnight here in Singapore

**Comment by dttung2905** [comment]
Hi @kisunji, I have reverted the code to the previous commit.

2 of the intergration tests are still failed because the CI task failure to get docker engine assignment. Could you help triggering those CI task again? if not, I can add a dummy commit too

**Comment by kisunji** [comment]
Great @dttung2905, I think this is mergeable now. I think CircleCI is having failures allocating containers to run tests so hopefully it should be resolved soon. I'll re-run the tests and merge when things are green!

**Review by kisunji — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/566613.

**Pull request merged**
