### PR TITLE
Include the Web UI in the consul binary

### LINKED ISSUE #1220: Compile UI assets into the Consul binary
We can use (https://github.com/jteeuwen/go-bindata) to compile the UI assets into the binary. We should still support the `-ui-dir` option, but now we can just have a `-ui` flag to enable the compiled in version. This makes distributing even simpler.

### PR DESCRIPTION
**Pull request by rgl**
This is to close #1220. I'm not sure if I should have named the internal variable `EnableUi` instead of `Ui`. Let me known and I'll change it.

### CODE REVIEW

**Comment by ryanbreen** [comment]
This is really cool!

I think `EnableUi` would be a better match with similar bools in `config.go`.

Also, please add documentation for this setting to `website/source/docs/agent/options.html.markdown`.

**Comment by rgl** [comment]
I've re-updated the PR! Though, this is still missing the dependencies on https://github.com/jteeuwen/go-bindata and https://github.com/elazarl/go-bindata-assetfs; also, the travis build file needs to be changed to install the bundler gem and install the needed Web UI dependencies. how should I do it?

**Comment by rgl** [comment]
I've added the dependencies installation. The travis build is now failing due to some failing test. I think its not really related to my change.

**Comment by slackpad** [comment]
Hi @rgl thanks for the PR! Once we get Consul 0.6 rolled out I'll help review this and get it in for the following release.

**Comment by ryanuber** [comment]
Hey @rgl, this definitely looks good. I started the same thing in a branch (see [here](https://github.com/hashicorp/consul/compare/f-ui-static?expand=1)) before I realized you had already done this. If you want to finish this up I'll just close out my branch.

One idea, let's try to avoid the hard requirement on ruby/bundler and compiling the web UI assets in the typical build pipeline for Consul. The UI very rarely changes so I think we should just have a separate make target like `static-assets` to update the bindata_assetfs file and check in the `bindata_assetfs.go` file. You can see the linked branch for an example.

**Comment by rgl** [comment]
I would like to finish it up. I think that always generating the file is better for early catching build errors. But I can implement it either way. Lets see what @ryanbreen and @slackpad have to say.

**Comment by slackpad** [comment]
Yeah I'd go with @ryanuber's suggestion and just check in the go file - adding Ruby/bundler to the default build path is pretty heavy so this'll keep things fast and simple for most people who aren't updating the web UI.

**Comment by rgl** [comment]
Seems fair. As the @ryanuber branch already has that done, I'll retract this PR.

**Pull request closed without merging**
