### PR TITLE
remove Codecov from CI runs

### PR DESCRIPTION
**Pull request by chair6**
See https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512/2 for context.

### CODE REVIEW

**Review by mikemorris — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/358507.

**Comment by dnephin** [comment]
We run CI on every release branch, so to fully apply this we need to backport it. Let's see if the automated backport works.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/358741.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 8fc62cb87f83cfa46018df4ecc097d2e97ef23ea onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 8fc62cb87f83cfa46018df4ecc097d2e97ef23ea onto `release/1.9.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 8fc62cb87f83cfa46018df4ecc097d2e97ef23ea onto `release/1.8.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/358741)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 8fc62cb87f83cfa46018df4ecc097d2e97ef23ea onto `release/1.7.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/358741)

**Pull request merged**
