### PR TITLE
docs: Fix spelling errors across website

### PR DESCRIPTION
**Pull request by blake**
This change fixes a number of spelling errors I found across various documentation pages.

### CODE REVIEW

**Review by david-yu — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/412472.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 832896ed112b14b19a5abd603e8ebcb8e58773d7 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 832896ed112b14b19a5abd603e8ebcb8e58773d7 onto `release/1.10.x` succeeded!

**Pull request merged**
