### PR TITLE
Respect tokens in maintenance mode

### LINKED ISSUE #1223: consul `maint` being blocking by ACLs
In the default-deny setup, it seems `consul maint` is not able to make progress even with the correct ACL tokens that have write permissions. Errors also occur on the server side for this.

/cc: @ryanuber @sean-

### PR DESCRIPTION
**Pull request by ryanuber**
ACL tokens now get threaded through during check registration for maint mode. Fixes #1223

### CODE REVIEW

**Comment by ryanbreen** [comment]
:+1:

**Comment by slackpad** [comment]
LGTM

**Comment by slackpad** [comment]
Picked this up when @sfncook rebased and built #1187 - @ryanuber I think we missed a couple spots:

```
command/maint_test.go:48: not enough arguments in call to a1.agent.EnableServiceMaintenance
command/maint_test.go:53: not enough arguments in call to a1.agent.EnableNodeMaintenance
```

**Comment by slackpad** [comment]
I'm testing a fix and I'll PR.

**Comment by sfncook** [comment]
@slackpad - Actually I hadn't done a rebase/merge from the master branch for a while.  Just did so and pushed to my PR #1187 It's building now.

**Pull request merged**
