### PR TITLE
Update service-defaults - Complete configuration 

### PR DESCRIPTION
**Pull request by joomn11**
### Description

fix misconfiguration of service-defaults Complete configuration

### PR Checklist

* [x] updated test coverage
* [x] external facing docs updated
* [x] appropriate backport labels added
* [x] not a security concern

### CODE REVIEW

**Comment by joomn11** [comment]
fix misconfiguration of service-defaults Complete configuration

**Comment by joomn11** [comment]
hi, @boruszak 
i want to merge this pr 
but vercel check task is not passed , i think i need to skip that task.
can you show me how to skip that check task ?

**Comment by david-yu** [comment]
@joomn11 Do you have an example of working service-defaults? We want to double check if this is correct prior to merging.

**Comment by joomn11** [comment]
hi, @david-yu 
i am using json format of service-defaults

```
/ # consul config read -kind service-defaults -name echo
{
    "Kind": "service-defaults",
    "Name": "echo",
    "Protocol": "http",
    "TransparentProxy": {},
    "MeshGateway": {},
    "Expose": {},
    "UpstreamConfig": {
        "Defaults": {
            "Protocol": "http",
            "ConnectTimeoutMs": 5000,
            "PassiveHealthCheck": {
                "Interval": 10000000000,
                "MaxFailures": 1,
                "BaseEjectionTime": 10000000000
            },
            "MeshGateway": {
                "Mode": "local"
            }
        }
    },
    "CreateIndex": 4685452,
    "ModifyIndex": 4685452
}
```

in json format , service-default
i changed location of "UpstreamConfig.Defaults" location
it should be inside of " UpstreamConfig" block , but it was outside of "UpstreamConfig" 

and in hcl format, service-default
"UpstreamConfig.Overrides" is should be multi block

**Pull request closed without merging**
