### PR TITLE
nia/docs 0.2.0

### PR DESCRIPTION
**Pull request by lornasong**

### CODE REVIEW

**Review by findkim — APPROVED** [review]
🛳️

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/393000.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit edc41c9e47893eca10b36054c62c2adb82e9d6a2 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit edc41c9e47893eca10b36054c62c2adb82e9d6a2 onto `release/1.10.x` succeeded!

**Pull request merged**
