### PR TITLE
Update install.mdx

### PR DESCRIPTION
**Pull request by Petenerd**
missing a quote escape

### CODE REVIEW

**Review by kisunji — APPROVED** [review]

**Review by jkirschner-hashicorp — COMMENTED** [review]
Submitting a review to see if it allows me to authorize the `vercel` preview of the docs page.

**Comment by karl-cardenas-coding** [comment]
> Submitting a review to see if it allows me to authorize the `vercel` preview of the docs page.

Due to the PR coming from a forked branch, the Vercel actions will not trigger.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/610854.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 4f1bfeaf339e3870eb9de55677618e1969e90b43 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 4f1bfeaf339e3870eb9de55677618e1969e90b43 onto `release/1.11.x` succeeded!

**Pull request merged**
