### PR TITLE
connect: Add Envoy 1.21.1 to support matrix, remove 1.17.4

### PR DESCRIPTION
**Pull request by eculver**
Envoy 1.21.1 was released at the end of February. This adds it to our test matrix and removes 1.17.4.

### CODE REVIEW

**Review by rboyer — APPROVED** [review]
LGTM. Needs a changelog entry.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/639410.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 881e17fae1604f0431ad9a0f70397c8eadc7f837 onto `stable-website` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/639410)

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 881e17fae1604f0431ad9a0f70397c8eadc7f837 onto `release/1.12.x` succeeded!

**Pull request merged**
