### PR TITLE
Use KV store to generate responses to DNS queries

### PR DESCRIPTION
**Pull request by danielrowles-wf**
Consul DNS server can now be configured to query KV store to generate responses to DNS queries.

### CODE REVIEW

**Comment by danielrowles-wf** [comment]
I've run the 'integ' tests locally several times and they seem to pass ok. Can anyone suggest what the issue might be when they are run under Travis?

**Comment by armon** [comment]
Let's actually create a thinking / enhancement ticket + Google Docs for this. There is a lot more nuance to consider before merging this.

**Comment by ryanuber** [comment]
This is an interesting idea. I think if we were to support setting custom DNS records, we would want to have a first-class API for doing CRUD operations on them. I agree with @armon, there are going to be numerous edge cases we should think about.

**Comment by teaforthecat** [comment]
The ability to scope the dns requests to subset of keys is a neat feature.  It may be nice if the kv store only responded to TXT requests, then this would fix in better with the rest of the dns interface, limiting overlap or confusion. I'm looking forward to this feature to swap out an existing solution. - Thanks

**Comment by teaforthecat** [comment]
The ability to scope dns requests to a certain key set is a nice feature. It may be nice if the dns kv lookup only responded to TXT requests, then it would fit in better with the rest of the service, removing conflicts or confusion. I'm looking forward to this feature to swap out an existing solution. Thanks

**Comment by slackpad** [comment]
Closing this out in favor of working through the details in an issue per https://github.com/hashicorp/consul/pull/815#issuecomment-86149942.

**Pull request closed without merging**
