### PR TITLE
Fix issue #1221

### PR DESCRIPTION
**Pull request by alistanis**
This was the only place I could find that might be affected by a sudden shutdown during a write. If there are any I've missed, please let me know and I'll add them to this PR.

### CODE REVIEW

**Comment by multani** [comment]
You may want to reconsider the formatting changes in your commits! :)

**Comment by slackpad** [comment]
Hi @alistanis sorry for the delay on this. Can you please rebase and run `go fmt` on your changes? Thanks!

**Comment by alistanis** [comment]
@slackpad No problem! I'll take care of this tonight when I get home. I always run go fmt (or goimports) so I'm not totally sure what happened. 

Also thanks @multani, looks like I missed your comment the first time around.

**Comment by kyhavlov** [comment]
Fixed in #2480

**Pull request closed without merging**
