### PR TITLE
Support SesionTTLMin configuration

### PR DESCRIPTION
**Pull request by fraenkel**
- Allow setting SessionTTLMin
- Validate on the Server

### CODE REVIEW

**Comment by fraenkel** [comment]
Solves #796

**Comment by ryanuber** [comment]
This looks great! Thanks for tackling this. We just need another test for the config merging, and some supporting documentation, and with that I think we'll be ready to merge. Feel free to add that, or let me know and I'll be happy to wrap this up as well.

**Comment by fraenkel** [comment]
Updated with MergConfig support.

I will let you handle the supporting documentation. I wasn't sure if we wanted to go further and allow tweaking the Max and Multiplier but now at least we know all the spots if and when we do.

**Comment by ryanuber** [comment]
Thanks!

**Pull request merged**
