### PR TITLE
Fix logfile filter bug

### PR DESCRIPTION
**Pull request by dsouzajude**
Fixes the issue where when logging to file, it does not respect the log level filters. This PR fixes it by filtering out logs not matching the log level criteria.

Addressed issue: https://github.com/hashicorp/consul/issues/4778

### CODE REVIEW

**Comment by varnson** [comment]
I am sorry for I do not know the source well, but I am worried about Line:
filt.MinLevel = logutils.LogLevel("INFO").
And the test is also about Level INFO.
 I am not sure is it work well for Level DEBUG or ERROR?

Very thanks to dsouzajude, and very sorry if I misunderstand the source.
Thanks to dsouzajude again.

**Comment by dsouzajude** [comment]
Hi @varnson, i'm not sure i fully understand your point, but there is a test case [here](https://github.com/hashicorp/consul/blob/a85deba4aa001081931ee520869875646ec41392/logger/logfile_test.go#L68-L84) that tests the log filtering. If you set the `filt.MinLevel = logutils.LogLevel("INFO")` it will not log DEBUG level logs. You can have a look at that test case and maybe comment on those specific lines inside the PR if there is something that doesn't look right.

**Comment by dsouzajude** [comment]
Hi, looking forward for feedback, would really like this merged. It's been almost a week. Thanks!

**Comment by pearkes** [comment]
@dsouzajude thanks for your patience, we do want to provide feedback and land this fix, we're tracking it for our next release. 😄

**Comment by dsouzajude** [comment]
Thanks @freddygv for your comments/improvements. I've made the necessary changes to the test file. Let me know if you have  further comments.

**Pull request merged**
