### PR TITLE
add support for specifying custom policies with Auto Config

### LINKED ISSUE #11865: Auto Config with custom policies
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description

Assign custom policies to token generated with Auto Config.

Something like :

```
[…]
"auto_config": {
        "enabled": true,
        "intro_token_file": "/etc/consul/jwt",
+      "policy": "example",
        "server_addresses": [  
            "192.0.2.1",                                                             
            "192.0.2.2",        
            "192.0.2.3"
        ]                    
    },
[…]
```

#### Use Case(s)

Being able to deploy a client node with an auto config token linked to a specific policy (with DNS capabilities for example)

### PR DESCRIPTION
**Pull request by kevinschoonover**
closes #11865

I am not sure familiar with how the consul codebase works so I'm interested in any feedback / improvements / things I missed that I can change to help make this feature possible.

For security, this feature requires the user to specify [a custom claim_mapping](https://github.com/hashicorp/consul/pull/12783/files#diff-1d1f4987a6def6325e50a6992400d4382b696511662ec1482aa2808ba076f168R23-R24) in their server configuration which looks like

```hcl
auto_config {
  authorization {
    enabled = true

    static {
      claim_mappings {
        "http://consul.internal/allowedACLPolicy" = "allowed_acl_policy" # < here
      }
    }
  }
}

acl {
  enabled        = true
  default_policy = "allow"
}
```

When combined with the client sending the folowing JWT payload
```json
{
  "aud": "<AUD>",
  "exp": 1650473203,
  "http://consul.internal/allowedACLPolicies": [
    "consul-client"
  ],
  "iat": 1650430003,
  "iss": "<ISS>",
  "namespace": "root",
  "sub": "<SUB>"
}
```

and matching `policy` field
```hcl
auto_config {
  enabled          = true
  policy           = "consul-client"
  intro_token_file = "jwt"
  server_addresses = ["localhost:8300"]
}
```

the server will append the requested policy to the generated ACL token. If 
1. the server doesn't have the `allowed_acl_policy` mapping
2. the value mapped by the payload doesn't match the `policy` field in the client configuration

the auto_config request will be rejected

TODO:
- [x] update documentation to include the claim mapping authorization strategy
- [x] add tests for requested policy == custom claim mapping

### CODE REVIEW

**Comment by Amier3** [comment]
Hey @kevinschoonover 

Thanks for this contribution! This would be a great improvement IMO. We have a release coming up this week, so just a heads up we might not be able to take a look at this till next week.

**Comment by kevinschoonover** [comment]
Hey @Amier3, thanks for the heads up! Will give me time to make a toggle to enable this since there are potentially security implications so it should probably be disabled by default.

Future work on this can likely tie allowed roles to claims in the jwt.

**Comment by kevinschoonover** [comment]
Okay, everything should be plumbed in as far as tests go. One thing I could use help on when the reviewer has a chance to take a look at is the following failing test:

```
$ go test -test.run TestAutoConfigInitialConfiguration
[INFO] freeport: blockSize 1500 too big for system limit 1024. Adjusting...
[INFO] freeport: detected ephemeral port range of [32768, 60999]
[INFO] freeport: reducing max blocks from 30 to 22 to avoid the ephemeral port range
2022-04-21T18:45:40.910-0700 [WARN]  TestAutoConfigInitialConfiguration-node-1.server.rpc: Non-TLS connection attempted with VerifyIncoming set: conn=from=127.0.0.1:42882
2022-04-21T18:45:41.281-0700 [WARN]  TestAutoConfigInitialConfiguration-node-1.server.raft: heartbeat timeout reached, starting election: last-leader=
2022-04-21T18:45:41.310-0700 [ERROR] TestAutoConfigInitialConfiguration-node-1.server.autopilot: Failed to reconcile current state with the desired state
2022-04-21T18:45:41.341-0700 [ERROR] TestAutoConfigInitialConfiguration-node-1.server.rpc: INSECURERPC error: conn=from=127.0.0.1:42884 error="rpc: can't find service ACL.PolicySet"
2022-04-21T18:45:41.341-0700 [WARN]  TestAutoConfigInitialConfiguration-node-1.server.serf.lan: serf: Shutdown without a Leave
2022-04-21T18:45:41.341-0700 [ERROR] TestAutoConfigInitialConfiguration-node-1.server: error performing anti-entropy sync of federation state: error="shutdown waiting for leader"
2022-04-21T18:45:41.344-0700 [WARN]  TestAutoConfigInitialConfiguration-node-1.server.serf.wan: serf: Shutdown without a Leave
--- FAIL: TestAutoConfigInitialConfiguration (0.47s)
    auto_config_endpoint_test.go:220:
        	Error Trace:	auto_config_endpoint_test.go:220
        	Error:      	Received unexpected error:
        	            	rpc: can't find service ACL.PolicySet
        	Test:       	TestAutoConfigInitialConfiguration
FAIL
exit status 1
FAIL	github.com/hashicorp/consul/agent/consul	0.478s
```

I think whats happening is when I try to upsert the test policy

https://github.com/hashicorp/consul/pull/12783/commits/b15ac770300febfaadb61056f7ea9413c3367631#diff-9c03ca652327e8f06f313ae9cc4a035a2feb2c41f6b010b168109e9dab69b0d6R219-R220

the codec isn't properly authenticated to consul and as a result cannot create the policy or see the endpoint? Its a little unclear to me. Will do some more digging later after I add the documentation

**Comment by jkirschner-hashicorp** [comment]
Hi @kevinschoonover,

Thank you for contributing this PR for consideration! 

I'm a product manager on the Consul team who's been investigating potential improvements to Consul's user experience around the ACL system.

Before deciding how to move forward on this proposed change to auto-config UX, I'd like to discuss with you this proposed approach, the ACL experience(s) that led you to work on it, and other options you considered. If you're interested, please contact me using the info in my [Github profile](https://github.com/jkirschner-hashicorp) or by [filling out this brief form](https://hashicorp.sjc1.qualtrics.com/jfe/form/SV_b7cNuNBMrPr4b8q) (in the "Other" box you can reference consul#12783).

I've also reached out to the poster of https://github.com/hashicorp/consul/issues/11865 to further explore their perspective. I want to make sure the Consul team understands the root of what the issue/PR want to improve so we can weigh in on the best enhancement approach.

**Pull request closed without merging**
