### PR TITLE
docs: use correct previous name of recovery token

### PR DESCRIPTION
**Pull request by jkirschner-hashicorp**

### CODE REVIEW

**Review by boxofrad — APPROVED** [review]
Great catch! 👏🏻

**Review by trujillo-adam — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/657062.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit cf12f8af20aed3e85f379ab7da69335aefb9b2fc onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit cf12f8af20aed3e85f379ab7da69335aefb9b2fc onto `release/1.12.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit cf12f8af20aed3e85f379ab7da69335aefb9b2fc onto `release/1.11.x` succeeded!

**Pull request merged**
