### PR TITLE
docs: correct website documentation typo

### PR DESCRIPTION
**Pull request by kiambogo**

### CODE REVIEW

**Review by blake — APPROVED** [review]
Thanks for fixing this!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/368251.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit a7d96bb546bccb49eaa6effb9ee04abb0018f90d onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit a7d96bb546bccb49eaa6effb9ee04abb0018f90d onto `release/1.10.x` succeeded!

**Pull request merged**
