### PR TITLE
connect: ensure proxy-defaults protocol is used for upstreams

### PR DESCRIPTION
**Pull request by rboyer**
Fixes https://github.com/hashicorp/consul/issues/7859

### CODE REVIEW

**Comment by rboyer** [comment]
FYI: If we want to backport this to 1.6 or 1.5 I suspect the patch won't apply cleanly mostly due to namespace refactoring.

**Comment by david-yu** [comment]
Based on the official support policy, we should backport to 1.7 and 1.6.

**Comment by crhino** [comment]
I feel like I am missing something here, but when I tried out your reproduction steps I still got a `envoy.tcp_proxy` filter for the `web` upstream.

```
$ consul -v
Consul v1.7.0-727-g7e1310e02-dev (7e1310e02)
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

$ cat proxy-defaults.hcl
kind = "proxy-defaults"
name = "global"
config {
  protocol = "http"
}
$ consul config write proxy-defaults.hcl

$ cat foo.hcl
service {
  name = "foo"
  port = 8888

  connect {
    sidecar_service {
      proxy {
        upstreams = [
          {
            destination_name = "web"
            local_bind_port  = 5000
          },
        ]
      }
    }
  }
}

$ consul services register foo.hcl

$ consul connect envoy -sidecar-for foo

$ curl localhost:19000/config_dump
...
    {
     "name": "web:127.0.0.1:5000",
     "active_state": {
      "version_info": "00000001",
      "listener": {
       "@type": "type.googleapis.com/envoy.api.v2.Listener",
       "name": "web:127.0.0.1:5000",
       "address": {
        "socket_address": {
         "address": "127.0.0.1",
         "port_value": 5000
        }
       },
       "filter_chains": [
        {
         "filters": [
          {
           "name": "envoy.tcp_proxy",
           "config": {
            "stat_prefix": "upstream_web_tcp",
            "cluster": "web.default.dc1.internal.d06b74e9-a91e-6e29-aca2-10ef9c382d0c.consul"
           }
          }
         ]
        }
       ]
      },
      "last_updated": "2020-05-21T15:48:56.116Z"
     }
    }
...
```

**Comment by rboyer** [comment]
You need to enable this as well (it's not activated in dev mode): https://www.consul.io/docs/agent/options#enable_central_service_config

**Pull request merged**
