### PR TITLE
Coordinates: allow configuring the update rate

### PR DESCRIPTION
**Pull request by Aestek**
Allow to tune the coordinate update rate to reduce the load on the
servers for large datacenters.

### CODE REVIEW

**Comment by slackpad** [comment]
This is auto scaled based on the size of the cluster over in https://github.com/hashicorp/consul/blob/master/agent/agent.go#L1710 and batched on the server in https://github.com/hashicorp/consul/blob/master/agent/consul/coordinate_endpoint.go#L55-L153, so we tried hard to not need to tune this :-) Were you seeing a pathological heavy write case from coordinates?

**Comment by pierresouchay** [comment]
@slackpad We are trying to limit as much the writes on our large clusters (6k+ nodes) since the leader has much to do and using 100% of CPU sometimes for long duration, we we are trying to tune not used features (such as coordinates we don't really use for now)

**Comment by slackpad** [comment]
I see. I think you can just turn off coordinates if you aren't using them:

https://github.com/hashicorp/consul/blob/master/agent/config/config.go#L198

**Comment by pierresouchay** [comment]
> I see. I think you can just turn off coordinates if you aren't using them:
> 
> https://github.com/hashicorp/consul/blob/master/agent/config/config.go#L198

Yes, you're might be right, it might be simpler

**Comment by pierresouchay** [comment]
@slackpad this one is probably not a big deal, we can live without it especially with `DisableCoordinates`, but https://github.com/hashicorp/consul/pull/5873 might be interesting to reduce a bit the load on leader server

**Pull request closed without merging**
