### PR TITLE
Retry periodically for 60s if syslog setup fails

### LINKED ISSUE #1610: Consul fails to start with Unix syslog delivery error
Seeing this error occasionally starting consul:

```
consul: ==> Syslog setup failed: Unix syslog delivery error
```

This is with consul 0.6.1.

### PR DESCRIPTION
**Pull request by kyhavlov**
Fixes #1610

### CODE REVIEW

**Comment by slackpad** [comment]
LGTM

**Comment by DamionWaltermeyer** [comment]
This seems to still exist in 0.7.2. 

Never actually finds syslog and exits.    

==> Syslog setup error: Unix syslog delivery error
==> Retrying syslog setup in 5s...
==> Syslog setup error: Unix syslog delivery error
==> Syslog setup did not succeed within timeout (1m0s).

**Comment by slackpad** [comment]
Hi @DamionWaltermeyer is that reproducible for you or do you just see that occasionally?

**Comment by DamionWaltermeyer** [comment]
Very reproducible.  I'm using your dockerfile.  If I don't declare -dev, it happens.  

I've been giving it a shot adding and removing bits of CMD, but right now:
CMD  ["agent", "-dev", "-ui", "-client=0.0.0.0", "-bind=0.0.0.0", "-server","-datacenter=OurDataCenterName","-encrypt=myKeyData=="]
 
I'm trying to pair it with nginx-proxy and docker-gen to handle the ssl traffic, so I'm creating the container with this following.

docker create --name consul-server    -e VIRTUAL_HOST=OurVirtualHostName  -e VIRTUAL_PORT=8500    consul-server
I had some volumes at one point, but it didn't seem to make any difference in the troubleshooting of the issue.

I tried declaring things through the commandline, but they didn't seem to take, we have consul running as our central server/ui well on the host using a config file that meets our needs, but I'm having trouble getting it running in the container, I think if I could get past the syslog part, and figure out how to properly declare the IP for inside the container so other instances would know how to reach out to it's api, I'd be all set. 

Ubuntu 14.04 is the host system
Docker
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 64
 Dirperm1 Supported: false
Logging Driver: syslog

**Comment by kyhavlov** [comment]
@DamionWaltermeyer If you're running Consul inside a container, you probably don't want to enable syslog; it won't work unless you set up one inside the same container, which is more complicated than having docker itself send the container's logs to syslog: https://docs.docker.com/engine/admin/logging/overview/#/syslog-options.

For your second point about IPs, you probably want to look into the `--link` option or docker's network stuff, depending on your case.

**Pull request merged**
