### PR TITLE
ui: change coloring of secondary navigation elements

### PR DESCRIPTION
**Pull request by johncowen**
Following our branding update, we noticed that the new `rose` color we use as a highlight on our secondary nav/tabs looked a little weird next to our `red-500` which we use quite a lot. Considering current `structure` uses a `blue-500` for the highlight for the tabs, we took the opportunity to bring our tab coloring into line with that. This was a one line change here https://github.com/hashicorp/consul/pull/10259/files#diff-e0f0d30e1061b08e14e2c0c0ad168b4ce7fc4c638576abbb7893df5777433590L16, but we also:

1. Added a gray bottom border to the tabs whilst hovering (something else I noticed we we differed slightly from current `structure`)
2. Moved all the grays to use CSS properties rather than SASS variables now we have those (confusing _only all our grays_ are currently back to CSS properties)
3. I removed a top border that a realized we no longer need and we overwrite here: https://github.com/hashicorp/consul/blob/7dc78b39c9c5f5120619e70ba168a2d5c12081f2/ui/packages/consul-ui/app/styles/components/app-view/skin.scss#L26-L31 (theres a upcoming PR (https://github.com/hashicorp/consul/pull/10265) to remove that also now we don't need it)
4. Added docs for `TabNav` and noted that it's due for an overhaul since I think it's the first component we ever had.

tabs

### CODE REVIEW

**Review by kaxcode — APPROVED** [review]
🎨 LGTM

**Comment by johncowen** [comment]
Guessing the 1.9.x backport here needs to go in after https://github.com/hashicorp/consul/pull/10090 so I'm gonna wait on that before merging this so it auto backports.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/372958.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit dd4a66808da1aead8e4ef1e29261d540116d01f2 onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit dd4a66808da1aead8e4ef1e29261d540116d01f2 onto `release/1.9.x` succeeded!

**Comment by johncowen** [comment]
Quick note here, the auto backport to 1.9.x was reverted see ^ ( #10284 )

**Pull request merged**
