### PR TITLE
Check to see why a lock acquisition failed

### LINKED ISSUE #1006: Lock command performs very differently with one/multiple max lock holders
When running multiple `consul lock` commands at the same time with a command that completes almost instantly, there can be up to a 5 second delay until the next client obtains the lock (except the 2nd one, which appears to always happen immediately after the first). It takes ~30 seconds to run `date` 8 times.

`consul lock test date`

```
Fri Jun  5 11:04:15 EDT 2015
Fri Jun  5 11:04:15 EDT 2015
Fri Jun  5 11:04:20 EDT 2015
Fri Jun  5 11:04:25 EDT 2015
Fri Jun  5 11:04:30 EDT 2015
Fri Jun  5 11:04:35 EDT 2015
Fri Jun  5 11:04:40 EDT 2015
Fri Jun  5 11:04:45 EDT 2015
```

With a 1 second sleep added, it takes ~17 seconds to run the command 8 times:

`consul lock test 'sleep 1 && date'`
```
Fri Jun  5 11:02:53 EDT 2015
Fri Jun  5 11:02:54 EDT 2015
Fri Jun  5 11:02:58 EDT 2015
Fri Jun  5 11:02:59 EDT 2015
Fri Jun  5 11:03:03 EDT 2015
Fri Jun  5 11:03:04 EDT 2015
Fri Jun  5 11:03:05 EDT 2015
Fri Jun  5 11:03:10 EDT 2015
```

If the command take ~5 seconds instead of finishing instantly, the lock appears to transfer instantly as expected.

`consul lock test 'sleep 5 && date'`
```
Fri Jun  5 11:09:38 EDT 2015
Fri Jun  5 11:09:43 EDT 2015
Fri Jun  5 11:09:48 EDT 2015
Fri Jun  5 11:09:53 EDT 2015
Fri Jun  5 11:09:58 EDT 2015
Fri Jun  5 11:10:03 EDT 2015
Fri Jun  5 11:10:08 EDT 2015
Fri Jun  5 11:10:13 EDT 2015
```

However, when running with `-n 2`, the next client obtains the lock as soon as another command finishes, with no delays.

`consul lock -n 2 test date`
```
Fri Jun  5 11:04:58 EDT 2015
Fri Jun  5 11:04:58 EDT 2015
Fri Jun  5 11:04:58 EDT 2015
Fri Jun  5 11:04:58 EDT 2015
Fri Jun  5 11:04:58 EDT 2015
Fri Jun  5 11:04:58 EDT 2015
Fri Jun  5 11:04:58 EDT 2015
Fri Jun  5 11:04:58 EDT 2015
```

I'm assuming it's related to the algorithm differences mentioned in https://www.consul.io/docs/commands/lock.html: 

> The number of lock holders is configurable with the -n flag. By default, a single holder is allowed, and a lock is used for mutual exclusion. This uses the leader election algorithm.

> If the lock holder count is more than one, then a semaphore is used instead. A semaphore allows more than a single holder, but the is less efficient than a simple lock. This follows the semaphore algorithm.

Is this behavior intentional/expected?

### PR DESCRIPTION
**Pull request by highlyunavailable**
Fixes #1006 by adding an additional check for why a lock acquisition failed.

What changed is if a lock acquisition fails, it will now perform a `kv.Get` on the key that it is locking on **immediately** after failure to acquire to get the latest state, and if the session is not null, it deems the lock-delay to not be in effect and thus resets the loop to wait normally. If the session is null and the acquisition fails, it falls back to waiting and checking every `DefaultLockRetryTime` seconds.

The downside of this is that upon resetting the loop with `goto WAIT` it does _another_ `kv.Get` to update the latest state, but this one is a blocking request that actually does wait for the latest info since the WaitIndex is persisted from the "why did this fail to acquire" check result to the next loop iteration

### CODE REVIEW

**Comment by justincampbell** [comment]
Tested locally, seems to fix #1006. Thanks!

**Comment by highlyunavailable** [comment]
This looks like an unrelated CI failure.

**Comment by armon** [comment]
Does this fix it? I'd have to dig into the state management layer, but I *believe* that the Session will be the empty string both before and after the lock-delay period.

**Comment by highlyunavailable** [comment]
It does actually fix it. As I said in the PR message, all this is doing is doing a kv.Get on the lock key, and assuming the key is in lock-delay if the session id __is__ empty. In the case of a filled-in sessionID, it means the lock is held already by a real session that will be invalidated in the future, and short-circuits the time delay, just immediately jumping back to `WAIT` which does a blocking `GET` on the key.

**Comment by armon** [comment]
@highlyunavailable Ahh got it! That is subtle indeed, but it does the trick! Thanks!

**Pull request merged**
