### PR TITLE
Add missing "is" in "this is false"

### PR DESCRIPTION
**Pull request by amossc**

### CODE REVIEW

**Review by blake — APPROVED** [review]
Thanks for correcting this!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/439804.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 9870c8dc0f00d639d9c18fca2f2b4463fdf025db onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 9870c8dc0f00d639d9c18fca2f2b4463fdf025db onto `release/1.10.x` succeeded!

**Pull request merged**
