### PR TITLE
connect: add new internal flag to retain more details during discovery chain compilation to aid in visualizations

### LINKED ISSUE #6809: agent: surface some redirect information for the discovery chain compilation results for the ui
Currently the HTTP endpoint for accessing the compiled discovery chain fully compiles out some of the data found on the input config entries. This makes re-purposing this endpoint for the UI visualization less than ideal.

One piece of data this is not present at all is the `redirect` feature from `service-resolver` entries. These are compiled out like renames. This could in theory have compiled out a redirect of a redirect of a redirect of a .... etc, so figuring out how to surface the whole thing amounts to introducing possibly many more nodes and transitions in the graph which is a much larger change.

One very small change we could make would be somehow indicating on the edges affected by a redirect a small boolean value `Redirected`.

### PR DESCRIPTION
**Pull request by rboyer**
This is activated using /v1/internal/discovery-chain instead of /v1/discovery-chain

Fixes #6809 

Sample usage:
```
============================================================
CREATE CONFIG ENTRIES
{
    "Kind": "proxy-defaults",
    "Name": "global",
    "Config": {
        "protocol": "http"
    },
    "MeshGateway": {},
    "Expose": {},
    "CreateIndex": 29,
    "ModifyIndex": 114
}
{
    "Kind": "service-resolver",
    "Name": "web",
    "Redirect": {
        "Service": "other"
    },
    "CreateIndex": 12,
    "ModifyIndex": 115
}
{
    "Kind": "service-resolver",
    "Name": "fail",
    "Failover": {
        "*": {
            "Service": "web",
            "Datacenters": [
                "dc9",
                "dc42"
            ]
        }
    },
    "CreateIndex": 20,
    "ModifyIndex": 116
}
{
    "Kind": "service-splitter",
    "Name": "main",
    "Splits": [
        {
            "Weight": 50,
            "Service": "left"
        },
        {
            "Weight": 50,
            "Service": "right"
        }
    ],
    "CreateIndex": 30,
    "ModifyIndex": 117
}
{
    "Kind": "service-splitter",
    "Name": "left",
    "Splits": [
        {
            "Weight": 50,
            "Service": "left-left"
        },
        {
            "Weight": 50,
            "Service": "right"
        }
    ],
    "CreateIndex": 34,
    "ModifyIndex": 118
}

============================================================
diff between /v1/discovery-chain/web and /v1/internal/discovery-chain/web
{								{
    "Chain": {							    "Chain": {
        "ServiceName": "web",					        "ServiceName": "web",
        "Namespace": "default",					        "Namespace": "default",
        "Datacenter": "dc1",					        "Datacenter": "dc1",
        "Protocol": "http",					        "Protocol": "http",
        "StartNode": "resolver:other.default.dc1",	      |	        "StartNode": "redirect:web.default.dc1",
        "Nodes": {						        "Nodes": {
							      >	            "redirect:web.default.dc1": {
							      >	                "Type": "redirect",
							      >	                "Name": "web.default.dc1",
							      >	                "Redirect": {
							      >	                    "Mechanism": "explicit",
							      >	                    "NextNode": "resolver:other.default.dc1"
							      >	                }
							      >	            },
            "resolver:other.default.dc1": {			            "resolver:other.default.dc1": {
                "Type": "resolver",				                "Type": "resolver",
                "Name": "other.default.dc1",			                "Name": "other.default.dc1",
                "Resolver": {					                "Resolver": {
                    "ConnectTimeout": "5s",			                    "ConnectTimeout": "5s",
                    "Default": true,				                    "Default": true,
                    "Target": "other.default.dc1"		                    "Target": "other.default.dc1"
                }						                }
            }							            }
        },							        },
        "Targets": {						        "Targets": {
            "other.default.dc1": {				            "other.default.dc1": {
                "ID": "other.default.dc1",			                "ID": "other.default.dc1",
                "Service": "other",				                "Service": "other",
                "Namespace": "default",				                "Namespace": "default",
                "Datacenter": "dc1",				                "Datacenter": "dc1",
                "MeshGateway": {},				                "MeshGateway": {},
                "Subset": {},					                "Subset": {},
                "SNI": "other.default.dc1.internal.d1ab25f4-f	                "SNI": "other.default.dc1.internal.d1ab25f4-f
                "Name": "other.default.dc1.internal.d1ab25f4-	                "Name": "other.default.dc1.internal.d1ab25f4-
            }							            }
        }							        }
    }								    }
}								}

============================================================
diff between /v1/discovery-chain/fail and /v1/internal/discovery-chain/fail
{								{
    "Chain": {							    "Chain": {
        "ServiceName": "fail",					        "ServiceName": "fail",
        "Namespace": "default",					        "Namespace": "default",
        "Datacenter": "dc1",					        "Datacenter": "dc1",
        "Protocol": "http",					        "Protocol": "http",
        "StartNode": "resolver:fail.default.dc1",		        "StartNode": "resolver:fail.default.dc1",
        "Nodes": {						        "Nodes": {
            "resolver:fail.default.dc1": {			            "resolver:fail.default.dc1": {
                "Type": "resolver",				                "Type": "resolver",
                "Name": "fail.default.dc1",			                "Name": "fail.default.dc1",
                "Resolver": {					                "Resolver": {
                    "ConnectTimeout": "5s",			                    "ConnectTimeout": "5s",
                    "Target": "fail.default.dc1",		                    "Target": "fail.default.dc1",
                    "Failover": {				                    "Failover": {
                        "Targets": [				                        "Targets": [
                            "other.default.dc9",		                            "other.default.dc9",
                            "other.default.dc42"		                            "other.default.dc42"
							      >	                        ],
							      >	                        "InternalTargets": [
							      >	                            [
							      >	                                {
							      >	                                    "RedirectMechanism": "exp
							      >	                                    "Name": "web.default.dc9"
							      >	                                },
							      >	                                {
							      >	                                    "Name": "other.default.dc
							      >	                                }
							      >	                            ],
							      >	                            [
							      >	                                {
							      >	                                    "RedirectMechanism": "exp
							      >	                                    "Name": "web.default.dc42
							      >	                                },
							      >	                                {
							      >	                                    "Name": "other.default.dc
							      >	                                }
							      >	                            ]
                        ]					                        ]
                    }						                    }
                }						                }
            }							            }
        },							        },
        "Targets": {						        "Targets": {
            "fail.default.dc1": {				            "fail.default.dc1": {
                "ID": "fail.default.dc1",			                "ID": "fail.default.dc1",
                "Service": "fail",				                "Service": "fail",
                "Namespace": "default",				                "Namespace": "default",
                "Datacenter": "dc1",				                "Datacenter": "dc1",
                "MeshGateway": {},				                "MeshGateway": {},
                "Subset": {},					                "Subset": {},
                "SNI": "fail.default.dc1.internal.d1ab25f4-f6	                "SNI": "fail.default.dc1.internal.d1ab25f4-f6
                "Name": "fail.default.dc1.internal.d1ab25f4-f	                "Name": "fail.default.dc1.internal.d1ab25f4-f
            },							            },
            "other.default.dc42": {				            "other.default.dc42": {
                "ID": "other.default.dc42",			                "ID": "other.default.dc42",
                "Service": "other",				                "Service": "other",
                "Namespace": "default",				                "Namespace": "default",
                "Datacenter": "dc42",				                "Datacenter": "dc42",
                "MeshGateway": {},				                "MeshGateway": {},
                "Subset": {},					                "Subset": {},
                "SNI": "other.default.dc42.internal.d1ab25f4-	                "SNI": "other.default.dc42.internal.d1ab25f4-
                "Name": "other.default.dc42.internal.d1ab25f4	                "Name": "other.default.dc42.internal.d1ab25f4
            },							            },
            "other.default.dc9": {				            "other.default.dc9": {
                "ID": "other.default.dc9",			                "ID": "other.default.dc9",
                "Service": "other",				                "Service": "other",
                "Namespace": "default",				                "Namespace": "default",
                "Datacenter": "dc9",				                "Datacenter": "dc9",
                "MeshGateway": {},				                "MeshGateway": {},
                "Subset": {},					                "Subset": {},
                "SNI": "other.default.dc9.internal.d1ab25f4-f	                "SNI": "other.default.dc9.internal.d1ab25f4-f
                "Name": "other.default.dc9.internal.d1ab25f4-	                "Name": "other.default.dc9.internal.d1ab25f4-
            }							            }
        }							        }
    }								    }
}								}

============================================================
diff between /v1/discovery-chain/main and /v1/internal/discovery-chain/main
{								{
    "Chain": {							    "Chain": {
        "ServiceName": "main",					        "ServiceName": "main",
        "Namespace": "default",					        "Namespace": "default",
        "Datacenter": "dc1",					        "Datacenter": "dc1",
        "Protocol": "http",					        "Protocol": "http",
        "StartNode": "splitter:main",				        "StartNode": "splitter:main",
        "Nodes": {						        "Nodes": {
            "resolver:left-left.default.dc1": {			            "resolver:left-left.default.dc1": {
                "Type": "resolver",				                "Type": "resolver",
                "Name": "left-left.default.dc1",		                "Name": "left-left.default.dc1",
                "Resolver": {					                "Resolver": {
                    "ConnectTimeout": "5s",			                    "ConnectTimeout": "5s",
                    "Default": true,				                    "Default": true,
                    "Target": "left-left.default.dc1"		                    "Target": "left-left.default.dc1"
                }						                }
            },							            },
            "resolver:right.default.dc1": {			            "resolver:right.default.dc1": {
                "Type": "resolver",				                "Type": "resolver",
                "Name": "right.default.dc1",			                "Name": "right.default.dc1",
                "Resolver": {					                "Resolver": {
                    "ConnectTimeout": "5s",			                    "ConnectTimeout": "5s",
                    "Default": true,				                    "Default": true,
                    "Target": "right.default.dc1"		                    "Target": "right.default.dc1"
                }						                }
            },							            },
            "splitter:main": {				      |	            "splitter:left": {
                "Type": "splitter",				                "Type": "splitter",
                "Name": "main",				      |	                "Name": "left",
                "Splits": [					                "Splits": [
                    {						                    {
                        "Weight": 25,			      |	                        "Weight": 50,
                        "NextNode": "resolver:left-left.defau	                        "NextNode": "resolver:left-left.defau
                    },						                    },
                    {						                    {
                        "Weight": 25,			      |	                        "Weight": 50,
                        "NextNode": "resolver:right.default.d	                        "NextNode": "resolver:right.default.d
							      >	                    }
							      >	                ]
							      >	            },
							      >	            "splitter:main": {
							      >	                "Type": "splitter",
							      >	                "Name": "main",
							      >	                "Splits": [
							      >	                    {
							      >	                        "Weight": 50,
							      >	                        "NextNode": "splitter:left"
                    },						                    },
                    {						                    {
                        "Weight": 50,				                        "Weight": 50,
                        "NextNode": "resolver:right.default.d	                        "NextNode": "resolver:right.default.d
                    }						                    }
                ]						                ]
            }							            }
        },							        },
        "Targets": {						        "Targets": {
            "left-left.default.dc1": {				            "left-left.default.dc1": {
                "ID": "left-left.default.dc1",			                "ID": "left-left.default.dc1",
                "Service": "left-left",				                "Service": "left-left",
                "Namespace": "default",				                "Namespace": "default",
                "Datacenter": "dc1",				                "Datacenter": "dc1",
                "MeshGateway": {},				                "MeshGateway": {},
                "Subset": {},					                "Subset": {},
                "SNI": "left-left.default.dc1.internal.d1ab25	                "SNI": "left-left.default.dc1.internal.d1ab25
                "Name": "left-left.default.dc1.internal.d1ab2	                "Name": "left-left.default.dc1.internal.d1ab2
            },							            },
            "right.default.dc1": {				            "right.default.dc1": {
                "ID": "right.default.dc1",			                "ID": "right.default.dc1",
                "Service": "right",				                "Service": "right",
                "Namespace": "default",				                "Namespace": "default",
                "Datacenter": "dc1",				                "Datacenter": "dc1",
                "MeshGateway": {},				                "MeshGateway": {},
                "Subset": {},					                "Subset": {},
                "SNI": "right.default.dc1.internal.d1ab25f4-f	                "SNI": "right.default.dc1.internal.d1ab25f4-f
                "Name": "right.default.dc1.internal.d1ab25f4-	                "Name": "right.default.dc1.internal.d1ab25f4-
            }							            }
        }							        }
    }								    }
}								}
```

### CODE REVIEW

**Comment by crhino** [comment]
Can we use `/v1/internal/ui/discovery-chain/` as the endpoint to be more consistent with `/v1/internal/ui/{nodes,node,services}`?

**Comment by johncowen** [comment]
Ah good call @crhino ! @mkeeler I noticed that the new `internal/acl` doesn't have `ui` not sure if we want to make these all consistent in the `ui` folder or not? - I don't think we are using them internally for anything else at the moment. It's neither here nor there for me really, but consistency is good.

**Comment by johncowen** [comment]
Hey @rboyer 👋 

So I've been playing a bit more with the disco-chain endpoint this week, and I think this will help massively for us to be able to show the details of what config produces the final discovery-chain output.

I wanted to just note here that one of my main problems at the moment is 'guessing' the 'type' of redirect/failover, i.e. is it a redirect to a different namespace or a different datacenter? I'm kind of guessing this by comparing 'parts' of the domain right now to see what changes between 2 domains, but this has edge case-y problems where this guessing will fail (periods in service names will mess things up etc).

I'm not sure if you'd want to have a chat about this before you merge this or not, but let me know and we can chat through.

@banks 👋 

> To play devil's advocate though - why is this internal only?

I think the main reason was so that we could spend time to find the correct approach without committing to anything in the public API (this is already the second revision of this endpoint). So the thinking was that we could work on it over time without the churn on a public endpoint. Once we are happy with it, I think the idea was we would then to be promote it back to the non-internal endpoint.

It's a similar approach to the one we used for the `/v1/internal/acl/authorize` endpoint.

**Comment by jmurret** [comment]
Closing as this is over two years old.

**Pull request closed without merging**
