### PR TITLE
docs: audit logging restructure sentence

### PR DESCRIPTION
**Pull request by joshRooz**
### Description
Very small correction to sentence structure on public facing documentation for Audit Logging.

### Testing & Reproduction steps
n/a

### Links
n/a

### PR Checklist

* [ ] updated test coverage
* [x] external facing docs updated
* [x] not a security concern

### CODE REVIEW

**Review by david-yu — APPROVED** [review]

**Comment by david-yu** [comment]
@joshRooz could you rebase your branch so we could get these tests to somehow pass? I'm not able to merge these until those test go green.

**Comment by joshRooz** [comment]
@david-yu done. Better than before but still failing a single go-test, unfortunately. I'm also not sure what, if anything, I need to do to authorize the Vercel checks. Please advise at your convenience.

**Comment by blake** [comment]
@joshRooz I just approved the Vercel builds. Assuming they pass, we should be able to merge this PR.

**Comment by david-yu** [comment]
Thanks @Blake I think somehow I needed some help on getting this over the line!

**Pull request merged**
