### PR TITLE
Backout Envoy 1.28.0

### PR DESCRIPTION
**Pull request by cthain**
### Description

This PR reverts the Enoy version bump to 1.28.0 because that version causes failures in sameness group integration tests.

### Links

Previous PR that introduced the change is #19276 

### PR Checklist

* [x] updated test coverage
* [x] ~external facing docs updated~
* [x] appropriate backport labels added
* [x] not a security concern

### CODE REVIEW

**Comment by cthain** [comment]
I'm not sure if this requires a new changelog entry. There is are specific changelog entries on the release/1.17.x and release/1.17.0 branches and we will probably have moved to Envoy 1.28.x by the next Consul release. But PLMK if you think I should add a CL for this.

**Comment by zalimeni** [comment]
> I'm not sure if this requires a new changelog entry. There are specific changelog entries on the release/1.17.x and release/1.17.0 branches and we will probably have moved to Envoy 1.28.x by the next Consul release. But PLMK if you think I should add a CL for this.

@cthain WDYT about just retaining the CL from 1.17.x for now, since this is effectively making `main` match `release/1.17.x`? Though I agree we'll probably upgrade by 1.18, if we for some reason don't get around to it, we'd be caught up to work so far. We can always revert + update the initial entry if we upgrade.

**Review by zalimeni — APPROVED** [review]
One thought re: CL, but non-blocking. Thank you for chasing this down 🙏🏻

**Review by NiniOak — COMMENTED** [review]
This revert will cause Verify Envoy Check to fail in CI. Please set [this](https://github.com/hashicorp/consul/blob/9d00b13140aea3d6bf8cc65f9feccbf1b807c1dc/.github/workflows/verify-envoy-version.yml#L18) value to `true` to skip Envoy version check. Thanks @cthain

**Pull request merged**
