### PR TITLE
api: remove dependency on proto-public, protobuf, and grpc

### PR DESCRIPTION
**Pull request by rboyer**
### Description

The api submodule has a test-only dependency on `proto-public`. This has the unfortunate side effect of making anybody importing `api` navigate the dependency maze that is protobuf + grpc *for no reason*.

This PR removes the need from the dependency.

### CODE REVIEW

**Review by jmurret — APPROVED** [review]
👍 thank you!

**Comment by zalimeni** [comment]
Oh wow, this is excellent and will have a big impact on releases. Thank you!

**Review by zalimeni — APPROVED** [review]

**Review by mkeeler — APPROVED** [review]

**Comment by mkeeler** [comment]
Thanks everyone. I was trying to pull in the client lib last week and was running into dep issues due to this and it will be great to get it fixed

**Review by dhiaayachi — APPROVED** [review]
LGTM!

**Pull request merged**
