### PR TITLE
ui: Move actual dependencies into dependencies, prune some dependencies

### PR DESCRIPTION
**Pull request by johncowen**
We want to make sure its clear what are actual shipped dependencies and
what are build/dev dependencies. This splits the ember populated
`devDependencies` up to reflect this.

If somebody spots something that should be in `dependencies` or vice versa, please shout!

We also took the opportunity to remove a few dependencies that were no
longer needed.

### CODE REVIEW

**Comment by DingoEatingFuzz** [comment]
This is weird to me. Since the entire app is statically built, no dependencies are "shipped"/required for production.

**Comment by johncowen** [comment]
All `dependencies` are shipped, just in a different format.

But I do see what you are saying here. I think it's more the 'idea' that the app itself is dependent on the `dependencies` to run - the fact that we then copy the dependencies, bundle them together and compress them isn't hugely important, that's just the way of the world right now, our app still depends on them to be able to run. 

`devDependencies` on the other hand aren't actually shipped ever (not bundled, compressed or whatever). They are only needed to build the app (combine the dependencies into a format that's acceptable for people to consume). If it wasn't for the fact that we need to do this bundling and compressing it would be clear that they are dependencies, I think most people outside of the ember world treat them as such and put them in `dependencies`

The only other option here is to do a different split, so `devDependencies` and `optionalDependencies` for example. I prefer the one we've done here, as its a more common way of doing things.

Overall the reason for doing this split makes it easier for us to do other things that maybe @alvin-huang can expand upon.

**Comment by DingoEatingFuzz** [comment]
Building frontend things with npm is definitely weird, but I see the difference between `dependencies` and `devDependencies` as more mechanical than that. 

If you aren't developing a module, you only need the dependencies (whether you are a dependent or running the module in production) and therefore use `npm install --production`/`yarn install --production`. Since frontends are rarely dependencies and aren't modules run in production, there are 0 dependencies that aren't devDependencies.

Ultimately, we're sorta splitting hairs here, but I'm curious what @alvin-huang has to say about what this differentiation unlocks.

**Comment by johncowen** [comment]
@gregone mentioned this addon might be useful here:

https://github.com/kaliber5/ember-cli-bundle-analyzer

pros: we don't have to distinguish between `dependencies` and `devDependencies`
cons: we add a bunch more devDependencies (and dependencies of dependencies etc etc) only to distinguish between what is going in the bundled build and what we use to make the bundled build.

I've not looked too much into the above addon myself, but at first glance it looks like this would solve the issue of 'whats in the shipped code'. @alvin-huang lemme know what you want to do.

**Comment by johncowen** [comment]
Closing this since https://github.com/hashicorp/consul/pull/5992 will have changed the package dependencies so much, this will probably just be a huge conflict, if we were to go with splitting them, it would be more straight forwards to just re-do the moving about in the package.json file.

@alvin-huang let me know if/when you ever want to pick this back up again

**Pull request closed without merging**
