### PR TITLE
Network diags

### PR DESCRIPTION
**Pull request by jsullivan3**
This pull request ports the 'reachability' command from Serf and adds the ability to issue Memberlist 'ping' packets to a specified node.  These new commands greatly help in diagnosing network connectivity issues in a Consul cluster, especially in cases where a node is misbehaving by dropping some (or all) UDP packets.

This PR requires https://github.com/hashicorp/memberlist/pull/55 in order to properly build.

### CODE REVIEW

**Comment by slackpad** [comment]
Hi @jsullivan3 - this looks very useful. I'll review this once we get 0.6 out the door, as this is probably too big of a change to make it into that release. Thanks!

**Comment by DanyC97** [comment]
@slackpad any chance this PR can get some love now that v 0.7 is out? cheers

**Comment by slackpad** [comment]
Hi @jsullivan3 sorry for the looong delay on this one :-) Any chance you can rebase this one and we can work towards getting it in?

**Comment by jsullivan3** [comment]
Hi!  I'm not sure when I can get it done, but I'll certainly take a look and see what I can do...

**Comment by slackpad** [comment]
I super apologize that we didn't get this in sooner, but I think we should close this down unless someone gets some bandwidth to reintegrate it. In the meantime, we've done a bunch of work under https://www.consul.io/docs/internals/gossip.html#lifeguard-enhancements to make Consul deal automatically with hosts that are struggling network-wise, so the need for a tool like this might be lower now, though it still looks useful.

**Pull request closed without merging**
