### PR TITLE
test: test server should auto cleanup

### PR DESCRIPTION
**Pull request by rboyer**
Backport of patch in enterprise.

### CODE REVIEW

**Review by freddygv — APPROVED** [review]

**Review by eculver — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/521245.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 592ac8f96a415e1109e5c5628809d279d4de772e onto `release/1.11.x` succeeded!

**Comment by dnephin** [comment]
I'm going to backport this into 1.10 and 1.9 as well, so that as we add new tests that don't call Shutdown, they will also be safe to backport.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/523437.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 592ac8f96a415e1109e5c5628809d279d4de772e onto `release/1.11.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/523437)

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 592ac8f96a415e1109e5c5628809d279d4de772e onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 592ac8f96a415e1109e5c5628809d279d4de772e onto `release/1.9.x` succeeded!

**Pull request merged**
