### PR TITLE
increase envoy route timeout to 5mins

### PR DESCRIPTION
**Pull request by zduymz**
default envoy route timeout is 15s. It's not sufficient for request that take long time to process.
An Issue was raised here: https://github.com/hashicorp/consul/issues/6382
PR add timeout to 5mins

### CODE REVIEW

**Comment by jippi** [comment]
Isn't this something that can be configured by the end-user in the `connect{}` stanza? imo it _really_ should - we got many endpoints where an envoy request can take a looooong time (by design), talking +10min easily

**Comment by i0rek** [comment]
Thank you for your work @zduymz! Would you want to take a stab at making this configurable? The default is not good for you and I guess someone doesn't like 5minutes either.
Thanks!

**Comment by zduymz** [comment]
sure @i0rek. What variable name should be? I'm not good at naming concisely.

**Comment by rboyer** [comment]
Incidentally, this can already be configured for all clients of a given service by editing that service's `service-router` config entry and updating the `RequestTimeout` setting: https://www.consul.io/docs/agent/config-entries/service-router#requesttimeout

Would that work for your use cases, or do you also require this to be configured for individual clients of a service in the upstream configuration itself?

**Comment by mikemorris** [comment]
Closing this as it's bit sitting a while with several conflicts now, and I believe the approach we'd want to take would instead be to implement a configurable timeout as described in #6382

**Pull request closed without merging**
