### PR TITLE
Add headings to Helm docs

### PR DESCRIPTION
**Pull request by lkysow**

### CODE REVIEW

**Review by david-yu — APPROVED** [review]
This looks great! Thank you!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/404645.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 75b21259a1a5fa5a6bbd5e78ce6842177924f0ea onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 75b21259a1a5fa5a6bbd5e78ce6842177924f0ea onto `release/1.10.x` succeeded!

**Pull request merged**
