### PR TITLE
Add failures_before_warning to checks

### PR DESCRIPTION
**Pull request by dnephin**
Closes #10701

I don't have permission to make changes on that remote, and CI was not running on that PR, so opening another one to get CI running.

### CODE REVIEW

**Review by kisunji — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/444028.

**Comment by jakubgs** [comment]
Thanks for fixing the test and CI issues @kisunji !

**Comment by kisunji** [comment]
It was all @dnephin! I just pressed the merge button 😆

**Comment by jakubgs** [comment]
Thanks @dnephin then! Appreciate it. Now our alerts will be a bit less noisy, which is great.

Well, I guess I'll have to wait for a release to roll it out, but it's gonna be great.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/444828.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 1f9479603cbcc53ea616c5326822fa02dfcfa983 onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/444828)

**Comment by kisunji** [comment]
☝️ Will manually cherry pick to make sure this goes into the next 1.10 release

**Comment by kisunji** [comment]
Ah I may have misled everyone! Judging by Daniel's comments in the original PR (and the docs) this was meant for the next minor version `1.11` and not to be included in a patch for `1.10.x`. 

Expect to see this in our Consul 1.11 release! Sorry for the misunderstanding 😬

**Comment by jakubgs** [comment]
I've deployed [v1.11.0-alpha](https://github.com/hashicorp/consul/releases/tag/v1.11.0-alpha) to 12 hosts and set up few services with different values for `failures_before_warning`.

I'm seeing no issues so far.

**Pull request merged**
