### PR TITLE
Restrict sidecar service registration in the catalog.

### PR DESCRIPTION
**Pull request by rboyer**
Parent PR: https://github.com/hashicorp/consul/pull/5353
Note: this is merging into a long lived feature branch, not master.

Treat the `"-sidecar-proxy"` service suffix as a semi-reserved suffix. If `"FOO-sidecar-proxy"` is registered as a service it MUST be a connect service AND the destination must be `"FOO"`.

You are still free to register sidecars with whatever nomenclature you desire, but if you want some of the upcoming ACL UX improvements to kick in you really should use the `"-sidecar-proxy"` naming convention.

This is a small backwards incompatibility in the off chance someone had chosen to manually register services in a manner that does not align with the above restriction.

### CODE REVIEW

**Comment by mkeeler** [comment]
I commented on the other PR but I don't think we should do this. There could be many other sidecar proxy services users might want to register that are completely unrelated to Connect. Also the restriction seems completely arbitrary and I don't see the utility in it.

**Comment by banks** [comment]
Hmm. I don't remember this from RFC was it proposed/decided or is this just speculative? 

What is the benefit from a security/UX point of view?

**Comment by banks** [comment]
Oh I found #5369 after that comment...

**Comment by rboyer** [comment]
This will be shelved in favor of improving the docs instead: #5386

**Pull request closed without merging**
