### PR TITLE
Update ECR tag in CRT Builds

### PR DESCRIPTION
**Pull request by smacfarlane**
This updates the ECR tag to the correct naming convention.

Signed-off-by: Scott Macfarlane <smacfarlane@hashicorp.com>

### CODE REVIEW

**Review by markan — APPROVED** [review]
Approved after chatting with @smacfarlane. This seems pretty reasonable, given that old version doesn't even exist in DNS :-)

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/558988.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 20c3d6670f70f48260beb0a2251656e055a00bc7 onto `release/1.11.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 20c3d6670f70f48260beb0a2251656e055a00bc7 onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 20c3d6670f70f48260beb0a2251656e055a00bc7 onto `release/1.9.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 20c3d6670f70f48260beb0a2251656e055a00bc7 onto `release/1.8.x` succeeded!

**Pull request merged**
