### PR TITLE
website: Add Demandbase tag to consent manager

### PR DESCRIPTION
**Pull request by EnMod**
[:mag: Preview link](https://consul-git-nqweb-add-demandbase-consent-hashicorp.vercel.app/)

---

This PR adds a Demandbase tag to the consent manager for the Consul website.

### CODE REVIEW

**Review by alexcarpenter — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/569842.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 2de3a6900fc300d3c0a34d4c98dc146797c7be29 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 2de3a6900fc300d3c0a34d4c98dc146797c7be29 onto `release/1.11.x` succeeded!

**Pull request merged**
