### PR TITLE
Fix dead server removal condition to use correct failure tolerance

### PR DESCRIPTION
**Pull request by preetapan**
The dead server removal code in autopilot was more conservative than necessary. This PR changes it to use the correct failure tolerance so that as long as there is quorum, failed servers are cleaned up correctly.

This is an example scenario where the current logic failed to remove dead servers:

- Add two new replacement servers to a cluster of 3 servers for an upgrade. 
- Stop two old servers

### CODE REVIEW

**Comment by i0rek** [comment]
I rebased this PR and fixed the tests. This PR changes how many dead servers autopilot can delete which depends on the number of raft peers (which is the number of raft voters, possibly including itself). The result is the following:

| peers | pre | post |
|-------|-----|------|
| 1     | 0   | 1    |
| 2     | 1   | 1    |
| 3     | 1   | 2    |
| 4     | 2   | 2    |
| 5     | 2   | 3    |
| 6     | 3   | 3    |
| 7     | 3   | 4    |

**Comment by banks** [comment]
@i0rek your table seems dangerous to me - if there are 3 peers, allowing removal of 2 of them breaks quorum and shouldn't really be allowed.

Also since this PR we discussed adding a way to configure a minimum quorum size since AutoPilot will happily reduce the quorum size currently. I forget if that was WIP or merged (I think it was in the last release though). I also see `MinQuorum` in the diff now which I presume was from that change.

How does that interact with this change now? It would be handy to see in the table the MinQuorum setting as well as the actual number of peers so we can work out what is safe/expected?

**Comment by banks** [comment]
Ah yeah the PR for the MinQuorum fix was https://github.com/hashicorp/consul/pull/6654 and ASFICS it actually implemented the same change this PR intended to as well already since we moved to allowing any number of servers to be removed provided there was still a minQuorum size left up.

I think this PR should be closed since the one above already implemented what was intended here. The changes I see seem to take it too far and allow unsafe removal of _more_ servers than necessary to leave you with the configured min quorum size?

**Comment by banks** [comment]
Oh wait that PR didn't change - we always attempted to remove only a minority we just had a bug in the integer rounding.

Old code was just `removalCount < peers/2` as the condition to go ahead. An example where that is wrong as Preetha provided was 3 servers intended (quorum or 2) but another 2 have been started as replacements and then old 2 removed. That should be safe to clean both since there will still be 3 remaining however while 5/2 is 2.5 which is great than 2, due to integer truncation 5/2 is 2 and `2 > 2` is false.

So I see the value in the fix for that, but your table still puzzles me a bit. Here is my version:

| Peers | MinQuorum| Dead | `removalCount <= (peers-1)/2` | Removal Allowed |
|===|===|===|===|===|
| 1 | 1 | 1 | 1 <= 0 is `false` | ❌  |
| 3 | 3 | 1 | 1 <= 1 is `true` | ❌ because of MinQuorum check |
| 4 | 3 | 3 | 3 <= 1 is `true` | ❌ because of MinQuorum check |
| 5 | 3 | 2 | 2 <= 2 is `true` | ✅  | <== preetha's example case |


So I _think_ I've convinced myself the new logic is OK when combined with the MinQuorum check.

I also wondered why we make this a binary decision?

If there are 3 dead servers and we can only safely remove 2, why don't we just remove 2 of them instead of refusing to remove any? I think the answer is that we can't know _which_ two are best to remove in this case - consider the upgrade case where there are meant to be 3 servers but two new ones are started to replace two old. Now if one of the healthy new servers happens to fail just at the same time the two old servers are taken down, autopilot could choose to delete one new server and one old and be left in a broken state.

So overall I think this is correct behaviour now! The key for me to understanding this PR was noting that it's about correcting an _integer division bug_ not changing the intent of what Consul does.

**Comment by i0rek** [comment]
Thank you for reviewing @banks! My table doesn't have the MinQuorum, which I agree is confusing. I didn't think of adding it.

> So overall I think this is correct behaviour now! The key for me to understanding this PR was noting that it's about correcting an _integer division bug_ not changing the intent of what Consul does.

Thank you for your explanation! I was not sure myself if this PR is correct, but since we had it sitting for so long and it was already approved I went ahead and prepared it for merging. Thinking that while working on it, things would become more clear :).

**Comment by i0rek** [comment]
I thought about this again and my table bothered me too much, and I extracted a function which decides if autopilot should move on removing servers or not. The output of the tests is the following: 

```
{peers:1 minQuorum:1 deadServers:1 ok:false}: denied, because removing 1 would leave less then quorum of 1 servers.
{peers:3 minQuorum:3 deadServers:1 ok:false}: denied, because removing 1 would leave less then quorum of 3 servers.
{peers:4 minQuorum:3 deadServers:3 ok:false}: denied, because removing 3 would leave less then quorum of 3 servers.
{peers:5 minQuorum:3 deadServers:3 ok:false}: denied, because removing 3 would leave less then quorum of 3 servers.
{peers:5 minQuorum:3 deadServers:2 ok:true}: allowed, because removing 2/5 servers is above quorum of 3 and leaves a majority of servers
{peers:5 minQuorum:3 deadServers:1 ok:true}: allowed, because removing 1/5 servers is above quorum of 3 and leaves a majority of servers
{peers:9 minQuorum:3 deadServers:5 ok:false}: denied, because removing the majority of servers 5/3 is not safe.
```

**Pull request merged**
