### PR TITLE
Fix TestDNS_ServiceLookup_AnswerLimits  so that it only creates test agents the minimal amount of time.

### PR DESCRIPTION
**Pull request by jmurret**
### Description

This takes a similar approach as https://github.com/hashicorp/consul/pull/21608 and reduces 36 created test agents down to 12.  This reduces local runtime from 61 seconds to 20 secs.

### PR Checklist

* [x] updated test coverage
* [x] external facing docs updated
* [x] appropriate backport labels added
* [x] not a security concern

### CODE REVIEW

**Review by zalimeni — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
@jmurret, a backport is missing for this PR [21609] for versions [1.15] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@jmurret, a backport is missing for this PR [21609] for versions [1.15] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@jmurret, a backport is missing for this PR [21609] for versions [1.15] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@jmurret, a backport is missing for this PR [21609] for versions [1.15] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Pull request merged**
