### PR TITLE
adding NIA to sidebar nav

### PR DESCRIPTION
**Pull request by pcmccarron**

### CODE REVIEW

**Review by mikemorris — APPROVED** [review]
Checked preview site, LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/441773.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit d10dd5fbb196934560d72b4d48c723cc5481cb0c onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit d10dd5fbb196934560d72b4d48c723cc5481cb0c onto `release/1.10.x` succeeded!

**Pull request merged**
