### PR TITLE
URL-encode/decode resource names for HTTP API part 4

### PR DESCRIPTION
**Pull request by fulviodenza**
Hi, I noticed that #12103 and #11957 did not contain changes to consul/ui_endpoint.go, I changed that endpoint.

### CODE REVIEW

**Comment by kisunji** [comment]
Hi @fulviodenza, thank you for your interest! There are a few more handlers in `ui_endpoint.go` which naively use `strings.TrimPrefix`. Could you update them as well?

**Comment by fulviodenza** [comment]
@kisunji sure! done

**Comment by fulviodenza** [comment]
if there is something else in which I can help, ask for it

**Review by kisunji — APPROVED** [review]
Looks good! Will wait for our CI to stabilize (some issues with provisioning containers) but can merge shortly after

**Comment by fulviodenza** [comment]
Hi! Any update with this pr?

**Comment by kisunji** [comment]
Looks good! Thanks for the reminder 👍

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/569958.

**Pull request merged**
