### PR TITLE
Allow context propagation through Lock operations

### PR DESCRIPTION
**Pull request by jonasi**
To enable functionality such as tracing http via context, we
need to make sure that any query or write operations are context-aware.

This commit adds a ctx field to LockOptions and Context()/WithContext()
methods in the same style as WriteOptions and QueryOptions. For each
write or query operation in the Lock lifecycle, we pass along the ctx
value to the WriteOptions or QueryOptions.

### CODE REVIEW

**Comment by i0rek** [comment]
Thank you for your work @jonasi! Are you still interested in adding this?

**Comment by jonasi** [comment]
> Thank you for your work @jonasi! Are you still interested in adding this?

Sure

**Comment by i0rek** [comment]
Thanks for your reply! This looks good! Could you rebase your PR and add it test for it, similar to the one here: https://github.com/hashicorp/consul/blob/56e7c9e1084b073832f285e1957c0a98b7504c52/api/session_test.go#L251-L283?

Thanks!

**Comment by i0rek** [comment]
Closing because no reply. I am happy to reopen in case there are updates. Thanks!

**Pull request closed without merging**
