### PR TITLE
add notarize darwin arm64 workflow

### PR DESCRIPTION
**Pull request by claire-labry**
### Description
Consul needs to have a workflow that notarizes the darwin arm64 binary. Currently there's no workflow to notarize it. 

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [ ] not a security concern
* [ ] checklist [folder](./../docs/config) consulted

### CODE REVIEW

**Review by lkysow — APPROVED** [review]

**Review by alvin-huang — APPROVED** [review]
LGTM!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/651496.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 0c48f2c77cdaeb20dc06086c37b6f67446dde2c4 onto `release/1.12.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 0c48f2c77cdaeb20dc06086c37b6f67446dde2c4 onto `release/1.11.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 0c48f2c77cdaeb20dc06086c37b6f67446dde2c4 onto `release/1.10.x` succeeded!

**Pull request merged**
