### PR TITLE
ui: [Backport 1.10.x] Add version information back into the footer (#11803)

### PR DESCRIPTION
**Pull request by johncowen**
See https://github.com/hashicorp/consul/pull/11803 and #11850 (which was also added post initial PR)

### CODE REVIEW

**Review by amyrlam — APPROVED** [review]
LGTM 👍 

Writing my steps to make sure this is the right process:
`cd ui/packages/consul-ui && yarn start` cause the Vercel wasn't there

Looks like you added in this thing:
image

**Comment by johncowen** [comment]
Ooops sorry! Can you see this in the GH Checks?

Screenshot 2021-12-17 at 11 15 38

If you click the [Details] link for the "Vercel - consul-ui-staging" it will take you to the Vercel deployment page then clicking [Visit] there will take you to the Preview site for this specific PR.

Lemme know if you can't see that, thanks for the 👍

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/533082.

**Comment by amyrlam** [comment]
@johncowen Makes sense now, I was clicking on "Vercel - consul" which was ignored, so I just ran it locally instead. Will try "Vercel - consul-ui-staging" next time.

**Comment by johncowen** [comment]
Ah yes gotcha! I think the `Vercel - consul` one is the docs site, which I guess isn't run for a UI change (we have CircleCI things going on to skip golang tests and other things for just a UI change)

**Pull request merged**
