### PR TITLE
More understandable timeouts in checks when value exceeds interval, Fixes #5834

### LINKED ISSUE #5834: Long timeouts unintuitive behaviour
#### Overview of the Issue

Handling of timeouts in checks is counter-intuitive in Consul.

Consider this example:

```
Checks: [
 {
   "http": "http://localhost:80/healthz",
   "interval": "30s",
   "timeout": "30s"
  }
]
```
=> Will create a HTTP check with timeout of 10s

While:
```
Checks: [
 {
   "http": "http://localhost:80/healthz",
   "interval": "30s",
   "timeout": "29s"
  }
]
```
=> Will create a HTTP check with timeout of 29s

While I see the point of setting the timeout to interval at maximum, in that case, it should behave as an upper boudary.

I thus propose the following:

if timeout ≥ Interval => use Interval and display a Warning at registration time

### PR DESCRIPTION
**Pull request by pierresouchay**
When Timeouts were greater or equal than interval for checks,

Consul used to set timeout to 10s. Now, use the interval as upper boundary in that case.

Also outputs a warning in logs in that case.

Thus:
```
Checks: [
 {
   "http": "http://localhost:80/healthz",
   "interval": "30s",
   "timeout": "30s"
  }
]
```
Will now use a timeout of 30s and not 10s as it used to be the case

### CODE REVIEW

**Comment by pierresouchay** [comment]
Will fix #5834

**Comment by pierresouchay** [comment]
@i0rek Thank you for watching this PR.

To be frank, I don't know what is the best. I was not sure whether having timeout bigger than interval could cause issues, I thought that compared to existing implementation, it is the less disruptive.

The interval = 0 seems impossible for checks, since it would be set to [checks.MinInterval](https://github.com/hashicorp/consul/search?q=checks.MinInterval&unscoped_q=checks.MinInterval) which means 1s , so the code is still valid.

I can change it if you want, but compared to the existing implementation, I think it is a reasonable choice.

Maybe we can document more that having timeouts greater than interval will cause timeouts to be used?

**Comment by pierresouchay** [comment]
@i0rek what do you think about my last comment https://github.com/hashicorp/consul/pull/5835#issuecomment-504173934 ?

**Comment by pierresouchay** [comment]
@i0rek It basically means that for now: duration between 2 checks is between 1 and 2*interval (timeout which is bounded by interval + interval)

So basically, this PR changes nothing to the existing behavior except for people using very long timeout (bigger than interval) that used to be time outed after 10s and will be at interval now...

Sound quite OK to me and easier to understand for people without the knowledge about Consul internals without completely changing behavior in an insane way.

Might probably deserves a note un documentation anyway

**Comment by freddygv** [comment]
@pierresouchay If the configured timeout is 12s and the interval is 10s why not set the timeout at 12s? This bounds the duration between checks at timeout + interval.

We are leaning toward changing the implementation so that timeouts are configurable without being capped.

It's worth considering that the check registration docs don't mention the timeouts being restricted:
https://www.consul.io/api/agent/check.html#timeout

**Comment by adams-sarah** [comment]
Closing this in favor of https://github.com/hashicorp/consul/pull/6094 which will go in with the 1.6 release.

**Pull request closed without merging**
