### PR TITLE
connect: update SNI label extraction to support new taxonomy for partitions

### PR DESCRIPTION
**Pull request by eculver**
For 1.11 and Admin Partitions, we updated the SNI taxonomy to include partition. Prior to 1.11, cluster names use our SNI pattern:
```
<subset>.<service>.<namespace>.<datacenter>.internal.<trustdomain>.consul
```

The updates to the SNI for 1.11 are summarized by:
- If the partition is non-default, the internal infix is renamed to be `internal-v1`.
- If the partition is the default, the SNI is unchanged.

To support this, I had to update the patterns to include a optional capture group for the partition. @freddygv helped put together some examples in regex101.com for demonstration:
- [pre 1.11 pattern](https://regex101.com/r/OP9Yrk/1)
- [updates from this PR](https://regex101.com/r/I6TtVs/1)

For the reviewer this change is going to be pretty cryptic, so I would suggest looking at the test case being added that includes all the permutations of components for the SNI.

### CODE REVIEW

**Comment by kisunji** [comment]
Looks like there's other tests that need to be updated as a result of this PR

**Review by dhiaayachi — APPROVED** [review]
LGTM!!
is there any documentation related to this to be updated?

**Comment by eculver** [comment]
> is there any documentation related to this to be updated?

Good question. I didn't see anything that referenced the existing labels, but I'll give it another pass.

**Review by kisunji — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/524229.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit a0c754d44f904ee15dd7e34aacbc6f4c839f2146 onto `release/1.11.x` succeeded!

**Pull request merged**
