### PR TITLE
docs: fix exported-services to use ConfigEntryReference block

### PR DESCRIPTION
**Pull request by rboyer**

### CODE REVIEW

**Review by trujillo-adam — CHANGES_REQUESTED** [review]
I think this is a step backward. We should be moving away from lists for this type of content because they are more difficult for readers to process.
What is the reason for this change?

**Comment by rboyer** [comment]
It basically reverts the k8s-parity added by https://github.com/hashicorp/consul/pull/9416 which allowed a single config entry kind doc to work for the consul json/hcl format as well as the slightly different k8s yaml formats without a lot of duplication of efforts. Unfortunately this component only generates list forms, but the inputs are structured data so in theory the component could be updated to switch them all to a table + child specific sub-tables.

**Comment by karl-cardenas-coding** [comment]
@trujillo-adam and @rboyer were you two able to come to an agreement on next steps for this PR?

**Comment by jmurret** [comment]
Closing as this is over two years old.

**Pull request closed without merging**
