### PR TITLE
Give code blocks coloured background

### PR DESCRIPTION
**Pull request by lkysow**
This will make them stand out more and matches the style of terraform.io

### CODE REVIEW

**Comment by lkysow** [comment]
Before:
image

After:
image

**Comment by alvin-huang** [comment]
I'd also run this by @jescalan.

**Comment by johncowen** [comment]
Hey @lkysow 

I noticed you chatting through this offline, great spot btw! Anyway, thought I'd take a quick look and just thought I'd mention what I noticed just incase.

The code you've changed is for `#inner .alert code` and the `.alert` caught my eye and I thought 'somebody must have put that code there originally for a reason'. So then the whole thing gets weirder when you look at Web Inspector for the current site:

Screenshot 2019-09-20 at 10 46 56

Notice that the active selector doesn't include the `.alert` (a similar selector with `.alert` is in the group of selectors but is not 'active'), oh also just incase in that screengrab `consul.exe` only has a grey background because I have it selected with my cursor.

Now the entire thing is weird, I'm thinking I must be missing something as the change you made works fine as I can see from the preview. I'm just wondering if we need to check that we haven't done something to whatever `.alert` is that means any code within it is unreadable.

No biggie but I'm gonna take a bit of a deeper look in a sec, as I'm intrigued, shout me when you are around.

Cheers,

**Comment by banks** [comment]
I like it. 👍 Will like John approve once he's happy with the CSS thing.

**Comment by johncowen** [comment]
Ok at first I thought there things might be getting compiled differently all of a sudden, but I took a quick look and false alarm there. Then I noticed this change doesn't just change `#inner .alert code` but a bunch of other things also (which explains the screengrab above). So, I would guess this is all fine, as briefly looking at the other selectors it make sense, I can't imagine why the `transparent` was ever there in the first place? 1 other thing I did notice though, I think the text was intended to be Consul magenta color:

Screenshot 2019-09-20 at 11 35 45

But maybe not, I'm not entirely sure! Whichever, this is much better.

**Pull request merged**
