### PR TITLE
docs: ExportedServices YAML correction

### PR DESCRIPTION
**Pull request by david-yu**
Correcting ExportedServices reference and example

### CODE REVIEW

**Review by trujillo-adam — APPROVED** [review]
LGTM - thanks for fixing

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/533491.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit bd011ab7b6a5e91f8dc6080028312c612a5f8ff7 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit bd011ab7b6a5e91f8dc6080028312c612a5f8ff7 onto `release/1.11.x` succeeded!

**Pull request merged**
