### PR TITLE
website: remove source code

### PR DESCRIPTION
**Pull request by BRKalow**
* Removes website source code, which now lives in hashicorp/dev-portal
* Removes algolia indexing job, now handled elsewhere
* Removes website docker image job, we're using a separate, centralized image

### CODE REVIEW

**Review by dstaley — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/643837.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/643890.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 239c84a5c1bd08e9d0d674f3e32b5afe77a1862d onto `stable-website` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/643890)

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 239c84a5c1bd08e9d0d674f3e32b5afe77a1862d onto `release/1.12.x` succeeded!

**Pull request merged**
