### PR TITLE
oss: use wildcard partition in metrics proxy ui endpoint

### PR DESCRIPTION
**Pull request by kyhavlov**

### CODE REVIEW

**Review by freddygv — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/525160.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/530226.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit b50ef696c67117af8cbd32c854aa04c334273dab onto `release/1.11.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/530269.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit b50ef696c67117af8cbd32c854aa04c334273dab onto `release/1.11.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/530269)

**Pull request merged**
