### PR TITLE
docs: remove BETA from Consul K8s CLI

### PR DESCRIPTION
**Pull request by david-yu**
- Remove references to BETA
- Add more commands for GA

### CODE REVIEW

**Review by ndhanushkodi — APPROVED** [review]

**Review by karl-cardenas-coding — APPROVED** [review]
lgtm

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/533001.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 147c6724d52e968781cda4230d4169e97c34194a onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 147c6724d52e968781cda4230d4169e97c34194a onto `release/1.11.x` succeeded!

**Pull request merged**
