### PR TITLE
docs: rename enterprise to Consul enterprise

### PR DESCRIPTION
**Pull request by karl-cardenas-coding**
This PR renames the documentation sidebar collection name `Enterprise Features` to `Consul Enterprise`. This is to follow the same pattern as the other products (Nomad, and Vault).

### CODE REVIEW

**Review by blake — APPROVED** [review]
LGTM.

I also tagged Jasmine to provide her feedback.

**Comment by jnwright** [comment]
LGTM!

**Review by jnwright — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/374093.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 63762ac2506e09ee930945b42bddc53d00180730 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 63762ac2506e09ee930945b42bddc53d00180730 onto `release/1.10.x` succeeded!

**Pull request merged**
