### PR TITLE
AgentRPC takes agent via an interface

### PR DESCRIPTION
**Pull request by njbennett**
We're working on some code that interacts with the agent via RPC.  For tests of this client, it is useful to mock out the Agent, but still lean on the AgentRPC.

This change enables us to pass a mock Agent object into the AgentRPC constructor.

cc @rosenhouse

### CODE REVIEW

**Comment by slackpad** [comment]
Hi @njbennett sorry for the late reply on this one! This is a pretty low-level interface and not really intended for use by other applications. Are you using the AgentRPC directly in your app and not the HTTP endpoints?

**Comment by rosenhouse** [comment]
cc: @ryanmoran @zankich you guys are maintaining [Consul Release](https://github.com/cloudfoundry-incubator/consul-release) now, right?

**Comment by rosenhouse** [comment]
@slackpad  The functionality we needed (rotating encryption keys) is not available in the HTTP API.  In https://github.com/hashicorp/consul/issues/1368 we were told that RPC interface was not internal.

**Comment by slackpad** [comment]
@rosenhouse ah ok now I understand the full context. This RPC interface should eventually be replaced by HTTP endpoints, so I'd like to avoid adding more public stuff related to it (we will give a clear heads up before we deprecate anything). Would you have any issues switching to an HTTP endpoint if that was available? I'd prefer to not merge this and focus on that instead.

**Comment by ryanmoran** [comment]
@slackpad speaking on behalf of @rosenhouse we would prefer to only interact with consul over HTTP if that were possible. We were only using the RPC client out of necessity.

**Comment by slackpad** [comment]
@ryanmoran ok thanks - I'll close this against https://github.com/hashicorp/consul/issues/1867 which tracks adding an HTTP endpoint for this.

**Pull request closed without merging**
