### PR TITLE
docs: consul-k8s service mesh overview - move verification section

### PR DESCRIPTION
**Pull request by david-yu**
The `Verifying the Installation` section seemed out of place at the bottom. Moving it higher up.

### CODE REVIEW

**Review by jmurret — APPROVED** [review]
👍

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/601117.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit c8865be799a8493f7fa4ef0ce626153c14777a3f onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit c8865be799a8493f7fa4ef0ce626153c14777a3f onto `release/1.11.x` succeeded!

**Pull request merged**
