### PR TITLE
Fix broken links for roles and service identities

### PR DESCRIPTION
**Pull request by swenson**
### Description
Fix broken links on `acl/auth-methods` page for roles and service identities

### Testing & Reproduction steps
N/A

### Links
N/A

### PR Checklist

* [x] updated test coverage
* [x] external facing docs updated
* [x] not a security concern
* [ ] checklist [folder](./../docs/config) consulted

### CODE REVIEW

**Comment by swenson** [comment]
Sorry, I don't have permissions for the `consul` repository, so I can't label the PR or merge it.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/663993.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 7dbe048dbff1359c40060fbf37044c90daecd9f2 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 7dbe048dbff1359c40060fbf37044c90daecd9f2 onto `release/1.12.x` succeeded!

**Pull request merged**
