### PR TITLE
Adding NIA to Consul Ent page

### PR DESCRIPTION
**Pull request by pcmccarron**

### CODE REVIEW

**Review by karl-cardenas-coding — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/440953.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit cd47e2b57260bbef3c93ef6e2392eb97bfb27f8b onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit cd47e2b57260bbef3c93ef6e2392eb97bfb27f8b onto `release/1.10.x` succeeded!

**Pull request merged**
