### PR TITLE
ui: %horizontal-kv-list CSS component (and related)

### PR DESCRIPTION
**Pull request by johncowen**
Possibly our most used component in Consul UI is this kind of thing:

Screenshot 2021-05-26 at 15 53 50

Sometimes we use it with icons like above, sometimes without, sometimes with a list of things (like our tag listing), sometimes with a pill/badge rounded background, and sometimes with a 'text: value' (and probably more things)

We use them in our listings, our detail pages, for our 'badges' (Kinds and ExternalSources) in menus and probably other places.

Overall we use it a lot.

This PR uses `docfy` to isolate the individual parts and options and investigates the _why_ you might use certain options and document _how_ you might use certain options.

Originally we used a single `%icon-definition` CSS component to represent this, but seeing as some of them don't have icons, it didn't seem like the best name. So this PR splits this component into various different ones and then uses the new ones to continue to provide a now deprecated `%icon-definition`.

The component is currently a CSS only component that assumes a single (or multiple) [description lists](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl) for its markup component, and provides for multiple different options (including a reversed mode which I'm still not totally sure about, but we don't use this right now anyway).

- `%icon-definition` [Docs](https://consul-ui-staging-4m6k3t7cv-hashicorp.vercel.app/ui/docs/components/icon-definition)
- `%horizontal-kv-list` [Docs](https://consul-ui-staging-4m6k3t7cv-hashicorp.vercel.app/ui/docs/components/horizontal-kv-list)
- `%csv-list` [Docs](https://consul-ui-staging-4m6k3t7cv-hashicorp.vercel.app/ui/docs/components/csv-list)
- `%tag-list` [Docs](https://consul-ui-staging-4m6k3t7cv-hashicorp.vercel.app/ui/docs/components/tag-list)
- `%badge` [Docs](https://consul-ui-staging-4m6k3t7cv-hashicorp.vercel.app/ui/docs/components/badge)

There's potentially more to come in the description here, but thought I could take this out of draft as it is.

### CODE REVIEW

**Review by kaxcode — APPROVED** [review]
oh, first time I notice the class types. Sorry, I thought this was still in draft. LGTM

**Comment by kaxcode** [comment]
@johncowen looks like this needs a rebase.

**Comment by johncowen** [comment]
Quick note: I've added a backport 1.10.x here, but I think I would like to wait to merge this until 1.10.0 is frozen and merge this onto 1.10.x then.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/390237.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit ac424187fe8a38962393e08b39186a0bb0b73890 onto `release/1.10.x` succeeded!

**Pull request merged**
