### PR TITLE
Fix Windows logging to files

### PR DESCRIPTION
**Pull request by kisunji**
closes https://github.com/hashicorp/consul/issues/11773

Our logger uses [`io.MultiWriter`](https://pkg.go.dev/io#MultiWriter) which at minimum writes to `os.Stdout` and optionally to syslog or log file targets.

When Consul is run as a Windows Service, `os.Stdout` is not available and any writes by the logger fails silently, which inadvertently stopped writes to other targets because of `io.MultiWriter`'s behaviour:
```
If a listed writer returns an error, that overall write operation stops 
and returns the error; it does not continue down the list.
```

This PR uses a `noErrorWriter` wrapper which never returns an error so that even if writes to Stdout fail, writes to syslog and log file are unaffected.

### CODE REVIEW

**Review by dnephin — COMMENTED** [review]
Nice fix!

`UIWriter` also strips trailing newlines, I wonder if that might cause other problems.

Would this also work?

```go
type noErrorWriter struct {
    w io.Writer
}

func (w noErrorWriter) Write(p []byte) (n int, err error) {
    n, _ := w.w.Write(p)
    return n, nil
}
```

**Review by dnephin — APPROVED** [review]
Nice! Thanks for debugging and fixing this!

**Comment by kisunji** [comment]
Testing on windows: 
image

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/542579.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 08af4f7ffca9f96e1f55fec8d81e83208a706e5b onto `release/1.11.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 08af4f7ffca9f96e1f55fec8d81e83208a706e5b onto `release/1.10.x` succeeded!

**Pull request merged**
