### PR TITLE
Adding UI screenshots to L7 overview

### PR DESCRIPTION
**Pull request by jnwright**
- replaced current diagram under "Stages" with screenshot of UI
CleanShot 2022-01-10 at 14 32 55@2x

- added screenshots to routing, splitting, and resolution sections:

CleanShot 2022-01-10 at 14 33 04@2x
CleanShot 2022-01-10 at 14 33 12@2x
CleanShot 2022-01-10 at 14 33 19@2x

### CODE REVIEW

**Review by hannahhearth — APPROVED** [review]
These screenshots are great. Love that you've called attention to specific areas with the pink border. I think this will help people visualizations L7 routing really easily!

**Comment by Amier3** [comment]
All done on my end 👍

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/547942.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 665c9933ce8b9814783c7018bafbac77036bedfb onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 665c9933ce8b9814783c7018bafbac77036bedfb onto `release/1.11.x` succeeded!

**Pull request merged**
