### PR TITLE
website: update alert banner

### PR DESCRIPTION
**Pull request by mwickett**
Updates alert banner content to promote HashiConf US 2021

[_Created by Sourcegraph campaign `mwickett/update-alert-banner-hashiconf-2021`._](https://sourcegraph.hashi-mktg.com/users/mwickett/campaigns/update-alert-banner-hashiconf-2021)

### CODE REVIEW

**Review by blake — APPROVED** [review]
LGTM.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/430184.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 39b3c3e2bddc519ac1b79ca471967afd0c6d1641 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 39b3c3e2bddc519ac1b79ca471967afd0c6d1641 onto `release/1.10.x` succeeded!

**Pull request merged**
