### PR TITLE
agent: ensure we hash the non-deprecated upstream fields on ServiceConfigRequest

### PR DESCRIPTION
**Pull request by rboyer**

### CODE REVIEW

**Review by dnephin — APPROVED** [review]
LGTM!

And also answers the TODO question I left in #9556

**Review by markan — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/369074.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 7e1d7803b8b33b22796a7aac3cdf2bcbc3acd69f onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 7e1d7803b8b33b22796a7aac3cdf2bcbc3acd69f onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/369074)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 7e1d7803b8b33b22796a7aac3cdf2bcbc3acd69f onto `release/1.8.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/369074)

**Pull request merged**
