### PR TITLE
Update stray ref to old admin-partition cmd

### PR DESCRIPTION
**Pull request by freddygv**
Related to #11682

The CLI command was renamed but the sidebar hadn't been updated to reflect it.

Preview: https://consul-84c6uqi8c-hashicorp.vercel.app/commands/partition

### CODE REVIEW

**Review by msiege2 — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/523686.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 09136441413fb3fe24bcd083b5d7332d6a9c6bed onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 09136441413fb3fe24bcd083b5d7332d6a9c6bed onto `release/1.11.x` succeeded!

**Pull request merged**
