### PR TITLE
Bump `go-discover` to fix broken dep tree

### PR DESCRIPTION
**Pull request by jeffwidman**
The previous version of `go-discover` pulled in a broken version of
`tencentcloud-sdk-go`, resulting in anything that runs `go get -d`
downstream breaking... ie, a dep on hashicorp consul will break
Dependabot (among other things).

I already fixed it in `go-discover`, so this just pulls in the update.

More details in
hashicorp/go-discover@657e803
and hashicorp/go-discover#172.

Unfortunately, it looks like pulling this in also forces a couple of k8s
packages to get updated. I did not manually bump these... they were the
outcome of running `go mod tidy`.

### CODE REVIEW

**Comment by kisunji** [comment]
Thanks for the diligence @jeffwidman !

Unfortunately as our CI shows, this version bump includes a transitive dependency update which has breaking API changes.
There is some ongoing work internally to be able to update our k8s versions, but this PR will be unable to be merged until that is resolved.

I'll check with the team and circle back to you

**Comment by jeffwidman** [comment]
> Unfortunately as our CI shows, this version bump includes a transitive dependency update which has breaking API changes.
There is some ongoing work internally to be able to update our k8s versions, but this PR will be unable to be merged until that is resolved.

Yep, as soon as I saw it was bumping k8s, I was like "I guess I'll be checking back in 6 months on this one...". Lots of work to stay updated with that ecosystem, so I completely understand and empathize.

**Comment by eculver** [comment]
So we're waiting on confirmation that this version is supported correct?

**Comment by kisunji** [comment]
> So we're waiting on confirmation that this version is supported correct?

I thought it would be a messy resolution but I found a similar PR that was closed last year: https://github.com/hashicorp/consul/pull/9030. I don't think we ever followed through with the upgrade in our new releases.

I'll apply some of the changes in that PR (seems to be adding a few params) and see if that gets the CI building.

**Review by kisunji — APPROVED** [review]

**Comment by kisunji** [comment]
Managed to get this building! Thanks again @jeffwidman

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/447727.

**Comment by jeffwidman** [comment]
Awesome! Thanks @kisunji for pushing this across the line.

**Pull request merged**
