### PR TITLE
Backport of add docs for consul-k8s config read command into release/1.15.x

### PR DESCRIPTION
**Pull request by hc-github-team-consul-core**
## Backport

This PR is auto-generated from #17461 to be assessed for backporting due to the inclusion of the label backport/1.15.

:rotating_light:
>**Warning** automatic cherry-pick of commits failed. If the first commit failed,
you will see a blank no-op commit below. If at least one commit succeeded, you
will see the cherry-picked commits up to, _not including_, the commit where
the merge conflict occurred.

The person who merged in the original PR is:
@david-yu
This person should manually cherry-pick the original PR into a new backport PR,
and close this one when the manual backport PR is merged in.

> merge conflict error: unable to process merge commit: "4a22f34b599242962638bd0f85c054da6cdac30f", automatic backport requires rebase workflow

The below text is copied from the body of the original PR.

---

This PR adds documentation for the functionality introduced in https://github.com/hashicorp/consul-k8s/pull/2078.

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [ ] appropriate backport labels added
* [ ] not a security concern

---

<details>
<summary> Overview of commits </summary>

  - 6e537507efda59ac982febb9cf0b921140317922  - fbdab01e8548635ff86ebc0ae1241ea35ce0d20f  - 4a22f34b599242962638bd0f85c054da6cdac30f  - 54bcb95a25308f1f905809cbc83902bdb9bf37f5 

</details>

### CODE REVIEW

**Review by github-team-consul-core-pr-approver — APPROVED** [review]
Auto approved Consul Bot automated PR

**Comment by hanshasselberg** [comment]
This PR is fine as is -- only merge commits didn't make it in here.

**Comment by david-yu** [comment]
@hanshasselberg I can merge for you when 1.1.2 is released.

**Comment by hanshasselberg** [comment]
@david-yu sounds good, letting you merge this one. I will try to keep an eye out on the ent merge.

**Pull request merged**
