### PR TITLE
Backport some ent changes for serf tags

### PR DESCRIPTION
**Pull request by dnephin**
Also add a changelog for the fix which motivated these changes

### CODE REVIEW

**Review by mkeeler — APPROVED** [review]

**Review by markan — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/372258.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit d5dec9399249c0889d52ab063285208c9ce52ed0 onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit d5dec9399249c0889d52ab063285208c9ce52ed0 onto `release/1.9.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit d5dec9399249c0889d52ab063285208c9ce52ed0 onto `release/1.8.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/372258)

**Pull request merged**
