### PR TITLE
[Streaming][bugfix] handle TLS signalisation when TLS is disabled on client side (alternative to #9494)

### PR DESCRIPTION
**Pull request by pierresouchay**
Tnis is an alternative to https://github.com/hashicorp/consul/pull/9494

We just patch the GRPC side, not everything as suggested by @dnephin

### CODE REVIEW

**Review by dnephin — COMMENTED** [review]
Nice! looks good! Do you think it would be possible to write a test for `newDialer` that fails without this change? I think there is an integration test somewhere that uses a stub RPC server that might work.

**Comment by pierresouchay** [comment]
@dnephin Done! 

Added unit test in new commit on this PR: https://github.com/hashicorp/consul/pull/9512/commits/c5a2e3a90dbf48d8d87e9ed35753ed06d996acce 

Putting this file on current master fails, succeeds with this patch.

**Review by dnephin — APPROVED** [review]
LGTM!

**Comment by dnephin** [comment]
Those integration tests seem to be failing on master, so not related to this change.

**Pull request merged**
