### PR TITLE
Adds default set of accept headers for HTTP checks.

### PR DESCRIPTION
**Pull request by slackpad**

### CODE REVIEW

**Comment by macbash** [comment]
@slackpad - Any idea tcp health isn't working for me, I'm running mongo container as per the reference in http://gliderlabs.com/registrator/latest/user/backends/#backend-reference ( consul tcp check ) , but in consul UI i didn't see the health point. Version : 0.6.4. please advise me.

**Comment by slackpad** [comment]
Hi @macbash can you provide a little more detail about "i didn't see the health point"? Is the check not getting registered or is it registered but not working?

**Comment by macbash** [comment]
Check is not registered for TCP..

**Comment by slackpad** [comment]
@macbash the TCP check is relatively new to Consul. Is it possible you have an older version of registrator? You might want to ask the registrator folks about this problem as it sounds like it's not registering the check with Consul for some reason. Sorry about that.

**Comment by klynch** [comment]
Setting the Host header would be extremely useful for us as well.

**Pull request merged**
