### PR TITLE
Use header to send Consul token rather than query param.

### PR DESCRIPTION
**Pull request by jefferai**

### CODE REVIEW

**Comment by slackpad** [comment]
LGTM

**Comment by vishalnayak** [comment]
Cool! LGTM.

**Comment by slackpad** [comment]
Added to CHANGELOG - https://github.com/hashicorp/consul/commit/6a3076296543515fbf8892161d80c25f2c828435.

**Comment by leprechau** [comment]
I've worked up a really simple test that doesn't even use a consul server.  It really looks like the 0.7.0 api client isn't sending the header.

https://github.com/leprechau/api-test

```
-- New Request --
Request URL: /v1/kv/?recurse=
Request Header: User-Agent => [Go-http-client/1.1]
Request Header: Referer => [http://localhost:9900/v1/kv//?recurse=]
Request Header: Accept-Encoding => [gzip]
-- End-Of-Request --

-- New Request --
Request URL: /v1/kv/?recurse=
Request Header: User-Agent => [Go-http-client/1.1]
Request Header: Referer => [http://localhost:9900/v1/kv//?recurse=]
Request Header: Accept-Encoding => [gzip]
-- End-Of-Request --
```

**Pull request merged**
