### PR TITLE
Validate ServiceID/CheckID when deregistering.

### PR DESCRIPTION
**Pull request by foostan**
I think delete an agent node unintentionally when deregistering with empty ID.
For example, 
```
# current nodes
$ curl http://127.0.0.1:8500/v1/catalog/nodes
[{"Node":"mba.local","Address":"192.168.11.5"}]

# current services
$ curl http://127.0.0.1:8500/v1/catalog/services
{"consul":[],"web":[]}

# deregister service with empty ID
$ curl http://127.0.0.1:8500/v1/agent/service/deregister/

# nodes are missing!
$ curl http://127.0.0.1:8500/v1/catalog/nodes
[]

# services are missing!
$ http://127.0.0.1:8500/v1/catalog/services
{}
```

So ignore L122 and execute L133?
https://github.com/hashicorp/consul/blob/master/consul/fsm.go#L122-L137

My PR is adding validation of empty ServiceID/CheckID when deregistering.
Please check it.

### CODE REVIEW

**Comment by ryanuber** [comment]
This LGTM. Can we add some tests for this to make sure deregistering without an ID does not delete the entire node? We should probably also guard this in `deleteService()` in `local.go`, which is what actually assembles the `DeregisterRequest`, which ultimately is what causes the entire node to be deleted.

**Comment by foostan** [comment]
Thanks! I'll add some tests and move validaters to deleteService()/deleteCheck().

**Comment by foostan** [comment]
Add some tests and validator in local.go.
Should I add some tests for deleteService()/deleteCheck() in local.go?

**Comment by ryanuber** [comment]
@foostan this LGTM! I merged before I read your question about adding tests, so I added them in 58eba95. Thanks for the fix!

**Comment by foostan** [comment]
>  I merged before I read your question about adding tests, so I added them in 58eba95. 

Thank you for accepting PR and helping me!

**Pull request merged**
