### PR TITLE
GH-8728 add raft default values

### PR DESCRIPTION
**Pull request by jjshanks**
Add raft default values to default config used by the agent endpoint.

### CODE REVIEW

**Review by freddygv — APPROVED** [review]
Looks good, thanks!

**Comment by dnephin** [comment]
Added a changelog entry

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/370380.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit ce5ef18911902bfc6cc671bea090e143aa90b7c6 onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit ce5ef18911902bfc6cc671bea090e143aa90b7c6 onto `release/1.9.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit ce5ef18911902bfc6cc671bea090e143aa90b7c6 onto `release/1.8.x` succeeded!

**Pull request merged**
