### PR TITLE
ui: Upgrade d3 packages to update color dependency

### PR DESCRIPTION
**Pull request by sarahalsmiller**
### Description
Update D3 packages to resolve DoS issue

### Testing & Reproduction steps
- CI Passes and UI deployment looks as expected

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [ ] appropriate backport labels added
* [ ] not a security concern

### CODE REVIEW

**Review by philrenaud — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
@sarahalsmiller, a backport is missing for this PR [21588] for versions [1.15,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by philrenaud** [comment]
Backports in fact were merged yesterday:

[1.19](https://github.com/hashicorp/consul/pull/21597)
[1.15](https://github.com/hashicorp/consul-enterprise/pull/9691)

**Comment by hc-github-team-consul-core** [comment]
@sarahalsmiller, a backport is missing for this PR [21588] for versions [1.15,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by jmurret** [comment]
hey @philrenaud for manual backports you need to add the list of commits so `backport-assistant` picks them up.  You will need to add this:
```
---

<details>


 

 <summary> Overview of unprocessed commits </summary>

 
 * [e1350c9e2ef2b6436dfca01276da827e175da283](https://github.com/hashicorp/consul/commit/e1350c9e2ef2b6436dfca01276da827e175da283)
 
 * [b3a423b7663549372cd4766092cfa921d6614b53](https://github.com/hashicorp/consul/commit/b3a423b7663549372cd4766092cfa921d6614b53)
 
 * [04d2887ed42b3a59b0101f9712caee30c422cb83](https://github.com/hashicorp/consul/commit/04d2887ed42b3a59b0101f9712caee30c422cb83)
 
 * [e12eff0cc2e43dfe769ab97532cd3577b5bbbc0a](https://github.com/hashicorp/consul/commit/e12eff0cc2e43dfe769ab97532cd3577b5bbbc0a)
 
</details>
```

which are the commits specific this change as it relates to  PR comments like [this](https://github.com/hashicorp/consul/pull/21588#issuecomment-2288251024) 

I've copied these from one of the [PRs](https://github.com/hashicorp/consul-enterprise/pull/9691) that `backport-assistant` auto generated when this was merged.

**Comment by hc-github-team-consul-core** [comment]
@sarahalsmiller, a backport is missing for this PR [21588] for versions [1.15,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@sarahalsmiller, a backport is missing for this PR [21588] for versions [1.15,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@sarahalsmiller, a backport is missing for this PR [21588] for versions [1.15,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@sarahalsmiller, a backport is missing for this PR [21588] for versions [1.15,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@sarahalsmiller, a backport is missing for this PR [21588] for versions [1.15,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@sarahalsmiller, a backport is missing for this PR [21588] for versions [1.15,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@sarahalsmiller, a backport is missing for this PR [21588] for versions [1.15,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@sarahalsmiller, a backport is missing for this PR [21588] for versions [1.15,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@sarahalsmiller, a backport is missing for this PR [21588] for versions [1.15,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@sarahalsmiller, a backport is missing for this PR [21588] for versions [1.15,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@sarahalsmiller, a backport is missing for this PR [21588] for versions [1.15,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@sarahalsmiller, a backport is missing for this PR [21588] for versions [1.15,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@sarahalsmiller, a backport is missing for this PR [21588] for versions [1.15,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by philrenaud** [comment]
@zalimeni yes, I think this probably should also have been backported. Seems like there was a failed cherry-pick in both backports. I'll give it a look shortly

**Comment by philrenaud** [comment]
Oops! I see that you'd already resolved those. Approved both!

**Comment by zalimeni** [comment]
> Oops! I see that you'd already resolved those. Approved both!

Yeah @jmurret was quick - thank you for the look!

**Pull request merged**
