### PR TITLE
convert windows style path to posix style path

### PR DESCRIPTION
**Pull request by gaoxinge**
I use the `agent.NewTestAgent` api in windows:

```go
func TestSomething(t *testing.T) {
	a := agent.NewTestAgent(t, t.Name(), "")
	a.Shutdown()
}
```

It will raise `illegal char escape` error because the temp file, generated by code 

https://github.com/hashicorp/consul/blob/fc9fcdfa53ec09ae11eec815a64638907d9c49d6/agent/testagent.go#L125

is `C:\Users\gaoxinge\AppData\Local\Temp\agent833109515` with windows style path split `\`.

Further more, I think we should treat a slash in this situtation as a path split instead of an escape, so we should convert the windows style path into posix style path.

Reference

- https://github.com/hashicorp/hcl/issues/282

### CODE REVIEW

**Comment by i0rek** [comment]
Thank you for your work @gaoxinge! Is this still something you are interested in adding?

**Comment by gaoxinge** [comment]
@i0rek There is nothing that I want to add further.

**Comment by i0rek** [comment]
@gaoxinge thank you for your reply. It seems like our CLA tool cannot tell if you signed it or not. Probably because your username is different from the one in the commit. Can you do something about that?

**Comment by gaoxinge** [comment]
@i0rek I have signed the CLA for hashicorp.

**Pull request merged**
