### PR TITLE
ui: Alias all our Structure Icons to Flight Icons

### PR DESCRIPTION
**Pull request by johncowen**
This PR updates our `styles/base` with the output from `iris`, so just machine generated code.

User facing change is: We are now using `@hashicorp/flight-icons` 🎉 

[Preview Link](https://consul-ui-staging-h46yyck1w-hashicorp.vercel.app/ui/dc1/services)

Screenshot 2022-01-27 at 14 20 53

Small note: There are a few icons where the sizing or padding or something has changed, for example:

Screenshot 2022-01-27 at 14 19 46

I'm going to look at these an PR separately ontop of here and potentially merge those onto here, but I'd be perfectly happy for this PR to go in before those little fixups and for the whatever work is involved in fixing up those odd icons to go in after. As always, I'm easy.

cc @didoo just an FYI that we are doing this now.

### CODE REVIEW

**Comment by johncowen** [comment]
Quick note, just pushed a commit to move the aliased icons use the thicker-lined 16px icons. The change is basically this https://github.com/johncowen/iris/commit/adc72741a650183cf43770ef28ccb764d64e7f8a followed by a re-build/re-publish.

**Review by amyrlam — CHANGES_REQUESTED** [review]
I did some QA and found this, need to tweak the alignment. It's hard to read the code diff, I'm not sure exactly what's wrong yet... but please fix this one:

image

**Comment by amyrlam** [comment]
Note: I have not done an exhaustive QA of the UI.

**Comment by johncowen** [comment]
Thankyou! Take a look at https://github.com/hashicorp/consul/pull/12222. I didn't want to merge that one down here until this was approved, this one is machine generated so wanted to keep the entire PR like that for approval. If thats the only requested change, happy to merge that in now?

**Comment by johncowen** [comment]
K #12222 is merged, should have fixed up that stray icon, you can see the change for that in #12222

**Review by amyrlam — APPROVED** [review]
🎨

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/572992.

**Pull request merged**
