### PR TITLE
mesh: add concrete wrapper types

### PR DESCRIPTION
**Pull request by rboyer**
### Description

Introduces some generated `DecodedResource[X, *X]` wrappers for each type which cut down on the verbosity in my own code so instead of having something like:

```
stuff map[resource.ReferenceKey]*resource.DecodedResource[pbmesh.HTTPRoute, *pbmesh.HTTPRoute]
```
you have
```
stuff map[resource.ReferenceKey]*wrappedtypes.HTTPRoute
```

(part of NET-5052)

### CODE REVIEW

**Comment by rboyer** [comment]
#18352 introduced something similar in `internal/mesh/internal/intermedate/types.go`

**Review by ishustava — APPROVED** [review]
That's awesome! I'll try to consolidate the types I introduced so that it's more consistent with this.

**Review by mkeeler — CHANGES_REQUESTED** [review]
I think I would prefer we avoid the codegen here and use type aliasing where desired to elide all the generic type parameters

**Comment by rboyer** [comment]
@mkeeler 

Alternate PR: https://github.com/hashicorp/consul/pull/18448

**Pull request closed without merging**
