### PR TITLE
sync enterprise files with oss

### PR DESCRIPTION
**Pull request by kisunji**
Updates to test files and comments from enterprise PR feedback

### CODE REVIEW

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/417226.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 9c3af1a4298add7161512bc2bc817eb6d67f6531 onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/417226)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 9c3af1a4298add7161512bc2bc817eb6d67f6531 onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/417226)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 9c3af1a4298add7161512bc2bc817eb6d67f6531 onto `release/1.8.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/417226)

**Pull request merged**
