### PR TITLE
add gobetween to the Consul tools

### PR DESCRIPTION
**Pull request by shantanugadgil**
add gobetween to the Consul tools

@eveld

### CODE REVIEW

**Comment by shantanugadgil** [comment]
no clue why CircleCI is failing as this is just a documentation change! 🤷‍♂️

**Comment by shantanugadgil** [comment]
> LGTM.
> 
> Minor thing, from a style perspective it looks like the project name should be all lowercase (i.e., gobetween).

Ok, but I am super confused 😕 There are many other projects with first letter capital!

**Comment by blake** [comment]
I was referring to the fact that name gobetween isn't capitalized on the project's GitHub or website (gobetween.io). I assumed the project prefers the name to be stylized as lowercase.

This is super minor and not worth holding up the PR. Thanks for your contribution to add this to Consul's list of community tools.

**Comment by shantanugadgil** [comment]
> 
> 
> I was referring to the fact that name gobetween isn't capitalized on the project's GitHub or website (gobetween.io). I assumed the project prefers the name to be stylized as lowercase.
> 
> This is super minor and not worth holding up the PR. Thanks for your contribution to add this to Consul's list of community tools.

fixed ... gobetween is now all small case

**Pull request merged**
