### PR TITLE
Added QueryOptions for status api

### PR DESCRIPTION
**Pull request by bogdanov1609**
Added QueryOptions for status api, according to the documentation https://www.consul.io/api/status.html

### CODE REVIEW

**Comment by bogdanov1609** [comment]
Added the use of a variable Datacenter and two tests with wrong dc

**Comment by bogdanov1609** [comment]
> LGTM! Thank you for your contribution!

Let's merge then? :)

**Comment by bogdanov1609** [comment]
@i0rek ping?

**Comment by Sinketsu** [comment]
Hello!
May be merge it? This will be useful for my project!

**Comment by jsosulska** [comment]
Hello All - Once an Approval is made, it is generally the original user who will merge in the change. I will merge this as it has been approved.

**Comment by mikemorris** [comment]
👋 Just wanted to update y'all that these functions have been renamed to `LeaderWithQueryOptions(q *QueryOptions)` and `PeersWithQueryOptions(q *QueryOptions)` in https://github.com/hashicorp/consul/pull/8395 to avoid breaking the prior function signature.

Thanks for adding this!

**Pull request merged**
