### PR TITLE
test: fix compat integration error from new access log api

### PR DESCRIPTION
**Pull request by DanStough**
### Description
This fixes failures in the integration test suite for upgrades. The problem was caused by using the latest version of `api` module, with new fields, against the upgrade source of Consul, resulting in a 400 error. [This causes the tests to timeout](https://app.circleci.com/pipelines/github/hashicorp/consul/48423/workflows/9e8c0326-6824-4888-98d4-e01ef42f45aa/jobs/1099014). 

This isn't a fix for the problem so much as removing a nice-to-have step. All the values in the proxy-default are assumed to be the fault, so the effect is negligible.

### CODE REVIEW

**Review by huikang — APPROVED** [review]

**Comment by huikang** [comment]
> ### Description
> 
> This fixes failures in the integration test suite for upgrades. The problem was caused by using the latest version of `api` module, with new fields, against the upgrade source of Consul, resulting in a 400 error. [This causes the tests to timeout](https://app.circleci.com/pipelines/github/hashicorp/consul/48423/workflows/9e8c0326-6824-4888-98d4-e01ef42f45aa/jobs/1099014).
> 

@DanStough , thanks for fixing this. Having a question about what caused the problem: I observed that the error occurs when the test code constructs clusters using images of old version https://github.com/hashicorp/consul/blob/ab199a11b0d37f3f943936c8f26eaa43918e0b6f/test/integration/consul-container/test/upgrade/peers_http_test.go#L51-L60

So should the root cause be `using the latest version of `api` module, with new fields, against the __old__ source of Consul, resulting in a 400 error. `? Please correct me if I am wrong.


```        	Error Trace:	./test/integration/consul-container/test/upgrade/helpers.go:131
        	            				./test/integration/consul-container/test/upgrade/peers_http_test.go:60
        	            				./test/integration/consul-container/test/upgrade/asm_amd64.s:1594
        	Error:      	Received unexpected error:
        	            	Unexpected response code: 400 (Request decoding failed: 1 error occurred:
        	            		* invalid config key "AccessLogs")
        	Test:       	TestPeering_UpgradeToTarget_fromLatest/upgrade_from_1.14_to_local
2022/12/16 19:45:23 Container is ready id: 604bbd9dd3bd image: consul:1.14
    helpers.go:67: 
        	Error Trace:	/test/integration/consul-container/test/upgrade/helpers.go:67
        	            				/test/integration/consul-container/test/upgrade/peers_http_test.go:51
        	            				/test/integration/consul-container/test/upgrade/asm_amd64.s:1594
        	Error:      	Received unexpected error:
        	            	Unexpected response code: 400 (Request decoding failed: 1 error occurred:
        	            		* invalid config key "AccessLogs")

```

**Comment by eculver** [comment]
I'm having a hard time with the fact that _new_ fields in the request cause failures, but that's a separate issue altogether. We should definitely revisit this at some point.

**Review by eculver — CHANGES_REQUESTED** [review]
I was able to get this working by pinning a version of the api submodule and using that instead of the local version. I will link to the PR shortly.

**Comment by eculver** [comment]
> I was able to get this working by pinning a version of the api submodule and using that instead of the local version. I will link to the PR shortly.

See #15830.

**Comment by DanStough** [comment]
Closing this PR in favor of #15831

**Pull request closed without merging**
