### PR TITLE
ui: update Build-UI.dockerfile

### PR DESCRIPTION
**Pull request by mikemorris**
Bumps the Node.js minor version on `release/1.9.x` and `release/1.8.x` to allow `make ui` to successfully run locally - I'm guessing the older packages are no longer available from the remote but we're avoiding this issue in CI because of some caching layer? Prior to this change, it would fail with the following error:
```
Building UI build container
[+] Building -0.0s (5/6)
 => [internal] load build definition from Dockerfile                                                                                                                         0.0s
 => => transferring dockerfile: 436B                                                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                                                            0.0s
 => => transferring context: 2B                                                                                                                                              0.0s
 => [internal] load metadata for docker.io/library/alpine:3.11                                                                                                               1.0s
 => CACHED [1/3] FROM docker.io/library/alpine:3.11@sha256:20117524da64d995fd769f0aa3d7cfe2040518426f4b238f43e8373f4aa56c06                                                  0.0s
 => => resolve docker.io/library/alpine:3.11@sha256:20117524da64d995fd769f0aa3d7cfe2040518426f4b238f43e8373f4aa56c06                                                         0.0s
 => ERROR [2/3] RUN apk update &&     apk add nodejs=12.15.0-r1 nodejs-npm=12.15.0-r1 make=4.2.1-r2 &&     npm config set unsafe-perm true &&     npm install --global yarn  1.1s
------
 > [2/3] RUN apk update &&     apk add nodejs=12.15.0-r1 nodejs-npm=12.15.0-r1 make=4.2.1-r2 &&     npm config set unsafe-perm true &&     npm install --global yarn@1.19.1 &&     mkdir /consul-src:
#5 0.486 fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
#5 0.625 fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
#5 0.881 v3.11.11-73-gd2566ed888 [http://dl-cdn.alpinelinux.org/alpine/v3.11/main]
#5 0.881 v3.11.11-64-g27a30e0e72 [http://dl-cdn.alpinelinux.org/alpine/v3.11/community]
#5 0.881 OK: 11274 distinct packages available
#5 1.057 ERROR: unable to select packages:
#5 1.058   nodejs-12.22.1-r0:
#5 1.070     breaks: world[nodejs=12.15.0-r1]
#5 1.070     satisfies: npm-12.22.1-r0[nodejs]
#5 1.070   npm-12.22.1-r0:
#5 1.070     breaks: world[nodejs-npm=12.15.0-r1]
------
executor failed running [/bin/sh -c apk update &&     apk add nodejs=${NODEJS_VERSION} nodejs-npm=${NODEJS_VERSION} make=${MAKE_VERSION} &&     npm config set unsafe-perm true &&     npm install --global yarn@${YARN_VERSION} &&     mkdir /consul-src]: exit code: 2
make: *** [ui-build-image] Error 1
```

### CODE REVIEW

**Review by johncowen — APPROVED** [review]
LGTM!

**Comment by johncowen** [comment]
@mikemorris not sure if you meant to add a backport/1.9 here also?

**Comment by mikemorris** [comment]
Targets the `release/1.9.x` branch, so only the `backport/1.8` label is necessary (`release/1.10.x` and `main` are on newer major release versions and doesn't have this issue IIRC)

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit dd8b1cad68d5a08e4f8c5612c4662dd765c918d6 onto `release/1.8.x` succeeded!

**Pull request merged**
