### PR TITLE
[NET-10719] Fix cluster generation for jwt clusters for external jwt providers

### PR DESCRIPTION
**Pull request by jm96441n**
### Description

JWT clusters were previously not being created correctly, this adds the plumbing to handle this in the enterprise fork

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [ ] appropriate backport labels added
* [ ] not a security concern

### CODE REVIEW

**Review by missylbytes — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
@jm96441n, a backport is missing for this PR [21604] for versions [1.15,1.18] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@jm96441n, a backport is missing for this PR [21604] for versions [1.15,1.18] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@jm96441n, a backport is missing for this PR [21604] for versions [1.15,1.18] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@jm96441n, a backport is missing for this PR [21604] for versions [1.15,1.18] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@jm96441n, a backport is missing for this PR [21604] for versions [1.15,1.18] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@jm96441n, a backport is missing for this PR [21604] for versions [1.15,1.18] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Pull request merged**
