### PR TITLE
Add check for not reading files with an incorrect extension in the config directory

### LINKED ISSUE #4477: -config-file, -config-dir format and permissions issues
#### Overview of the Issue

I've edited a config file in the `-config-dir` with an editor via `sudo`. This leaves a backup copy with a suffix of `~`, owned by root. When restarting the server, it stops with 

    ==> config: ReadFile failed on /etc/consul.d/config.json~: open /etc/consul.d/config.json~: permission denied

I would expect the server to skip any files that it can't access, especially if they aren't matching the `*.json` or `*.hcl` pattern for config files.

#### Reproduction Steps

1. setup a server or agent, using `-config-dir`
2. add a file that is not accessible by consul
3. restart the server

### Consul info for both Client and Server

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 39f93f01
	version = 1.2.1
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 10.8.0.1:8300
	server = true
raft:
	applied_index = 81860
	commit_index = 81860
	fsm_pending = 0
	last_contact = 0
	last_log_index = 81860
	last_log_term = 22
	last_snapshot_index = 65556
	last_snapshot_term = 10
	latest_configuration = [{Suffrage:Voter ID:47e7f178-ca40-1043-39c0-c3ce9b3abdd7 Address:10.8.0.1:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 22
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 109
	max_procs = 2
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 8
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 125
	members = 7
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 15
	members = 1
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

Devuan jessie (debian w/o systemd), x64

### Log Fragments

    ==> config: ReadFile failed on /etc/consul.d/config.json~: open /etc/consul.d/config.json~: permission denied

### PR DESCRIPTION
**Pull request by shubheksha**
Fixes #4477

### CODE REVIEW

**Comment by shubheksha** [comment]
Running the agent works fine, we don't get a permission error anymore. However, there are some test failures that I've not been able to wrap my head around properly.

**Comment by mkeeler** [comment]
@shubheksha One of our ongoing projects is stabilizing the test suite. Many of the test failures in travis don't look related. Have you tried running tests locally?

**Comment by freddygv** [comment]
@shubheksha Thank you for submitting this PR! I'd like to help you finish it so that we can merge it for the next release.

I just ran the tests locally with: 
`go test -short -timeout 8m -v -p 3 -parallel 4 -tags '' "./..." 2>&1 |  egrep '^(ok|FAIL|panic:|--- FAIL)'`

I found that with these changes, the following tests aren't passing:
- TestValidateCommand_SucceedOnMinimalConfigDir
- TestValidateCommand_Quiet
- TestConfigFlagsAndEdgecases

The associated error for the top two is: `Config validation failed: Multiple private IPv4 addresses found.`

However in the tests themselves, we do pass a single IP into `bind_addr` of the config: https://github.com/hashicorp/consul/blob/master/command/validate/validate_test.go#L135

This suggests that the config in these tests is no longer being read, even though they contain valid json.

Could you look into why ReadPath might skip these config files?

Looking forward to seeing your changes to get these tests passing again.

**Comment by shubheksha** [comment]
Hey y'all, sorry for delay in getting back to this. Unfortunately, my laptop died so it'll take me some time to finish this up :(

**Comment by freddygv** [comment]
Hey @shubheksha sorry to hear about that, hopefully you were able to sort out your laptop problems. 

Let us know if you would still like to finish up this PR.

**Comment by freddygv** [comment]
Hi @shubheksha, we like your patch, but since we hadn't heard from you we went ahead and made the last edit ourselves (while preserving your commit). Thanks again for your contribution!

The new PR is: #5593.

**Pull request closed without merging**
