### PR TITLE
Update install.mdx; add port-forward missing namespace flag

### PR DESCRIPTION
**Pull request by artemkozlenkov**
add the  missing namespace flag to kubectl port-forwad

### CODE REVIEW

**Review by karl-cardenas-coding — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/537550.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit f94763f3f6f63c3b0bbe0332fa87962e1fc7c6f7 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit f94763f3f6f63c3b0bbe0332fa87962e1fc7c6f7 onto `release/1.11.x` succeeded!

**Pull request merged**
