### PR TITLE
[Website] Update community tools page to add condenserdotnet

### PR DESCRIPTION
**Pull request by Drawaes**
Would be good if this could be added to your page. Supplies higher level functionality wrapped up such as leader election and service with health registration etc.

### CODE REVIEW

**Comment by Drawaes** [comment]
Bounce?

**Comment by slackpad** [comment]
Thanks!

**Comment by Drawaes** [comment]
Cool!

**Comment by Drawaes** [comment]
Time to get that consul api router on asp.net core finished!

**Pull request merged**
