### PR TITLE
docs: ECS docs for beta

### PR DESCRIPTION
**Pull request by ishustava**

### CODE REVIEW

**Review by trujillo-adam — APPROVED** [review]
LGTM

**Review by pglass — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/448386.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 770c67a7e322cef0b8e26ae1f2f3e410bd3cf2d7 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 770c67a7e322cef0b8e26ae1f2f3e410bd3cf2d7 onto `release/1.11.x` succeeded!

**Pull request merged**
