### PR TITLE
Update Helm Docs for v0.36.0 Consul K8s release

### PR DESCRIPTION
**Pull request by t-eckert**
Consul on Kubernetes released version 0.36.0 on 2 November 2021. This pull request updates the documentation for the Helm chart to reflect values released in this version and the previous version released.

### CODE REVIEW

**Review by david-yu — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/492505.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 875fa920c99f41f4f625186b4dd9b58e62ae2dc5 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 875fa920c99f41f4f625186b4dd9b58e62ae2dc5 onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/492505)

**Pull request merged**
