### PR TITLE
docs: fix ExportedServices typo on example

### PR DESCRIPTION
**Pull request by david-yu**
Fix typo

### CODE REVIEW

**Review by blake — APPROVED** [review]

**Review by karl-cardenas-coding — APPROVED** [review]
Nice catch

**Review by msiege2 — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/533301.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 459746114ae59b65da0ba183343fec1306ab0693 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 459746114ae59b65da0ba183343fec1306ab0693 onto `release/1.11.x` succeeded!

**Pull request merged**
