### PR TITLE
ci: allow bash_env in load-test

### PR DESCRIPTION
**Pull request by alvin-huang**
This PR allows `BASH_ENV` to be used within the `hashicorp/terraform` image which is alpine based. 

I also fixed the cluster_name uniqueness. The variable was set in the CI run but the variable was never declared in TF config and passed to the module so it was never used 🤦 . Now each cluster should be uniquely named with the shortref

### CODE REVIEW

**Comment by alvin-huang** [comment]
I ran load tests on this commit just to try it and make sure it works. The uniqueness can be seen in the TF apply with output like: 
```
  # module.load-test.module.consul_servers.aws_security_group.lc_security_group will be created
  + resource "aws_security_group" "lc_security_group" {
      + arn                    = (known after apply)
      + description            = "Security group for the 9ae1b1fc8-server launch configuration" <----- here
      + egress                 = (known after apply)
      + id                     = (known after apply)
      + ingress                = (known after apply)
      + name                   = (known after apply)
      + name_prefix            = "9ae1b1fc8-server"
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Name" = "9ae1b1fc8-server" <----- here
        }
      + tags_all               = {
          + "Name" = "9ae1b1fc8-server" <----- here
        }
      + vpc_id                 = (known after apply)
    }
```

**Comment by alvin-huang** [comment]
I am not sure of the errors in the run though. Is that a legit consul error?

**Review by dnephin — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/372482.

**Pull request merged**
