### PR TITLE
Local tag service discovery

### PR DESCRIPTION
**Pull request by ekristen**
Initial attempt at implementing a special tag `local` that returns DNS records for a service only if it is registered with the local agent. Basically uses the advertised IP address of the agent compared to the service address to determine if it is local or not.

This is the ticket I originally opened about this feature. https://github.com/hashicorp/consul/issues/1229

### CODE REVIEW

**Comment by slackpad** [comment]
What would you think about replacing `service` with `local` in the query, instead of adding a reserved tag (eg. `db.local.consul`.)? This way there's no potential conflict for anybody with an existing `local` tag. It might also be good to use `agent` instead of `local` so it's more clear where things are associated (ie. `db.agent.consul`).

**Comment by ekristen** [comment]
@slackpad that isn't a bad option. I'd probably need someone's assistance to make that happen though. 

However my only counter comment is that we could make the `local` tag configurable and change it to something like `local-agent` by default, something that has a low probability of being used already. 

This method just leaves all the existing conventions as is, but if you or someone else can/will help with the path you suggested, I'm all for it.

I just really need a way to get the IP/port into for "local" services to the agent and I think there is a pretty good use case in general for it.

Thanks!

**Comment by slackpad** [comment]
I'll take a look at this as I'm working on some prepared query stuff that's in the same part of the code.

**Comment by ekristen** [comment]
@slackpad thanks! My golang experience is limited (as evident by the PR) but if you can make this work, or you need my help, please let me know.

**Comment by ekristen** [comment]
@slackpad any progress on this by chance? Thanks!

**Comment by slackpad** [comment]
@ekristen not yet - I'm hoping to get to prepared queries next week.

**Comment by slackpad** [comment]
I don't think this will be able to make it into 0.6 since we are trying to not expand the scope at this point now than an RC has been cut, but I'll see about getting this into the following release.

**Comment by slackpad** [comment]
https://github.com/hashicorp/consul/pull/2137 will enable this feature with a simple prepared query so I'll close this out in favor of that.

**Pull request closed without merging**
