### PR TITLE
Fix terraform aws variables

### PR DESCRIPTION
**Pull request by sathiyas**
Added the AWS Provisioner details and corresponding variables. Also added the optional Tag details which will have a nice thing to do when Launching servers

### CODE REVIEW

**Comment by armon** [comment]
@phinze Thoughts?

**Comment by sathiyas** [comment]
If you run with egress rules, AWS throws an error, it gets created without mentioning it

**Comment by phinze** [comment]
Hi @sathiyas - thanks for this contribution!

I think the `egress` rule confusion is just a matter of using the latest version of Terraform. In 0.5.0 we changed the behavior of security groups to avoid the implicitly created egress rule, so it needs to be in the config now.

As for the provider variables, it's actually important to leave those out of the module definition to support users who are configuring their provider via environment variables.

I think the name tag is a good idea though. Can you re-push this PR with just the name tag stuff?

**Comment by sathiyas** [comment]
Sure @phinze,will do shortly

**Comment by sathiyas** [comment]
@phinze, modified, tested and submitted. Thanks for quick review

**Comment by phinze** [comment]
Looks good - thank you @sathiyas!

**Comment by phinze** [comment]
Answering a question from @sathiyas here for public record.

> I have question on why you think the Provider info is not needed to run the stack.
> Without the follwowing block in my TF file, I cannot run the stack.

There are two ways to configure the provider without a `provider { ... }` declaration inside the module.

__One__: provider config inherits into modules, so you can simply configure the provider in the place where you invoke the module.

```js
module "consul" {
  source = "https://github.com/hashicorp/consul/blob/master/terraform/aws"  // ...
}
provider "aws" {
  access_key = "..."  // ...
}
```

__Two__: provider config can be provided solely via environment variables, so you can completely omit any `provider { ... }` blocks and simply set these environment variables:

```sh
export AWS_ACCESS_KEY_ID="..."
export AWS_SECRET_ACCESS_KEY="..."
export AWS_DEFAULT_REGION="..."
```

Either of these methods should work for you.

The important thing is that we omit the provider config from _inside_ the official Consul Terraform module, so that callers can choose which provider config style they prefer.

Hope this helps to clarify - let me know if you have any further questions!

**Pull request merged**
