### PR TITLE
fix ui style

### PR DESCRIPTION
**Pull request by beiciye**
Thank you for your effort for this program.

There are two UI problem

1. The text in this block overflow
image

2.In key/value panel,  the more the left items are, the more difficult to look up different key's value,
if I scroll to bottom , I can't get the value friendly

 image

wish to get your reply!

### CODE REVIEW

**Comment by whit537** [comment]
[Spurious test failure](https://travis-ci.org/hashicorp/consul/builds/262124329#L473)? Seems to be a theme—https://github.com/hashicorp/consul/pull/3785#issuecomment-357366766 https://github.com/hashicorp/consul/pull/3188#issuecomment-357791209. 😉

**Comment by whit537** [comment]
I don't see that this PR fixes the tags overflow issue.

```
mkdir foo
vi foo/service.json
```

```json
{"service": {"name": "overflow", "tags": 
    [ "foo"
    , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar"
    , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar"
    , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar"
    , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar"
    , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar"
    , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar"
    , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar" , "bar"
    , "baz"
     ], "port": 80}}
```

```
consul agent -dev -ui -data-dir=foo -config-dir=foo -node=foo
```

screen shot 2018-01-15 at 4 52 16 pm

**Comment by whit537** [comment]
> In key/value panel, the more the left items are, the more difficult to look up different key's value,
if I scroll to bottom , I can't get the value friendly

I'm not sure what this PR does for (2), either. Maybe I'm not picking up the changes properly? 🤔

**Comment by whit537** [comment]
Sorry for the noise. I've discovered `make -C ui watch`.

**Comment by whit537** [comment]
Yeah the fix on here for the tags overflow is insufficient. It breaks the thick left gray border and the vertical spacing and _still_ doesn't show all tags in super-long tag situations:

screen shot 2018-01-18 at 5 17 47 pm

The fix for the multiferous kv problem is also horked. The `booth` shouldn't overlap the key list, and doesn't stay fixed while scrolling.

screen shot 2018-01-18 at 5 21 08 pm

The behavior when a key is select is the same both on master and on this PR. It stays fixed while scrolling in both cases, so I'm not sure I understand the original issue.

**Comment by whit537** [comment]
I suggest closing this PR as stale, reticketing the first issue since it's reproducible and real.

**Comment by whit537** [comment]
P.S. Helper for the kv test:

```
for i in {1..100}; do consul kv put "foo-`printf %03d $i`" bar; done
```

**Comment by pearkes** [comment]
Thank you @beiciye for the PR.

Thanks @chadwhitacre -- you're right I think we can close this out given it is stale. In regards to the still existent overflow issue we are in the process of rewriting large aspects of the UI (to be released in the future) and we'll eventually deprecate the current (but soon old) version of the UI. We are still fixing critical issues (such as recent XSS problems) but have stopped other maintenance work given the relative fragility of it.

**Pull request closed without merging**
