### PR TITLE
agent/grpc: add counter metrics

### PR DESCRIPTION
**Pull request by dnephin**
Branched from #8961

Gauge metrics are great for understanding the current state, but can sometimes hide problems if there are many disconnect/reconnects.

This commit adds counter metrics for connections and streams to make it easier to see the count of newly created connections and streams.

### CODE REVIEW

**Review by i0rek — APPROVED** [review]
LGTM

**Review by mkcp — APPROVED** [review]
Looks good - just need to add some docs for the new and changed metrics to `telemetry.mdx` in this or a follow up PR!

**Comment by dnephin** [comment]
Thank you for the reviews! I will add the docs to this PR.

This PR is branched from #8961, so I'll need to merge that one first

**Comment by dnephin** [comment]
Pushed a commit with the docs

**Pull request merged**
