### PR TITLE
ui: Wrap service names on show and instance routes

### PR DESCRIPTION
**Pull request by WenInCode**
### Description
Moves labels/kinds/sources to the bottom row of the title, and allows wrapping of the title text. Actions (ip, create, edit, etc.) are in their own column on the right and bottom aligned to match with either the labels, if they are present, or the title. 

Makes it so the breadcrumb overflow is hidden with an ellipsis, and a tooltip is show with the value. I think we could rethink breadcrumbs/tooltips so that:
- you don't have to manually add the breadcrumbs for routes in the templates
- you don't have to manually add tooltips to specific breadcrumbs

However, I felt that I didn't need to add more scope to this ticket.

### Screenshots
**Before:**
Screen Shot 2022-09-27 at 4 30 08 PM
Screen Shot 2022-09-27 at 4 29 50 PM
Screen Shot 2022-09-27 at 4 29 31 PM
Screen Shot 2022-09-27 at 4 29 20 PM

**After:**
Screen Shot 2022-10-03 at 8 30 25 PM
Screen Shot 2022-10-03 at 8 30 11 PM
Screen Shot 2022-10-03 at 8 29 44 PM
Screen Shot 2022-10-03 at 8 29 31 PM
Screen Shot 2022-10-03 at 8 25 29 PM
ant to apply this everywhere. (thinking auth methods, etc.).

### Links
- [NET-964](https://hashicorp.atlassian.net/browse/NET-964)
- [Design](https://www.figma.com/file/D6yYLKYMnuWR40w1QtGcQ2/Wrapping-service-name?node-id=143%3A7970)

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [x] not a security concern

### CODE REVIEW

**Comment by jnwright** [comment]
tested and LGTM!

**Review by jnwright — APPROVED** [review]
tested and LGTM!

**Comment by jnwright** [comment]
@WenInCode yeah, that looks great! so:
1. actions will be right aligned to labels **or**
2. actions will be right aligned to service name if there are no labels
sounds good to me!

**Comment by WenInCode** [comment]
@jnwright Updated the description with the new look, please take another look when you have a minute :)

**Review by jnwright — APPROVED** [review]
looks great to me! 🎉

**Pull request merged**
