### PR TITLE
api/agent: Support HTTP service checks in client api

### PR DESCRIPTION
**Pull request by nicholascapo**

### CODE REVIEW

**Comment by armon** [comment]
Thanks!

**Comment by nicholascapo** [comment]
Sure.  Is it expected that this will make it into v0.5.0rc2?

**Comment by ryanuber** [comment]
@nicholascapo yep! Currently we don't have any special branches, we just tag master as we go for each release.

**Comment by nicholascapo** [comment]
Excellent, thanks!

**Pull request merged**
