### PR TITLE
server: ensure that central service config flattening properly resets the state each time

### PR DESCRIPTION
**Pull request by rboyer**
The prior solution to call reply.Reset() aged poorly since newer fields
were added to the reply, but not added to Reset() leading serial
blocking query loops on the server to blend replies.

This could manifest as a service-defaults protocol change from
default=>http not reverting back to default after the config entry
reponsible was deleted.

### CODE REVIEW

**Review by markan — APPROVED** [review]
This looks reasonable. 

I'm a little sad at the demise of Reset, (because I would love to see a little more encapsulation and factoring out of common code) but here it was only used once so shrug.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/369168.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 597448da4790aeae270e7fda74d355c6fc96756e onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 597448da4790aeae270e7fda74d355c6fc96756e onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/369168)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 597448da4790aeae270e7fda74d355c6fc96756e onto `release/1.8.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/369168)

**Pull request merged**
