### PR TITLE
ci: test BPA 0.4.1 with no-op doc change

### PR DESCRIPTION
**Pull request by zalimeni**
Add a newline to docs/README.md to test a backport without functional changes.

Uses BPA 0.4.1: https://github.com/hashicorp/consul/blob/zalimeni/test-bpa-0.4.1/.github/workflows/backport-assistant.yml#L22

### Description

This is a no-op change.

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [x] appropriate backport labels added
* [x] not a security concern

### CODE REVIEW

**Comment by zalimeni** [comment]
Backport labels applied correctly from `backport/all`, then new runs of BPA opened correct PRs ^

**Comment by zalimeni** [comment]
`backport/1.17` label ignored as expected per https://github.com/hashicorp/consul/blob/6bf42140ce5e32a80ece56064b9d1da0e661e86d/.release/versions.hcl#L13 (`ce_active` is defaulted to `false`)

**Comment by hc-github-team-consul-core** [comment]
@zalimeni, a backport is missing for this PR [21091] for versions [1.18] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by zalimeni** [comment]
^ Disabling `backport-checker` for closed PR

**Comment by zalimeni** [comment]
@zalimeni, a backport is missing for this PR [21091] for versions [1.17] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by zalimeni** [comment]
^ test, ignore

**Comment by zalimeni** [comment]
@zalimeni, a backport is missing for this PR [21091] for versions [1.17] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@zalimeni, a backport is missing for this PR [21091] for versions [1.15,1.16] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Pull request merged**
