### PR TITLE
[Security] Bump envoy versions

### PR DESCRIPTION
**Pull request by sarahalsmiller**
### Description

Update envoy versions to most recent available versions. 

### Testing & Reproduction steps
- CI passes

### Links
https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [ ] appropriate backport labels added
* [ ] not a security concern

### CODE REVIEW

**Review by NiniOak — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @sarahalsmiller! a backport is missing for this PR [22002] for versions [1.15,1.18,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @sarahalsmiller! a backport is missing for this PR [22002] for versions [1.15,1.18,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @sarahalsmiller! a backport is missing for this PR [22002] for versions [1.15,1.18,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @sarahalsmiller! a backport is missing for this PR [22002] for versions [1.15,1.18,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @sarahalsmiller! a backport is missing for this PR [22002] for versions [1.15,1.18,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @sarahalsmiller! a backport is missing for this PR [22002] for versions [1.15,1.18,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by abhishek-hashicorp** [comment]
Removing the labels backport/ent/1.15, backport/ent/1.18, backport/ent/1.19 based on @sarahalsmiller's comment [here](https://github.com/hashicorp/consul-enterprise/pull/10201#issuecomment-2552424262).

**Pull request merged**
