### PR TITLE
Validate gossip encryption key before made persistent in local.keyring

### PR DESCRIPTION
**Pull request by rboyer**
This fixes https://github.com/hashicorp/consul/issues/1299

### CODE REVIEW

**Comment by rboyer** [comment]
Corresponding change to the memberlist library represented in the changes to the vendored code: https://github.com/hashicorp/memberlist/pull/87

**Comment by rboyer** [comment]
Is there anything I can do to move this along?

**Comment by slackpad** [comment]
Hi @rboyer sorry for the delay - working through a review backlog but this should make it into the next release for sure - looks like a good change.

**Comment by slackpad** [comment]
Thanks for fixing this! Merged after a rebase in #2270.

**Pull request closed without merging**
