### PR TITLE
Docs: updated versions on install page and other minor fixes.

### PR DESCRIPTION
**Pull request by Jeff-Apple**
### Description
Update some version numbers as part of the API Gateway v0.2.0 release and correcting minor Markdown issues

### Testing & Reproduction steps
Ran website locally

### PR Checklist

* [x] updated test coverage - NA
* [x] external facing docs updated
* [] not a security concern
* [x] checklist [folder](./../docs/config) consulted - N/A

### CODE REVIEW

**Review by andrewstucki — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/654925.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 62311368c625a6b45d60e46b85685d5894ad3b8a onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 62311368c625a6b45d60e46b85685d5894ad3b8a onto `release/1.12.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 62311368c625a6b45d60e46b85685d5894ad3b8a onto `release/1.11.x` succeeded!

**Pull request merged**
