### PR TITLE
use go 1.21.7

### PR DESCRIPTION
**Pull request by skpratt**
This bumps golang to avoid any change in the BoringCrypto module for FIPS builds: https://github.com/golang/go/issues/65321

### CODE REVIEW

**Review by zalimeni — APPROVED** [review]

**Comment by zalimeni** [comment]
@skpratt we typically add a changelog entry for these - copying from https://github.com/hashicorp/consul/pull/20062/files#diff-b0b11f4216bda65c2a8dbc878d1e646c7e0355af558118dee097199909b4afd6 you could use: 
````
```release-note:improvement
Upgrade to use Go 1.21.7.
```
````

**Comment by zalimeni** [comment]
We should also backport this to n-2 for consistency

**Comment by hc-github-team-consul-core** [comment]
@skpratt, a backport is missing for this PR [20545] for versions [1.15,1.16,1.17] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@skpratt, a backport is missing for this PR [20545] for versions [1.15,1.16,1.17] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
@skpratt, a backport is missing for this PR [20545] for versions [1.15,1.16,1.17] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Pull request merged**
