### PR TITLE
[docs] Add some notes about installing consul-helm in local k8s cluster

### PR DESCRIPTION
**Pull request by soonoo**
How about adding some tips about installing consul-helm in local kubernetes cluster?

### CODE REVIEW

**Comment by jsosulska** [comment]
Hi @soonoo 

Apologies on the long tail on the response, and thank you for opening this. I'd like to offer some feedback. 

This call out looks good. Have you tried running a helm `values.yml` file with only `server.replica:1`? This should provide you an appropriately configured dev cluster, like the example outlined in our [Minikube](https://learn.hashicorp.com/tutorials/consul/kubernetes-minikube) guide. I would also recommend making the call out in the [Customizing your Installation](https://www.consul.io/docs/k8s/installation/overview#customizing-your-installation) section.

As an addition - if there is a specific error being output, either by Consul or Kubernetes, and your recommendation fixes that error, I would add it to the [troubleshooting section](https://github.com/hashicorp/consul/blob/master/website/pages/docs/troubleshoot/common-errors.mdx). 

Let me know if there's anything I can help with, and thank you again for the contribution!
Best,
Jono

**Comment by soonoo** [comment]
Hi @jsosulska.
Thank you for response.

I just typed installation commands in [Installing Consul on Kubernetes](https://www.consul.io/docs/k8s/installation/overview) page. At that time, I expected it to succeed without any customization.  
However since my k8s cluster has only one worker node, installation with default `values.yml` failed while printing error message. Error message was about the failure to elect a leader. It took a while to figure out that I needed to fix `server.replicas` or to increase worker nodes.  

I'm not using Minikube so didn't notice that comment about `server.replicas` is in Minikube guide. 


It would be nice if it was added to the troubleshooting sectionr, but I'm not sure.(Since it is not common to have only one worker node)

**Comment by jsosulska** [comment]
Hi @soonoo 

Apologies for the incredibly long tail on this response. During the interim, we've updated all of our Kubernetes guides, as well as our website. Rather than have you rebase, I've added you on https://github.com/hashicorp/consul/pull/10293 as a co-author. I used the basis of your request to point to all of our learn guides, as those have individual deployment caveats. I hope this will be more clear :)

Thank you for the request, and for your patience!

**Comment by soonoo** [comment]
@jsosulska Thank you for reflecting my request!

**Pull request closed without merging**
