### PR TITLE
ui: Add AWS Lambda as potential external source

### PR DESCRIPTION
**Pull request by johncowen**
### Description
See title. This is essentially adding to our list of icons and updating the mocks to add the potential new external-source metadata. Currently we are using our existing generic AWS icon. Expects the `external-source` value to be exactly `lambda`.

Screenshot 2022-09-14 at 11 24 03

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [x] not a security concern

### CODE REVIEW

**Review by evrowe — APPROVED** [review]
Looks good!

**Comment by johncowen** [comment]
Quick note, I added a no-changelog considering this feature doesn't do anything without the backend work being finished up

**Comment by evrowe** [comment]
@johncowen That seems fine so long as we make sure that there is some kind of changelog entry for this when the release goes out, whether it's from us or from backend

**Comment by johncowen** [comment]
Gotcha, I'll add something to the ticket open for this

**Pull request merged**
