### PR TITLE
Updating consul on k8s to remove known limitations of serverAdditionalDNSSans and serverAdditionalIPSans

### PR DESCRIPTION
**Pull request by jmurret**
This limitation was enabled last week with https://github.com/hashicorp/consul-k8s/pull/1020

### CODE REVIEW

**Review by lkysow — APPROVED** [review]
Just checking that this is released?

**Review by trujillo-adam — APPROVED** [review]

**Review by thisisnotashwin — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/593798.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit f956e662072fe1f403c973a8acfdde5fb7650bde onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit f956e662072fe1f403c973a8acfdde5fb7650bde onto `release/1.11.x` succeeded!

**Pull request merged**
