### PR TITLE
replace mutex as atomic, less memory

### PR DESCRIPTION
**Pull request by SenseyeDeveloper**

### CODE REVIEW

**Comment by mkcp** [comment]
Hey @SenseyeDeveloper, welcome. Thanks for your interest in providing contributions for Consul!

Could you please provide a description of your change, especially in the future when dealing with more complex code changes. For this particular change in the state syncer, have you run some before and after benchmarks to confirm your change reduces the memory usage as expected? If so, could you share them? Thank you!

**Comment by SenseyeDeveloper** [comment]
@mkcp 

> have you run some before and after benchmarks to confirm your change reduces the memory
Reduce memory only in structure StateSyncer as removed property

```go
func (s *StateSyncer) Pause() {
	atomic.AddInt32(&s.paused, 1)
}

func (s *StateSyncer) PauseOld() {
	s.pauseLock.Lock()
	s.paused++
	s.pauseLock.Unlock()
}

// Paused returns whether sync runs are temporarily disabled.
func (s *StateSyncer) Paused() bool {
	return atomic.LoadInt32(&s.paused) != 0
}

func (s *StateSyncer) PausedOld() bool {
	s.pauseLock.Lock()
	defer s.pauseLock.Unlock()
	return s.paused != 0
}

// Resume re-enables sync runs. It returns true if it was the last pause/resume
// pair on the stack and so actually caused the state syncer to resume.
func (s *StateSyncer) Resume() bool {
	paused := atomic.AddInt32(&s.paused, -1)
	if paused < 0 {
		panic("unbalanced pause/resume")
	}

	trigger := paused == 0
	if trigger {
		s.SyncChanges.Trigger()
	}
	return trigger
}

func (s *StateSyncer) ResumeOld() bool {
	s.pauseLock.Lock()
	s.paused--
	if s.paused < 0 {
		panic("unbalanced pause/resume")
	}
	trigger := s.paused == 0
	s.pauseLock.Unlock()
	if trigger {
		s.SyncChanges.Trigger()
	}
	return trigger
}
```

```go
package ae

import "testing"

func BenchmarkStateSyncer_Pause(b *testing.B) {
	l := NewStateSyncer(nil, 0, nil, nil)

	for i := 0; i < b.N; i++ {
		l.Pause()
	}
}

func BenchmarkStateSyncer_PauseOld(b *testing.B) {
	l := NewStateSyncer(nil, 0, nil, nil)

	for i := 0; i < b.N; i++ {
		l.PauseOld()
	}
}

func BenchmarkStateSyncer_Paused(b *testing.B) {
	l := NewStateSyncer(nil, 0, nil, nil)

	for i := 0; i < b.N; i++ {
		l.Paused()
	}
}

func BenchmarkStateSyncer_PausedOld(b *testing.B) {
	l := NewStateSyncer(nil, 0, nil, nil)

	for i := 0; i < b.N; i++ {
		l.PausedOld()
	}
}

func BenchmarkStateSyncer_Resume(b *testing.B) {
	l := NewStateSyncer(nil, 0, nil, nil)

	l.paused = int32(b.N) + 1

	for i := 0; i < b.N; i++ {
		l.Resume()
	}
}

func BenchmarkStateSyncer_ResumeOld(b *testing.B) {
	l := NewStateSyncer(nil, 0, nil, nil)

	l.paused = int32(b.N) + 1

	for i := 0; i < b.N; i++ {
		l.ResumeOld()
	}
}
```

```text
_Pause-4       	160100785	         7.32 ns/op	       0 B/op	       0 allocs/op
_PauseOld-4    	55436031	        19.6 ns/op	       0 B/op	       0 allocs/op
_Paused-4      	1000000000	         0.381 ns/op	       0 B/op	       0 allocs/op
_PausedOld-4   	25208220	        45.6 ns/op	       0 B/op	       0 allocs/op
_Resume-4      	100000000	        10.3 ns/op	       0 B/op	       0 allocs/op
_ResumeOld-4   	51983314	        21.2 ns/op	       0 B/op	       0 allocs/op
```

**Comment by mkcp** [comment]
@SenseyeDeveloper Appreciate you showing some benchmarks for it. After discussing internally, we're not sure that there's a specific need to make this performance-related change. Is there a specific use case or pain point you're aware of, or have run into, that you intend for this PR to fix?

**Comment by SenseyeDeveloper** [comment]
> Is there a specific use case or pain point you're aware of, or have run into, that you intend for this PR to fix?

No

**Comment by mkcp** [comment]
Well, again we appreciate the contribution! The quality of your code is up to Consul's standards. In the future please try to provide more context around the intent of your work, especially ahead of time, so it is not wasted.

**Pull request closed without merging**
