### PR TITLE
[OSS] Remove remaining references to master

### PR DESCRIPTION
**Pull request by boxofrad**
This is the OSS port of enterprise PR 1443 (see that one for a commit-by-commit review).

### CODE REVIEW

**Comment by FFMMM** [comment]
@boxofrad thanks for taking this on!

Could we backport this to 1.10, 1.9 as well? Provided it's a no conflict merge/ doesn't require significant work on your part.

**Comment by boxofrad** [comment]
@FFMMM Do you mean just the internal changes (struct field names, test cases etc.) to make backporting other changes easier/avoid conflicts?

Some of that could be possible for sure, but it may make things a bit confusing, as the external-facing names would still be the old names in these versions.

**Comment by johncowen** [comment]
Just to note a quick removal of UI label,I saw it was a bot one, but I checked in case and the mock-api change is fine by me 👍

**Review by markan — APPROVED** [review]

**Comment by FFMMM** [comment]
> Some of that could be possible for sure, but it may make things a bit confusing, as the external-facing names would still be the old names in these versions. 

Makes sense!

---

There's currently a conflict but LGTM as well!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/560153.

**Pull request merged**
