### PR TITLE
Provide error if -ui and -ui-dir are both specified

### PR DESCRIPTION
**Pull request by slackpad**
This does a rebase of #2577 and tweaks the wording.

Closes #2577, #2903, #2576.

### CODE REVIEW

**Comment by tylerwalts** [comment]
This breaks for me on Windows, between using release `0.8.0 and `0.8.5`.  I do not use `ui_dir` (only `ui` set to `true`) in the config.  Since upgrading, I now get that (incorrect) error message, and now it will not launch.  Even adding in a line for `"ui_dir": ""` with blank string value I thought might work after looking at the diff, but does not. Maybe there is a default or something that only happens on Windows?

**Comment by slackpad** [comment]
@tylerwalts that's super strange - there's no special treatment of `ui-dir` on Windows that I can find. Is it possible you have a stray config file that's maybe getting picked up?

**Comment by tylerwalts** [comment]
Thanks for the quick response!  I verified no other config files exist, and simplified it down to this only to still reproduce the symptom:

```
{
  "addresses": {
    "http": "0.0.0.0"
  },
  "advertise_addr": "192.168.1.123",
  "datacenter": "foo",
  "log_level": "info",
  "node_name": "bar",
  "server": true,
  "ui": true
}
```


Results in log:
```
==> Both the ui and ui-dir flags were specified, please provide only one
```

**Comment by slackpad** [comment]
@tylerwalts thanks for checking - opened https://github.com/hashicorp/consul/issues/3229 to track this since this is a PR - I think we will need to fire up Windows and trace through this a bit; I can't think of any mechanism that would cause this.

**Pull request merged**
