### PR TITLE
[docs] update connect ca vault provider docs to include vault auth method field

### PR DESCRIPTION
**Pull request by kschoche**
Update the connect CA documentation for vault provider to include updated vault auth method field.

### CODE REVIEW

**Review by ishustava — APPROVED** [review]
🙏 thank you!

**Review by karl-cardenas-coding — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/605006.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit d6792f14a38ceebb3edba48f3fd9b56011f4e8e7 onto `stable-website` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/605006)

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit d6792f14a38ceebb3edba48f3fd9b56011f4e8e7 onto `release/1.11.x` succeeded!

**Pull request merged**
