### PR TITLE
IPV6 only deployments cli fix

### PR DESCRIPTION
**Pull request by burdandrei**
switching 127.0.0.1 to localhost to make consul cli work by default in IPv6 only environment

### CODE REVIEW

**Comment by burdandrei** [comment]
@mkeeler talk to me

**Comment by banks** [comment]
@burdandrei sorry for the delay here. The hold up was that the exact same change was rejected by the Vault team on grounds of an additional vulnerability to hostfile attacks (https://github.com/hashicorp/vault/issues/4903).

We are not sure the same is important to Consul as it's a different product but we are still evaluating if there is a real additional risk and if it's worth it for the convenience on v6 systems (which can always just set what they need explicitly).

**Comment by burdandrei** [comment]
all good @banks, no one is late =)
For the Vault it's understandable. Maybe for really tweaking it the best way is to implement `GetLocalhostIP` like `GetPrivateIP`

**Comment by mkeeler** [comment]
@burdandrei Are you in a situation where there is no 127.0.0.1 address on the machine or you have just instructed Consul not to use it?

For the case where it doesn't exist I was thinking a potential solution would be to have some logic in api.go that would look at the interface addresses on the system and if it doesn't find a 127.0.0.1 address then it would default it to ::1. This would just make it so that in default cases (default Consul configuration and default env) things can still connect when there is no ipv4 loopback.

**Comment by burdandrei** [comment]
I never had a chance to run IPv6 only deployment, only dualstack. So I had Consul listening on 0.0.0.0 and was advertising IPv6 address. Now that I'm thinking about that @Lasering did you manage to make loopback v6 only?

**Comment by Lasering** [comment]
When setting Consul to listen on 0.0.0.0 it will also advertise in IPv6 but AFAIK that quirk comes from Go (https://github.com/hashicorp/consul/issues/4306#issuecomment-401373703) and not from the OS. Also its a misleading behavior which, on my opinion, should not exist.

My development has been in a dualstack machine, but all my configurations are set to IPv6 values because that is my intention, aka, only to serve Consul in IPv6.

**Comment by mkeeler** [comment]
@burdandrei After talking this over with the vault team and internally I think we want to stick with the current behavior as its unlike to not have a ipv4 loopback. In scenarios where you modify the default bind addresses the expectation is that you will need corresponding env vars set for the consul binary to talk back to the agent. Therefore I am going to close this PR.

**Comment by burdandrei** [comment]
@mkeeler  All good.
@Lasering Doesn't loopback always listens on 127.0.0.1 ?

**Pull request closed without merging**
