### PR TITLE
docs: fix broken link

### PR DESCRIPTION
**Pull request by BhautikChudasama**
### Description

Fix broken link of `Chubby lock service`.

### PR Checklist

* [ ] updated test coverage
* [x] external facing docs updated
* [x] appropriate backport labels added
* [x] not a security concern

### CODE REVIEW

**Review by blake — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by abhishek-hashicorp** [comment]
@BhautikChudasama : Can you please check the backport for this PR?

**Comment by BhautikChudasama** [comment]
I don't understand how to backport can you help me? Is that any branch / tag? @abhishek-hashicorp

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @BhautikChudasama! a backport is missing for this PR [21971] for versions [1.15,1.18,1.19,1.20] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Pull request merged**
