### PR TITLE
add script to generate changelog for a PR

### PR DESCRIPTION
**Pull request by jm96441n**
### Description

QoL to generate changelog entries

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [ ] appropriate backport labels added
* [ ] not a security concern

### CODE REVIEW

**Review by zalimeni — APPROVED** [review]
This is great. Thank you!

**Review by nathancoleman — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @jm96441n! a backport is missing for this PR [21719] for versions [1.18] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @jm96441n! a backport is missing for this PR [21719] for versions [1.18] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @jm96441n! a backport is missing for this PR [21719] for versions [1.18] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Pull request merged**
