### PR TITLE
Include DC in the members command output

### LINKED ISSUE #942: Feature request: Include datacenter in consul members output.
I'm not sure everybody feels the same. But, I'm constantly in need of knowing exactly to what datacenter a member belongs too, when faced with this list:

### PR DESCRIPTION
**Pull request by tgwizard**
Fixes #942. Should I add more detailed tests?

### CODE REVIEW

**Comment by armon** [comment]
LGTM! Thanks!

**Comment by c4milo** [comment]
@tgwizard I think we could also remove the datacenter from the node name when listing WAN members, now that we have a column dedicated to that.

**Comment by tgwizard** [comment]
Hmm, @c4milo I don't think that is the datacenter but part of the actual node name. If I run it locally I get

```
↳ $ consul members
Node                     Address             Status  Type    Build  Protocol  DC
Adams-MacBook-Pro.local  192.168.1.148:8301  alive   server  0.5.1  2         dc1
```

**Comment by c4milo** [comment]
-wan

**Pull request merged**
