### PR TITLE
docs: fix helm stanza in admin-partitions

### PR DESCRIPTION
**Pull request by krastin**
### Description

The sample Helm chart for the Admin Partitions guide has a typo regarding the ACL system that would potentially fail the deployment when a practitioner blindly copy/pastes to deploy.

### PR Checklist

* [ ] updated test coverage
* [x] external facing docs updated
* [x] not a security concern

### CODE REVIEW

**Review by jkirschner-hashicorp — APPROVED** [review]
Thanks for catching this :)

**Comment by david-yu** [comment]
@krastin Could you rebase? Btw in the future if you prefix your branch with `docs` like `docs/krastin-docs-pr` we can skip integration tests.

**Comment by krastin** [comment]
> @krastin Could you rebase? Btw in the future if you prefix your branch with `docs` like `docs/krastin-docs-pr` we can skip integration tests.

Hey @david-yu ! I've updated my fork. Sorry about the branch naming, I will have the right prefix from now on. I tried renaming the branch but that closed the PR. Shall we force-merge this one or would you like me to draft a new PR? Thanks!

**Comment by david-yu** [comment]
No problem, I was able to merge but in the future please use a branch name with that prefix so its easier to get past the checks!

**Pull request merged**
