### PR TITLE
Add UpgradeConfig to HTTP Connection Manager

### PR DESCRIPTION
**Pull request by Legogris**
This should solve #8283 

Credit goes to @blake , I simply rebased his commit on master with small changes to get CI passing to get this PR considered for merging.

### CODE REVIEW

**Comment by evandam** [comment]
Hey @Legogris, looking forward to websocket support out of the box! I just wanted to confirm this 100% works right? I stumbled across https://github.com/envoyproxy/envoy/issues/5595 which seems like there's some extra config in `http2_protocol_options` needed but not sure if that's applicable here.

**Comment by blake** [comment]
@evandam I was able to get WebSocket upgrades to function by simply adding the UpgradeConfigs to the listener configuration, and did not need to add any additional config under `http2_protocol_options`. The description from the issue #8283 shows how WebSocket upgrades currently fail in Consul, and then succeed after applying this config patch https://github.com/hashicorp/consul/commit/fd993ccebb37ebdf5c08450da44a5ce8e22c6b30.

We are looking to submit a separate PR which will provide a configuration parameter to enable WebSocket upgrades on a per-service basis rather than explicitly enabling it for all services as is the case with this PR.

**Comment by neliseev** [comment]
Guys any news regards this feature requests? Maybe I can help you somehow for make it quickly, we really need support web sockets for our infrastructure. Thank you!

**Comment by markan** [comment]
Thank you for the PR.  

We're closing this because making it on by default isn't quite the behavior we need; it must be configurable on a per service basis. 

Supporting websocket upgrades in a configurable fashion is something we are interested in doing but haven't fully figured out the implementation details on. We'll track that work in the original issue (#8283)

**Comment by Legogris** [comment]
@markan I see - did that get anywhere?

**Comment by porterctrlz** [comment]
@markan @blake Looks like [#8283 ](https://github.com/hashicorp/consul/issues/8283) has stalled, any hope of getting momentum there?

**Pull request closed without merging**
