### PR TITLE
Bump x/net, client-go, and coredns dependencies to mitigate CVEs.

### PR DESCRIPTION
**Pull request by dlorenc**
### Description

These are probably not actually real, but show up in scanners. The bumps look safe, so I figured I'd send a PR.

This was the output of:

go get golang.org/x/net@v0.7.0
go get k8s.io/client-go@v0.20.1
go get github.com/coredns/coredns@v1.10.1
go mod tidy

The mitigated alerts are:

GHSA-vvpx-j8f3-3w6h
GHSA-8cfg-vx93-jvxw
GHSA-ch7v-37xg-75ph

and maybe more.

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [ ] not a security concern

### CODE REVIEW

**Comment by forty** [comment]
It would be nice to merge this MR, unfixed known vulnerabilities, even if not "actually real", are annoying for compliance.

**Comment by dlorenc** [comment]
> It would be nice to merge this MR, unfixed known vulnerabilities, even if not "actually real", are annoying for compliance.

FWIW I patched these over in our linux distro wolfi and things work there: https://github.com/wolfi-dev/os/blob/main/consul.yaml

Feel free to try that if you want clean scans.

**Comment by forty** [comment]
@dlorenc thanks for the suggestion, but unfortunately our scanner (AWS Inspector) only supports a few major distributions https://docs.aws.amazon.com/inspector/latest/user/supported.html#supported-os-ecr

**Comment by dlorenc** [comment]
> @dlorenc thanks for the suggestion, but unfortunately our scanner (AWS Inspector) only supports a few major distributions https://docs.aws.amazon.com/inspector/latest/user/supported.html#supported-os-ecr

Thanks, support will hopefully be coming soon there!

**Comment by david-yu** [comment]
Closing as the dependencies are now already updated in main

**Pull request closed without merging**
