### PR TITLE
Github Actions Migration - move verify-ci workflows to GHA

### PR DESCRIPTION
**Pull request by jmurret**
### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [ ] not a security concern

### CODE REVIEW

**Review by loshz — APPROVED** [review]
We should probably add a TODO or note somewhere to investigate if we still need this going forward so we can potentially remove this.

**Comment by jmurret** [comment]
@loshz yea, I am going to close for now and when we change the required GH Checks for PRs, let's see if we can't just remove this.  if we need it, we can re-open this.

**Comment by jmurret** [comment]
@loshz actually re-opening.  This is used as a `fail fast` check so that we detect when CI is down as quickly as possible.

**Comment by loshz** [comment]
> @loshz actually re-opening. This is used as a `fail fast` check so that we detect when CI is down as quickly as possible.

Sounds good. Do we need to run on push as well as pr?

**Pull request merged**
