### PR TITLE
Add version label to Docker image

### PR DESCRIPTION
**Pull request by marianoasselborn**
### Description
https://hashicorp.atlassian.net/browse/RELENG-20

### Testing & Reproduction steps
* In the case of bugs, describe how to replicate
* If any manual tests were done, document the steps and the conditions to replicate
* Call out any important/ relevant unit tests, e2e tests or integration tests you have added or are adding

### Links
Include any links here that might be helpful for people reviewing your PR (Tickets, GH issues, API docs, external benchmarks, tools docs, etc). If there are none, feel free to delete this section.

Please be mindful not to leak any customer or confidential information. HashiCorp employees may want to use our internal URL shortener to obfuscate links.

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [ ] not a security concern

### CODE REVIEW

**Review by alvin-huang — APPROVED** [review]

**Comment by marianoasselborn** [comment]
### Local testing

Build artifact:
```
✔ ~/Repos/hashicorp/consul [RELENG-20 L|…1]
12:39 $ make dev-build
mkdir -p bin
CGO_ENABLED=0 go install -ldflags "-X github.com/hashicorp/consul/version.GitCommit=249214624+CHANGES -X github.com/hashicorp/consul/version.BuildDate=2022-08-18T16:18:23Z " -tags ""
cp -f /Users/marianodonnet/go/bin/consul ./bin/consul
```
Move artifact:
```
✔ ~/Repos/hashicorp/consul [RELENG-20 L|…1]
12:39 $ mkdir -p dist/linux/amd64/ && cp ./bin/consul dist/linux/amd64/ && ls -lah dist/linux/amd64/
total 264192
drwxr-xr-x  3 marianodonnet  staff    96B Aug 18 12:36 .
drwxr-xr-x  3 marianodonnet  staff    96B Aug 18 12:36 ..
-rwxr-xr-x  1 marianodonnet  staff   120M Aug 18 12:41 consul
```
Build ubi image:
```
✔ ~/Repos/hashicorp/consul [RELENG-20 L|…1]
12:41 $ docker build --tag=consul:1.13.1-ubi --no-cache --target=ubi --build-arg PRODUCT_VERSION=1.13.1 --build-arg BIN_NAME=consul .
[+] Building 15.6s (14/14) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                     0.0s
 => => transferring dockerfile: 37B                                                                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                                                                        0.0s
 => => transferring context: 34B                                                                                                                                                                                         0.0s
 => [internal] load metadata for registry.access.redhat.com/ubi8/ubi-minimal:8.6                                                                                                                                         0.0s
 => CACHED [ubi 1/9] FROM registry.access.redhat.com/ubi8/ubi-minimal:8.6                                                                                                                                                0.0s
 => [internal] load build context                                                                                                                                                                                        2.0s
 => => transferring context: 125.90MB                                                                                                                                                                                    2.0s
 => [ubi 2/9] COPY LICENSE /licenses/mozilla.txt                                                                                                                                                                         0.1s
 => [ubi 3/9] RUN set -eux &&     microdnf install -y ca-certificates curl gnupg libcap openssl iputils jq iptables wget unzip tar &&     wget -O /usr/bin/dumb-init https://github.com/Yelp/dumb-init/releases/downlo  10.8s
 => [ubi 4/9] RUN groupadd consul &&     adduser --uid 100 --system -g consul consul                                                                                                                                     0.3s
 => [ubi 5/9] COPY dist/linux/amd64/consul /bin/                                                                                                                                                                         0.4s
 => [ubi 6/9] RUN mkdir -p /consul/data &&     mkdir -p /consul/config &&     chown -R consul /consul &&     chgrp -R 0 /consul && chmod -R g+rwX /consul                                                                0.4s
 => [ubi 7/9] RUN test -e /etc/nsswitch.conf || echo 'hosts: files dns' > /etc/nsswitch.conf                                                                                                                             0.3s
 => [ubi 8/9] COPY .release/docker/docker-entrypoint-ubi.sh /usr/local/bin/docker-entrypoint.sh                                                                                                                          0.0s
 => [ubi 9/9] RUN chmod +x /usr/local/bin/docker-entrypoint.sh                                                                                                                                                           0.3s
 => exporting to image                                                                                                                                                                                                   0.7s
 => => exporting layers                                                                                                                                                                                                  0.7s
 => => writing image sha256:c870c2785ce17452c67db2cf9ba847ae05a744a0276b684b8c1de36703e37e8d                                                                                                                             0.0s
 => => naming to docker.io/library/consul:1.13.1-ubi                                                                                                                                                                     0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
```
Build default image:
```
✔ ~/Repos/hashicorp/consul [RELENG-20 L|…1]
12:43 $ docker build --tag=consul:1.13.1 --no-cache --target=default --build-arg PRODUCT_VERSION=1.13.1 --build-arg BIN_NAME=consul .
[+] Building 7.7s (13/13) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                     0.0s
 => => transferring dockerfile: 37B                                                                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                                                                        0.0s
 => => transferring context: 34B                                                                                                                                                                                         0.0s
 => [internal] load metadata for docker.mirror.hashicorp.services/alpine:3.15                                                                                                                                            1.3s
 => CACHED [default 1/8] FROM docker.mirror.hashicorp.services/alpine:3.15@sha256:69463fdff1f025c908939e86d4714b4d5518776954ca627cbeff4c74bcea5b22                                                                       0.0s
 => [internal] load build context                                                                                                                                                                                        0.0s
 => => transferring context: 4.51kB                                                                                                                                                                                      0.0s
 => [default 2/8] RUN apk add -v --no-cache   dumb-init   libc6-compat   iptables   tzdata   curl   ca-certificates   gnupg   iputils   libcap   openssl   su-exec   jq                                                  3.4s
 => [default 3/8] RUN addgroup consul &&     adduser -S -G consul consul                                                                                                                                                 0.5s
 => [default 4/8] COPY dist/linux/amd64/consul /bin/                                                                                                                                                                     0.4s
 => [default 5/8] RUN mkdir -p /consul/data &&     mkdir -p /consul/config &&     chown -R consul:consul /consul                                                                                                         0.4s
 => [default 6/8] RUN test -e /etc/nsswitch.conf || echo 'hosts: files dns' > /etc/nsswitch.conf                                                                                                                         0.4s
 => [default 7/8] COPY .release/docker/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh                                                                                                                          0.0s
 => [default 8/8] RUN chmod +x /usr/local/bin/docker-entrypoint.sh                                                                                                                                                       0.3s
 => exporting to image                                                                                                                                                                                                   0.8s
 => => exporting layers                                                                                                                                                                                                  0.8s
 => => writing image sha256:133787a887cf35a3f917a51aef4a67f0ed7f287a6ed6a06b616c14efafc556f5                                                                                                                             0.0s
 => => naming to docker.io/library/consul:1.13.1                                                                                                                                                                         0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
```
Check images:
```
✔ ~/Repos/hashicorp/consul [RELENG-20 L|…1]
12:44 $ docker image ls | grep consul | grep "1.13.1"
consul                                        1.13.1       133787a887cf   39 seconds ago       153MB
consul                                        1.13.1-ubi   c870c2785ce1   About a minute ago   290MB
```
Check versions on each image:
```
✔ ~/Repos/hashicorp/consul [RELENG-20 L|…1]
12:47 $ for id in $(docker image ls | grep consul | grep "1.13.1" | awk '{print $3}'); do echo "$id: $(docker inspect --format='{{ index .Config.Labels "version" }}' $id)"; done
133787a887cf: 1.13.1
c870c2785ce1: 1.13.1
```
Check ``opencontainer`` version:
```
✔ ~/Repos/hashicorp/consul [RELENG-20 L|…1]
12:47 $ for id in $(docker image ls | grep consul | grep "1.13.1" | awk '{print $3}'); do echo "$id: $(docker inspect --format='{{ index .Config.Labels "org.opencontainers.image.version" }}' $id)"; done
133787a887cf: 1.13.1
c870c2785ce1: 1.13.1
```

**Comment by marianoasselborn** [comment]
See [00dda33](https://github.com/hashicorp/consul/pull/14204/commits/00dda337e65f55c6c5619dee6599d80a7cbd9560) for full CI run.

**Review by alvin-huang — APPROVED** [review]

**Comment by alvin-huang** [comment]
Can someone from @hashicorp/consul-core have a quick look?

**Review by mdeggies — APPROVED** [review]
Thanks for adding the tests! I must have messed something up locally during my testing. Appreciate the 💯 PR

**Comment by marianoasselborn** [comment]
All backports merged, thanks everyone 👍

**Pull request merged**
