### PR TITLE
docs: Add annotations for consul-sidecar resource overrides

### PR DESCRIPTION
**Pull request by ishustava**
Add docs for https://github.com/hashicorp/consul-k8s/pull/956

Note: this will need to be merged together or after the next consul-k8s release

### CODE REVIEW

**Review by david-yu — APPROVED** [review]
LGTM

**Review by thisisnotashwin — APPROVED** [review]
💥

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/569052.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit ea375742e138a60d8363caa95129c9c6cf076a41 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit ea375742e138a60d8363caa95129c9c6cf076a41 onto `release/1.11.x` succeeded!

**Pull request merged**
