### PR TITLE
Add TOC to helm reference

### PR DESCRIPTION
**Pull request by lkysow**

### CODE REVIEW

**Review by david-yu — APPROVED** [review]
LGTM

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/459862.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit dfc74f56f5a197f1c797d47cc8c9246a8d767bb3 onto `stable-website` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/459862)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit dfc74f56f5a197f1c797d47cc8c9246a8d767bb3 onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/459862)

**Comment by lkysow** [comment]
Manually cherry picked to stable-website and release/1.10.x

**Pull request merged**
