### PR TITLE
Added docs link to Learn tutorial for Kind.

### PR DESCRIPTION
**Pull request by DerekStrickland**
Added docs link to Learn tutorial for Kind. Also, updated some links that I saw were pointing to legacy urls.

### CODE REVIEW

**Review by kschoche — APPROVED** [review]
Excellent work!

**Comment by alvin-huang** [comment]
I manually picked these over to:

stable-website: e2d713adf7780bd6df1d67d7d07a40f799f2ce04
release/1.8.x: eb710f47119a9fc6cb9e272fd33cef791be84024

**Comment by DerekStrickland** [comment]
So did I do something wrong here? If so, do we know what? I'd love to avoid
it in the future :P

**Comment by alvin-huang** [comment]
Oh no you're good, usually the auto cherry picking will do it fine but sometimes it merge conflicts and you will have to resolve it manually. The CircleCI `unauthorized` error that we were seeing was fixed so after you reran it, the automation posted those comments ^ in the PR saying it was unable to cherry-pick (usually due to merge conflict). There was a conflicting PR that was merged into `master` that was also not picked to `stable-website` so I picked that and then picked yours over cleanly.

**Pull request merged**
