### PR TITLE
docs: Add HCL examples to agent config options

### PR DESCRIPTION
**Pull request by blake**

### CODE REVIEW

**Review by karl-cardenas-coding — APPROVED** [review]
👍🏼

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/554039.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit a3c0f748f58af364c6e91cda9619a0292b144044 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit a3c0f748f58af364c6e91cda9619a0292b144044 onto `release/1.11.x` succeeded!

**Pull request merged**
