### PR TITLE
Return every time lock acquisition fails

### PR DESCRIPTION
**Pull request by babbottscott**
Attempt to address https://github.com/hashicorp/consul/issues/800

Not sure how to pursue a negative test case for this.

### CODE REVIEW

**Comment by babbottscott** [comment]
@armon or others, can I get a review on this, time permitting?

**Comment by armon** [comment]
@babbottscott Does this change the behavior? It seems like the same behavior as before

**Comment by armon** [comment]
NVM I see the output is much improved, thanks!

**Comment by babbottscott** [comment]
It's not just output.  The previous test would continue when err was nil, even though lockCh was also nil.  If lockCh is nil, it must return.

**Comment by babbottscott** [comment]
In any event, many thanks!

**Pull request merged**
