### PR TITLE
docs: Formatting for Consul K8s uninstall commands

### PR DESCRIPTION
**Pull request by david-yu**
Formatting issue on command, add $ prior to command. Also ensure bulleted numbers are in correct order.

### CODE REVIEW

**Review by karl-cardenas-coding — APPROVED** [review]
👍🏼

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/551031.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit a17c78ab21d45b37cbafdb2fbc4313786abee11c onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit a17c78ab21d45b37cbafdb2fbc4313786abee11c onto `release/1.11.x` succeeded!

**Pull request merged**
