### PR TITLE
ui: Disabling policy form fields from users with 'read' permissions

### PR DESCRIPTION
**Pull request by kaxcode**
### 🐛 Description:
User with `read` permission can `edit` policies. An error message denying their request appears. The change temporarily appears in policy list page. The changes do not persist. Refreshing the page resets the changes.

### 💻 Replication Steps:

Using a new Consul cluster with ACLs enabled with default deny.

- Create the a new policy with the following rules:
acl = "read" 
operator = "read" 
service_prefix "" { policy = "write" }
node_prefix "" { policy = "write" }
agent_prefix "" { policy = "write" }
- Create a new Role
- Update the Anonymous Token to use the new Role and Policy
- Log off and log back in with Anonymous Token
- Try to update a Policy name

### 🎉 Solution:

Fix up a typo in the `canWrite()` permission for policy.

Now, the user can't edit any policies because form fields are disabled. 

### 🧪 Testing:

Test coverage can be found [here](https://github.com/hashicorp/consul/blob/main/ui/packages/consul-ui/tests/acceptance/dc/acls/policies/update.feature#L19. ).

### 📝 PR Tasks:

- [x]  Backport
- [x]  Changelog

### CODE REVIEW

**Comment by johncowen** [comment]
Oh no! 😬 Thanks for spotting this, I'm pretty sure this isn't related to the original issue, if I'm not mistaken the original bug was reported in 1.9.5?

I think this is a fix here, but I don't think it's the whole story. The code with the typo in that you fixed here was only added to 1.10.x so doesn't explain the 1.9.5 bug report. Not sure whether you want to do it all in separate chunks or not? Also could we maybe think of adding a test here? The link you added here is a link to existing tests that test something else, not entirely sure what you meant there?

**Comment by kaxcode** [comment]
> Oh no! 😬 Thanks for spotting this, I'm pretty sure this isn't related to the original issue, if I'm not mistaken the original bug was reported in 1.9.5?
> 
> I think this is a fix here, but I don't think it's the whole story. The code with the typo in that you fixed here was only added to 1.10.x so doesn't explain the 1.9.5 bug report. Not sure whether you want to do it all in separate chunks or not? Also could we maybe think of adding a test here? The link you added here is a link to existing tests that test something else, not entirely sure what you meant there?

@johncowen I'll look more into 1.9.5 issue. Is it in a GitHub issue? 

As for the tests, what exactly would be tested here? I wanted to point out that there is test coverage. Unfortunately, a typo scenario like we have here can't be caught in a test.

**Comment by kaxcode** [comment]
@johncowen about splitting this into chunks. I'll have to do that since this can't be back-ported to 1.9.x.

**Comment by johncowen** [comment]
hey!

> I'll look more into 1.9.5 issue. Is it in a GitHub issue?

I think it was reported in the forums, there's a link to it on the top of the issue we are tracking in Asana

https://discuss.hashicorp.com/t/consul-ui-acl-policy-edit-issue/28167

I've just seen a PR from @DingoEatingFuzz which I think is to address the rest of the story here, so we can pick the rest up over there maybe? I'll approve this one in the meantime, thanks again for spotting it! 😅

**Review by johncowen — APPROVED** [review]
🎉 thanks so much for spotting this!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/433281.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit a777b0a9babc86e022c264b0bba641c4fcc47e8c onto `release/1.10.x` succeeded!

**Pull request merged**
