### PR TITLE
agent: update proxy upstreams to inherit namespace from service

### PR DESCRIPTION
**Pull request by kisunji**
enterprise change sync to oss

### CODE REVIEW

**Review by freddygv — APPROVED** [review]
🎉

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/416483.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 91c90a672ab124885bb1829ac2f771fcc9c6b8ad onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/416483)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 91c90a672ab124885bb1829ac2f771fcc9c6b8ad onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/416483)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 91c90a672ab124885bb1829ac2f771fcc9c6b8ad onto `release/1.8.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/416483)

**Pull request merged**
