### PR TITLE
docs: Hyptothetical release note structure for work streams

### PR DESCRIPTION
**Pull request by david-yu**
Testing out release notes per workstream

### CODE REVIEW

**Comment by trujillo-adam** [comment]
I'm a little confused about what's happening. The nav shows version numbers like "0.41.0", but the page that's presented is Consul 1.11.0. Is this intended or is the content for placement only?

**Comment by david-yu** [comment]
@trujillo-adam I was testing this out to see what others think. The content of the Consul K8s releases notes are just placeholder pages copied over from the Core release notes. 

Do you think this outline would make sense? cc @karl-cardenas-coding. The PM team was discussing moving towards this model.

**Comment by karl-cardenas-coding** [comment]
I like this idea too, it's helpful 👍🏼 . But I see what Adam means by it being odd with the overall versioning. That being said, the sub-components iterate faster than core, so we would have this problem without versioning.  @trujillo-adam once the web design shares the design for the breakout of sub-components we can revisit the changelog.

**Comment by david-yu** [comment]
@karl-cardenas-coding I don't know if Consul K8s and Consul ECS are necessarily subcomponents (i.e. they should be listed under Consul Core). I think more thought is needed here. Consul K8s is tied to Core for main releases but API GW and ECS are not at the moment. 

> once the web design shares the design for the breakout of sub-components we can revisit the changelog.

**Comment by trujillo-adam** [comment]
Hey @david-yu , can we close this PR since we've adopted this approach?

**Pull request closed without merging**
