### PR TITLE
Add -advertise flag to consul connect proxy command

### PR DESCRIPTION
**Pull request by remilapeyre**
As described in #4788, there is no way to specify the address to advertise in `consul connect proxy` if it needs to differ from the one in the `-listen` flag.

This PR adds a new `-advertise` flag that overrides the `-listen` flags when specified.
If `-advertise` is not specified, it defaults to `-listen` like the current behavior.

### CODE REVIEW

**Comment by i0rek** [comment]
Thank you for your work @remilapeyre! Would you still be interested in adding this feature?

**Comment by remilapeyre** [comment]
Yes. Do you want me to update the documentation?

**Comment by i0rek** [comment]
Yeah, sure! Also could you rebase so that our new CI picks up this PR?

**Comment by remilapeyre** [comment]
I updated the documentation. It seems to me that the failing test is not because of this change though.

**Comment by i0rek** [comment]
Closing because no reply. I am happy to reopen in case there are updates. Thanks!

**Pull request closed without merging**
