### PR TITLE
ui: [Bugfix] Added Tags tab to gateways(just like exists for non-gateway services)

### PR DESCRIPTION
**Pull request by chinmaym07**
fixes: #11322 

Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>

### CODE REVIEW

**Comment by johncowen** [comment]
Thanks for looking at this @chinmaym07 , looks perfect! Lemme just give it a run first. I've done a couple of housekeeping tasks here (added some categorising labels and tweaked your title a little) just to help us find things if we ever have to in the future. I think the only thing I might need you to add is a changelog. I think this one might be good to backport to other version also. Lemme look a little more and I'll let you know 👍

**Comment by johncowen** [comment]
Hey @chinmaym07 

Just to let you know I took this for a spin and it's all good. Let me know if you want to add a changelog yourself, otherwise I can do it from here if that's easier. I'm easy either way.

Half talking out loud here: re backports. I think I'd like to backport this as far as possible (back to 1.9) and I know off the top of my head that its probably easier to do it manually, I'm guessing the backport bot won't be able to manage it. So I can do that separately.

Anyway let me know on the changelog thing, no probs if you don've have time, we can just go ahead and merge and I can do the 'paperwork'

**Review by johncowen — APPROVED** [review]

**Comment by chinmaym07** [comment]
Hey @johncowen . thankyou for testing this .
I can add the changelog. 
Do I need to follow [this](https://github.com/hashicorp/consul/blob/main/docs/contributing/add-a-changelog-entry.md) to add a changelog entry.?

**Comment by johncowen** [comment]
Yeah exactly 👍 , also if it helps take a look at any other `theme/ui` labelled closed PR (that don't have a no-changelog label).

**Comment by johncowen** [comment]
Screenshot 2022-03-07 at 17 56 35

**Pull request merged**
