### PR TITLE
Correct inaccurate bind reference, closes #2234

### LINKED ISSUE #2234: Bind docs inaccurate
From https://www.consul.io/docs/agent/options.html#_bind:

> By default, this is "0.0.0.0", meaning Consul will use the first available private IPv4 address.

This is incorrect, setting bind to 0.0.0.0 (or accepting the default) results in Consul binding to all private interfaces.

### PR DESCRIPTION
**Pull request by brianshumate**

### CODE REVIEW

**Comment by brianshumate** [comment]
Is this addition adequate to clarify the [::] behavior?

**Comment by slackpad** [comment]
I think we need to mention the advertise address. Maybe something like:

```
By default, this is "0.0.0.0", meaning Consul will bind to all addresses on the local machine and
will [advertise](/docs/agent/options.html#_advertise) the first available private IPv4 address to
the rest of the cluster. If there are multiple private IPv4 addresses available, Consul will exit with
an error at startup. If you specify "[::]", Consul will [advertise (/docs/agent/options.html#_advertise) 
the first available public IPv6 address.
```

I'm not 100% sure what `[::]` actually binds to. Would you mind cooking up a quick test and trying that, then looking at what the process actually binds to? I traced the code and it looks like it passes that into the listen() call.

**Comment by brianshumate** [comment]
I see what you mean now, and your version reads better indeed.

I did a bit of experimenting for this like so:

#### Only private or link local IPv6 available (IPv4 also available):

```
consul agent -bind=[::] -data-dir=/tmp/consul
==> Starting Consul agent...
==> Error starting agent: Failed to get advertise address: No public IPv6 address found
```

#### Multiple public IPv6 available:

```
consul agent -bind=[::] -data-dir=/tmp/consul
==> Starting Consul agent...
==> Error starting agent: Failed to get advertise address: Multiple public IPv6 addresses found. Please configure one.
```

#### Single public IPv6 available:

```
consul agent -bind [::] -data-dir=/tmp/consul        
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
           Version: 'v0.7.0'
         Node name: 'wow.local'
        Datacenter: 'dc1'
            Server: false (bootstrap: false)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
      Cluster Addr: 2601:589:8300:659d:6203:8ff:fe90:1f5e (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
             Atlas: <disabled>
```

Then after successful bind above, `lsof -P -n | grep consul` shows the following listening, with Client Addr bound to IPv4 localhost only and the cluster stuff only on the public IPv6:

```
consul    73353       brian    5u     IPv6 0xad1dc3d4cb84aff3        0t0      TCP *:8301 (LISTEN)
consul    73353       brian    7u     IPv6 0xad1dc3d4c68d5913        0t0      UDP *:8301
consul    73353       brian    8u     IPv4 0xad1dc3d4c5691e83        0t0      TCP 127.0.0.1:8400 (LISTEN)
consul    73353       brian    9u     IPv4 0xad1dc3d4c3d1f39b        0t0      TCP 127.0.0.1:8500 (LISTEN)
consul    73353       brian   10u     IPv4 0xad1dc3d4c68d4aa3        0t0      UDP 127.0.0.1:8600
consul    73353       brian   11u     IPv4 0xad1dc3d4bf52139b        0t0      TCP 127.0.0.1:8600 (LISTEN)
```

So how about this then:

```
By default, this is "0.0.0.0", meaning Consul will bind to all addresses on 
the local machine and will [advertise](/docs/agent/options.html#_advertise)
the first available private IPv4 address to the rest of the cluster. If there
are multiple private IPv4 addresses available, Consul will exit with an error
at startup. If you specify "[::]", Consul will 
[advertise (/docs/agent/options.html#_advertise) the first available public
IPv6 address. If there are multiple public IPv6 addresses available, Consul
will exit with an error at startup.
```

**Comment by slackpad** [comment]
Looks good and thanks for double checking! Only thing is you need to close the "[" in the second advertise link.

**Comment by brianshumate** [comment]
Thanks for spotting that! I have updated with the correction so it should be g2g.

**Pull request merged**
