### PR TITLE
Link to Reverse Proxy from Load Balancer

### PR DESCRIPTION
**Pull request by christopherlai**

### CODE REVIEW

**Review by dnephin — APPROVED** [review]
Thank you for the docs fix! If you can sign the CLA we can get this merged.

**Comment by christopherlai** [comment]
> Thank you for the docs fix! If you can sign the CLA we can get this merged.

Signed 😄

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/400069.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 391a0eae468b90935d333d9bed689e9b6ab0e986 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 391a0eae468b90935d333d9bed689e9b6ab0e986 onto `release/1.10.x` succeeded!

**Pull request merged**
