### PR TITLE
docs: update acl token generation with uuidgen

### PR DESCRIPTION
**Pull request by kschoche**
Updates documentation to include uuidgen as a means to generate the uuid for ACL tokens when using Vault as a secrets backend.

### CODE REVIEW

**Comment by vanphan24** [comment]
Looks good. I would also add text to state that you are "generating" in vault as well for these tokens. Like:
```
Generate the Secret in Vault
First, generate and store the ACL bootstrap token in Vault:
```

**Review by jmurret — APPROVED** [review]
👍 🎉

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/648115.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 636ecf7eed8b3095856cf6505ca0082870d54709 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 636ecf7eed8b3095856cf6505ca0082870d54709 onto `release/1.12.x` succeeded!

**Pull request merged**
