### PR TITLE
ui: [Backport/1.12.x] Fixup icons not displaying in Safari (#12738)

### PR DESCRIPTION
**Pull request by evrowe**
Backport of #12738

Icons that were using currentColor were not displaying their color in Safari (leading to invisible icons). See original PR for more details.

no changelog due to base not being `main`

### CODE REVIEW

**Review by johncowen — APPROVED** [review]
🚢

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/661833.

**Comment by jnwright** [comment]
it seems like this fix added backgrounds to icons in badges 
CleanShot 2022-05-19 at 17 08 27@2x

**Comment by johncowen** [comment]
Addresses backgrounded icons https://github.com/hashicorp/consul/pull/13166

**Pull request merged**
