### PR TITLE
xds: Parent resource update should invalidate any pending child updates

### LINKED ISSUE #17640: Envoy times out waiting for endpoints on startup
#### Overview of the Issue

Sometimes after a leader change, a newly started Envoy proxy will timeout waiting for endpoints from the Consul agent and then run in a broken state until either restarted or something changes that causes all the upstreams to get reconfigured.

#### Reproduction Steps

I'll open a PR shortly with a test case that demonstrates the issue. This is somewhat reproducible in our staging environment by repeatedly churning pods that run mesh services while triggering Consul leader changes.

After reviewing trace-level agent logs from a few occurrences, we found a pattern where this problem happens when a proxycfg snapshot update occurs after the initial Cluster list is sent to Envoy but before Envoy has acknowledged the initial Endpoints list. The communication between Envoy and Consul looks like this:

1. Envoy connects to Consul and subscribes to Clusters.
2. Consul sends Clusters.
3. Something triggers a new snapshot that requires all the Clusters to be updated again. Consul defers this update because Envoy hasn’t ACKed the first Cluster update yet.
    * In all the instances we've observed, this is a certificate renewal, which requires updating all of the Clusters that use EDS. We’re not entirely sure why the renewal happens when it does, but more details on it are below.
4. Envoy subscribes to Endpoints for the Clusters that use EDS.
5. Consul sends Endpoints.
6. Envoy ACKs the Cluster update.
7. Consul now sends updated Clusters to Envoy, which clears out the Endpoints that were just sent. **Consul is supposed to resend Endpoints immediately, but in this case it does not.**
8. Envoy ACKs the original Endpoints update. (It probably sends both ACKs at the same time, but Consul doesn’t observe the Endpoint ACK until now).
9. Envoy subscribes to Listeners. (This sometimes happens after the timeout, but the behavior is the same either way.)
10. The channel hangs for 15 seconds (the default for EDS `initial_fetch_timeout`). Consul cannot send Listeners yet because the second Cluster update is still pending an ACK, and Envoy is not sending the ACK because it’s waiting for the Endpoints.
11. Envoy times out and sends an ACK for the second Cluster update. Envoy logs `gRPC config: initial fetch timed out for type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment` for each cluster.
12. Consul sends Listeners, and Envoy ACKs.
13. Envoy considers startup complete and marks itself ready, but none of the upstreams have endpoints configured.

It's possible that other config updates could trigger the same bug, but in our case it's always been a leaf certificate update. When this problem happens, the new Envoy is initially configured with a cached certificate that was issued by a previous Consul leader. A new certificate from the current leader is issued almost immediately, which then races with the Cluster/Endpoint updates described above. At least a few conditions have to be met:
- The Consul agent for the node has to have been running for awhile, so that it has an older certificate already in cache.
- There has to have been previously been another pod running for the same mesh service on the same node, and then a period when the node did not have any pods for the service.
- A leader change has to occur during the period when the node does not have any pods from this service (or possibly more than one leader change)

Even then, we're not entirely sure why the certificate gets renewed when it does, and it's possible that part is working as intended.

### Consul info for both Client and Server

1.15.2

### Operating system and Environment details

Linux, amd64

### PR DESCRIPTION
**Pull request by ksmiley**
### Description

For Envoy types that have a parent-child relation (e.g. Cluster and Endpoint), sending an update for the parent type is supposed to trigger re-sending related child records. The parent update calls `ensureChildResend` to remove related entries from the child type’s `resourceVersions` map, which tracks the resources that Envoy already knows about. The next invocation of `SendIfNew` for the child type will then re-send the missing resources.

However, if `ensureChildResend` is called after resources for the child have been sent to Envoy but before Envoy has acknowledged them, those in-flight resources will not be removed because they’re stored in the `pendingUpdates` map. The subsequent ACK will then move them into `resourceVersions`, and `SendIfNew` will incorrectly think it doesn’t need to re-send anything.

This patch makes `ensureChildResend` also remove resources from `pendingUpdates` so that they get re-sent immediately after the ACK.

Fixes #17640

### Testing & Reproduction steps

The first commit has a test case reproducing the current behavior, and #17640 has some more background. 

We’ve been running this applied to 1.15.3 in our staging environments for a few days now and are in the process of rolling it out to production. I wanted to go ahead and open the PR now in case anyone more familiar with this code has feedback. In staging, we've confirmed through logs that the certificate renewal that's triggered the bug in the past is still happening but is no longer causing any problems with this patch applied.

### PR Checklist

* [x] updated test coverage
* [ ] external facing docs updated
* [ ] appropriate backport labels added
* [x] not a security concern

### CODE REVIEW

**Comment by david-yu** [comment]
Thanks for the PR. It may take us some time to get to review since we are in the middle 1.16 rc/ga activities.

**Comment by karlhungus** [comment]
@david-yu We've been running this patch for about a month, would it be possible to get some eyes on this, would be excellent to not have to patch our consul version

**Comment by david-yu** [comment]
Hi @karlhungus and @ksmiley we have glanced at the PR and this PR has some impact on the xDS lifecycle so we likely need som more time to review this. If you have any more pointers on how to review the PR that would be helpful (i.e. diagrams, logs, or comments to the code). Thanks!

**Comment by ksmiley** [comment]
@david-yu I'm happy to answer any questions about the change, but I'm not sure what else to add right now. The linked issue (#17640) has a more detailed description of the communication between Consul and Envoy that triggers the bug.

**Comment by david-yu** [comment]
@ksmiley We're finally getting around to this again. We'll go ahead and close this PR and re-open on our branch to finish out the remaining updates on our end. We will also make sure to add you as committer for the PR. Thanks for your patience.

**Comment by david-yu** [comment]
Closing as is now resolved by https://github.com/hashicorp/consul/pull/19866

**Pull request closed without merging**
