### PR TITLE
api: add interfaces for all api services

### PR DESCRIPTION
**Pull request by a8m**
This changes add a package `consuliface` that should provide an interface for each of the handlers (K/V, Catalog, etc..).
Currently, it contains interfaces for K/V, and Catalog APIs. but if your feedback will be positive, and you like this idea, I will add the rest. 

I didn't see how we can solve this issue without breaking changes, so I decided to adopt a similar pattern to aws-sdk-go package (see [example][example]), so we keep backwards compatibility.

Interfaces facilitate unit testing, and make mocking and stubbing much easier.
I believe that this is what most people do today, they just create the interface by themselves.

it also solves #1622 as well.

[example]:https://github.com/aws/aws-sdk-go/blob/master/service/dynamodb/dynamodbiface/interface.go

### CODE REVIEW

**Comment by shay-stratoscale** [comment]
:+1:

**Comment by magiconair** [comment]
That sounds like a reasonable idea. Why would you want to put the interface definitions into a separate package? Could you provide some example code that uses the interfaces?

**Comment by magiconair** [comment]
Also, I think you don't need the elaborate comments since it is clear that you can mock implementations with interfaces.

**Comment by a8m** [comment]
I agree. there's no need for a new package, I changed the code. 

> Could you provide some example code that uses the interfaces?

What do you mean by example code? 
I can add an `example_test.go` file or create a test case for each of the interface. which one is preferred?

**Comment by magiconair** [comment]
I don't think that we should approach it this way since having both `KV` and `KVAPI` only adds confusion and will make it incompatible in the long run. If we add interfaces then they should replace the existing structs.

As for example code I'd like to see some code that creates a mock as a verification that this change achieves what you want.

**Comment by magiconair** [comment]
As for approach I'd try to rename `KV` to `kv` for example and then add the `KV` interface which is returned by the `Client`. All method comments should then also move to the interface.

**Comment by a8m** [comment]
Are we really want to change the method signatures? this change will break people code.
besides that, It's recommended that constructors will return concrete types, and dependencies will be interfaces.

I decided to suffix the current types with `API`, but I agree that we can find a better alternative.

Any ideas? you can see the example I mentioned above from aws-go-sdk if it helps somehow.

**Comment by magiconair** [comment]
Why would this not work?

```patch
diff --git a/api/acl.go b/api/acl.go
index 15d1f9f5..f93b4e66 100644
--- a/api/acl.go
+++ b/api/acl.go
@@ -1,8 +1,29 @@
 package api

-import (
-	"time"
-)
+import "time"
+
+type ACL interface {
+	// Create is used to generate a new token with the given parameters
+	Create(acl *ACLEntry, q *WriteOptions) (string, *WriteMeta, error)
+
+	// Update is used to update the rules of an existing token
+	Update(acl *ACLEntry, q *WriteOptions) (*WriteMeta, error)
+
+	// Destroy is used to destroy a given ACL token ID
+	Destroy(id string, q *WriteOptions) (*WriteMeta, error)
+
+	// Clone is used to return a new token cloned from an existing one
+	Clone(id string, q *WriteOptions) (string, *WriteMeta, error)
+
+	// Info is used to query for information about an ACL token
+	Info(id string, q *QueryOptions) (*ACLEntry, *QueryMeta, error)
+
+	// List is used to get all the ACL tokens
+	List(q *QueryOptions) ([]*ACLEntry, *QueryMeta, error)
+
+	// Replication returns the status of the ACL replication process in the datacenter
+	Replication(q *QueryOptions) (*ACLReplicationStatus, *QueryMeta, error)
+}

 const (
 	// ACLCLientType is the client type token
@@ -33,17 +54,16 @@ type ACLReplicationStatus struct {
 }

 // ACL can be used to query the ACL endpoints
-type ACL struct {
+type acl struct {
 	c *Client
 }

 // ACL returns a handle to the ACL endpoints
-func (c *Client) ACL() *ACL {
-	return &ACL{c}
+func (c *Client) ACL() ACL {
+	return &acl{c}
 }

-// Create is used to generate a new token with the given parameters
-func (a *ACL) Create(acl *ACLEntry, q *WriteOptions) (string, *WriteMeta, error) {
+func (a *acl) Create(acl *ACLEntry, q *WriteOptions) (string, *WriteMeta, error) {
 	r := a.c.newRequest("PUT", "/v1/acl/create")
 	r.setWriteOptions(q)
 	r.obj = acl
@@ -61,8 +81,7 @@ func (a *ACL) Create(acl *ACLEntry, q *WriteOptions) (string, *WriteMeta, error)
 	return out.ID, wm, nil
 }

-// Update is used to update the rules of an existing token
-func (a *ACL) Update(acl *ACLEntry, q *WriteOptions) (*WriteMeta, error) {
+func (a *acl) Update(acl *ACLEntry, q *WriteOptions) (*WriteMeta, error) {
 	r := a.c.newRequest("PUT", "/v1/acl/update")
 	r.setWriteOptions(q)
 	r.obj = acl
@@ -76,8 +95,7 @@ func (a *ACL) Update(acl *ACLEntry, q *WriteOptions) (*WriteMeta, error) {
 	return wm, nil
 }

-// Destroy is used to destroy a given ACL token ID
-func (a *ACL) Destroy(id string, q *WriteOptions) (*WriteMeta, error) {
+func (a *acl) Destroy(id string, q *WriteOptions) (*WriteMeta, error) {
 	r := a.c.newRequest("PUT", "/v1/acl/destroy/"+id)
 	r.setWriteOptions(q)
 	rtt, resp, err := requireOK(a.c.doRequest(r))
@@ -90,8 +108,7 @@ func (a *ACL) Destroy(id string, q *WriteOptions) (*WriteMeta, error) {
 	return wm, nil
 }

-// Clone is used to return a new token cloned from an existing one
-func (a *ACL) Clone(id string, q *WriteOptions) (string, *WriteMeta, error) {
+func (a *acl) Clone(id string, q *WriteOptions) (string, *WriteMeta, error) {
 	r := a.c.newRequest("PUT", "/v1/acl/clone/"+id)
 	r.setWriteOptions(q)
 	rtt, resp, err := requireOK(a.c.doRequest(r))
@@ -108,8 +125,7 @@ func (a *ACL) Clone(id string, q *WriteOptions) (string, *WriteMeta, error) {
 	return out.ID, wm, nil
 }

-// Info is used to query for information about an ACL token
-func (a *ACL) Info(id string, q *QueryOptions) (*ACLEntry, *QueryMeta, error) {
+func (a *acl) Info(id string, q *QueryOptions) (*ACLEntry, *QueryMeta, error) {
 	r := a.c.newRequest("GET", "/v1/acl/info/"+id)
 	r.setQueryOptions(q)
 	rtt, resp, err := requireOK(a.c.doRequest(r))
@@ -132,8 +148,7 @@ func (a *ACL) Info(id string, q *QueryOptions) (*ACLEntry, *QueryMeta, error) {
 	return nil, qm, nil
 }

-// List is used to get all the ACL tokens
-func (a *ACL) List(q *QueryOptions) ([]*ACLEntry, *QueryMeta, error) {
+func (a *acl) List(q *QueryOptions) ([]*ACLEntry, *QueryMeta, error) {
 	r := a.c.newRequest("GET", "/v1/acl/list")
 	r.setQueryOptions(q)
 	rtt, resp, err := requireOK(a.c.doRequest(r))
@@ -153,8 +168,7 @@ func (a *ACL) List(q *QueryOptions) ([]*ACLEntry, *QueryMeta, error) {
 	return entries, qm, nil
 }

-// Replication returns the status of the ACL replication process in the datacenter
-func (a *ACL) Replication(q *QueryOptions) (*ACLReplicationStatus, *QueryMeta, error) {
+func (a *acl) Replication(q *QueryOptions) (*ACLReplicationStatus, *QueryMeta, error) {
 	r := a.c.newRequest("GET", "/v1/acl/replication")
 	r.setQueryOptions(q)
 	rtt, resp, err := requireOK(a.c.doRequest(r))
diff --git a/api/coordinate.go b/api/coordinate.go
index ae8d16ee..87d4baf4 100644
--- a/api/coordinate.go
+++ b/api/coordinate.go
@@ -1,13 +1,20 @@
 package api

-import (
-	"github.com/hashicorp/serf/coordinate"
-)
+import coord "github.com/hashicorp/serf/coordinate"
+
+type Coordinate interface {
+	// Datacenters is used to return the coordinates of all the servers in the
+	// WAN pool.
+	Datacenters() ([]*CoordinateDatacenterMap, error)
+
+	// Nodes is used to return the coordinates of all the nodes in the LAN pool.
+	Nodes(q *QueryOptions) ([]*CoordinateEntry, *QueryMeta, error)
+}

 // CoordinateEntry represents a node and its associated network coordinate.
 type CoordinateEntry struct {
 	Node  string
-	Coord *coordinate.Coordinate
+	Coord *coord.Coordinate
 }

 // CoordinateDatacenterMap has the coordinates for servers in a given datacenter
@@ -19,18 +26,16 @@ type CoordinateDatacenterMap struct {
 }

 // Coordinate can be used to query the coordinate endpoints
-type Coordinate struct {
+type coordinate struct {
 	c *Client
 }

 // Coordinate returns a handle to the coordinate endpoints
-func (c *Client) Coordinate() *Coordinate {
-	return &Coordinate{c}
+func (c *Client) Coordinate() Coordinate {
+	return &coordinate{c}
 }

-// Datacenters is used to return the coordinates of all the servers in the WAN
-// pool.
-func (c *Coordinate) Datacenters() ([]*CoordinateDatacenterMap, error) {
+func (c *coordinate) Datacenters() ([]*CoordinateDatacenterMap, error) {
 	r := c.c.newRequest("GET", "/v1/coordinate/datacenters")
 	_, resp, err := requireOK(c.c.doRequest(r))
 	if err != nil {
@@ -45,8 +50,7 @@ func (c *Coordinate) Datacenters() ([]*CoordinateDatacenterMap, error) {
 	return out, nil
 }

-// Nodes is used to return the coordinates of all the nodes in the LAN pool.
-func (c *Coordinate) Nodes(q *QueryOptions) ([]*CoordinateEntry, *QueryMeta, error) {
+func (c *coordinate) Nodes(q *QueryOptions) ([]*CoordinateEntry, *QueryMeta, error) {
 	r := c.c.newRequest("GET", "/v1/coordinate/nodes")
 	r.setQueryOptions(q)
 	rtt, resp, err := requireOK(c.c.doRequest(r))
```

**Comment by magiconair** [comment]
The only way I could see this break is when people have two different versions of the `github.com/hashicorp/consul/api` package imported and they are trying to assign the interface to a variable that has a pointer to the struct. This would be wrong in any case and having two different versions of the package imported is also not supported IMHO.

This change should be source compatible but I agree that it requires a re-compile.

Maybe I'm missing something here.

**Comment by magiconair** [comment]
@a8m Are you going to pick this up? Otherwise, I'll do it. I think this is a good idea.

**Comment by a8m** [comment]
Sorry for the delay @magiconair

We can do these changes, but it will break the current API and it will require a major version bump. this is what I meant.

In Go it's more recommended that the constructor returns a [concrete type and not an interface](https://github.com/golang/go/wiki/CodeReviewComments#interfaces). however the dependencies should be interfaces, in order to be able to mock them.

In the current API, users still able to mock the consul services, they just need to write the interface by themselves. 
This is why I created this PR, to maintain the interface in one place. here.

After my changes, users will be able to use the consul services like this:
```go
type P struct {
    kv api.KVAPI
    // ...
}

// in your main program:
p := P{client.KV()}
// ...
p.kv.Get(...)


// in your testing:
type mockKV struct {
    api.KVAPI
    mock.Mock
}

func (k *mockKV) Get(key string, q *QueryOptions) (*KVPair, *QueryMeta, error) {
    // mock behavior...
}

// expectations..
```

What do you think?

**Comment by magiconair** [comment]
I think maintaining two full sets of the same things isn't helpful either. It will just create confusion on whether or not to use the real type or the interface and you will see code which uses the one or the other or both making it more complex to refactor in the future. The link you've provided states to **not** provide interfaces for mocking and not to put them into the producers package. From that perspective the whole approach is wrong. 

I understand what you're trying to do but I believe we should maintain one public interface and that is either the structs or the interface but not both. 

I'm also not concerned about a breaking change since you vendor your dependencies to prevent exactly this situation. Once you upgrade you replace your `kv *api.KV` vars with `kv api.KV` or just pass the client around and be done. I've used the patch above as a drop-in replacement in fabio and just had to recompile.

I have to think about this a bit more.

**Comment by magiconair** [comment]
Another thing is that when you provide the full API as an interface then every mock has to implement all methods independent of whether they need only one or two.

**Comment by a8m** [comment]
> I believe we should maintain one public interface and that is either the structs or the interface but not both.

I agree.

> every mock has to implement all methods independent of whether they need only one or two.

You can embed the interface in your mock, and implement only the methods you use in your program.

OK, I'll start by adding these changes to the KV handler (to see how it is), and I'll ping you when it'll be ready.

**Comment by a8m** [comment]
I Added the changes to the KV handler. PTAL @magiconair

**Comment by magiconair** [comment]
@a8m After thinking about this for a bit longer I'm leaning towards not merging this. The link from the Go dev team provides good arguments to support this. I see the following options:

1. We keep the structs (status-quo): Users will have to implement their own mocks. While this is some work it isn't that much and users can decide to mock only the functions they need instead of implementing a full mock with all functions. The biggest issue here may be other libraries that use an `*api.Client` which can't be mocked. 

2. We switch to interfaces (@magiconair initial suggestion): This may break some programs although this shouldn't be that big of a deal since dependencies should be vendored in. Again, the problem here may be transitive dependencies but that is a general problem.

3. We provide both structs and interfaces (@a8m initial suggestion): We have to maintain two sets of identical call interfaces which will create confusion and some will choose to use interfaces while others keep using the structs. This will make it more difficult in the future to refactor code and users of the interfaces have to mock them in full to take advantage of them.

I think option 3 provides the most confusion with the least gain. Option 2 is somewhat better but has other drawbacks. 

At this point I don't see good options only ones with the different levels of impact and I think the status-quo creates the least amount of friction at this point. Therefore, I think we're going to stay with the status quo: provide structs and have users implement their own mocking interfaces.

I'm open for compelling counter arguments but would prefer to see concrete examples of actual problems.

**Comment by magiconair** [comment]
@a8m in reply to
> You can embed the interface in your mock, and implement only the methods you use in your program.

I didn't know that. https://play.golang.org/p/f33G-rm3os

**Comment by magiconair** [comment]
OK, after some more thought and some internal discussion I've decided to close this PR and #1622. While I get both the motivation and the approach for the initial submission I feel that it doesn't provide enough value but has the chance for confusion. From that perspective it is a nice-to-have and not a must-have. The strongest argument IMHO is from the Go team link you've provided. 

Closes #2799 
Closes #1622

**Comment by magiconair** [comment]
Please note that I'm open for compelling counter arguments and will re-open if such argument surface.

**Comment by a8m** [comment]
Thanks for your comments.

Like I said early, people like me, that want to use interfaces in their code (for consul handlers), need to write them by themselves. (this code repeating itself in all of my projects).

I thought that it will be nice to provide them, same as the aws-sdk does, and remove this overhead for the users. this is why it's nice-to-have and not must-have.

I think that the overhead for maintain these interfaces is really low, and I don't see how adding interfaces will make the users confused.

I appreciate your decision, and I'll continue to contribute in the future.


> I didn't know that.

👍

**Comment by magiconair** [comment]
@a8m This isn't about the overhead but about that users will then use both `*api.KV` or `iface.KV` in their code since both are provided by us. 

Yes, you have to write/copy/steal the code for the interface for every project but once you've done it for one you can just copy it. I'm also wondering how many new projects you are starting. I've certainly spent way more time writing the tests than creating the mock interfaces. ;) 

There is even a Go proverb for this: "A little copying is better than a little dependency" https://go-proverbs.github.io :)

Thanks for your contribution and the discussion and I'm looking forward to your next one.

**Comment by a8m** [comment]
> users will then use both *api.KV or iface.KV in their code

I don't see any problem with that. users do it with aws-sdk, and this package is widely used. 

> There is even a Go proverb for this: "A little copying is better than a little dependency" https://go-proverbs.github.io

I don't think this proverb fits here. it's talking about avoid import whole package just for "3 lines code". This is isn't the case here. you already import consul to your dependency tree.
It'll compile the same time, it's more readable and maintainable imo. think about a case when you have two services (or more) in your project that use the kv handler for example, where your gonna put the KV interface? 

Let's agree to disagree ;). it was a fun discussion though.

**Pull request closed without merging**
