### PR TITLE
[NET-5163] Support locality testing in consul-container

### PR DESCRIPTION
**Pull request by zalimeni**
* Support including locality in client sidecar config.
* Refactor fortio test helpers to separate HTTP retries from waiting on fortio result changes due to e.g. service startup and failovers.
* Align test config structs with Ent to avoid future conflicts.

I was planning to backport the non-locality changes further back, but there's other divergence that complicates doing that, so just doing 1.16 for now.

_Note: these changes are primarily to support Ent testing in a separate change_

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [x] appropriate backport labels added
* [x] not a security concern

### CODE REVIEW

**Review by hashi-derek — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
Backport failed @zalimeni. Run: https://github.com/hashicorp/consul/actions/runs/5891712985

**Comment by hc-github-team-consul-core** [comment]
Backport failed @zalimeni. Run: https://github.com/hashicorp/consul/actions/runs/5891712985

**Comment by hc-github-team-consul-core** [comment]
Backport failed @zalimeni. Run: https://github.com/hashicorp/consul/actions/runs/5891712985

**Comment by hc-github-team-consul-core** [comment]
Backport failed @zalimeni. Run: https://github.com/hashicorp/consul/actions/runs/5891712985

**Pull request merged**
