### PR TITLE
docs: fixed redirect issue

### PR DESCRIPTION
**Pull request by karl-cardenas-coding**
This PR fixes an issue related to redirects that is breaking local builds.

### CODE REVIEW

**Review by BRKalow — APPROVED** [review]
Thank you!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/640263.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 78c346cbb3a47fafc419b222161ca8a4224a569d onto `stable-website` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/640263)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 78c346cbb3a47fafc419b222161ca8a4224a569d onto `release/1.12.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/640263)

**Comment by BRKalow** [comment]
I _think_ the cherry-pick failures are okay as those branches didn't have the broken redirect definition.

**Pull request merged**
