### PR TITLE
Rename partition CLI command

### PR DESCRIPTION
**Pull request by freddygv**
Renamed for consistency with the HTTP API and CLI flags.

### CODE REVIEW

**Comment by karl-cardenas-coding** [comment]
Tagging @webdog for awareness, as this will affect the new tutorial and existing tutorial.

**Review by karl-cardenas-coding — APPROVED** [review]
lgtm

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/517622.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit ff1e71efec2df5b4d8ed0ee9edd885183f3d8193 onto `release/1.11.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/523642)

**Pull request merged**
