### PR TITLE
[RelAPI Onboarding] Add release API metadata file

### PR DESCRIPTION
**Pull request by mdeggies**
👋  This PR does the following:

1) Adds a `.release/release-metadata.hcl` file to the repo. This file contains static metadata that will be processed and sent as part of the payload in RelAPI POST requests, which will be sent when staging and production releases are triggered.  

2) Adds a top-level 'Release' page to the docs, and nests the 'Release Notes' under that page. My main goal was to add an index page to release notes, as it's currently 404'ing at https://www.consul.io/docs/release-notes, but other projects have a different setup that I thought was nice, so I copied that. Boundary example here: https://www.boundaryproject.io/docs/releases/release-notes

Before (Current sidebar view) at https://www.consul.io/docs:
Screen Shot 2022-03-22 at 4 47 03 PM

After (New sidebar view) at https://www.consul.io/docs: 
Screen Shot 2022-03-22 at 4 46 27 PM

3. Adds a 'Release Notes' index page for NIA (CTS project) so that we can link to this page from the releases API. 

Before (Current sidebar view) at https://www.consul.io/docs/nia
Screen Shot 2022-03-28 at 12 31 17 PM

After (New sidebar view) at https://www.consul.io/docs/nia: 
Screen Shot 2022-03-28 at 12 31 35 PM

This can be merged now, but the RelAPI changes will not have any effect until after the RelAPI launch. We'll also want to add any backport labels to add this change to active release branches. Similar additions are being added across all projects that publish to releases.hashicorp.com.

### CODE REVIEW

**Review by BRKalow — APPROVED** [review]
I don't have any feedback on the content, but from an implementation and structure perspective this all looks correct to me!

**Review by BRKalow — APPROVED** [review]
👏

**Comment by mdeggies** [comment]
Big thanks to @BRKalow for all your help with this. Really appreciate you!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/615971.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 535edfa2470473b3d246b67f6fab7a5e231fcbe2 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 535edfa2470473b3d246b67f6fab7a5e231fcbe2 onto `release/1.11.x` succeeded!

**Pull request merged**
