### PR TITLE
Add config option to disable HTTP printable char path check

### PR DESCRIPTION
**Pull request by banks**
The documentation change pretty much sums up this PR:

image

> Consul 1.0.3 fixed a potential security vulnerability where
>  malicious users could craft KV keys with unprintable chars that would confuse
>  operators using the CLI or UI into taking wrong actions. Users who had data
>  written in older versions of Consul that did not have this restriction will be
>  unable to delete those values by default in 1.0.3 or later. This setting
>  enables those users to _temporarily_ disable the filter such that delete
>  operations can work on those keys again to get back to a healthy state. It is
>  strongly recommended that this filter is not disabled permanently as it
>  exposes the original security vulnerability.

### CODE REVIEW

**Comment by slackpad** [comment]
An alternative way to remove bad keys like this is https://www.consul.io/api/txn.html, which doesn't carry the key name in the URL (it's in the JSON payload).

**Comment by banks** [comment]
Good point James!

@pearkes we could consider removing this again and updating docs?

**Comment by pearkes** [comment]
Yeah that is a great point. In the scenario we've seen it was a time sensitive issue, so the idea that you could change the config and re-run some `consul kv` command to get out of a downtime scenario was helpful. My only concern with the transaction API is you'd have to educate someone about that live and it may require a bit more finagling...guess we could deprecate this option in 1.3 though and write a quick guide.

**Comment by slackpad** [comment]
Yeah the txn API would require a bit of JSON to use. You could change the `consul kv delete` CLI to always use the `kv.Txn()` API under the hood (it's fine even if it's just deleting a single key) so it always uses the form that doesn't depend on any URL weirdness. This isn't a huge deal in any case :-)

**Pull request merged**
