### PR TITLE
docs: Bump core downloads to beta3

### PR DESCRIPTION
**Pull request by david-yu**

### CODE REVIEW

**Review by mikemorris — APPROVED** [review]
Thanks!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/376723.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 1802f47f5ccd0fbe4fef897b03727f3808670c8f onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 1802f47f5ccd0fbe4fef897b03727f3808670c8f onto `release/1.10.x` succeeded!

**Pull request merged**
