### PR TITLE
Add http2 and grpc support to ingress gateways

### PR DESCRIPTION
**Pull request by jackloughran**
While evaluating a Consul + Envoy request routing solution, I noticed ingress gateways don't support grpc (https://github.com/hashicorp/consul/pull/8454). We were hoping to route grpc traffic though an ingress gateway during the first phase of our migration.

Out of curiosity, I tried adding `grpc` to the ingress gateway supported protocols map, and Consul was able to correctly configure the Envoy ingress gateway. From what I can tell, ingress gateways share a lot of code with sidecar proxies which already support grpc.

Could this work? Is there another reason why ingress gateways don't support grpc?

I'm happy to expand on our use case if that would help.

### CODE REVIEW

**Comment by jackloughran** [comment]
Any updates on this? Is there any more information I can give you?

@blake

**Comment by freddygv** [comment]
Hi @jackloughran, you are correct that grpc/http2 is supported for sidecar proxies.

The only reason why gRPC wasn't supported for ingress gateways initially is that it hasn't been tested.  Have you tested sending gRPC traffic to the gateway with the changes in this PR?

**Comment by jackloughran** [comment]
@freddygv Yes, I tried this out, and I was able to successfully proxy grpc traffic on my computer with the changes in this PR.

**Comment by jackloughran** [comment]
@freddygv Thanks so much for writing that out! It was really helpful. I added the integration test, and I added http2 to the list of supported protocols since grpc always uses http2.

https://github.com/hashicorp/consul/blob/master/test/integration/connect/envoy/case-grpc/verify.bats#L31

**Comment by freddygv** [comment]
Great, thanks @jackloughran! This looks good. 

One last request: We recently moved to automating changelog entries, can you add a file like this one to `./changelog` where the filename is the PR number?

https://github.com/hashicorp/consul/blob/master/.changelog/7628.txt

This would also be considered as an improvement, like 7628.

**Comment by jackloughran** [comment]
@freddygv Sure! Thanks again for all the help!

**Comment by freddygv** [comment]
I'll take care of fixing up this cherry-pick @jackloughran. You're all set here.

**Pull request merged**
