### PR TITLE
Fixes #20930 - expose path for HTTPS endpoints

### LINKED ISSUE #20930: in Connect, I cannot expose path for HTTPS endpoints inside the container
#### Feature Description

Allow using [Expose Paths](https://developer.hashicorp.com/consul/docs/connect/proxies/proxy-config-reference#expose-paths-configuration-reference) with HTTPS, in addition to the existing `http` and `http2` modes.

#### My alternatives
- I downgrade the server I want to expose from HTTP to HTTPS (not an option for me)
- I expose the HTTPS server outside of the Connect network (but intentions won't apply!)

#### Use Case(s)

I am using cockroachdb, set up with my own self-signed certificates manually (because otherwise it enters this restrictive 'insecure' mode).

It exposes health checks and metrics endpoints I would like to scrape with prometheus, but these are served via HTTPS only.

I tried using the [expose config with Nomad](https://developer.hashicorp.com/nomad/docs/job-specification/expose), but it seems that TLS is terminated somewhere by the sidecar:

```
# the sidecar proxy exposes the path at 10.10.0.1:20373

❯ curl 10.10.0.1:20373/_status/vars
# this is returned by the cockroachdb HTTP server and forwarded appropriately:
<a href="https://10.10.0.1:20373/_status/vars">Temporary Redirect</a>.


❯ curl https://10.10.0.1:20373/_status/vars
# sidecar returned HTTP response?
curl: (35) LibreSSL/3.3.6: error:1404B42E:SSL routines:ST_CONNECT:tlsv1 alert protocol version
```

I do not mind that the sidecar terminates HTTPS and exposes the path at HTTP (although ideally it would not terminate TLS at all) but in this case I would expect to be able to expose my container's HTTPS endpoint for scraping

### PR DESCRIPTION
**Pull request by vijayraghav-io**
### Description

fixes #20930 

Added 3 parameters CAFile, CertFile, KeyFile to ServiceDefinition -> Proxy -> Expose -> Path.
In case of HTTPS path , these 3 parameters are used to configure envoy and allow HTTPS -> HTTPS traffic for external service path to be exposed.

### Testing & Reproduction steps

refer #20930 for reproduction scenario

### PR Checklist

* [x] updated test coverage
* [ ] external facing docs updated
* [ ] appropriate backport labels added
* [ ] not a security concern

### CODE REVIEW

**Comment by vijayraghav-io** [comment]
Hi @david-yu / @huikang / @jkirschner-hashicorp ,

Kindly take this PR for review.

@Cottand

**Comment by Cottand** [comment]
@vijayraghav-io thanks for the PR.

Do we **need** these fields to be set in config for HTTPS -> HTTPS ? I would expect it should be possible to simply not terminate TLS at all.

And if it does terminate TLS, why do we need the keyFile? Can we not have envoy trust the provided CA and expose HTTP? As in HTTP -> HTTPS

**Comment by vijayraghav-io** [comment]
@Cottand Thanks for your comments

Yes, as an option HTTPS passthrough, i.e. without terminating HTTPS and using normal TCP_Proxy can be provided. Updated to accommodate this. For this `protocol` must be provided as "tcp" (Service -> Proxy -> Expose -> Path -> Protocol = "tcp") , no need to provide certfile or keyfile path in this case.

For non-terminating HTTPS, yes its a good suggestion to have envoy trust the provided CA, let me get a collective feedback from other reviewers as well if any before updating.

**Comment by vijayraghav-io** [comment]
reminding for this PR review

**Pull request closed without merging**
