### PR TITLE
Fixes cluster peering docs (remove deprecated file)

### PR DESCRIPTION
**Pull request by im2nguyen**
### Description

This should fix https://github.com/hashicorp/consul/pull/16398 

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [ ] not a security concern

### CODE REVIEW

**Comment by im2nguyen** [comment]
@david-yu and @boruszak can you review?

**Review by david-yu — APPROVED** [review]

**Comment by david-yu** [comment]
Looks like an empty commit?

**Comment by im2nguyen** [comment]
It should have deleted the configuration file... https://github.com/hashicorp/consul/commit/b26536d4e46d13045b4c6c322ce2f4c66d780cae

The vercel deploy preview works and can verify that it's correct

image

**Comment by zalimeni** [comment]
Updated backport labels since this change is a manual backport to 1.15, and the backport to 1.14 happened separately (see links in original, https://github.com/hashicorp/consul/pull/16291)

**Pull request merged**
