### PR TITLE
[Security] Fix XSS Vulnerability where content-type header wasn't explicitly set

### PR DESCRIPTION
**Pull request by sarahalsmiller**
### Description
Added middleware to ensure that content-type header is always set to mitigate XSS vulnerability.

### Testing & Reproduction steps
- Updated unit tests to add additional checks for content-type header
- Vercel should deploy UI with no errors

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [ ] appropriate backport labels added
* [ ] not a security concern

### CODE REVIEW

**Review by dduzgun-security — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @sarahalsmiller! a backport is missing for this PR [21704] for versions [1.15,1.17,1.18,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @sarahalsmiller! a backport is missing for this PR [21704] for versions [1.15,1.17,1.18,1.19] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @sarahalsmiller! a backport is missing for this PR [21704] for versions [1.15,1.17,1.18] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Comment by hc-github-team-consul-core** [comment]
:mega: Hi @sarahalsmiller! a backport is missing for this PR [21704] for versions [1.15,1.17,1.18] please perform the backport manually and add the following snippet to your backport PR description:
```
<details>
	<summary> Overview of commits </summary>
		- <<backport commit 1>>
		- <<backport commit 2>>
		...
</details>
```

**Pull request merged**
