### PR TITLE
docs: Update responses for /v1/session/ endpoints post 1.7

### LINKED ISSUE #7341: Session info endpoint returns undocumented check keys
## Overview of the Issue

The `/v1/session/info` endpoint returns `ServiceChecks` and `NodeChecks` keys, and does not return `Checks` [as documented](https://www.consul.io/api/session.html).

Change appears to have been introduced in #6909.

#### Reproduction Steps

Start a server:

```
$ perl -MTest::Consul -E '$tc = Test::Consul->start(port => 8500); sleep 86400'
==> Starting Consul agent...
           Version: 'v1.7.1'
           Node ID: '99846629-02db-889f-c538-4657ac5593b4'
         Node name: 'tc_node1'
        Datacenter: 'tc_dc1' (Segment: '<all>')
            Server: true (Bootstrap: false)
       Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, gRPC: -1, DNS: -1)
      Cluster Addr: 127.0.0.1 (LAN: 49153, WAN: 49154)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false, Auto-Encrypt-TLS: false
```

Create a session:

```
$ curl -X PUT http://127.0.0.1:8500/v1/session/create
{
    "ID": "1ef29c5f-719b-7b59-e486-d6d1c797468e"
}
```

Get session info:

```
$ curl http://127.0.0.1:8500/v1/session/info/1ef29c5f-719b-7b59-e486-d6d1c797468e
[
    {
        "ID": "1ef29c5f-719b-7b59-e486-d6d1c797468e",
        "Name": "",
        "Node": "tc_node1",
        "LockDelay": 15000000000,
        "Behavior": "release",
        "TTL": "",
        "NodeChecks": [
            "serfHealth"
        ],
        "ServiceChecks": null,
        "CreateIndex": 16,
        "ModifyIndex": 16
    }
]
```

Note the keys do not match the documentation.

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 2cf0a3c8
	version = 1.7.1
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 127.0.0.1:49155
	server = true
raft:
	applied_index = 93
	commit_index = 93
	fsm_pending = 0
	last_contact = 0
	last_log_index = 93
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:99846629-02db-889f-c538-4657ac5593b4 Address:127.0.0.1:49155}]
	latest_configuration_index = 0
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 74
	max_procs = 8
	os = linux
	version = go1.13.7
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
$  consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 2cf0a3c8
	version = 1.7.1
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 127.0.0.1:49155
	server = true
raft:
	applied_index = 93
	commit_index = 93
	fsm_pending = 0
	last_contact = 0
	last_log_index = 93
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:99846629-02db-889f-c538-4657ac5593b4 Address:127.0.0.1:49155}]
	latest_configuration_index = 0
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 74
	max_procs = 8
	os = linux
	version = go1.13.7
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

Linux.

### LINKED ISSUE #10095: docs: Session Lock read response documentation update
The documentation for the read response for Session Locks uses the old pre-1.7 shape:

https://www.consul.io/api-docs/session#sample-response-2

This was changed in 1.7:

```javascript
// pre1.7
"Checks": ["serfHealth", ...]

//post-1.7
"NodeChecks": ["serfHealth", ...],
"ServiceChecks": null
```

Creating/updating sessions accepts both new style and old style payloads for back compat reasons, but guessing we should add something to the documentation around that also.

### PR DESCRIPTION
**Pull request by blake**
Update output for /v1/session/ endpoints to match output post Consul 1.7.0.

Documents new `NodeChecks` and `ServiceChecks` parameters which were added in that release.

Resolves #7341, resolves #10095

### CODE REVIEW

**Review by johncowen — APPROVED** [review]
Thanks for doing this @blake, LGTM, not sure if you are after a docs type person to look at this but 👍 from me!

**Comment by blake** [comment]
Thanks for the review @johncowen!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/413694.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit e515c9d44950b459ef156463c7c084ed2b1a8ab2 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit e515c9d44950b459ef156463c7c084ed2b1a8ab2 onto `release/1.10.x` succeeded!

**Pull request merged**
