### PR TITLE
docs: fix api-docs namespace descriptions

### PR DESCRIPTION
**Pull request by shoenig**
Looks like some copy/paste from ACL docs.

### CODE REVIEW

**Review by blake — APPROVED** [review]

**Comment by dnephin** [comment]
Thanks @shoenig , just rebased so we can merge

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/364775.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 7b5d43212156746badcfd895360fd0c89eddf469 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 7b5d43212156746badcfd895360fd0c89eddf469 onto `release/1.10.x` succeeded!

**Pull request merged**
