### PR TITLE
Update latest version on website to 1.11.4

### PR DESCRIPTION
**Pull request by eculver**
Per the latest release.

### CODE REVIEW

**Review by msiege2 — APPROVED** [review]
All good

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/598673.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit d041559fce58dfa358a1f4e12920626c36930cf5 onto `stable-website` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit d041559fce58dfa358a1f4e12920626c36930cf5 onto `release/1.11.x` succeeded!

**Pull request merged**
