### PR TITLE
UI: use new pink hues for active/primary btns

### PR DESCRIPTION
**Pull request by brianshumate**

### CODE REVIEW

**Comment by slackpad** [comment]
That looks good. The only purple thing left is the Knight Rider thing - is that easy to get w/CSS?

**Comment by brianshumate** [comment]
I think that's got it!

**Comment by slackpad** [comment]
Loading thing looks good - I found one more spot - the "active" thing on the left is purple in node/service/kv view:

image

**Comment by brianshumate** [comment]
Hey hey! I swapped all relevant occurrences of purples with pinks throughout the ui codebase and so this pass should be the charm. 😄

**Comment by slackpad** [comment]
Looks like you got 'em all!

**Pull request merged**
