### PR TITLE
Add s390x support

### PR DESCRIPTION
**Pull request by rajaskakodkar**
Signed-off-by: Rajas Kakodkar <rajas.kakodkar@ibm.com>

This PR adds support for s390x cross built binaries similar to arm and also adds a job `build-s390x` in circleci.

### CODE REVIEW

**Comment by freddygv** [comment]
Hi @rajaskakodkar, 

Is the aim of the PR only to add it to the build scripts and test it in CI? or for us to release s390x binaries on https://releases.hashicorp.com/consul?

**Comment by rajaskakodkar** [comment]
Hello @freddygv ,

The aim of the PR is to release s390x binaries on https://releases.hashicorp.com/consul and also to add it to the build scripts and test it in CI. Please let me know if I have to touch any other files to get the binaries released.

**Comment by freddygv** [comment]
Hi @rajaskakodkar, thanks for the contribution. Our release process isn't driven by the public CircleCI scripts, so this PR does not trigger your intended changes.

After some internal discussion we are going to close this PR. We have concerns about releasing binaries for architectures that we (maintainers) have limited/no access to. 

Anyone can build Consul from source for s390x, and we can do a best-effort support for it on GitHub through our issues.

**Comment by rajaskakodkar** [comment]
Hello @freddygv, thanks for the reply. If access to s390x is the only concern then does it help if we provide you with an s390x VM?

**Pull request closed without merging**
