### PR TITLE
DNS forwarding with iptables

### PR DESCRIPTION
**Pull request by fusiondog**
Adding notes on using iptables to forward ports instead of a second service.

### CODE REVIEW

**Comment by sean-** [comment]
Hi @fusiondog .  Thanks for the suggestion.  Can you add a small bit to this that includes a reference to the `recursors` option?  Without at least one specified, users with this configuration will have a hard time resolving non-Consul addresses.  In general we recommend a caching DNS service vs relying exclusively on Consul because Consul does not cache, it forwards.  Thanks!

https://www.consul.io/docs/agent/options.html#recursors

**Comment by fusiondog** [comment]
Hey, I added a bit to make it clear what the limits of the option were and how recursors would help.  Let me know if you think it still needs some massaging.

**Comment by akurniawan** [comment]
hi, is there any further explanation on this PR? I've tried to use the command listed on your commmit, and it worked for ```.consul``` TLD but not with other hostnames like ```google.com``` for example.

here is the output
```
$ nslookup consul.service.consul
Server:		172.16.0.23
Address:	172.16.0.23#53

Name:	consul.service.consul
Address: 10.164.18.99
Name:	consul.service.consul
Address: 10.174.4.106
Name:	consul.service.consul
Address: 10.145.172.175
```
```
$ nslookup google.com
Server:		172.16.0.23
Address:	172.16.0.23#53

** server can't find google.com: SERVFAIL
```

**Comment by fusiondog** [comment]
Hey @akurniawan.  In the latest update to the branch I have this line that explains about using the recursors option to resolve other domains.  Let me know what changes might clarify that better.
```
Since Consul, by default, only resolves the `.consul` TDL, it is especially important to use the `recursors` option if you wish the `iptables` setup to resolve for other domains.
```

**Comment by akurniawan** [comment]
Hey @fusiondog, ah yes I forgot to mention that. I use recursors option actually, when I haven't applied the iptables rule everything was fine, I can resolve other TDL such google.com with this command ```dig @localhost -p 8600 google.com```, but after I applied those rules I mentioned above, suddenly I couldn't resolve any host other than consul. Do you know why it's happen?

**Comment by fusiondog** [comment]
@akurniawan Do you have the recursors on a separate system or the same system?
You could check and post that the rules are in place properly: iptables -L -t nat
Or run a tcpdump to see if the connections are going where they are expected to go.

**Comment by akurniawan** [comment]
@fusiondog the recursors is on the same system.
Here is the output from ```iptables -L -t nat```
```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:domain redir ports 8600
REDIRECT   udp  --  anywhere             anywhere             udp dpt:domain redir ports 8600

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:domain redir ports 8600
REDIRECT   udp  --  anywhere             anywhere             udp dpt:domain redir ports 8600

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
```
Here is the output from ```tcpdump -ni any udp port 53```
```
23:41:51.873549 IP 172.16.0.23.53 > 10.174.4.106.59482: 33201*- 3/0/0 A 10.174.4.106, A 10.164.18.99, A 10.145.172.175 (150)
23:42:11.579686 IP 172.16.0.23.53 > 10.174.4.106.56467: 43841 ServFail- 0/0/0 (28)
```

**Comment by fusiondog** [comment]
Ok, I will need to add that to clarify that point.  Since it is on the same machine, probably also running on port 53, the iptables rules are intercepting the traffic before it reaches the local DNS server.  The iptables method is best for situations where an external DNS service already running in your infrastructure is used as the recursor or if you want to use an existing DNS server as your query endpoint and forward requests for the consul domain to the consul server.  In both of those cases you may want to query the consul server but not need the overhead of a separate service on the consul host.
I will update the branch and add that.  Thanks for the help.

**Comment by slackpad** [comment]
Thanks!

**Pull request merged**
